### ISSUE TITLE
What is the Microsoft Graph API for adding a row to excel present in another drive?

### ISSUE THREAD

**Issue by raga-adbe-gh** [microsoftgraph/microsoft-graph-docs-contrib#1003]
The documents on add row to workbook don't mention how to add row in Excel file present in another drive.

Although we have got the below api which works but it's not mentioned anywhere in documentation.

```
https://graph.microsoft.com/v1.0
 /sites/{siteId}
 /drives/{driveId}
 /items/{itemId}
 /workbook/tables/Status/rows/add
```

we need to get the actual documentation for the API to update Excel present in another drive for which I have the driveId.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa8ea6cf-6f8f-c862-ae29-699c5e0ddc0e
* Version Independent ID: 5787d91b-2b8d-3a44-e2ec-475909e682ed
* Content: [Create TableRow - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/table-post-rows.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by raga-adbe-gh** [comment]
Hi @jasonjoh, Would it be possible to advice on this.

**Comment by jasonjoh** [comment]
@raga-adbe-gh the URL you posted above works, right? This makes sense to me, since the `/workbook/tables/Status/rows/add` bit of the API URL should be the same no matter how you arrive at the file.

I see that the doc only lists URLs going through the `/me/drive` route, but there are so many other ways the API lets you get to a file:

- `/me/drives/{drive-id}/...`
- `/users/{user-id}/drive/...`
- `/users/{user-id}/drives/{drive-id}/...`
- `/sites/{site-id}/drives/{drive-id}/...`

And lots others, as listed in https://learn.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http#http-request.

**Comment by raga-adbe-gh** [comment]
Thanks a lot @jasonjoh this helps. The `drives/{drive-id}/items/{item-id}/workbook/...` worked good. As suggested we will proceed.
However the `drives/{drive-id}/root:{item-path}:/workbook/...` failed with `Could not obtain a WAC access token`, we could not get much details on this. But both works for default drive though.

**Comment by raga-adbe-gh** [comment]
Thanks @jasonjoh 

Adding few more details on previous question. 

For the `https://graph.microsoft.com/v1.0/sites/{siteIds}/drives/{driveId}/root:/{item-path}:/workbook/tables/Status/rows/add` 

We are getting this error though, any inputs on this could help

`{
	"error": {
		"code": "AccessDenied",
		"message": "Could not obtain a WAC access token.",
		"innerError": {
			"date": "xyz",
			"request-id": "xyz",
			"client-request-id": "xyz"
		}
	}
}`

This would helps us to avoid additional call to get itemId from a path.

**Comment by jasonjoh** [comment]
@raga-adbe-gh Disclaimer: I'm not part of the OneDrive or SharePoint teams so I'm just answering based on my observation. I reproduce the WAC access token error using the file path. It looks like you'll need to use the item's ID to access the Excel APIs.

**Comment by raga-adbe-gh** [comment]
Thank you @jasonjoh for helping again with valuable inputs.
