### ISSUE TITLE
If this API available in v1.0 then why example shows beta endpoint?

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs-contrib#101]
Beta endpoint works fine but v1.0 does not but the documentation says v1.0 is supported

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d004147-c5a2-11ec-7ad0-2df88d695c6f
* Version Independent ID: 84d53f2e-5c52-fc05-a330-ce22351e410a
* Content: [List enterpriseCodeSigningCertificates - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/intune-apps-enterprisecodesigningcertificate-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-apps-enterprisecodesigningcertificate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-apps-enterprisecodesigningcertificate-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @jaiprakashmb
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/23902 fixes this issue.

**Comment by Danielabom** [comment]
Fix applied.
