### ISSUE TITLE
Menu missing on the v1 endpoint

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/microsoft-graph-docs-contrib#1014]
The topic menu is missing on the v1.0 endpoint.  It is there when switching to beta but switching back to v1.0, it is gone again.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d489b596-8db6-6b4e-7271-77a6fb735c37
* Version Independent ID: afc8208d-990b-098f-0508-fcd5745d35e6
* Content: [Microsoft Graph REST API v1.0 endpoint reference - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/overview.md)
* Product: **non-product-specific**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @RayGHeld for catching this error. I've linked a PR that will fix the issue.
