### ISSUE TITLE
Incorrect throttling limit Per app across all tenants

### ISSUE THREAD

**Issue by boeapen** [microsoftgraph/microsoft-graph-docs-contrib#1019]
Incorrect throttling limit Per app across all tenants. This is currently listed as 2000 requests per second per app across all tenants. Based on discussions with Graph PMs, the limit is 135K requests per 10s per app across all tenants. Can you please correct this? Thanks!

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/142046080/8d399638-e8c0-40e0-9f30-2d3228ada0c9)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Version Independent ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Content: [Microsoft Graph service-specific throttling limits - Microsoft Graph](https://learn.microsoft.com/en-us/graph/throttling-limits?view=graph-rest-1.0)
* Content Source: [concepts/throttling-limits.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/throttling-limits.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @boeapen for raising this issue. After internal confirmation, I've raised a PR to update the limits to 130,000 requests per 10 seconds per app across all tenants.

**Comment by boeapen** [comment]
Thank you @FaithOmbongi
