### ISSUE TITLE
NewItemGetMemberGroupsPostRequestBody() not defined - import needs to be corrected.

### ISSUE THREAD

**Issue by vishwaspai** [microsoftgraph/microsoft-graph-docs-contrib#102]
[Enter feedback here]

ItemGetMemberGroupsPostRequestBody() method is not defined in the import in the sample

This import `graphmodels "github.com/microsoftgraph/msgraph-sdk-go/Me/GetMemberGroups"` should be something like `graphusers "github.com/microsoftgraph/msgraph-sdk-go/users". 

New

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a16de20-6176-fcb2-37f0-0b38f12431dc
* Version Independent ID: 54aacb41-fcef-1366-d91d-9dd32aa0812e
* Content: [directoryObject: getMemberGroups - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/directoryobject-getmembergroups?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directoryobject-getmembergroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/directoryobject-getmembergroups.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
This has been corrected in the snippets. Closing.
