### ISSUE TITLE
Authentication_MissingOrMalformed when calling addKey to rotate a certificate 

### ISSUE THREAD

**Issue by buman56** [microsoftgraph/microsoft-graph-docs-contrib#1076]
Hi All, 

I've been attempting for days to test using this API to rotate a key. But regardless out how I do it, I always end up with 
"Authentication_MissingOrMalformed" and Error code 401. Is there something else I need to do?

I first created an Azure AD App Registration  with the following permissions:
![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/22307415/1f620a2a-e993-4dcf-b6fe-d073d92b3093)
I then created a Self-Signed certificate and uploaded it to use as a Client Certificate, following [this guide](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-self-signed-certificate).

I then followed the guide as specified [here ](https://learn.microsoft.com/en-us/graph/application-rollkey-prooftoken?tabs=csharp)to generate the proof. 
```
string pfxFilePath = "certandkey.pfx";
string password = "password";
string objectId = {objectId}";

// Get signing certificate
X509Certificate2 signingCert = new X509Certificate2(pfxFilePath, password);

// audience
string aud = $"00000003-0000-0000-c000-000000000000";

// aud and iss are the only required claims.
var claims = new Dictionary<string, object>()
{
    { "aud", aud },
    { "iss", objectId }
};

// token validity should not be more than 10 minutes
var now = DateTime.UtcNow;
var securityTokenDescriptor = new SecurityTokenDescriptor
{
    Claims = claims,
    NotBefore = now,
    Expires = now.AddMinutes(10),
    SigningCredentials = new X509SigningCredentials(signingCert)
};

var handler = new JsonWebTokenHandler();
var x = handler.CreateToken(securityTokenDescriptor);
```

Then I generated a new self-signed certificate that I'd like to add, and export that to another file. I then attempt to call the API as follows below, but I cannot get past the exception that I see.

```
string tenantId = "{tenantId}";
string clientId = "{clientId}";
string newCertPath = "newcert.pfx";
X509Certificate2 newCert = new X509Certificate2(newCertPath);
var credential = new ClientCertificateCredential(tenantId, clientId, signingCert);
var graphClient = new GraphServiceClient(credential);

var requestBody = new Microsoft.Graph.Applications.Item.AddKey.AddKeyPostRequestBody
{
    KeyCredential = new KeyCredential
    {
        Type = "AsymmetricX509Cert",
        Usage = "Verify",
        Key = newCert.GetRawCertData()
    },
    PasswordCredential = null,
    Proof = x,
};
var result = await graphClient.Applications[objectId].AddKey.PostAsync(requestBody);
```

I would really appreciate some help in figuring out what I'm doing wrong here. I've tried this using both C# and Java, and have resulted in the same error. 

Thanks,
Aaron 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb011a0-dc99-d162-3f2a-d84c002ef2e7
* Version Independent ID: 10adc564-dbbb-6688-07c1-8576727990be
* Content: [application: addKey - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/application-addkey?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-addkey.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
Reopening because this *is* a documentation issue. The audience of the proof token needs to be "00000002-0000-0000-c000-000000000000". The documented value does not work and never has.
