### ISSUE TITLE
$search documentation does not explain how to encode ampersand (&) character

### ISSUE THREAD

**Issue by dixonte** [microsoftgraph/microsoft-graph-docs-contrib#1081]
As far as I can see, there doesn't seem to be any indication of how to use $search to filter AD groups by displayName containing the ampersand character specifically. The documentation lists what to do with quotes, and says all other special characters should be URL encoded. However, the following query gives an error:

GET https://graph.microsoft.com/v1.0/groups?$search="displayName:F%26O Update"

```json
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Unrecognized query argument specified: ''.",
        "innerError": {
            "date": "2023-07-11T01:22:14",
            "request-id": "dd4f8470-e221-4478-b8a7-785180f73e93",
            "client-request-id": "0a70c1e8-5ceb-e0c6-4ae0-69e54cab4596"
        }
    }
}
```

I assume the correct method for searching displayName for a phrase containing an ampersand is not documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7415c6-cfbb-27a1-109c-78aa85e69cef
* Version Independent ID: dfd0a8f0-b01d-baab-67aa-a64eb39d3224
* Content: [Use the $search query parameter in Microsoft Graph - Microsoft Graph](https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http)
* Content Source: [concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/search-query-parameter.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
UPDATE: We have implemented an official workaround for v1.0. Please see the updated known issues details. https://developer.microsoft.com/en-us/graph/known-issues/?search=18185

cc @dixonte
