### ISSUE TITLE
The documentation for the scripts is invalid.  The quotes dont match for the cloud shell one, and when run give an error as described.  The powershell one isnt even a powershell command.

### ISSUE THREAD

**Issue by Patrick-Robbins** [microsoftgraph/microsoft-graph-docs-contrib#109]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b356f4b8-50b3-7ff6-8c3f-a5210b027c7c
* Version Independent ID: b356f4b8-50b3-7ff6-8c3f-a5210b027c7c
* Content: [Enable metered APIs and services in Microsoft Graph - Microsoft Graph](https://learn.microsoft.com/en-us/graph/metered-api-setup?tabs=powershell)
* Content Source: [concepts/metered-api-setup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/metered-api-setup.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
