### ISSUE TITLE
Please document the limits on the creation of subscription for OneDrive?

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs-contrib#112]
Please document the limits on the creation of subscriptions on one drive, the document says there are no limits on the one drive resource 
<img width="503" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/30771683/56a10638-f593-401f-baa2-907ad0a68ada">

However, we are getting limit reached error while using the oneDrive resource in subscription {
    'error': {
        'code': 'ExtensionError',
        'message': 'Operation: Create; Exception: [Status Code: Forbidden; Reason: Maximum number of subscriptions has been reached]',
        'innerError': {
            'date': '2023-05-18T09:17:40',
            'request-id': 'a58611e7-85f9-4380-87a6-7fdf4bda93a0',
            'client-request-id': 'a58611e7-85f9-4380-87a6-7fdf4bda93a0'
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in resource data. - Microsoft Graph](https://learn.microsoft.com/en-us/graph/webhooks#azure-ad-resource-limitations)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The documentation has been improved with limitations and much more details. I'm going to close this item. Thanks.
