### ISSUE TITLE
List eligibilityScheduleRequests only shows recently created assignments

### ISSUE THREAD

**Issue by EUCTechTopics** [microsoftgraph/microsoft-graph-docs-contrib#115]
I have discovered something peculiar. Turns out that the API for [List eligibilityScheduleRequests](https://learn.microsoft.com/en-us/graph/api/privilegedaccessgroup-list-eligibilityschedulerequests?view=graph-rest-beta) returns the assignments only that were created recently somehow.

So to get the correct response, I would need to unassign the user from all eligible assignments, and re-assign them (e.g. using the new API).

Here you can see I only get two results:

``` http
GET https://graph.microsoft.com/beta/IdentityGovernance/privilegedAccess/group/eligibilityScheduleRequests?filter=principalId%20eq%20%277199c3c1-c7dc-4614-aa48-a6091ef27dff%27%20and%20status%20ne%20%27Revoked%27&select=principalId,action,groupId

HTTP/1.1 200 OK
Content-Type: application/json

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#identityGovernance/privilegedAccess/group/eligibilityScheduleRequests(principalId,action,groupId)",
    "value": [
        {
            "principalId": "7199c3c1-c7dc-4614-aa48-a6091ef27dff",
            "action": "adminAssign",
            "groupId": "850000f2-9566-4083-9c11-87bca4282c61"
        },
        {
            "principalId": "7199c3c1-c7dc-4614-aa48-a6091ef27dff",
            "action": "adminAssign",
            "groupId": "30a7575e-27a7-430f-a2f9-7aacd98af53e"
        }
    ]
}

```

Whereas in the Azure Portal I see the account is eligible for 8 Privileged Access Groups.

![SCR-20230522-fs2](https://github.com/microsoftgraph/microsoft-graph-docs/assets/33999622/15f3ff8f-3515-4342-a3ef-2ba7f654ba14)

And after unassigning one, and reassigning it again, I get 3 results via the API:

``` http
GET https://graph.microsoft.com/beta/IdentityGovernance/privilegedAccess/group/eligibilityScheduleRequests?filter=principalId%20eq%20%277199c3c1-c7dc-4614-aa48-a6091ef27dff%27%20and%20status%20ne%20%27Revoked%27&select=principalId,action,groupId

HTTP/1.1 200 OK
Content-Type: application/json

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#identityGovernance/privilegedAccess/group/eligibilityScheduleRequests(principalId,action,groupId)",
    "value": [
        {
            "principalId": "7199c3c1-c7dc-4614-aa48-a6091ef27dff",
            "action": "adminAssign",
            "groupId": "850000f2-9566-4083-9c11-87bca4282c61"
        },
        {
            "principalId": "7199c3c1-c7dc-4614-aa48-a6091ef27dff",
            "action": "adminAssign",
            "groupId": "30a7575e-27a7-430f-a2f9-7aacd98af53e"
        },
        {
            "principalId": "7199c3c1-c7dc-4614-aa48-a6091ef27dff",
            "action": "adminAssign",
            "groupId": "c7bcd3f1-ce42-49fe-bbd7-58ef7d75d765"
        }
    ]
}

```

Am I missing something here? Or is there a discrepancy between how accounts were made eligible in the past, and the way the new API retrieves assignments...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e6166d2-994b-24c8-45a0-3310225eab62
* Version Independent ID: ee0e90ca-abf8-426c-b2e9-af009f706178
* Content: [List eligibilityScheduleRequests - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/privilegedaccessgroup-list-eligibilityschedulerequests?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedulerequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/privilegedaccessgroup-list-eligibilityschedulerequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @ilyalushnikov
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Closing the issue
