### ISSUE TITLE
Docs mentioned the wrong endpoint

### ISSUE THREAD

**Issue by pschaufelberger** [microsoftgraph/microsoft-graph-docs-contrib#119]
The Graph API is still using the beta endpoint, the docs should be updated

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4edb5f2-57d2-7c5d-51e3-7c71c91acb43
* Version Independent ID: 8ba928b5-426f-81c1-8369-1a87bef403fa
* Content: [List microsoftTunnelServers - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/intune-mstunnel-microsofttunnelserver-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-mstunnel-microsofttunnelserver-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-mstunnel-microsofttunnelserver-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @jaiprakashmb
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closed as this seems to be fixed. Thanks
