### ISSUE TITLE
Microsoft graph api /drives/{drive-id}/items/{item-id}/invite does not grant permissions to the given item for the invited user

### ISSUE THREAD

**Issue by FuniGameDev** [microsoftgraph/microsoft-graph-docs-contrib#12]
When calling POST to /drives/{drive-id}/items/{item-id}/invite endpoint using Graph API explorer with this body:

```JSON
{
    "recipients": [
        {
            "email": "{user-email}"
        }
    ],
    "message": "",
    "requireSignIn": true,
    "sendInvitation": false,
    "roles": [
        "write"
    ]
}
```

I get a response OK - 200 - 566ms with response body being:

```JSON
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(permission)",
    "value": [
        {
            "@odata.type": "#microsoft.graph.permission",
            "id": "{id}",
            "roles": [
                "write"
            ],
            "grantedTo": {
                "user": {
                    "email": "{correct-user-email}",
                    "id": "{correct-user-id}",
                    "displayName": "{correct-user-displayName}"
                }
            }
        }
    ]
}
```
The user does not have the proper permissions for the given driveItem when I check it on SharePoint. There is nothing special about the folder i tried a few and none of them work. 
It appears that this endpoint doesn't work only when the user is in the same tenant as the Sharepoint site, when I tried it with external user it worked perfectly. 
For now I have remade the request in the old Sharepoint API which seems to work fine so the problem seems to be only on Microsoft Graph API when the user is in the same tenant as the Sharepoint site.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b75e1562-24d6-bfaf-be46-d52ee93ffb1d
* Version Independent ID: cd35f8f6-774e-70d3-9bd5-11110ab450b1
* Content: [Send an invite to access an item - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/driveitem-invite.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
