### ISSUE TITLE
Thumbnail Permanence (svc.ms tempauth token)

### ISSUE THREAD

**Issue by influential-eliot** [microsoftgraph/microsoft-graph-docs-contrib#126]
# Summary
This is not a big incident request (_although it'd be nice to have permanence!_), I just think that there should be a notation that the thumbnail URLs generated will only be valid for a few hours.

# More Detail
I think that some notation about the fact that these the thumbnails that are produced here are not usable in HTML documents (like emails, or static pages) that you might generate using the API initially. As they will not show the image a few hours after the API call has provided the link.

I believe that this is a result of the fact that, when requested, the image is done so using the query value of '`tempauth`' and a given token to then produce the thumbnail, even for the defaul 'small', 'medium', and 'large', types.

So, if I make a page somewhere, or author an email, which uses said thumbnail URLs to nicely display content from a library, then if I load that page a day later, the thumbnail will not work as the `tempauth` value has expired.

Adding a section somewhere on this page about the thumbnail permanence might better allow others to figure out why their thumbnails are not showing up.

# Additional Thoughts
Equally, perhaps some good advice to include as a work around to this would be advising users to create a thumbnail from the binary in the same place as the original file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 493fd563-8a90-df7d-1373-80e82b18f8ee
* Version Independent ID: 62d1050e-1a7d-8167-f7a1-8f139d07af9c
* Content: [Retrieve thumbnails for a file or folder - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/driveitem-list-thumbnails?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/driveitem-list-thumbnails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/driveitem-list-thumbnails.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
