### ISSUE TITLE
Creating an AAD Application proxy app throws: Invalid property 'onPremisesPublishing'

### ISSUE THREAD

**Issue by brolifen** [microsoftgraph/microsoft-graph-docs-contrib#133]
The documentation goes over how an AAD app proxy app can be configured using MS Graph.

However this parts throws an error:
https://learn.microsoft.com/en-us/graph/application-proxy-configure-api?tabs=powershell#request-2

It seems that MSgraph does not know about the onpremisespublishing resource documented here:
https://learn.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta

This is also confirmed by retrieving the app in MS Graph, there is no "onpremisespublishing" in the repsonse body.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d2015e7-e498-603f-d189-78164e652dee
* Version Independent ID: 27c57019-5424-886e-bb7b-3a1c2248ce4a
* Content: [Configure Application Proxy using the Microsoft Graph API - Microsoft Graph](https://learn.microsoft.com/en-us/graph/application-proxy-configure-api?tabs=http)
* Content Source: [concepts/application-proxy-configure-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/application-proxy-configure-api.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @brolifen for raising this issue. 

Q: Is the issue only occurring with the PowerShell SDK or do you see the same problem when using the REST API? You can use Graph Explorer to test the REST API.
