### ISSUE TITLE
Incorrect request URL used for updating a team photo

### ISSUE THREAD

**Issue by spg-iwilson** [microsoftgraph/microsoft-graph-docs-contrib#135]
In the HTTP Request section, the example for updating a team photo is "PUT /**team**/{id}/photo/$value". It should be "PUT /**teams**/{id}/photo/$value".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d517bc8-e757-3822-848a-bf6b65d456b5
* Version Independent ID: ed8cafa6-65b9-fe58-57b3-3d57676fae46
* Content: [Update profilePhoto - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/profilephoto-update.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this has been fixed. Thanks.
