### ISSUE TITLE
This endpoint only works when you request for the singed in user's data

### ISSUE THREAD

**Issue by saraamini8** [microsoftgraph/microsoft-graph-docs-contrib#136]
Hello Team,

Since by calling endpoint analytics/activitystatistics, the signed in user have access to only their own data, would it be possible to add this note somewhere in the doc, please?

Indeed, we can call "/users/{**User B**}/analytics/activitystatistics", however, user A cannot make this call on User B. 

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aec4a12a-5174-6c69-9576-312a78273960
* Version Independent ID: 3165332b-cb92-53eb-6154-c69ded90cdf3
* Content: [List activityStatistics - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/activitystatistics-list?view=graph-rest-beta&tabs=http&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/api/activitystatistics-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/activitystatistics-list.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @madehmer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Thanks.
