### ISSUE TITLE
Authorization_RequestDenied

### ISSUE THREAD

**Issue by BakkerJan** [microsoftgraph/microsoft-graph-docs-contrib#1382]
Despite having Domain.ReadWrite.All permissions, I cannot update the federatedIdpMfaBehavior parameter. 
I have the same with PowerShell Graph. 
I have Global Admin role. 

{
    "error": {
        "code": "Authorization_RequestDenied",
        "message": "Insufficient privileges to complete the operation.",
        "innerError": {
            "date": "2023-02-15T10:48:47",
            "request-id": "5ba27ecd-cc59-4a03-9966-4e40cb1c9566",
            "client-request-id": "8c2f3bea-f982-db33-0a3c-e1c897037c6b"
        }
    }
}

Tried both V1.0 and BETA, same result. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1c84fd3-1154-ae9f-ad85-eb0b1f4b1112
* Version Independent ID: 9d1f0e0b-b694-4157-996d-e46806df8ccc
* Content: [Update internalDomainFederation - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/internaldomainfederation-update.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @rahul-nagraj
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
UPDATE: Since fixing the issue is taking a bit longer than we hoped, I've documented a known issue and added a note in the documentation for the affected WRITE operations recommending *Directory.AccessAsUser.All* as a temporary workaround.

Please be on the lookout for when the issue is fixed so you can remove the use of the permission which is too highly privileged.
