### ISSUE TITLE
Please mention in the documentation if the pagination is supported?

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs-contrib#145]
Please mention in the documentation if the pagination is supported?

Currently it looks like it is not supported, since the API does not have oData.Next.Link

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9ff916-e1b7-c60b-bf05-2c5976617ad7
* Version Independent ID: 092666d9-dfd3-44f9-9571-bc67f45c4842
* Content: [List Files Shared With Me - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/drive-sharedwithme?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/drive-sharedwithme.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/drive-sharedwithme.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
