### ISSUE TITLE
Why are rooms and equipment listed under users endpoint?

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#15]
What is the reason that meeting rooms or equipment can be listed via `/users` endpoint?

When calling the `/v1.0/users` endpoint it returns also "users" associated with a meeting room, or a piece of equipment (theirs mailBoxSettings.UserPurpose is either a room or a piece of equipment).

I cannot use `POST /users` to create a room or a piece of equipment, so it's a little bit confusing.
It's also hard to filter only real users.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
I agree with you. This is probably some legacy design where some services used User entity to represent non-user resources. Today we have review processes set up and we make sure any new services can't use the User entity this way.
