### ISSUE TITLE
Some characters in permission names are replaced with underscores?

### ISSUE THREAD

**Issue by catmanjan** [microsoftgraph/microsoft-graph-docs-contrib#150]
Through trial and error we have discovered that a number of characters are replaced with underscores when listing driveItem permissions and the permissions contain group names.

So far we have found the following are replaced with underscores

```
*+'";:/\,
```

Is this behavior documented anywhere?

What other characters might be replaced?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69e3ab60-0af1-e537-d9cf-c23415dd1dc6
* Version Independent ID: 7bc60c80-43f9-88ec-fc3e-030bf0dface6
* Content: [List who has access to a file - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-list-permissions.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
