### ISSUE TITLE
Permissions are not supported at SubSite level

### ISSUE THREAD

**Issue by swettstein** [microsoftgraph/microsoft-graph-docs-contrib#153]
In my testing it appears that these permissions are manageable at the site level and cannot be applied to sub-sites. Do sub-sites inherit these permissions when set at the parent site?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1191235c-879e-dffc-82eb-4e8f7edfd29c
* Version Independent ID: 322f9be4-7921-41d8-78c2-2bdc62f916a3
* Content: [Permission - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/permission.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
