### ISSUE TITLE
The sample mentioned in the documentation doesn't work

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs-contrib#156]
POST reqyest  /v1.0/drives/{driveID}/items/{itemId}/invite

{
    "recipients": [
        {
            "email": "user@example.org"
        }
    ],
    "requireSignIn": true,
    "sendInvitation": false,    
    "retainInheritedPermissions": false,
    "roles": [
        "read"
    ]
}

Gives bad request 

{
    "error": {
        "code": "invalidRequest",
        "message": "Invalid request",
        "innerError": {
            "date": "2023-04-11T04:44:22",
            "request-id": "96499ca0-0ffd-4e09-ad5d-bd0532b56a44",
            "client-request-id": "2e740735-22bf-d6b5-0388-0d0c42716c90"
        }
    }
}
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b75e1562-24d6-bfaf-be46-d52ee93ffb1d
* Version Independent ID: cd35f8f6-774e-70d3-9bd5-11110ab450b1
* Content: [Send an invite to access an item - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-invite.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Now the code sample has been updated and it works as expected.
