### ISSUE TITLE
Condition missing

### ISSUE THREAD

**Issue by scign** [microsoftgraph/microsoft-graph-docs-contrib#160]
[Enter feedback here]
There's a conditional peculiarity missing from this page. When `allowMultipleLines` is true, setting `appendChangesToExistingText` creates a versioned field. To create a non-versioned multi-line text field the `appendChangesToExistingText` property must be omitted. A non-versioned field displays the text data normally. A versioned field displays a "View Entries" link instead of the text content.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7741ee-6dae-6f54-a7b1-3108eaed4343
* Version Independent ID: 5be79cf1-f943-3add-b505-59bac868e15e
* Content: [TextColumn - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/textcolumn?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/textcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/textcolumn.md)
* Product: **sites-and-lists**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
