### ISSUE TITLE
Access Package Policy v1 - No option to add   "isRequestorJustificationRequired": true

### ISSUE THREAD

**Issue by kellybeazley** [microsoftgraph/microsoft-graph-docs-contrib#1636]
Hi,

In Beta it was possible to add   "isRequestorJustificationRequired" 

```
"requestApprovalSettings": {
        "isApprovalRequired": true,
        "isApprovalRequiredForExtension": false,
        "isRequestorJustificationRequired": true,
        "approvalMode": "SingleStage",
        "approvalStages": [ 

```

In v1 in the documentation I don't see this as an option anywhere? Is this missing from the docs or is it not possible in v1?  And I have noticed you can still set this through the UI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 74da5bc8-3101-084c-187a-253ab493935c
* Version Independent ID: a0a8739d-1680-fc9c-a60c-421470ccef51
* Content: [Create assignmentPolicies - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentpolicies?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/entitlementmanagement-post-assignmentpolicies.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jleef365** [comment]
Hello, are there any further updates on this please? Thank you!
