### ISSUE TITLE
$filter parameter for getting drive id

### ISSUE THREAD

**Issue by aagirre92** [microsoftgraph/microsoft-graph-docs-contrib#166]
Hello,

I am trying to get a particular drive id ("Documents") but I see that there is no $filter query parameter for this request. Are you planning on adding this?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3653cef-ec16-6001-b06b-b63418f748d8
* Version Independent ID: 598c4f75-f2b0-25cf-81f3-6aac3ce7a573
* Content: [Get Drive - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/drive-get?view=graph-rest-beta&tabs=http#optional-query-parameters)
* Content Source: [api-reference/beta/api/drive-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/drive-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
