### ISSUE TITLE
chatMessage: delta not working with application permissions

### ISSUE THREAD

**Issue by milolav** [microsoftgraph/microsoft-graph-docs-contrib#172]
Using application permission with the application approved for protected APIs through request form does not work as on `delta` endpoint.

https://graph.microsoft.com/v1.0/teams/e74...0a6/channels/19:67e...cv2/messages/delta

{"error":{"code":"BadRequest","message":"Invalid request. Delta query is not supported by this resource.","innerError":{"date":"2023-03-27T13:33:46","request-id":"629a81e3-52fc-4948-a816-2cb40258d3ce","client-request-id":"629a81e3-52fc-4948-a816-2cb40258d3ce"}}}

https://graph.microsoft.com/v1.0/teams/e74...0a6/channels/19:67e...cv2/messages/delta?$filter=lastModifiedDateTime gt 2019-02-27T07:13:28.000z

{"error":{"code":"BadRequest","message":"Parameter 'Filter' not supported for this request.","innerError":{"date":"2023-03-27T13:30:19","request-id":"ddaec87a-ec17-4ca9-be55-4fb06175a74e","client-request-id":"ddaec87a-ec17-4ca9-be55-4fb06175a74e"}}}

Both queries work correctly in graph explorer using delegated permissions.

Querying just messages (without delta):
https://graph.microsoft.com/v1.0/teams/e74...0a6/channels/19:67e...cv2/messages
works without issues, but this endpoint doesn't have datetime filtering.

Documentation states it is supposed to work using Application permission with ChannelMessage.Read.All privileges.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5d8e638-3695-72a4-fa08-2622d0281d42
* Version Independent ID: faa5b2f3-45a4-ff2f-24b7-09b0363aea8c
* Content: [chatMessage: delta - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-delta.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
Hello @milolav - Sorry for delay in response.
Hope your issue has resolved now.

We are closing this issue for now, please feel free to reopen it, if required.
