### ISSUE TITLE
Getting site permissions returns "operation not supported" error

### ISSUE THREAD

**Issue by djmrky** [microsoftgraph/microsoft-graph-docs-contrib#173]
Hello,

The code  
**var result = await graphClient.Sites["{site-id}"].Permissions.GetAsync();**
(there also seems to be an error in the docs - missing "Request()")

returns an error "Operation not supported" 

The same happens with the call to
GET https://graph.microsoft.com/v1.0/sites/{sitesId}/permissions

I have the app permissions set to "Sites.FullControl.All"

**How can I get site permissions?**

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84ceb9ba-94da-4909-6b6d-82b6c5c112e0
* Version Independent ID: 01c96dd9-45f7-50d9-a899-baf6ce7faedb
* Content: [List permissions - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-list-permissions.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @barrysh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
