### ISSUE TITLE
POST to /beta/deviceManagement/deviceShellScripts endpoint documentation incorrectly states a 'required' property for JSON Body

### ISSUE THREAD

**Issue by abotroskyro** [microsoftgraph/microsoft-graph-docs-contrib#174]
Hello,

I was trying to use the /beta/deviceManagement/deviceShellScripts endpoint with  POST request. For some reason, I kept getting a 500 (internal server error). It turns out that you DON'T NEED an **id** in the POST request body when you submit a script. I simply removed the ID from the JSON object I fed to the POST request and it successfully imported the shell script. The documentation however, states that an ID is required in the JSON body in the POST request. 

So I think the documentation should be updated to remove the ID as one of the required objects for the JSON body on POST /beta/deviceManagement/deviceShellScripts. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07a8e4df-d31a-813d-5313-a8140e1b55cc
* Version Independent ID: c976b78e-4b63-04f2-d1d6-5fbc691395a7
* Content: [Create deviceShellScript - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/intune-devices-deviceshellscript-create?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-devices-deviceshellscript-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-devices-deviceshellscript-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @jaiprakashmb
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Please feel free to reopen otherwise. Thanks.
