### ISSUE TITLE
Query parameters should use the $ syntax

### ISSUE THREAD

**Issue by olivermue** [microsoftgraph/microsoft-graph-docs-contrib#179]
All query examples should use the usual query parameters like `$expand` and `$select` just to be in sync will all the other graph examples. Otherwise you could end up with [issues like this](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1748) due to imbalance.

Additionally a warning box should be added to describe that the error message `Parsing OData Select and Expand failed: Term '(select=description,displayName,name,columnGroup)' is not valid in a $select or $expand expression.` could be come from the imbalance usage of the `$` character for the query parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03c7c1ae-8156-ffdb-e684-71c4d5e9c9b8
* Version Independent ID: d90c10f3-7d79-e8e1-411b-8ccb84eb0eb4
* Content: [Get a SharePoint list - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/list-get?view=graph-rest-1.0&tabs=http#http-request)
* Content Source: [api-reference/v1.0/api/list-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/list-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.

**Comment by olivermue** [comment]
The bot just linked to the repository, but not to the concrete issue. So here it is: https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/185
