### ISSUE TITLE
Please fix this workflow and make it sane for M365 only customers

### ISSUE THREAD

**Issue by k00laidIT** [microsoftgraph/microsoft-graph-docs-contrib#182]
We are really struggling with this being the best guidance you can provide on how to link the azure app registration to the now required azure subscription ID. We at 11:11 Systems represent ~1500 customers that consume this API, most of which are vanilla M365 customers who know next to nothing about Azure AD and now we have to point them personally (as opposed to us or Veeam upstream) at cloud shell and tell them to gather information and then issue AZ CLI commands to create the link. Further you aren't providing guidance on how to verify if the  link is there or is not leading to further confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b356f4b8-50b3-7ff6-8c3f-a5210b027c7c
* Version Independent ID: b356f4b8-50b3-7ff6-8c3f-a5210b027c7c
* Content: [Enable metered APIs and services in Microsoft Graph - Microsoft Graph](https://learn.microsoft.com/en-us/graph/metered-api-setup)
* Content Source: [concepts/metered-api-setup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/metered-api-setup.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
