### ISSUE TITLE
v1.0 of results shows property that isn't there

### ISSUE THREAD

**Issue by loryanstrant** [microsoftgraph/microsoft-graph-docs-contrib#19]
The examples on this page contain the azureADAppId property within appDefinitions, however this is not returned on the v1.0 of the endpoint - only on the beta version.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25dedd5f-9625-df69-0ce6-b8d0f981ad22
* Version Independent ID: 6b1b4ed7-1b5c-a269-9de2-3c2cd04ec665
* Content: [List teamsApp - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/appcatalogs-list-teamsapps.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
The doc has been updated, we are closing this issue. Please feel free to reach out to us if you have any further queries. Thank you.
