### ISSUE TITLE
2 chapters Missing in Japanese page

### ISSUE THREAD

**Issue by v-sashig** [microsoftgraph/microsoft-graph-docs-contrib#207]
In Japanese page, last 2 chapters are missing.
https://learn.microsoft.com/ja-jp/graph/teams-licenses#monitor-costs-billed-for-the-metered-microsoft-teams-apis

- Monitor costs billed for the metered Microsoft Teams APIs
- Frequently asked questions

Please update the Japanese page to match English page accordingly.

Thank you
Sayaka

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 learn.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 01f880b9-2394-f540-9b06-bcddbe40bfa8
* Version Independent ID: 22de9e03-e917-bcc6-abd7-ebfb3a0cdec8
* Content: [Microsoft Teams API のライセンスと支払いの要件 - Microsoft Graph](https://learn.microsoft.com/ja-jp/graph/teams-licenses#monitor-costs-billed-for-the-metered-microsoft-teams-apis)
* Content Source: [concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs.ja-JP/blob/main/concepts/teams-licenses.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by v-sdhakshina** [comment]
Localization parameter is marked as High, and it will be picked up for human translation. Sent a reminder to localization team.

**Comment by Soran-M** [comment]
Only today I became aware of this issue. Please note when I am tagged using my GH account Soran-M, I will not receive a notification.

I am working on fixing this.
Please note tagging the as high priority does not force it to be human translated like it used to.

**Comment by Meghana-MSFT** [comment]
The document has been updated. Hence closing this issue. Please feel free to reach out to us if you have any questions. Thank you.
