### ISSUE TITLE
Permissions reference missing for /group/{groupId}/sites/root

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/microsoft-graph-docs-contrib#211]
Hello,
The permission Group.Read.All is sufficient to read a root site from a Microsoft 365 Group. I haven't found this documented on this page. 

Would it make sense to provide the permissions required for each call?

Cheers,
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d792f6b-8c07-bb1e-1d8c-f0f779951e0b
* Version Independent ID: dd1aa2b5-55fa-9114-7bf4-6dd0b887d1ca
* Content: [Get a SharePoint Site - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
