### ISSUE TITLE
termColumn never gets set for Taxonomy Fields in the columns endpoint

### ISSUE THREAD

**Issue by jimmywim** [microsoftgraph/microsoft-graph-docs-contrib#216]
When querying for list columns (or site columns), any Managed Metadata columns returned in the response do not have a `termColumn` property.

Any special requirements for queries, such as additional headers, or whether this is even implemented is not made clear on this page.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb16d92d-ab37-1272-fe2d-97f69adc53dd
* Version Independent ID: c0557b9e-b45d-911c-9cbe-e6752f9fa31f
* Content: [ColumnDefinition - Microsoft Graph beta](https://learn.microsoft.com/en-gb/graph/api/resources/columndefinition?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/columndefinition.md)
* Product: **sites-and-lists**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
