### ISSUE TITLE
Please add a java example.

### ISSUE THREAD

**Issue by Olliver3** [microsoftgraph/microsoft-graph-docs-contrib#220]
Could you please add a java example.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e621007-b67f-9b43-a215-34346262a307
* Version Independent ID: 5f103903-d402-281a-aaa9-38cfe1ce9d00
* Content: [Update range - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/range-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/range-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/range-update.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
This should have been fixed in the new generation of SDKs. This needs to be addressed in the code snippet generation tool: https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/2794

**Comment by fey101** [comment]
I have transferred this issue to the appropriate repo https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1949 and closed the earlier one. However, @isvargasmsft still remains as the PM there I believe.
