### ISSUE TITLE
Document checkout HTTP status codes

### ISSUE THREAD

**Issue by AliveDevil** [microsoftgraph/microsoft-graph-docs-contrib#222]
There are missing HTTP status codes for error-cases.

That is if a file is already checked-out, and another user tries to check that file out again, `/checkout` will return with `500 Internal Server Error`, please document all possible erroneous status codes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec038ea-161a-44d6-1122-82b14bee5d02
* Version Independent ID: 933f5fa6-a7f6-c4f5-c6f0-b81cbbcad84b
* Content: [driveItem: checkout - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-checkout?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-checkout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-checkout.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @learafa
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
