### ISSUE TITLE
Is List Sites Supported ?

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs-contrib#228]
The documentation says GET https://graph.microsoft.com/v1.0/sites is supported however it always gives 200 ok with empty response.

We have tested this with multiple users in multiple tenants. All give same response.

This query however gives me all the sites https://graph.microsoft.com/v1.0/sites?search=* .

Curious to know why List Sites not working ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b05ccb12-48fb-7f65-a695-0846564d2bc2
* Version Independent ID: 769c63c0-4981-7506-8320-56beafaa8770
* Content: [List sites - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/site-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/site-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
