### ISSUE TITLE
When sending a sharing invitation for a driveItem using the graph API, the retainInheritedPermissions parameter throws an "invalid request" error.

### ISSUE THREAD

**Issue by zhaozhu1010** [microsoftgraph/microsoft-graph-docs-contrib#23]
Hi, Support Team.

When sending a [sharing invitation](https://learn.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http) for a drive item using the graph API, the `retainInheritedPermissions` parameter throws an "invalid request" error, and when I remove that parameter in the request body, the API call succeeds. Does this mean that the parameter is currently unavailable or is this an unknown bug?

![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/55869255/8dd24186-a292-47d6-9e5a-2e2d5fabeebb)

![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/55869255/4cb34a0d-4408-48a3-8b30-4140d7493b2d)

Looking forward to your reply.

Best regards.
Carl

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b75e1562-24d6-bfaf-be46-d52ee93ffb1d
* Version Independent ID: cd35f8f6-774e-70d3-9bd5-11110ab450b1
* Content: [Send an invite to access an item - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-invite.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
