### ISSUE TITLE
Application Sites.Manage.All granted; Nevertheless, encountering `Error getting lists: Code: accessDenied`

### ISSUE THREAD

**Issue by CalvinQuark** [microsoftgraph/microsoft-graph-docs-contrib#230]
I have configured and granted admin consent to my application for `Sites.Manage.All` permission which this page indicates should suffice to enable my app to call this API. Nevertheless, I am encountering: `Error getting lists: Code: accessDenied`.  Assuming I am not encountering a bug and it should work as indicated on this page, then perhaps there is some key bit of information which could be included on this page to help the uninitiated get past this particular issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 986fb32a-c9aa-fbad-12b2-30eef3d9f7b1
* Version Independent ID: 722992d5-18ee-5499-b2a6-440ac705d40a
* Content: [Create a SharePoint List - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/list-create?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/list-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/list-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. I also suggest you to rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) to find an answer to your question. Thanks for your understanding.
