### ISSUE TITLE
Suggest adding or linking to an explanation of process for obtaining {site-id} param

### ISSUE THREAD

**Issue by CalvinQuark** [microsoftgraph/microsoft-graph-docs-contrib#232]
Many pages in this documentation set such as this page assume that the reader understands how to obtain the `SiteId` parameter. It would be quite helpful if an explanation was included for the uninitiated.

If using Graph Explorer, `https://developer.microsoft.com/en-us/graph/graph-explorer`
to invoke `https://graph.microsoft.com/v1.0/sites/{host-name}:/{server-relative-path}`
I obtain the `siteId`:
`string siteId = "{host-name},{guid},{guid}";`
But if I try to use the `siteId` with the `GraphServiceClient`
```
return _appClient.Sites[siteId].Lists
    .Request()
    .GetAsync();
```
The lists on the SharePoint site are not returned.

Nevertheless, Graph Explorer returns them using the same `siteId` via `https://graph.microsoft.com/v1.0/sites/{siteId}/lists`

Hence my confusion and desire for a better explanation on these API pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d792f6b-8c07-bb1e-1d8c-f0f779951e0b
* Version Independent ID: dd1aa2b5-55fa-9114-7bf4-6dd0b887d1ca
* Content: [Get a SharePoint Site - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
