### ISSUE TITLE
Graph API query Application permission is not working as expected.

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs-contrib#233]
This has been reported by multiple clients

https://graph.microsoft.com/v1.0/users/$userID/followedSites 
gives

{
    "error": {
        "code": "generalException",
        "message": "General exception while processing",
        "innerError": {
            "date": "2023-01-18T02:11:50",
            "request-id": "52563b06-d4ed-47af-afbd-8affa4ca7426",
            "client-request-id": "52563b06-d4ed-47af-afbd-8affa4ca7426"
        }
    }
}
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 540a3ce4-9f33-9250-230b-c8b759135abc
* Version Independent ID: 96802ec9-c33a-247f-269a-85640b3887bd
* Content: [List followed sites - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/sites-list-followed?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/sites-list-followed.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/sites-list-followed.md)
* Product: **sites-and-lists**
* Technology: **microsoft-graph**
* GitHub Login: @learafa
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia-MSFT** [comment]
Hi @ProgrammingWithDJ and @shcherbakov88,
The _/followedSites_ endpoint works for the current signed in user only. In fact, if you invoke it for any other user than the current signed in one, you will now get the following exception: "The current caller is not the drive owner."

Also the description of the API makes this behavior very clear: "List the sites that have been followed by the signed in user."

**Comment by shcherbakov88** [comment]
Thanks @PaoloPia-MSFT !
This question occurred because this endpoint had been working with application permission. However at some point it stopped working. And now works only with delegated permission.

**Comment by PaoloPia** [comment]
This API is not supported in application only mode, based on the current documentation. I'm sorry.
