### ISSUE TITLE
$filter support for appliedConditionalAccessPolicy

### ISSUE THREAD

**Issue by manuel-falcao-magalhaes** [microsoftgraph/microsoft-graph-docs-contrib#234]
There are some properties (e.g. appDisplayName) in the signIn resource type documentation page (https://learn.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-1.0) which explicitly state they support $filter. There is no indication about it for appliedConditionalAccessPolicy, despite not being explicitly stated does it support the $filter query parameter? If not, does that mean that only properties that explicitly state they support $filter support that query parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61cf8069-b779-ea2a-c02a-c8efd2e18019
* Version Independent ID: 9a912f06-6ffd-d5c9-de30-66c8fff1d578
* Content: [signIn resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/signin.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Only the **id** was confirmed to support `$filter` and the documentation was updated accordingly. Closing this issue.
