### ISSUE TITLE
Incorrect reference for TimeZoneStandard

### ISSUE THREAD

**Issue by cowley05** [microsoftgraph/microsoft-graph-docs-contrib#236]
[Enter feedback here]
The code example for getting IANA timezones in Java (and I suspect in other languages but IDK) is not correct and does not compile:

```
GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

OutlookUserSupportedTimeZonesCollectionPage supportedTimeZones = graphClient.me().outlook()
	.supportedTimeZones(OutlookUserSupportedTimeZonesParameterSet
		.newBuilder()
		.withTimeZoneStandard(microsoft.graph.timeZoneStandard'Iana')
		.build())
	.buildRequest()
	.get();
```

specifically the line `.withTimeZoneStandard(microsoft.graph.timeZoneStandard'Iana')`

Both the import and the way it is accessed is incorrect and I believe it should like this: `com.microsoft.graph.models.TimeZoneStandard.IANA`

Also this does not seem to work and gives an error of: `The parameter 'TimeZoneStandard=IANA' is not in scope.` any helps on this part would be great!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03a09144-1c0b-7e8e-cd0f-7b8a84489b5c
* Version Independent ID: f45d8ded-bdee-3ea1-e2e5-632488c8a996
* Content: [outlookUser: supportedTimeZones - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/outlookuser-supportedtimezones.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/outlookuser-supportedtimezones.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
It should have been fixed by the new generation of SDKs. Issue tracking the fix can be found at: https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/2794

**Comment by fey101** [comment]
Hi @maisarissi , I have transferred this issue to the appropriate repo https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1949 and closed the earlier one. However, @isvargasmsft still remains as the PM there I believe.

**Comment by lramosvea** [comment]
Closing as this will be tracked here: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1949
