### ISSUE TITLE
OneDrive "upload new file" is limited to JSON files but not mentioning this

### ISSUE THREAD

**Issue by BloodyRain2k** [microsoftgraph/microsoft-graph-docs-contrib#238]
https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http#http-request-to-upload-a-new-file
No mention that "upload new file" approach does ONLY work for JSON files, until one tries it out and gets yelled at by the server.

Non JSON files need to be first created with the approach described under https://learn.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http#request but as "file" obviously, and THEN "uploaded" with the procedure described for updating an existing file: https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http#http-request-to-replace-an-existing-item

I spent the last hour messing around with API calls just to find out something that could be given in a foot note below the approach.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d92fb8c7-4409-d945-57dd-5d6fc4010051
* Version Independent ID: f77c05bd-2688-bd4e-1f8f-f18feb3a8639
* Content: [Upload small files - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by bretthacker** [comment]
Figured that out. Glad I didn't wait :).
