### ISSUE TITLE
Cannot update nested fields for Sharepoint List Item column

### ISSUE THREAD

**Issue by wesleycmtsang** [microsoftgraph/microsoft-graph-docs-contrib#239]
I cannot update a list item field if it is nested.

Here is an example:
'fields': {..., 'pdf_link': {'Description': 'old_link.jpg', 'Url': 'old_link.jpg'}, ...}

I would like to update the 'pdf_link' field which is a URL. It contains two values: 'Description' and 'Url'. If I tried to update the 'pdf_link' field by passing a nested JSON structure, like the following:

{'pdf_link': {"Description": "new_link.pdf", "Url": "new_link.pdf"}}

I get returned an "Invalid request" error.
The documentation does not provide an example of how to update a nested field.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec4e338a-772e-0fc8-cff2-14d5a2f0d173
* Version Independent ID: 01362b8b-5f0b-4a40-d21f-0d27012c7311
* Content: [Update listItem - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/listitem-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/listitem-update.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your comprehension.
