### ISSUE TITLE
This page is confusing because it doesn't discuss multi-geo at all

### ISSUE THREAD

**Issue by chewbacca9000** [microsoftgraph/microsoft-graph-docs-contrib#242]
Does Microsoft Graph API Beta for SharePoint Sites support multi-geo? If so, how should one enumerate all sites and subsites using the Microsoft Graph API Beta for ALL GEOS?

This is not discussed or covered in the documentation and is a huge gap. The fact that it isn't even discussed or documented as a feature/limitation is super confusing. Please fix this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c69782e4-57f5-8739-1e03-12fcdf4853aa
* Version Independent ID: ae3692d0-2697-9713-46d9-628b29cf0e9c
* Content: [Enumerate sites - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/site-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/site-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/site-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia-MSFT** [comment]
Hi @chewbacca9000, thanks for your feedback. The multi-geo is now covered in this page: https://learn.microsoft.com/en-us/graph/api/site-getallsites?view=graph-rest-beta&tabs=http - Thanks.
