### ISSUE TITLE
Add Sites Selected as Permission

### ISSUE THREAD

**Issue by Serkar1** [microsoftgraph/microsoft-graph-docs-contrib#244]
Hello,

I noticed, that the permission application sites.selected is missing in the documentation. I have tested it and [documented it](https://sposcripts.com/how-to-upload-files-to-sharepoint-using-graph-api/) here.

br
Serkar

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d92fb8c7-4409-d945-57dd-5d6fc4010051
* Version Independent ID: f77c05bd-2688-bd4e-1f8f-f18feb3a8639
* Content: [Upload small files - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi @Serkar1, thanks for your feedback. The Resource Specific Consent topic (aka Sites.Selected) is covered in docs here: https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins-modernize/understanding-rsc-for-msgraph-and-sharepoint-online. Thanks.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs as well as the "*.Selected" permission model. We'll do our best to keep your feedback into account while doing that.
