### ISSUE TITLE
Position of docs for Teams and Channels in the API Reference

### ISSUE THREAD

**Issue by cadi3s** [microsoftgraph/microsoft-graph-docs-contrib#245]
Please move the API Reference documentation pages for topics related to Teams and Channels back directly under "Teamwork and communications".  They are now under a subheader "Messaging" which is not where anyone would try to find them.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9da05bd1-f389-cc6d-1c51-00eac3a5f581
* Version Independent ID: e4fadfc1-26e8-fb24-424a-a37c5a77b911
* Content: [team resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/team.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @AkJo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
@cadi3s -Thank you for your feedback. We appreciate your input. Currently, the channels and teams messaging APIs align with our current terms of service, and any updates would require user studies. Your feedback is valuable, and we'll explore ways to address this in our next update.

**Comment by sayali-MSFT** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
