### ISSUE TITLE
Cannot get team owner via graph team API

### ISSUE THREAD

**Issue by blake-zhang-avepoint** [microsoftgraph/microsoft-graph-docs-contrib#25]
Sometimes we cannot get team owners when using team API, there is no owners in response.

Tenant id: c875ae83-5ffc-4215-ac8d-f289614119e5
Team object id: f7cbb7ca-8b63-4078-89b9-967b333aa64a
it should return Samuel_IT.M365x713869@M365x713869.onmicrosoft.com in API response. it is the only one owner.

API:
https://graph.microsoft.com/v1.0/teams/f7cbb7ca-8b63-4078-89b9-967b333aa64a/members

![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/43629067/fa6c4a0c-a560-419d-b4ef-a23a0f9db460)

![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/43629067/1dd16127-384f-4df3-945a-f1d2138d6877)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf854943-7edf-1dfa-14c4-b8877537cb06
* Version Independent ID: 83151040-4b99-2389-87da-b49443af92bf
* Content: [List members of team - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-list-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @AkJo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by blake-zhang-avepoint** [comment]
Hi @AkJo ,

 it's on a specific tenant, we cannot reproduce on other tenants.

Thanks,

**Comment by Prasad-MSFT** [comment]
@AkJo - Is there any update on this? We were not able to repro this at our end.

**Comment by Prasad-MSFT** [comment]
@AkJo - Is there any update on this? We were not able to repro this at our end.

**Comment by ChetanSharma-msft** [comment]
Hello @blake-zhang-avepoint - Please confirm whether the owner who created the team has left the organization?

**Comment by blake-zhang-avepoint** [comment]
It's been too long, I think the team should be created by app, and the owners are all in tenant.
