### ISSUE TITLE
information for {encoded-sharing-url} is missing

### ISSUE THREAD

**Issue by bckrma** [microsoftgraph/microsoft-graph-docs-contrib#256]
Hello,

There is no information in this page on what is meant by {encoded-sharing-url}
Apparently you have to follow a specific logic to encode the sharing url, the necessary steps are described here: [{encoded-sharing-url}](https://learn.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http#encoding-sharing-urls)](https://learn.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http#encoding-sharing-urls).

It would be nice if you could add these steps to this page as well.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09b8d398-f3d4-9808-2214-886fc1b42d86
* Version Independent ID: c722986c-9322-301b-2ac9-c5b202803d9f
* Content: [Grant permission - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/permission-grant?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/permission-grant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/permission-grant.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @learafa
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
