### ISSUE TITLE
The "/sites/{siteId}/drives" resource documentation is inconsistent and (for us) easy to misunderstand.

### ISSUE THREAD

**Issue by davidschlum** [microsoftgraph/microsoft-graph-docs-contrib#259]
We were attempting to figure out a Sharepoint Drive ID for use with the Graph API and had a really hard time finding where to do that. After much searching and trying things out, we finally noticed that we were accidentally using the "/sites/{siteId}/drive" resource to look up available sharepoint drives instead of "/sites/{siteId}/drives".

I think the confusion came in where the API returns the "Default" Document library when you call /sites/{siteId}/drive instead of failing. While I'm writing up this Issue, I'm noticing that there is a note on the ["API v1.0 reference > Users > Drive > Get drive" page](https://learn.microsoft.com/en-us/graph/api/drive-get?view=graph-rest-1.0&tabs=http#get-the-document-library-for-a-site) that explicitly states the /sites/{siteId}/drive resource returns the Site's default document library. It does not mention that you must use "/sites/{siteId}/drives" to get a list of all available Drives for that Site.

If you look at the menu from the ["API v1.0 reference > Files > Drives > Drive" page](https://learn.microsoft.com/en-us/graph/api/resources/drive?view=graph-rest-1.0), there is no mention of the "/sites/{siteId}/drives" resource. The only place you can see it is in the menu under ["List Drives"](https://learn.microsoft.com/en-us/graph/api/drive-list?view=graph-rest-1.0&tabs=http).

There seems to be a mixture of User > Drive stuff between the User > Drive location and the Files > Drive location. There seems to be a lot of duplication while there also seems to be a lot of stuff missing from one or the other.

It sure would be nice to be able to:
1. Get the "/Drives" Resources included as a first class citizen for everywhere that it exists (Our use case is primarily the "/sites/{siteId}/drives" Resource).
2. Consolidate and solidify the documentation around Drives between the users and sites resources.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd926e47-392d-8e60-a72c-bd3591417113
* Version Independent ID: 3094b7bd-9e38-20ea-71db-a4d9ea64550d
* Content: [drive resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/drive?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/drive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/drive.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
