### ISSUE TITLE
"allowMultipleLines": true

### ISSUE THREAD

**Issue by Chris-Whelan** [microsoftgraph/microsoft-graph-docs-contrib#268]
This seems to require "linesForEditing" not equal 0. Sort of obvious but would be nice if stated and / or error messages from graph stated this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7741ee-6dae-6f54-a7b1-3108eaed4343
* Version Independent ID: 5be79cf1-f943-3add-b505-59bac868e15e
* Content: [TextColumn - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/textcolumn?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/textcolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/textcolumn.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
