### ISSUE TITLE
Childcount always set to zero in delta DriveItem for Folder

### ISSUE THREAD

**Issue by incognito1234** [microsoftgraph/microsoft-graph-docs-contrib#278]
Hi,

I have not found the bug report page for MsGraph so I post the report here:

I catch delta item related to my personal OneDrive by using the query `GET /me/drive/root/delta`.
Folder DriveItem are correctly retrieved but `childCount `attribute is systemically set to `0`. Other attributes are correct.

The workaround is to perform a query `GET /me/drive/items/<folderId>` for each Folder driveItem.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5785f90e-b37c-c5a5-ddbc-7170307980c9
* Version Independent ID: d8b7729e-38c4-5562-7359-5e926f8d7ae4
* Content: [driveItem: delta - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-delta.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
