### ISSUE TITLE
Please specify if the ListItemID is immutable ?

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs-contrib#282]
Out of all the Id's in the documentation please specify which properties are immutable

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acc0dc7c-a98e-9614-9a27-72b0cdebb0d0
* Version Independent ID: ef2105cf-e31a-0dcf-f6f5-8b0bf98d8913
* Content: [SharePointIds - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/sharepointids?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/sharepointids.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/sharepointids.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
