### ISSUE TITLE
Is the itemID Immutable  ? are there any known scenario where this itemID could change ?

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs-contrib#284]
Is there any known scenario where this item ID could change?

I uploaded a few files on SharePoint and stored the id in my database, however, after a few days we noticed the Id(item Id) was changed.

would like to know if there are any scenarios where this could happen. Would like to add in the documentation as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ccfedc34-43c1-d07a-249f-a105967a7730
* Version Independent ID: 3af5bde5-0179-4cd7-eacd-a903f3cb106b
* Content: [Get a driveItem resource - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
