### ISSUE TITLE
Response should include 202 response with detail of Location header

### ISSUE THREAD

**Issue by JamesHoggIOH** [microsoftgraph/microsoft-graph-docs-contrib#290]
Not issue, just suggestion on clearer documentation. On page for Copy (https://learn.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http) you have 202 response with helpful information: 

"The value of the Location header provides a URL for a service that will return the current state of the copy operation. You can use this information to [determine when the copy has finished](https://learn.microsoft.com/en-us/graph/long-running-actions-overview)." 

This same long-running-action behaviour occurs for Move too with common response being a 202, not a 200; so this helpful information could be included as an alternate response. It was not at first obvious why my Content was returning empty. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d11b87a-816c-c20a-3cb3-d13ee68b64cb
* Version Independent ID: 9e15b4d9-7612-cc57-b1b0-5bab8e3775a5
* Content: [Move a file or folder - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-move?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-move.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
