### ISSUE TITLE
Get site: $select and $expand support

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#295]
The response from `GET /v1.0/sites/{site-id}` endpoint 

returns properties: `createdDateTime,description,id,lastModifiedDateTime,name, webUrl,displayName,root,siteCollection`.

According to the documentation `createdBy,lastModifiedBy,lastModifiedDateTime` defined on [baseItem][2] are missing in the response.

The response from

    GET /v1.0/sites/{site-id}?$select=id,displayName,name,webUrl,createdDateTime,createdBy&$expand=createdByUser

returns only `createdDateTime,name,webUrl,displayName`. 

`id,createdBy,createdByUser` are missing.

The request

    GET /v1.0/sites/{site-id}/createdByUser

returns 

```
{
    "error": {
        "code": "InternalServerError",
        "message": "Error processing response from backend service.",
        "innerError": {
            "date": "2022-11-02T08:28:58",
            "request-id": "40ea8528-57f6-42a0-9cad-d22613a508cd",
            "client-request-id": "25d7ba96-4b84-1c54-4f2d-3bc189b54efc"
        }
    }
}
```

Are `$select` and `$expand` fully supported for `GET /v1.0/sites/{site-id}`?

  [1]: https://learn.microsoft.com/en-us/graph/api/resources/baseitem?view=graph-rest-1.0#relationships
  [2]: https://learn.microsoft.com/en-us/graph/api/resources/baseitem?view=graph-rest-1.0#properties

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d792f6b-8c07-bb1e-1d8c-f0f779951e0b
* Version Independent ID: dd1aa2b5-55fa-9114-7bf4-6dd0b887d1ca
* Content: [Get a SharePoint Site - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
