### ISSUE TITLE
Incorrect samples for Viva Learning Learning Content Sample API (Patch Learning Content)

### ISSUE THREAD

**Issue by helepeut** [microsoftgraph/microsoft-graph-docs-contrib#299]
Hi, 

Following the documentation (see below), here are my feedbacks :
1. "contributor": "Scott Simpson", : should be "contributorS": ["Scott Simpson"] as it's a string collection
2. "createdDateTime": "2018-01-01T00:00:00" : missing a Z at the end (should be "2018-01-01T00:00:00Z")
3. in attributes list, it could be useful to precise that the duration should be in ISO 8601 format (I missed it, trying to push values in standard seconds).
4. I think that the step to create a new learning content item is not clear enough. May worth to mention that the first query should be PATCH /employeeExperience/learningProviders/{learningProviderId}/learningContents(externalId='{externalId}') , then that it can be patched / updated using the generated system ID. 

Kind regards !
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54cab990-a67c-cdd3-38b0-7b58c7e7f9bc
* Version Independent ID: 5ce0d8d7-6e12-0b19-b941-dab7175f1768
* Content: [Update learningContent - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/learningcontent-update.md)
* Product: **employee-learning**
* Technology: **microsoft-graph**
* GitHub Login: @malabikaroy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this has been fixed already. Thanks.
