### ISSUE TITLE
Add applicable limits on the number of Apps that can be published to Tenant's Catalog

### ISSUE THREAD

**Issue by ksarathkumar** [microsoftgraph/microsoft-graph-docs-contrib#30]
Please update on the applicable limits for publishing apps to Tenant's Catalog. And how many days will it take to permanently remove the deleted app from catalog.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc580041-9ed5-dc21-2eb1-813152044527
* Version Independent ID: b229cada-3a68-38b5-4236-7cd0d970679f
* Content: [Publish teamsapp - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&tabs=http&source=docs)
* Content Source: [api-reference/v1.0/api/teamsapp-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/teamsapp-publish.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
Hi @ksarathkumar - When publishing apps to a tenant's app catalog, there is no specific limit to the number of apps that can be published. However, it is important to ensure that the apps being published comply with the organization's policies and guidelines.

When an app is deleted from the tenant's app catalog, it may take some time for the app to be permanently removed. The exact time frame can vary, but it typically takes around 24-48 hours for the app to be completely removed from the catalog. It is important to note that removing an app from the tenant's app catalog does not automatically uninstall the app from users' devices. Users may need to manually uninstall the app if it is no longer needed.
