### ISSUE TITLE
The listed default value for conflictBehavior contradicts other documentation

### ISSUE THREAD

**Issue by webley** [microsoftgraph/microsoft-graph-docs-contrib#300]
The conflictBehavior setting is shown as a settable parameter in the Request body section as:

```json
{
  "@microsoft.graph.conflictBehavior": "fail (default) | replace | rename",
  "description": "description",
  "fileSize": 1234,
  "name": "filename.txt"
}
```

However. it is described in the [driveItem resource type docs](https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0#instance-attributes): You can use the values fail, replace, or rename. The default for PUT is _replace_.

My experience has also been that when not supplied, upload session creation succeeds and by default causes the existing file to be replaced, where explicitly passing "fail" results in a HTTP 409 Conflict.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c42d74d1-8c6f-5282-9fba-30fdd6449362
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [driveItem: createUploadSession - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
