### ISSUE TITLE
setting #microsoft.graph.windows10CustomConfiguration with oma settings only works with delegated permissions

### ISSUE THREAD

**Issue by bluuf** [microsoftgraph/microsoft-graph-docs-contrib#3024]
Creating new windows10CustomConfiguration with oma settings included fails when using Application permissions.
When I make the exact same API call using delegated permissions (with the exact same JSON body) works fine.

Sample Json body I use:
```
{
    "@odata.type": "#microsoft.graph.windows10CustomConfiguration",
    "deviceManagementApplicabilityRuleOsEdition": null,
    "deviceManagementApplicabilityRuleOsVersion": null,
    "deviceManagementApplicabilityRuleDeviceMode": null,
    "description": "",
    "displayName": "test-DefaultAPPsOutlookAdobeEdge",
    "omaSettings": [{
            "@odata.type": "#microsoft.graph.omaSettingString",
            "displayName": "Default Apps",
            "description": null,
            "omaUri": "./Vendor/MSFT/Policy/Config/ApplicationDefaults/DefaultAssociationsConfiguration",
            "value": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPERlZmF1bHRBc3NvY2lhdGlvbnM+CiAgPEFzc29jaWF0aW9uIElkZW50aWZpZXI9Ii5odG0iIFByb2dJZD0iQXBwWDRoeHRhZDc3ZmJrM2pra2VlcmtybTB6ZTk0d2pmM3M5IiBBcHBsaWNhdGlvbk5hbWU9Ik1pY3Jvc29mdCBFZGdlIiAvPgogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSIuaHRtbCIgUHJvZ0lkPSJBcHBYNGh4dGFkNzdmYmszamtrZWVya3JtMHplOTR3amYzczkiIEFwcGxpY2F0aW9uTmFtZT0iTWljcm9zb2Z0IEVkZ2UiIC8+CiAgPEFzc29jaWF0aW9uIElkZW50aWZpZXI9Ii5wZGYiIFByb2dJZD0iQWNyb0V4Y2guRG9jdW1lbnQuREMiIEFwcGxpY2F0aW9uTmFtZT0iQWRvYmUgQWNyb2JhdCBSZWFkZXIgREMiIC8+CiAgPEFzc29jaWF0aW9uIElkZW50aWZpZXI9Imh0dHAiIFByb2dJZD0iQXBwWHEwZmV2em1lMnB5czYybjNlMGZicWE3cGVhcHlrcjh2IiBBcHBsaWNhdGlvbk5hbWU9Ik1pY3Jvc29mdCBFZGdlIiAvPgogIDxBc3NvY2lhdGlvbiBJZGVudGlmaWVyPSJodHRwcyIgUHJvZ0lkPSJBcHBYOTBudjZuaGF5NW42YTk4Zm5ldHY3dHBrNjRwcDM1ZXMiIEFwcGxpY2F0aW9uTmFtZT0iTWljcm9zb2Z0IEVkZ2UiIC8+CiAgPEFzc29jaWF0aW9uIElkZW50aWZpZXI9Im1haWx0byIgUHJvZ0lkPSJPdXRsb29rLlVSTC5tYWlsdG8uMTUiIEFwcGxpY2F0aW9uTmFtZT0iT3V0bG9vayIgLz4KPC9EZWZhdWx0QXNzb2NpYXRpb25zPg=="
        }
    ]
}
```
urls I've trid:
https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations
https://graph.microsoft.com/v1.0/deviceManagement/deviceConfigurations

When I use Delegated permissions the API call succeeds. When I use Application Permissions I receive a HTTP 403.
My app registration has the application permissions DeviceManagementConfiguration.ReadWrite.All applied (and I also see this in my JWT token).
The content of the error message (not the strange date in the API version called internally)
**{
    "error": {
        "code": "UnknownInConvertApiError",
        "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-
        000000000000 - Activity ID: 944d1070-0f91-42d3-a2a3-26c7f2b57fb1 - Url: https://fef.amsub0302.manage.microsoft.com/DeviceConfiguration_2108/StatelessDeviceConfigurationFEService/deviceManagement/deviceCon
        figurations?api-version=5021-06-23\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}",
        "innerError": {
            "date": "2021-09-07
            T07:18:53",
            "request-id": "944d1070-0f91-42d3-a2a3-26c7f2b57fb1",
            "client-request-id": "944d1070-0f91-42d3-a2a3-26c7f2b57fb1"
        }
    }
}
**

To summarize: setting this with the sample Json payload works when using a token with delegated permissions.
Making this exact same API call using application permissions fails.

(to test I've also created an app registration and configured all possible MS Graph application permissions on this application, this also gave the same error).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0deba141-7ff8-3460-1923-68f3ea7a7039
* Version Independent ID: c2a8ab5e-0995-e736-ce06-cbd45ff5e710
* Content: [Create windows10CustomConfiguration - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-windows10customconfiguration-create?view=graph-rest-1.0&viewFallbackFrom=beta)
* Content Source: [api-reference/v1.0/api/intune-deviceconfig-windows10customconfiguration-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-deviceconfig-windows10customconfiguration-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
This was fixed in the Intune 2109 release.
