### ISSUE TITLE
Issue in documentation for sending mail with attachment - Java example

### ISSUE THREAD

**Issue by bithexe** [microsoftgraph/microsoft-graph-docs-contrib#310]
The section "Example 3: Create a message with a file attachment and send the message" has an issue on the Java tab:

The line `attachments.oDataType = "#microsoft.graph.fileAttachment";` seems to be missing; this leads to the following error:
```
400
Error code: RequestBodyRead
Error message: The property 'contentBytes' does not exist on type 'microsoft.graph.attachment'.
Make sure to only use property names that are defined by the type or mark the type as open type.
```
Adding the `oDataType` assignment makes the example work without problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [user: sendMail - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-sendmail.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
Hi @bithexe 

The code snippets has been updated based on the new [Microsoft Graph Java v6 version](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v6.1.0) and has now the following line to set the odataType:

```java
attachment.setOdataType("#microsoft.graph.fileAttachment");
```
You can check more info about the new version in the [v6 announcement blog post](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/) and the updated code snippet [here](https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=java#request-2).
