### ISSUE TITLE
Level `draft` not documented for PublicationFacet

### ISSUE THREAD

**Issue by AliveDevil** [microsoftgraph/microsoft-graph-docs-contrib#312]
There is an undocumented value `draft` for `PublicationFacet#level`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 461be976-9f25-8617-ca6f-e4ae11eb1b16
* Version Independent ID: bc1b2b32-932a-f809-719a-339e020d817d
* Content: [PublicationFacet resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/publicationfacet?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/publicationfacet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/publicationfacet.md)
* Product: **files**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
