### ISSUE TITLE
"This action allows you to obtain a short-lived embeddable URL for an item in order to render a temporary preview"

### ISSUE THREAD

**Issue by catmanjan** [microsoftgraph/microsoft-graph-docs-contrib#316]
What exactly is meant by "short-lived" in this documentation?

Can we get a number instead

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 399338a3-4d90-4c9b-b3e6-a7aaf970eec5
* Version Independent ID: 22fb7721-70f4-92af-db16-42967cd0043d
* Content: [driveItem: preview - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-preview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-preview.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
