### ISSUE TITLE
Byte range statements are contradictory

### ISSUE THREAD

**Issue by scastria** [microsoftgraph/microsoft-graph-docs-contrib#338]
[Enter feedback here]
Here are statements in this page:
1. You can upload the entire file, or split the file into multiple byte ranges, as long as the maximum bytes in any given request is less than 60 MiB.
2. If your app splits a file into multiple byte ranges, the size of each byte range MUST be a multiple of 320 KiB (327,680 bytes).
3. A byte range size of 10 MiB for stable high speed connections is optimal.
4. The recommended fragment size is between 5-10 MiB.
5. Use a byte range size that is a multiple of 320 KiB (327,680 bytes).

and then with all of these confusing statements, the example on this page uses a 26 byte range as it uploads bytes 0 through 25.  I am confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c42d74d1-8c6f-5282-9fba-30fdd6449362
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [driveItem: createUploadSession - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
