### ISSUE TITLE
Permission requirements all need updating

### ISSUE THREAD

**Issue by danmyhre** [microsoftgraph/microsoft-graph-docs-contrib#343]
These pages are missing the Sites.Selected scope in the permissions. That should be the least permissive scope required and is what people should be using when building app-based permissions for a given site or set of sites.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 264d21e6-769e-9a35-80b7-681a7060a3c2
* Version Independent ID: c430818f-ce11-f080-6c6c-25943efabcef
* Content: [Working with SharePoint sites in Microsoft Graph - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/sharepoint.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
