### ISSUE TITLE
Considerations for multi geo environment 

### ISSUE THREAD

**Issue by megdheep** [microsoftgraph/microsoft-graph-docs-contrib#349]
Per Kevin Lam (MS) 
To fully enumerate all (non-root) sites on all geos, you will need to do this initial request to discover all geos; then use the returned root site URLs to compose further requests against each geo to enumerate all sites on that geo. Unfortunately this latter step cannot be done using Microsoft Graph - it needs to be a request directly against the sharepoint tenant, using a separate oauth token valid for that tenant/geo combination. These follow up requests would look something like:
GET https://{tenant}.sharepoint.com/_api/v2.0/sites

GET [https://{tenant}-EUR.sharepoint.com/_api/v2.0/sites]

GET [https://{tenant}-APC.sharepoint.com/_api/v2.0/sites]

etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b05ccb12-48fb-7f65-a695-0846564d2bc2
* Version Independent ID: 769c63c0-4981-7506-8320-56beafaa8770
* Content: [List sites - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/site-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
