### ISSUE TITLE
Please remove the beta note from the v1.0 Documentation page

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs-contrib#35]
Please refer the error in the documentation

<img width="743" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/30771683/511f727b-2787-40b3-9dc3-213ef8b797df">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31ace01e-5ee0-f37f-4fc5-2bb6a96ba41c
* Version Independent ID: 988d3a03-bc1b-ab5f-7f5d-6be1846bfae7
* Content: [taskFileAttachment: createUploadSession - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/taskfileattachment-createuploadsession?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/taskfileattachment-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/taskfileattachment-createuploadsession.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @avijityadav
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this has been fixed. Thanks.
