### ISSUE TITLE
The documentation requires more detail to be useful (sharing links)

### ISSUE THREAD

**Issue by javieralvarezchiang** [microsoftgraph/microsoft-graph-docs-contrib#351]
The documentation requires more detail to be useful to an outsider.

From the page:

> To use a sharing URL with this API, your app needs to [transform the URL into a sharing token](https://docs.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http#encoding-sharing-urls).

The page even has the algorithm to encode the URL. However, there is no mention of the origin of the URL. Is that a driveItem URL from Graph? Is it the webURL from the driveItem properties? Is it something completely different?

link: https://docs.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f0e42a-0fc2-905d-b105-0b3de895e351
* Version Independent ID: 340a3a14-6067-15bb-3be3-a789caa31a44
* Content: [Access shared items - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/shares-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/shares-get.md)
* Product: **files**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
