### ISSUE TITLE
Incorrect info in Application permission section

### ISSUE THREAD

**Issue by saraamini8** [microsoftgraph/microsoft-graph-docs-contrib#352]
Hello.

Comparing the information of this page with the English format [here ](https://docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-1.0), we can see that in _**Permission**_ section, "Application" permission is listed incorrectly.

Checking this permission in a Tenant, I believe the English document is the correct one and this API dose not support Application permissions.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des défis GitHub.*

* ID: 20025e12-d3a6-2655-9117-61f8dbc59885
* Version Independent ID: 57ea5085-7ea5-383d-fbe0-c78d8e9b20d4
* Content: [List bookingBusinesses - Microsoft Graph v1.0](https://docs.microsoft.com/fr-fr/graph/api/bookingbusiness-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs.fr-FR/blob/main/api-reference/v1.0/api/bookingbusiness-list.md)
* Product: **bookings**
* Technology: **microsoft-graph**
* GitHub Login: @arvindmicrosoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed already. Thanks.
