### ISSUE TITLE
The documented values for role are incorrect here

### ISSUE THREAD

**Issue by martinlingstuyl** [microsoftgraph/microsoft-graph-docs-contrib#354]
The documented values for role are not correct here.

If I would post at the following endpoint:
`https://graph.microsoft.com/v1.0/sites/<site-id>/permissions`

or if I patch at the following endpoint:
`https://graph.microsoft.com/v1.0/sites/<site-id>/permissions/<permission-id>`

using the following json:
```json
{
	"roles": [
	  "owner"
	],
	"grantedToIdentities": [
	  {
		"application": {
		  "id": "<some-application-id>",
		  "displayName": "My AAD app"
		}
	  }
	]
}
```

I'm getting the following error:
`Invalid value for role`

**However...**
What does work is the following:
1. Create the permission by first posting the role `read` or `write`.
2. Patch the permission using the role `manage` or `fullcontrol`, the call comes through successfully and the permissions are assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1191235c-879e-dffc-82eb-4e8f7edfd29c
* Version Independent ID: 322f9be4-7921-41d8-78c2-2bdc62f916a3
* Content: [Permission - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0#roles-property-values)
* Content Source: [api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/permission.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
