### ISSUE TITLE
NextPageRequest is null in CollectionPage batch object

### ISSUE THREAD

**Issue by bretthacker** [microsoftgraph/microsoft-graph-docs-contrib#357]
Title says it. This may be a .Net SDK issue but when calling a collection directly, the PageIterator leverages the pre-populated NextPageRequest property to iterate through multiple pages of a response. But **the response from a batch call leaves this null** in the "Value" property (the CollectionPage). The CollectionResponse DOES have a "NextLink" string property, and this is effectively what's needed.

So for a batch response containing multiple pages, it's necessary to notice that "NextLink" is not null, then call InitializeNextPageRequest on the CollectionPage of the CollectionResponse:

`var page = memberRes.Value;

if (memberRes.NextLink != null)
{
    page.InitializeNextPageRequest(_client, memberRes.NextLink);
}`

This enables the PageIterator to do it's thing.

Since this has apparently been an issue since at least 2020, it might be best to document this workaround.
https://stackoverflow.com/questions/63292329/microsoft-graph-sdk-request-next-link-of-the-batch-response/65193048

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e33b4529-dfaa-b051-a73e-fa7312e911f5
* Version Independent ID: 55111137-63ad-3408-9295-ef44128aed14
* Content: [Combine multiple requests in one HTTP call using JSON batching - Microsoft Graph](https://docs.microsoft.com/en-us/graph/json-batching?context=graph%2Fapi%2F1.0&view=graph-rest-1.0)
* Content Source: [concepts/json-batching.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/json-batching.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@bretthacker Sorry for taking so long to tackle this one, but I do come with good news! The new Graph SDK (5.x) solves this problem, and collection responses pulled from batch responses now work out of the box with `PageIterator`.

For example, I tried this `MessageCollectionResponse` test, which worked as expected:

```csharp
var messagesRequest = graphClient.Me.Messages.ToGetRequestInformation();

// Build the batch
var batchRequestContent = new BatchRequestContentCollection(graphClient);

var messagesRequestId = await batchRequestContent
    .AddBatchRequestStepAsync(messagesRequest);

var returnedResponse = await graphClient.Batch.PostAsync(batchRequestContent);

var messages = await returnedResponse
    .GetResponseByIdAsync<MessageCollectionResponse>(messagesRequestId);
Console.WriteLine($"You have {messages.Value?.Count} messages.");

var iterator = PageIterator<Message, MessageCollectionResponse>
    .CreatePageIterator(
        graphClient,
        messages,
        (msg) =>
        {
            Console.WriteLine(msg.Subject);
            return true;
        });
await iterator.IterateAsync();
```

I'm closing this issue since the SDK supports this scenario now. If I've misunderstood the problem, or if you have any questions, feel free to let me know.
