### ISSUE TITLE
aboutMe and other SPO properties require Sites.ReadWrite.All

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs-contrib#36]
Folks,

Can you please verify that updating certain (Delve/SPO) properties such as aboutMe, birthday, etc all require permissions on SPO side as well. In particular, when updating such properties on another user, you need Sites.ReadWrite.All or equivalent.

Without such permissions granted, the request will result in the following error:

```
        "code": "-1, Microsoft.Office.Server.Directory.DirectoryObjectUnauthorizedAccessException",
        "message": "Attempted to perform an unauthorized operation.",
```

Please verify and update the document as needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
