### ISSUE TITLE
API is not available

### ISSUE THREAD

**Issue by dev-tony-hu** [microsoftgraph/microsoft-graph-docs-contrib#365]
This API always return empty collection when trying use graph explorer to retrieve site permissions with this api.
Not sure if anything wrong with my test,I shared this site to some persons in my tenant.Even when I try to use beta endpoint, same result.

Request and response are below, use [domain] replace my host.
> https://graph.microsoft.com/v1.0/sites/[domain].sharepoint.com,6f22c9d5-c32d-430d-b089-1e9eadbac5ec,df85d5e3-97bc-431c-8754-e4deb8ab9826/permissions
``` json

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#sites('[domain].sharepoint.com%2C6f22c9d5-c32d-430d-b089-1e9eadbac5ec%2Cdf85d5e3-97bc-431c-8754-e4deb8ab9826')/permissions",
    "value": []
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84ceb9ba-94da-4909-6b6d-82b6c5c112e0
* Version Independent ID: 01c96dd9-45f7-50d9-a899-baf6ce7faedb
* Content: [List permissions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-list-permissions.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @barrysh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
