### ISSUE TITLE
Graph API query options, improve documentation

### ISSUE THREAD

**Issue by tor-axbit** [microsoftgraph/microsoft-graph-docs-contrib#373]
I just spent a long time finding out that I can not filter Graph list items with `$filter=createdDateTime ge '<DATE_STRING>'` . The documentation states that `createdDateTime` is among the list item properties. However, I can not find very specific info on which properties are queriable, and more importantly, which query options do *not* work. 

I have a notion of spending too much time on manually exploring the combinatorics of Graph queries. I would greatly appreciate if the Graph API documentation in general would be more specific regarding query options, perhaps expanding the properties table with ($filter: yes/no) or similar.  So that is my suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e00d6372-f1f5-58ea-0fdf-90496cc68abf
* Version Independent ID: 82a66768-cf64-369a-944f-fb6c282b340b
* Content: [listItem resource - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/listitem.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
