### ISSUE TITLE
[Item Analytics] - Java Snippet Doesn't work

### ISSUE THREAD

**Issue by Jatish-Khanna** [microsoftgraph/microsoft-graph-docs-contrib#374]
The Java Snippet suggest to invoke allTime() or lastSevenDays() on analytics() method. The method is available in a different RequestBuilder. 

I've raised a [PR](https://github.com/microsoftgraph/msgraph-sdk-java/pull/1155) to fix the issue in SDK so Graph API, Documentation, and SDK are inline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc23aedb-c478-2515-0d37-a3683897eebc
* Version Independent ID: 60536091-1ce7-fde8-9e39-115517304400
* Content: [Get itemAnalytics - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/itemanalytics-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/itemanalytics-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/itemanalytics-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @daspek
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
Hi @Jatish-Khanna . Thanks for raising this issue.

The code snippets were updated based on the new [Microsoft Graph Java v6 version](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v6.1.0). You can check more info about the new version in the [v6 announcement blog post](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/).

When using v6 in my project, allTime method is available as the following:
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/22648831/b13ed0a1-4cd7-48c6-abd7-0e7d8b30c3d9)
