### ISSUE TITLE
All user's drives have the same name.

### ISSUE THREAD

**Issue by cylvoon** [microsoftgraph/microsoft-graph-docs-contrib#376]
When a user has several drives, name given by graph is always 'OneDrive' whereas the real drive's name is in the webUrl.
For instance, on a demo tenant, https://graph.microsoft.com/v1.0/me/drives?$select=name,weburl gives me the following response:

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drives(name,webUrl)",
    "value": [
        {
            "name": "OneDrive",
            "webUrl": "https://m365x******-my.sharepoint.com/personal/admin_m365x*******_onmicrosoft_com/PreservationHoldLibrary"
        },
        {
            "name": "OneDrive",
            "webUrl": "https://m365x*******-my.sharepoint.com/personal/admin_m365x*******_onmicrosoft_com/Documents"
        },
        {
            "name": "OneDrive",
            "webUrl": "https://m365x*******-my.sharepoint.com/personal/admin_m365x*******_onmicrosoft_com/Another%20library"
        }
    ]
}

This is definitely a bug.
Any idea whether it'll be fixed one day?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a83333f0-4746-a5d6-d66d-b1a5fccba828
* Version Independent ID: dfad0e75-10f8-374d-4dde-65372c4019da
* Content: [List Drives - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/drive-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/drive-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/drive-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Comment by cylvoon** [comment]
@PaoloPia I'm sorry but I'm fed up with Microsoft always closing the issues without fixing them! Just do your job for once!
