### ISSUE TITLE
The table "To update the profile photo of a group" is incorrect.

### ISSUE THREAD

**Issue by mikumeda** [microsoftgraph/microsoft-graph-docs-contrib#377]
The "To update the profile photo of a group" shows that updating the profile photo of a group is supported with Group.ReadWrite.All
permission in App-only permission.

![image](https://user-images.githubusercontent.com/61782095/186341207-edf9fbe5-1224-4cd9-8728-655c8f893d29.png)

But the desciption written in the following, says that there's a known issue that does not support application permission.

![image](https://user-images.githubusercontent.com/61782095/186341423-a0c1097f-81fb-4b44-bf86-460e347181df.png)

This is quite confusing for us and customers, so, maybe changing the "Group.ReadWrite.All" to "Not supported" with the link following.

https://docs.microsoft.com/en-us/graph/known-issues#groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d517bc8-e757-3822-848a-bf6b65d456b5
* Version Independent ID: ed8cafa6-65b9-fe58-57b3-3d57676fae46
* Content: [Update profilePhoto - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/profilephoto-update.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Thanks.
