### ISSUE TITLE
Site.read permission also required along with Files.Read.All permission while searching OneDrive items 

### ISSUE THREAD

**Issue by Vickyk1** [microsoftgraph/microsoft-graph-docs-contrib#378]
**Issue** 
Trying to reach out to OneDrive and searching file through API - https://graph.microsoft.com/v1.0/drive/root/microsoft.graph.search(q='File_Name')

 Already have permissions - "User.Read.All", "Files.Read.All" , but still got 403 error 

**Resolving steps:**
Tried to provide Sites.Read.All, permissions and it start working.
 
**Question:**
As per the docs, its mentioned that, one of the following permissions is required to call this API, as shown in the below screenshot 
<img width="487" alt="image" src="https://user-images.githubusercontent.com/99316327/186101776-f83b9ce4-f06b-4aa8-8ce7-66030ca55523.png">

If Site.read permission also required along with Files.Read.All permission, then document should be correctly updated.

doc - https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=java

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de33ed18-c074-a734-0b01-648888cb94aa
* Version Independent ID: 9fa15051-394e-d4ce-4687-c93be0ca8b80
* Content: [Search for files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/driveitem-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-search.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
