### ISSUE TITLE
Mismatch between example and SDK

### ISSUE THREAD

**Issue by vreddy-regis** [microsoftgraph/microsoft-graph-docs-contrib#381]
[Enter feedback here]
Using java example.

`AttachmentCollectionPage attachmentCollectionPage = new AttachmentCollectionPage(attachmentCollectionResponse, null);`

This line above is listed; however, AttachmentCollectionRequestBuilder the second param is non-nullable. What is an example of something I put in there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=java#example-3--create-a-message-with-a-file-attachment-and-send-the-message)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-sendmail.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
The code snippet was updated based on the new [v6 version](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v6.1.0) and there is no such thing anymore. You can check more info about the new version in the [v6 announcement blog post](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/).
