### ISSUE TITLE
Please mention in the documentation about how the search=*  works

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs-contrib#382]
Please specify in the documentation how this query works and what it is supposed to return https://graph.microsoft.com/v1.0/sites?search=* ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b05ccb12-48fb-7f65-a695-0846564d2bc2
* Version Independent ID: 769c63c0-4981-7506-8320-56beafaa8770
* Content: [List sites - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/site-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
