### ISSUE TITLE
Improve documentation for uploading files to Sharepoint via Graph

### ISSUE THREAD

**Issue by mmarcotte** [microsoftgraph/microsoft-graph-docs-contrib#386]
Your docs for uploading files to a Sharepoint page specify:

```
PUT /sites/{site-id}/drive/items/{parent-id}:/{filename}:/content
```

However, I found that confusing for a few reasons.

1. `{parent-id}` is not documented elsewhere on this page. It could be a resource? Or name of the folder within which to put the file? 
2. I could not get `/drive/items/` to work, and I could only get `/drive/root` to work.
3. If the file is to be uploaded into a directory, that is included in the filename. For example, I was able to upload into a directory using the following api call 

    `/sites/${siteId}/drive/root:${folderName}/${filename}:/content`

    `folderName` can be blank or it must be prefixed with a slash

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92fb8c7-4409-d945-57dd-5d6fc4010051
* Version Independent ID: f77c05bd-2688-bd4e-1f8f-f18feb3a8639
* Content: [Upload small files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
