### ISSUE TITLE
followedSites not returning all followed sites

### ISSUE THREAD

**Issue by Cyanic-Cloud** [microsoftgraph/microsoft-graph-docs-contrib#391]
Hello,

The following https://graph.microsoft.com/v1.0/users/$userID/followedSites will not return all followed sites.
I have tried both beta and v1.0, the results only return some followed sites but not all.
I am querying followed sites using app reg with the required permissions.

I see someone else also having the same issue on this site:
https://sharepoint.stackexchange.com/questions/301618/followed-sites-graph-api-not-working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a90f3751-7331-ff8b-e20a-fa81cbcfe631
* Version Independent ID: 96802ec9-c33a-247f-269a-85640b3887bd
* Content: [List followed sites - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/sites-list-followed?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/sites-list-followed.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/sites-list-followed.md)
* Product: **sites-and-lists**
* Technology: **microsoft-graph**
* GitHub Login: @learafa
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
