### ISSUE TITLE
availabilityView missing number 

### ISSUE THREAD

**Issue by xSinTx** [microsoftgraph/microsoft-graph-docs-contrib#399]
Hello Team!
I have encountered a problem while working with getschedule. I noticed that in the "availabilityView" the 4th number is missing. (**4= working elsewhere**) I recreated the problem and attached some pictures of it. You can see a snipet of my code and my outlook in which there are three "working elsewhere" event. I copy-pasted the availabilityView numbers:
"000000003300000000000000000000000000000000000000000000022222000000000000001000000000000000000000000000000000000330000000"
It may only occur in my code but if not I hope you can solve it.
Best Regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a6748e9-6e15-db5e-f85f-79dbe8171e9b
* Version Independent ID: a30e4438-c54b-643f-5573-c904ace73e70
* Content: [Get free/busy schedule of Outlook calendar users and resources - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-get-free-busy-schedule#feedback)
* Content Source: [concepts/outlook-get-free-busy-schedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-get-free-busy-schedule.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Tariq-Sharif
* Microsoft Alias: **MSGraphDocsVteam*
![availabilityTime1](https://user-images.githubusercontent.com/86297448/181359499-11b6231b-9863-4fec-a138-7dfba323106c.png)
![availabilityTime2](https://user-images.githubusercontent.com/86297448/181359529-fb3ce6cb-0b44-45f8-8f84-7022e2a434e4.JPG)
*

**Comment by nicolaibaralmueller** [comment]
I can confirm.

https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8680

**Comment by nicolaibaralmueller** [comment]
What is the estimated time for fixing this?
