### ISSUE TITLE
cTag info in table is wrong or contradictory

### ISSUE THREAD

**Issue by ajweber** [microsoftgraph/microsoft-graph-docs-contrib#406]
In the cTag field description, it is noted that the value is not returned for folders.  I believe this is incorrect, and it IS returned for folder driveItems per the contradictory comment at the end of that table regarding how cTag and eTags work for folders.  (Though I'm not sure either are getting updated when the number of childItems changes...but that's a different issue...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cae3149-c915-eee0-29da-5f5d515c3019
* Version Independent ID: 334d5d8f-79ec-6063-a026-c09a2f764b9a
* Content: [driveItem resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/driveitem.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
