### ISSUE TITLE
expand parameter: Which relationships are expandables?

### ISSUE THREAD

**Issue by habex-ch** [microsoftgraph/microsoft-graph-docs-contrib#4088]
Hi there,

how can I find out if a relationship is expandable or not?

E.g. when I get a team (https://docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&tabs=csharp). 
The relationship "primaryChannel" is expandable, the relationship "channels" is not. 

Is there a way without testing it?
It would be good if this documentation points this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#expand-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nivedipa-MSFT** [comment]
@habex-ch - We received an update from the engineering team stating that currently, there is no way to determine which relationship properties are expandable in each context.
