### ISSUE TITLE
How to get the Password Reset status using MS Graph SDK

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/microsoft-graph-docs-contrib#41]
We need to document how to use MS Graph SDKs to get the MS Graph HTTP response location header so that the Password Reset Status can be queried...
[https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#native-response-object](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmsgraph-sdk-dotnet%2Fblob%2Fdev%2Fdocs%2Fupgrade-to-v5.md%23native-response-object&data=05%7C01%7Cwillfid%40microsoft.com%7Cfaefdc51278642b68a3c08db86d77d16%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638252032350942139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=02FJ6GgTYxUn9jqQN0e5LKDMSfzltWkZnlu0bzUqoKw%3D&reserved=0)

So for example when using .NET SDK...
var requestBody = new Microsoft.Graph.Users.Item.Authentication.Methods.Item.ResetPassword.ResetPasswordPostRequestBody
                        {
                            NewPassword = "Cuyo5459",
                        };

                        var nativeResponseHandler = new NativeResponseHandler();
                        var result = await client.Users["{user-id}"].Authentication.Methods["28c10230-6103-485e-b985-444c60001490"].ResetPassword.PostAsync(requestBody, requestConfiguration => requestConfiguration.Options.Add(new ResponseHandlerOption() { ResponseHandler = nativeResponseHandler }));
                        var responseMessage = nativeResponseHandler.Value as HttpResponseMessage;

                        var location = responseMessage.Headers.Location;

                        RequestInformation request = new RequestInformation
                        {
                            URI = location,
                            HttpMethod = Method.GET
                        };
                        var passwordResetStatus = await client.RequestAdapter.SendAsync(request, PasswordResetResponse.CreateFromDiscriminatorValue);

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe81600e-7193-3178-0e9c-44055f5138e4
* Version Independent ID: 19ba9c42-1b6d-5193-3d9e-64bcf668004f
* Content: [passwordAuthenticationMethod: resetPassword - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/authenticationmethod-resetpassword?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/authenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authenticationmethod-resetpassword.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
I've put a fix for the API path in the beta topic into our publishing pipeline, which is all we can do in this repo. The other issue will have to be addressed in the snippet generator. Closing this issue.
