### ISSUE TITLE
How to get existing uploadUrl when /createUploadSession gives a 409?

### ISSUE THREAD

**Issue by jbt-jaime** [microsoftgraph/microsoft-graph-docs-contrib#412]
Most of the time I can successfully upload large files via an upload session. However, sometimes while developing and testing, when creating the upload session, I get a 409 Conflict  (`"error":{"code":"nameAlreadyExists","message":"A file with the same name is currently being uploaded. Change the filename and try to save again."`). This is despite my `conflictBehavior='replace'`, but apparently [that's just how it is](https://github.com/OneDrive/onedrive-api-docs/issues/747).

To work around the 409, I want to delete the existing upload session and retry creating it, but [to cancel an upload session I have to send a DELETE to the upload URL](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#cancel-the-upload-session), which is the very thing I'm trying to create with my call to `/createUploadSession`. How do I get the upload session then?

It'd be nice if the 409 can also return the very uploadUrl it is referring to. Alternatively, if there is a way to get that upload session, it'd be nice for the docs to mention it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c42d74d1-8c6f-5282-9fba-30fdd6449362
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [driveItem: createUploadSession - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
