### ISSUE TITLE
Contradictory guidance regarding presenter role assignment caveat

### ISSUE THREAD

**Issue by bretthacker** [microsoftgraph/microsoft-graph-docs-contrib#415]
The following guidance is contradictory. It says the create method will be accepted but the role isn't applied, then it immediately says the create method will be rejected with a 400.

`
Assigning the presenter or coorganizer role to users who are not registered in Azure Active Directory is not currently supported. Such requests will be accepted by the [create onlineMeeting](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings.md) method, but the role will not be applied when the participant joins the online meeting. The [create onlineMeeting](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings.md) method will reject the request and return a 400 Bad Request error.
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ab98f77-bf6f-4ce6-c189-dec2444a1bac
* Version Independent ID: ec5464a8-4def-9074-6e50-0b737b41b631
* Content: [Known issues with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/known-issues#presenter-role-cannot-be-assigned-to-non-azure-ad-participants)
* Content Source: [concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as the known issue was resolved. Thanks.
