### ISSUE TITLE
Channel property isFavoriteByDefault not being applied

### ISSUE THREAD

**Issue by YJasonY** [microsoftgraph/microsoft-graph-docs-contrib#417]
According to this: https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0#properties
The channel property "isFavouriteByDefault" should automatically be marked as 'favourite' for all members of a team. That means it should not be hidden. 

We have tried to apply this setting but the channels remain hidden.

Here is an example using the Graph Explorer:

1. Create team, define channels and set the isFavouriteByDefault property:
![image](https://user-images.githubusercontent.com/16281323/177232138-03659305-4f63-4242-8208-b72dc6d26b69.png)

2. Create team response
![image](https://user-images.githubusercontent.com/16281323/177232181-ec0065f5-3257-4e3d-8b25-9f4f6aa02b40.png)

3. Result - channels remain hidden:
![image](https://user-images.githubusercontent.com/16281323/177232194-70f19d5c-d976-4112-ba26-2f0525447569.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f86208-723e-a0c9-2cce-3e681dfa7b9c
* Version Independent ID: dc38068e-3b39-1352-117d-e770485b7b70
* Content: [channel resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/channel.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f86208-723e-a0c9-2cce-3e681dfa7b9c
* Version Independent ID: dc38068e-3b39-1352-117d-e770485b7b70
* Content: [channel resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/channel.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PieterVandendriessche** [comment]
@Meghana-MSFT Any update on this issue? My customer is facing the same issues.

**Comment by MasoudSamadi** [comment]
Any updates on this bug?!
Issue is reported on July 5th, 2022! (1,5 years ago)! and this is still not resolved?

**Comment by Meghana-MSFT** [comment]
Could you provide with a client request id/set of response headers (like in the screenshot) so team can look at the logs? Engineering team is unable to repro internally.
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/81138249/b79e664e-ff2d-489a-b4a2-b0f00c34b2bf)

**Comment by kdfarquharson** [comment]
Hi - Please see below, two response headers where the channels were not shown/favourite by default:
{ "Transfer-Encoding": [ "chunked" ], "Location": [ ***@***.***')" ], "Strict-Transport-Security": [ "max-age=31536000" ], "request-id": [ "6580c7d0-6b1e-4c25-8a15-7eab5380cb2a" ], "client-request-id": [ "6580c7d0-6b1e-4c25-8a15-7eab5380cb2a" ], "x-ms-ags-diagnostic": [ "{\"ServerInfo\":{\"DataCenter\":\"UK South\",\"Slice\":\"E\",\"Ring\":\"3\",\"ScaleUnit\":\"000\",\"RoleInstance\":\"LN2PEPF00006696\"}}" ], "OData-Version": [ "4.0" ], "Date": [ "Thu, 18 Jan 2024 16:42:39 GMT" ], "Content-Type": [ "application/json; odata.metadata=minimal; odata.streaming=true; IEEE754Compatible=false; charset=utf-8" ] }
Also
{ "Transfer-Encoding": [ "chunked" ], "Location": [ ***@***.***')" ], "Strict-Transport-Security": [ "max-age=31536000" ], "request-id": [ "0ef01077-ecd6-46e0-a698-97ef943ce569" ], "client-request-id": [ "0ef01077-ecd6-46e0-a698-97ef943ce569" ], "x-ms-ags-diagnostic": [ "{\"ServerInfo\":{\"DataCenter\":\"UK South\",\"Slice\":\"E\",\"Ring\":\"3\",\"ScaleUnit\":\"000\",\"RoleInstance\":\"LN2PEPF0000452D\"}}" ], "OData-Version": [ "4.0" ], "Date": [ "Thu, 18 Jan 2024 16:42:47 GMT" ], "Content-Type": [ "application/json; odata.metadata=minimal; odata.streaming=true; IEEE754Compatible=false; charset=utf-8" ] }
________________________________

**Comment by Meghana-MSFT** [comment]
Thank you for the details, we have shared these with engineering team.

**Comment by PieterVandendriessche** [comment]
Hello, please note that on a similar issue could be reproduced, see https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8787

**Comment by Meghana-MSFT** [comment]
Engineering team has looked into above logs and has the following request. Could you please share  - 

looking into those logs, I can see that we are missing a couple of network requests that we'd expect to see from channels being set as favDefault. In particular, there are the calls to show the channel for the team owner, and a call to confirm that the channel was set as default.

It would be easier for us to investigate this if the channel was created as part of the create team flow, as the create channel flow functions differently when being created from the graph api vs. the client. Apologies for the back-and-forth here, but I would like to make one more request of them.

Could you have them create the channel as part of a team using the following payload on the graph api? Below is also a screenshot of what the graph explorer should look like at the time of creation-- I will need the response headers once again. Thank you!

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/81138249/fb3f0743-15e9-42c1-a938-14b31c400ecb)
