### ISSUE TITLE
Web URL - File with .msg extension

### ISSUE THREAD

**Issue by Jatish-Khanna** [microsoftgraph/microsoft-graph-docs-contrib#419]
1. Create a new file or upload a new file on the SP drive with the extension ".msg" (Outlook message)
2. Get the item details using the graph explorer or graph API
3. The Web URL has been created differently from the O365 (Word, Excel, PPT) - Doesn't give a preview on the browser but stores a downloadable file

Note: It should give the preview URL for the file similar to O365 and similar for other formats supported a preview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14f44873-e61b-3f77-e2ad-b46112b065b2
* Version Independent ID: 3ef66bdc-06cf-4356-4e1e-f4d7bed17dcb
* Content: [Get listItem - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/listitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
