### ISSUE TITLE
Minimal size of image to upload

### ISSUE THREAD

**Issue by Sara-chi** [microsoftgraph/microsoft-graph-docs-contrib#423]
I tried to upload an image that was very small (23x23) as a group's photo.
I got this exception:
```
Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: ValidationWidthTooSmall
Message: Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileBadRequestException' was thrown.
```
I am assuming the image size is too small, but what is the minimal size? I can not find this information on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d517bc8-e757-3822-848a-bf6b65d456b5
* Version Independent ID: ed8cafa6-65b9-fe58-57b3-3d57676fae46
* Content: [Update profilePhoto - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/profilephoto-update.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Thanks.
