### ISSUE TITLE
Shared property not set when sharing links with specific people in SharePoint

### ISSUE THREAD

**Issue by xzuttz** [microsoftgraph/microsoft-graph-docs-contrib#426]
For the shared property, the documentation states:

>Indicates that the item has been shared with others and provides information about the shared state of the item. Read-only.

In SharePoint, when sharing a driveitem with Specific people, SharePoint produces a link that recipients can use to view or edit the file. 

Unfortunately the shared facet property will not be set in this situation, thus being unreliable, as the file is can be shared with someone outside of the organization.

The workaround is to call the /permissions endpoint on all driveitems.

It would be nice with some explanation on this behaviour for sharing links or some indication of scenarios where the shared property will be null, even though the file is directly shared.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cae3149-c915-eee0-29da-5f5d515c3019
* Version Independent ID: 334d5d8f-79ec-6063-a026-c09a2f764b9a
* Content: [driveItem resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/driveitem.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
