### ISSUE TITLE
Sites.Selected permission should be available in SharePoint REST/CSOM APIs.

### ISSUE THREAD

**Issue by akkomats** [microsoftgraph/microsoft-graph-docs-contrib#431]
Sites.Selected should now be available in production for SharePoint permissions in addition to Microsoft Graph.
Would you please change the description of the document as follows?

Before the change:
The Sites.Selected application permission is available only in the Microsoft Graph API.

After the change:
The Sites.Selected application permission is available in the Microsoft Graph API and SharePoint REST / CSOM APIs.

![image](https://user-images.githubusercontent.com/56673047/174754429-138c9366-bc35-45a2-bf6a-c70121460ef0.png)

The "API permissions" setting in Azure AD admin center shows the "Sites.Selected" application permissions for the SharePoint resource (https://microsoft.sharepoint-df.com/Sites.Selected), and I verified that the "Sites.Selected" permission works with the SharePoint REST API v1.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9edcc46d-c145-fad7-a54c-52c21f05ab7c
* Version Independent ID: 8b6bcf33-b048-2d3c-33b5-5a3dd5d25a75
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#sites-permissions)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
