### ISSUE TITLE
Is there any document about 21v support DriveItem change tracking (Delta)

### ISSUE THREAD

**Issue by dev-tony-hu** [microsoftgraph/microsoft-graph-docs-contrib#44]
I searched the Microsoft Graph document, but didn't find any update about DriveItem delta updates. But when after testing, I found Drive Item Delta API works on 21v now.
Would you help to confirm and update it in document?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2dbd263-9afd-aa90-cb50-bbadfc424cc2
* Version Independent ID: 63aaf699-609e-b4dd-bd02-9f891e09db8d
* Content: [National cloud deployments - Microsoft Graph](https://learn.microsoft.com/en-us/graph/deployments#supported-features)
* Content Source: [concepts/deployments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/deployments.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @adamedx
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
