### ISSUE TITLE
Get a driveItem resource restricted property 

### ISSUE THREAD

**Issue by ashleywb** [microsoftgraph/microsoft-graph-docs-contrib#442]
We've had some problems trying to download files with the following property 
 "restricted": {
        "decision": "Restricted",
        "restrictionType": "OwnerOnly"
    },

![image](https://user-images.githubusercontent.com/9212081/170953730-c22d7936-edd5-4f7a-9500-bdab9b7fc98d.png)

I can't seem to find any documentation on this property unless I have missed something. When trying to download the file with a generated shared link we get the following
The sharing link no longer exists, or you do not have permission to access it
When using the path, we get 404 not found.

We are using application token with Sites Full Control. Can you help? 

Using csom OpenBinaryStream works without any issue, but does have limitations around size of the files
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cae3149-c915-eee0-29da-5f5d515c3019
* Version Independent ID: 334d5d8f-79ec-6063-a026-c09a2f764b9a
* Content: [driveItem resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/driveitem.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
