### ISSUE TITLE
Documentation should emphasize that the order in the 'item' block is important

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/microsoft-graph-docs-contrib#444]
For createUploadSession:

`{"item":{"@microsoft.graph.conflictBehavior":"fail","name":"README.MD"}}` Works fine
`{"item":{"name":"README.MD","@microsoft.graph.conflictBehavior":"fail"}}` is a bad request

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c42d74d1-8c6f-5282-9fba-30fdd6449362
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [Resumable file upload - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.

**Comment by JustinGrote** [comment]
@PaoloPia why create more work by making us open up a new issue? Why not just allow us to mark this issue as still active?
