### ISSUE TITLE
Need examples for more complex values

### ISSUE THREAD

**Issue by aaronrogers** [microsoftgraph/microsoft-graph-docs-contrib#461]
It's great to have an example for a number and a string, but how does one enter a location or a person?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa7a3906-32dd-fab9-a6f4-a5f8e55429ce
* Version Independent ID: 088ac63e-886e-71f2-bc9b-36f25f93305a
* Content: [Create a new entry in a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-create?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/listitem-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
