### ISSUE TITLE
Permissions Need Update

### ISSUE THREAD

**Issue by z105776003** [microsoftgraph/microsoft-graph-docs-contrib#473]
I ran the PATCH command through Postman to update the permission to 'Owner'. But an invalid request was returned.
After researching from PnP package.  I successfully updated the request by setting the permission to 'Full Control'.
So the permissions list should be updated, right?

snapshots:
![image](https://user-images.githubusercontent.com/52906621/166647545-7251826d-f045-45f9-bc06-825ce49e2e26.png)

PnP Reference:
https://pnp.github.io/powershell/cmdlets/Set-PnPAzureADAppSitePermission.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e33e463-d9a4-44da-7ee2-e47430f0c46a
* Version Independent ID: fb2136da-415c-1254-576d-9fb1cd2ad26c
* Content: [Update permission - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-update-permission.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @barrysh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
