### ISSUE TITLE
Problems with Managed Metadata fields (Taxonomy - TermStore)

### ISSUE THREAD

**Issue by bas-eenhoorn** [microsoftgraph/microsoft-graph-docs-contrib#483]
Hi,

I've been struggling a lot for the past time with Managed Metadata fields. I finally know how it should work.
The format is for the value to PATCH is:

{ "{HiddenFieldName}": "-1;{TermName}|{TermGuid}" }

Example for a document (and a document set), with a field Countries (to get HiddenFieldName, get hidden column 'Countries_0', then get property 'name' , which is 'hae3...'.):

PATCH https://graph.microsoft.com/v1.0/sites/{siteId}/lists/{listId}/drive/root:/DocumentSetName/SomeDocument.docx:/listItem/fields

{"hea3aa7566354b84a259beabe0c96f6e":"-1;Netherlands|b81212d2-c69d-eb11-ba76-001dd8d70282"}

It works just fine on the document. But when i try to PATCH a field on a document set (url example below), it gives me a 200 OK, the response contains the updated field, sharepoint says my document set is modified. But the value of the field of the document set is not updated at all.

PATCH https://graph.microsoft.com/v1.0/sites/{siteId}/lists/{listId}/drive/root:/DocumentSetName:/listItem/fields

So, I have 2 questions actually. 1) Am i doing something wrong? It seems to me that if it works for a document, it shouls also work for a document set.

And 2) can the documentation be updated? Its not only the managed metadata fields missing. Its also, for example, Date fields: There is no information that it requires dates to be in ISO_8601 format. There is no information about complex fields at all.

This project is costing me waaay too much time because there is only bits of information scattered around the internet about this subject..

Anyways, thanks for reading. Have a nice day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec4e338a-772e-0fc8-cff2-14d5a2f0d173
* Version Independent ID: 01362b8b-5f0b-4a40-d21f-0d27012c7311
* Content: [Update listItem - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/listitem-update.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
