### ISSUE TITLE
update profile photo docs page with ambiguous wording

### ISSUE THREAD

**Issue by MichaMican** [microsoftgraph/microsoft-graph-docs-contrib#486]
The page states "There is currently a [known issue](https://docs.microsoft.com/en-us/graph/known-issues#groups) with **accessing** group photos using application permissions." 
![image](https://user-images.githubusercontent.com/45571948/163974043-7763d5be-6fe7-4599-8639-0dfcbe9fc16e.png)
This reads like it only would effect **getting** the image, however this issue seems also to occure while trying to set/update a picture of a group.
This also stands in contradiction with the permission table further up in the documentation:
https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http#to-update-the-profile-photo-of-a-group
![image](https://user-images.githubusercontent.com/45571948/163973370-172f8751-236f-4a25-a202-f1ca2929749b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d517bc8-e757-3822-848a-bf6b65d456b5
* Version Independent ID: ed8cafa6-65b9-fe58-57b3-3d57676fae46
* Content: [Update profilePhoto - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/profilephoto-update.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Thanks.
