### ISSUE TITLE
Missing Examples

### ISSUE THREAD

**Issue by ShadiNM** [microsoftgraph/microsoft-graph-docs-contrib#488]
Hello,
this page is missing examples for how to create ListItems with more complex Columns. Specifically I am missing examples for

- choices columns that allow multiple choices
- Lookup Columns
- User columns

Can you please add an example for each Column Type so that we can start using the API without spending hours on trial and error?

Thanks
Shadi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 986fb32a-c9aa-fbad-12b2-30eef3d9f7b1
* Version Independent ID: 722992d5-18ee-5499-b2a6-440ac705d40a
* Content: [Create a SharePoint List - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/list-create?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/list-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/list-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
