### ISSUE TITLE
[400 Bad Request] invalidRequest error with CreateUploadSession with POST method(works with PUT!!)

### ISSUE THREAD

**Issue by SrinivasaRaoDarna** [microsoftgraph/microsoft-graph-docs-contrib#490]
Looks like there is this needs to be corrected in documentation. From POST /sites/{siteId}/drive/items/{itemId}/createUploadSession to PUT /sites/{siteId}/drive/items/{itemId}/createUploadSession.

When using POST /sites/{siteid}/drive/root:/{item-path}:/createUploadSession returns 400 Bad Request error, see below.
![POST__createUploadSession_Error](https://user-images.githubusercontent.com/103647265/163403086-3df119b3-3a1e-4057-8a92-3a6ea9c4b1b3.jpg)

But it works fine when using PUT /sites/{siteid}/drive/root:/{item-path}:/createUploadSession .
![PUT_createUploadSession_Error](https://user-images.githubusercontent.com/103647265/163401930-4dcd0723-c33b-48fe-8032-b8cb63d7bf84.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c42d74d1-8c6f-5282-9fba-30fdd6449362
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [Resumable file upload - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
