### ISSUE TITLE
Please add additional information related to the possible permission roles like FullControl to the documentation

### ISSUE THREAD

**Issue by LeHailender** [microsoftgraph/microsoft-graph-docs-contrib#493]
Please add (or highlight) into the documentation that you also can set beside Read and Write permissions the following list of permissions "Read"|"Write"|"Manage"|"FullControl". 

And that you need two calls when you want to set FullControl permissions.
First call set Read or Write permissions.
Second call to update with FullControl permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e33e463-d9a4-44da-7ee2-e47430f0c46a
* Version Independent ID: fb2136da-415c-1254-576d-9fb1cd2ad26c
* Content: [Update permission - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-update-permission.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @barrysh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
