### ISSUE TITLE
Is authentication strictly necessary for personal one drive

### ISSUE THREAD

**Issue by webczat** [microsoftgraph/microsoft-graph-docs-contrib#494]
When reading the page "using shared items" there is the remark:

> For OneDrive for Business and SharePoint, the Shares API always requires authentication and cannot be used to access anonymously shared content without a user context.

This implies that for personal account, I can access anonymously shared content without any form of authentication. However, when trying to do so using graph.microsoft.com, it says that the access token is empty, as in it seems to require authentication anyway.
However authentication is not required when doing that through api.onedrive.com. Not sure if this is a graph api bug, or if the documentation is misleading here. It should state that only api.onedrive.com works here, unless I am doing something wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f0e42a-0fc2-905d-b105-0b3de895e351
* Version Independent ID: 340a3a14-6067-15bb-3be3-a789caa31a44
* Content: [Access shared items - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/shares-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/shares-get.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
