### ISSUE TITLE
Site permissions query returns 200 OK and an empty response

### ISSUE THREAD

**Issue by a23s4a** [microsoftgraph/microsoft-graph-docs-contrib#497]
Querying site permissions return 200 OK and an empty response

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84ceb9ba-94da-4909-6b6d-82b6c5c112e0
* Version Independent ID: 01c96dd9-45f7-50d9-a899-baf6ce7faedb
* Content: [List permissions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-list-permissions.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @barrysh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by calmills** [comment]
Same issue here.

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
