### ISSUE TITLE
PowerShell Commands for Mailbox Settings?

### ISSUE THREAD

**Issue by twelch-ricohnz** [microsoftgraph/microsoft-graph-docs-contrib#50]
What happened to PowerShell here?
```
find-MgGraphCommand -Uri '/me/mailboxSettings'
Find-MgGraphCommand: URI ' https://graph.microsoft.com/v1.0/me/mailboxSettings' in  is not valid or is not currently supported by the SDK. Ensure the URI is formatted correctly and try again.
```
Neither V1.0 or Beta seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e6b8492-815a-5809-acef-a7551489dbea
* Version Independent ID: f80ffa1b-6461-cfbf-d909-a0d5bff3159f
* Content: [Get user mailbox settings - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-get-mailboxsettings.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by CarolKigoonya** [comment]
I tested and noticed we have an issue with find-MgGraphCommand -Uri '' for /me endpoints and raised an issue on the PowerShell SDK repo

**Comment by CarolKigoonya** [comment]
Issue has been closed in this PR https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2317
