### ISSUE TITLE
AuthenticationBehaviors showing unexpected results

### ISSUE THREAD

**Issue by wUEZRs** [microsoftgraph/microsoft-graph-docs-contrib#501]
Running the suggested PowerShell returns all apps as expected, but "AuthenticationBehaviors" for all apps return as "Microsoft.Graph.Beta.PowerShell.Models.MicrosoftGraphAuthenticationBehaviors"

How are one supposed to see any info one can do something with?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b022f494-e3a7-c99c-0c91-6de64870578d
* Version Independent ID: b022f494-e3a7-c99c-0c91-6de64870578d
* Content: [Manage application authenticationBehaviors to avoid unverified use of email claims for user identification or authorization - Microsoft Graph](https://learn.microsoft.com/en-us/graph/applications-authenticationbehaviors?tabs=http)
* Content Source: [concepts/applications-authenticationbehaviors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/applications-authenticationbehaviors.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by jasonjoh** [comment]
The `AuthenticationBehaviors` property is a complex type, so basic PowerShell output just shows the type name. A script like this would show the individual properties inside:

```powershell
$apps = Get-MgBetaApplication -Property "id,displayName,appId,authenticationBehaviors"

foreach ($app in $apps)
{
  Write-Host $app.DisplayName "Id: " $app.Id "App ID:" $app.AppId
  Write-Host "Block Azure AD Graph:" $app.AuthenticationBehaviors.BlockAzureAdGraphAccess
  Write-Host "Remove unverified email claim:" $app.AuthenticationBehaviors.RemoveUnverifiedEmailClaim
  Write-Host "Require client service principal:" $app.AuthenticationBehaviors.RequireClientServicePrincipal
  Write-Host
}
```
