### ISSUE TITLE
How to get the check-in comment

### ISSUE THREAD

**Issue by ThomasBarnekow** [microsoftgraph/microsoft-graph-docs-contrib#505]
Is there any way to get the check-in comment provided when checking in the driveItem resource (e.g., using the following API request)?

```
POST /drives/{drive-id}/items/{item-id}/checkin
Content-Type: application/json

{
  "comment": "Updating the latest guidelines"
}
```

The documentation is silent on whether or not this is possible. There is only an inconclusive issue on GitHub, which only talks about SharePoint lists. While it is generally possible to get version information via the list endpoints, the `_CheckinComment` is identical for all versions and equal to the last comment provided when checking in.

Getting the version information via the list endpoint looks like this:

```
GET https://graph.microsoft.com/v1.0/sites/{siteId}/lists/{listId}/items/{itemId}/versions
```

The response includes a `fields` property (with a JSON object) that contains the `_CheckinComment` property. However, as stated above, the values of those properties are always identical.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a80b4146-ab1c-7d90-aa65-106961f2b57a
* Version Independent ID: bf6b72db-acf6-3b9e-d24c-681c172035f7
* Content: [driveItemVersion resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/driveitemversion?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/driveItemVersion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/driveItemVersion.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
