### ISSUE TITLE
Cannot create without setting parent folder?

### ISSUE THREAD

**Issue by darren-kay** [microsoftgraph/microsoft-graph-docs-contrib#508]
In the sample code it shows you can create a folder without setting a parent folder:

```
await graphClient.Me.MailFolders
	.Request()
	.AddAsync(mailFolder);
```

But when I try it states it is not allowed:

![image](https://user-images.githubusercontent.com/88029168/158802364-c6849eb1-eb57-49d3-8e6f-d2182f2ff6f2.png)

According to docs you have to set a parent folder:

```
await graphClient.Me
        .MailFolders["parent folder id"]
	.Request()
	.AddAsync(mailFolder);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d375272-71af-2fb3-0fd0-bd66406a6fbd
* Version Independent ID: 57e430ff-dc8b-b198-c40d-7a8ff5b1e811
* Content: [Create MailFolder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-post-mailfolders.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Thanks.
