### ISSUE TITLE
Behaviour for SharePoint Document Libraries that require Check In

### ISSUE THREAD

**Issue by markholst** [microsoftgraph/microsoft-graph-docs-contrib#511]
I've managed to determine through trial and error that files copied into a Document Library that require check-in simply won't work if you are supplying the file name.  The operation succeeds with a 202, and checking the Location in the Response Header tells me it that all completed successfully.

If you exclude the file name it all just works.

I've had to build my own download/upload operation and force the check-in at the end of the operation.

I'm fine with this behaviour, it just would have been nice to have it documented and save me half a day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d887c2a6-40ba-675b-7b09-a7a3fffe17f5
* Version Independent ID: 03692ea1-b802-f768-a3bc-04a846b6771a
* Content: [driveItem: copy - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-copy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-copy.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
