### ISSUE TITLE
Create Item from home link becomes create folder need good guidance on create SharePoint file

### ISSUE THREAD

**Issue by JerryMWeeks** [microsoftgraph/microsoft-graph-docs-contrib#519]
[Enter feedback here]
Thanks for the as always, really useful information, but I have more or less hit a wall in create a file.
The link "Create Item" on this page [driveItem resource type](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0)
becomes create folder - which is an item, but is not very useful before you have learnt how to create a simple file.

The guidance for create a file (SharePoint online - some site, one of the 20 document libraries on that site) is a little light on guidance.
I am really struggling around this "PUT /sites/{site-id}/drive/items/{parent-id}:/{filename}:/content"
on [Upload or replace the contents of a DriveItem](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http)
I get site id using GET: https://graph.microsoft.com/v1.0/sites/{company}.sharepoint.com:/sites/{site} using a token issued by an Azure app service registration with these scopes: Sites.Read.All Files.ReadWrite.All
The site id is returned as {company}.sharepoint.com, {guid}, {guid} like this: "id": "somecompany.sharepoint.com,3456789-1234-5678-b2a1-a6789bb5a724,1234a46c-1234-5678-912a-6c6475bb1269",
(above modified for security reasons)
I then use that in PUT /sites/{site-id}/drive/items/{parent-id}:/{filename}:/content
like this: https://graph.microsoft.com/v1.0/sites/somecompany.sharepoint.com,3456789-1234-5678-b2a1-a6789bb5a724,1234a46c-1234-5678-912a-6c6475bb1269/drive/items/b!5vSzRiIpR0mgxshhPMT2ESvFc5gwhpZDkD5sZHW7EmmSpz1MUGHjTZsEhT6G17XW:/file.txt:/content
aaaaa
run in Postman with the valid token causes 400 invalidRequest - is site id for this call different than site id returned in the GET call?
or is the way I am using it incorrect?

![image](https://user-images.githubusercontent.com/19207251/155119391-fc46c7dd-0a56-423e-aec1-253690db0ee1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9069032a-3cb9-37df-9ef5-3901aad572e0
* Version Independent ID: 37fce8f3-cd7c-2450-b1ee-95956653d179
* Content: [Create a new folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-post-children.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-post-children.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
