### ISSUE TITLE
Encoding not specified

### ISSUE THREAD

**Issue by programaths** [microsoftgraph/microsoft-graph-docs-contrib#52]
It says `{encoded-sharing-url}.` It doesn't work with urlEncode.

It should indicate which encoding to use. Base64, Base64Url, UrlEncoding, UrlFragmentEncoding, ... ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09b8d398-f3d4-9808-2214-886fc1b42d86
* Version Independent ID: c722986c-9322-301b-2ac9-c5b202803d9f
* Content: [Grant permission - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/permission-grant?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/permission-grant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/permission-grant.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @learafa
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. There is now an example about how to encode the URL. I'm going to close this item. Thanks for your understanding.
