### ISSUE TITLE
Documentation doesn't specify all Permissions that can be used with API

### ISSUE THREAD

**Issue by MarksPoint** [microsoftgraph/microsoft-graph-docs-contrib#520]
I noticed that I was able to use this endpoint with different permissions than what's described in documentation.
Documentation says you need one of these (Delegated):

- Sites.Read.All
- Sites.ReadWrite.All

But I have these (delegated) permissions in my App Registration and I'm still able to use the API:

- ChannelMessage.Send
- Files.ReadWrite.All
- User.Read

I believe it's the Files.ReadWrite.All that's making it 'work'.

I use this API url to get all the Folders in a list:
https://graph.microsoft.com/v1.0/groups/{GROUPID}/sites/root/lists/{LISTID}/items?$expand=fields&$filter=fields/ContentType eq 'Folder'&$top=10&$select=id,eTag,parentReference

**My question:**
Should I make sure I also have the Sites.Read.All permission in my App Registration (which would mean I have one more permission to ask for) or is the documentation not up to date and is it ok to stick to the permissions I already have?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14f44873-e61b-3f77-e2ad-b46112b065b2
* Version Independent ID: 3ef66bdc-06cf-4356-4e1e-f4d7bed17dcb
* Content: [Get listItem - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/listitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
