### ISSUE TITLE
Provide Example Search Queries

### ISSUE THREAD

**Issue by NickStees** [microsoftgraph/microsoft-graph-docs-contrib#522]
Provide example queries for the `?search={query}` for example can you do AND type searches `search=dogs+cats` or wildcards like `search=*support` or is it just a simple text search. Is it possible to just search certain fields like only Descriptions and not titles?

Also the page mentions sorting, but does not say how to pass sorting to the search, is it another query parameter? 

Please elaborate much more on what is possible with search and more examples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5159efcf-058c-7bf8-3bd4-a680224b72b6
* Version Independent ID: f94e77f3-c166-cc46-de80-b4ca5e8e2803
* Content: [Search for sites - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-search.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
