### ISSUE TITLE
Missing information about the default expiration policy

### ISSUE THREAD

**Issue by J-a-k-o-b** [microsoftgraph/microsoft-graph-docs-contrib#524]
Hi,
in the remarks section is mentioned:
- Links created using this action do not expire unless a default expiration policy is enforced for the organization.

What is the "default expiration policy", please add a link or info where I can find any info about it or explain it here. Does it have any relation to the expirationDateTime setting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 537290c1-f301-4874-d790-740fde5239d3
* Version Independent ID: 31ddb53d-5b63-2d8e-06c3-e56125d22937
* Content: [driveItem: createLink - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&tabs=csharp#remarks)
* Content Source: [api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/driveitem-createlink.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
