### ISSUE TITLE
Document known issue of clone teams do not include all owners of original/cloned team

### ISSUE THREAD

**Issue by DTronD** [microsoftgraph/microsoft-graph-docs-contrib#526]
MSFT Support Case# 29640650 confirmed that the following is a known issue. Please add a note to this documentation page to warn users of this issue until the product team corrects the issue.  Thanks.
++++
When calling the MSFT Graph API and invoking the Clone Team method, if the source/reference team contains more than one Owner, the cloned team ends up having all but one of the Owners demoted to Members.  The Owner that is selected by the Graph API as the retained Owner does not appear to be controllable by user or configuration. E.g. not alphabetical first, or order-added.  Possibly based on Owners' SID?

Issue appears to exist in both v1.0 and beta versions of the Graph API at this time.

Current workaround is to use the Add Members method (https://docs.microsoft.com/en-us/graph/api/team-post-members ) after team cloning completes and "promote" the demoted Owners back up to Owners from Members.

_++++++++ BEGIN Support ticket snippet_

> Thanks for your patience, the issue you are reporting is a known limitation. The product group is aware of the limitation, and they have it on their long-term backlog. However, the issue is not simple to resolve and we can provide no ETA for the design change that would be needed to clone team with multiple owners.
> 
> I hope this resolves your questions.
> 
> Regards,
> Dipesh Jadhav
> Developer Support Engineer

_++++++++ END Support ticket snippet_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8770dbec-d5f8-6737-ddf6-da50a7892657
* Version Independent ID: 93752ea2-470d-0226-2928-439d71fe711b
* Content: [Clone a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/team-clone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/team-clone.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Thanks.
