### ISSUE TITLE
Specify value needed to have a boolean column to default to false

### ISSUE THREAD

**Issue by danwatford** [microsoftgraph/microsoft-graph-docs-contrib#538]
When updating a list column definition we should be able to set the default value for that column by setting the _default_ property on the relevant ColumnDefinition object.

Attempts to set the default value for boolean columsn to false ('No') are failing. 

What values should be applied to the default property of the ColumnDefinition for a boolean column such that a default value of No can be observed in the column's settings in SharePoint.

Please could a note of these values be added to the documentation.

I have tried string values "0", "false", "No" which have not worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f895c860-20d5-a075-1f01-41cc06e5182e
* Version Independent ID: c0557b9e-b45d-911c-9cbe-e6752f9fa31f
* Content: [columnDefinition resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/columnDefinition?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/columndefinition.md)
* Product: **sites-and-lists**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
