### ISSUE TITLE
Permission list api response contains less permissions than actual permissions

### ISSUE THREAD

**Issue by vikasprabhakar** [microsoftgraph/microsoft-graph-docs-contrib#542]
[Enter feedback here]

The permission list API only gives the result of <100 permissions of driveItem.
While the driveItem has >1000 user permissions.

API details:
https://graph.microsoft.com/v1.0/sites/<site-id>/drives/b!xW-35tD9ikWshVn2xcPZl1fuiLscGWxNklv5sGFS3gPX3eK7J6hET67ZS9fIWC0D/items/01QBYIXKNUESXTHRVPORDLFPHBCSZBABFL/permissions?$select=id,grantedToV2,roles&$top=999&$filter=roles/any(c:c eq 'read') or roles/any(c:c eq 'write') and grantedToV2/user/id ne null

request-id: 8442429a-edea-4ac6-b403-aee0e3820f66
client-request-id: 8442429a-edea-4ac6-b403-aee0e3820f66

Response:
The response contains only 96 permissions but in actuality, the drive item (01QBYIXKNUESXTHRVPORDLFPHBCSZBABFL) has more than 1000 user permissions.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69e3ab60-0af1-e537-d9cf-c23415dd1dc6
* Version Independent ID: 7bc60c80-43f9-88ec-fc3e-030bf0dface6
* Content: [List who has access to a file - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-list-permissions.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
