### ISSUE TITLE
Incorrect Json payload

### ISSUE THREAD

**Issue by mhardy** [microsoftgraph/microsoft-graph-docs-contrib#543]
The example Request for "Add two rows to a table" is incorrect.

{
  "values": "[
    [1, 2, 3],
    [4, 5, 6]
  ]"
}

should not have quotes around the array.

it should be 
{
  "values": [
    [1, 2, 3],
    [4, 5, 6]
  ]
}

If using the example as listed, the API request will fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8ea6cf-6f8f-c862-ae29-699c5e0ddc0e
* Version Independent ID: 5787d91b-2b8d-3a44-e2ec-475909e682ed
* Content: [Create TableRow - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/table-post-rows.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MartinM85** [comment]
Can be closed. Example was fixed.

**Comment by lramosvea** [comment]
Closing as this seems to be fixed already. Thanks.
