### ISSUE TITLE
Missing docs for setting sensitivity

### ISSUE THREAD

**Issue by giggio** [microsoftgraph/microsoft-graph-docs-contrib#544]
I saw this article on LinkedIn from a Microsoft employee mentioning it is possible to set sensitivity labels using the rest api, but it is not documented.
See: https://www.linkedin.com/pulse/programatic-way-apply-sensitivity-label-file-sanjoyan-mustafi/

According to the post, the operation is like:

````
https://<​foo_domain>.sharepoint.com/_api/v2.1/drives/<​driveID>/items/<​docID>/setsensitivityLabel
{
"id"​: "​<​labelID>"​,
"justificationText"​: "​<​Any text; This will be part of audit entry>"​,
"assignmentMethod"​: "standard"​,
"ifMatchLabelId"​:"​"​
} 
````

Would you please document it so we can better understand it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18dfd099-0d73-55e4-56ec-d9129b83aa07
* Version Independent ID: 5705a946-2c25-0d04-a297-01ccb21d7284
* Content: [List the contents of a folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-list-children.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-list-children.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
