### ISSUE TITLE
Java example doesn't work

### ISSUE THREAD

**Issue by ys-hkwong** [microsoftgraph/microsoft-graph-docs-contrib#550]
The java SDK cannot get the rooms or room list. Please check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b836740-9263-12cc-9001-c61f08448f0d
* Version Independent ID: 4a5b79f8-d685-6c86-d7ed-12d7c5d309cb
* Content: [List places - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/place-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/place-list.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
Hi. Thanks for raising this issue.

The code snippets has been updated based on the new [Microsoft Graph Java v6 version](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v6.1.0).
You can also check more info about the new version in the [v6 announcement blog post](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/).
