### ISSUE TITLE
Undocumented limit on number of columns in response

### ISSUE THREAD

**Issue by Cmohan** [microsoftgraph/microsoft-graph-docs-contrib#556]
I have found with lists that have a lot of columns, not all of them are returned when you use the `expand=fields` parameter. You also can't get them all using `fields(select=...)`. If there is a limit, please specify how many columns are returned and how Graph determines which to return.

Same feedback applies to the endpoint for getting individual list items.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2524650e-06e7-dc8c-b2ae-0c2fbffdb541
* Version Independent ID: 3eb41d73-2b60-1459-e921-20403004655c
* Content: [Retrieve items from a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/listitem-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
