### ISSUE TITLE
Clarity over whether a driveitem webUrl can be encoded into a sharing token?

### ISSUE THREAD

**Issue by martiansteve** [microsoftgraph/microsoft-graph-docs-contrib#567]
Hello

Could the documentation be clarified as to whether a normal webUrl (from a DriveItem) can be encoded into a sharing token using the method described under "Encoding sharing URLs"?

There are a [couple](https://stackoverflow.com/questions/60174302/ms-graph-api-weburl-to-driveitem) of [places](https://blog.aterentiev.com/ms-graph-get-driveitem-by-file-absolute) online that have read it this way, but I don't think the text is clear on this or whether this is just supposed to be for sharing links.

I have tested this myself with webUrl's and it has mostly worked, but I do now have some examples where it does not (403 - the sharing link no longer exists, or you do not have permission to access it) and I am not sure whether this is down to sharing/site settings or webUrl's not being supported in certain situations. So it would be good to add clarity on this.

Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f0e42a-0fc2-905d-b105-0b3de895e351
* Version Independent ID: 340a3a14-6067-15bb-3be3-a789caa31a44
* Content: [Access shared items - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/shares-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/shares-get.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
