### ISSUE TITLE
Unclear item details in the request

### ISSUE THREAD

**Issue by dariobauer** [microsoftgraph/microsoft-graph-docs-contrib#575]
Thanks for providing this api, associated docs, and the opportunity to provide feedback.

1. Top of page section [HTTP request](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#http-request) has some odd endpoints. Should these not end with `items/{itemId}:/{item-path}:/createUploadSession`?

2. Request section is unclear if the `{item-path}` should be equal to the `item.name` and include an extension. Through testing seems to accept an extension. Also unclear what happens if the name provided in the body differs from that in the url.

3. The use of the body in the request is quite unclear and could use more examples (such as how to include `fileSystemInfo`, also there seem to be a few issues with it:

- Including `"@odata.type": "microsoft.graph.driveItemUploadableProperties"` results in a 400 error (tested using OneDrive for Business)
- Including `size` results in a 400 error (tested using OneDrive for Business)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c42d74d1-8c6f-5282-9fba-30fdd6449362
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [Resumable file upload - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#resuming-an-in-progress-upload)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
