### ISSUE TITLE
What properties are searched?

### ISSUE THREAD

**Issue by kurtgetonwithit** [microsoftgraph/microsoft-graph-docs-contrib#577]
The page states "The search filter is a free text search that uses multiple properties when retrieving the search results." but does not specify which properties are used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5159efcf-058c-7bf8-3bd4-a680224b72b6
* Version Independent ID: f94e77f3-c166-cc46-de80-b4ca5e8e2803
* Content: [Search for sites - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-search.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
