### ISSUE TITLE
Education service limits incorrect? 400000 requests per 20 seconds, 35000 requests per 10 seconds

### ISSUE THREAD

**Issue by mwchambers** [microsoftgraph/microsoft-graph-docs-contrib#578]
This section here:                                                                      
                                                                                        
https://docs.microsoft.com/en-us/graph/throttling#education-service-limits              
                                                                                        
States: 400000 requests per 20 seconds  35000 requests per 10 seconds                   
                                                                                        
This seems very high compared to other APIs and I am getting HTTP 429 rate limited way below this figure.                                                                  
                                                                                        
Is there an issue with the auto generation of these documents? For example were these both intentional increases to the figures:                                              
                                                                                        
https://github.com/microsoftgraph/microsoft-graph-docs/commit/e8edc1010fb2496f9f3c09f36085702738d97f32#diff-753c5ef5e83cee56bf0bbeccc5e82f3c3fd89009108e01f89d1ef9eed3abb595
                                                                                        
https://github.com/microsoftgraph/microsoft-graph-docs/commit/bbcbcc09be36618b13179a029c6d027588918c9b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df32e5f-8ccb-0c93-28d9-02392f9c7256
* Version Independent ID: 4aadd084-fb61-e89b-f63f-3b71622636b7
* Content: [Microsoft Graph throttling guidance - Microsoft Graph](https://docs.microsoft.com/en-us/graph/throttling)
* Content Source: [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Thanks.
