### ISSUE TITLE
webUrl is not updated in the return tracking changes

### ISSUE THREAD

**Issue by Herz3h** [microsoftgraph/microsoft-graph-docs-contrib#579]
[Enter feedback here]

The page only states that `parentReference->path` won't be returned even if it has changed. So taking this into account, i rebuiled all the paths internally using (parent->children relation). However I noticed that webUrl is never updated......

Say I have this path:

```RootFolder/MyFolder/test.pdf```

If I rename `MyFolder` to `MyFolder2`

I received a notification that the folder has been renamed, however the property webUrl will have this content:

```https://jpl66.sharepoint.com/Documents partages/RootFolder/MyFolder/test.pdf```

 I mean I could try to rebuild this url, but it's not always the same depending on the filetype as I've noticed, and I'm not sure it'll be the same format in the future...

So how does one manage this kind of changes ???
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5785f90e-b37c-c5a5-ddbc-7170307980c9
* Version Independent ID: d8b7729e-38c4-5562-7359-5e926f8d7ae4
* Content: [Sync the contents of a drive - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-delta.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
