### ISSUE TITLE
Response body states "createdBy" will be returned, yet it is not

### ISSUE THREAD

**Issue by jessewalter** [microsoftgraph/microsoft-graph-docs-contrib#59]
The response body for the eDiscovery List Cases endpoint states that it will return createdBy. However, no createdBy property is returned. Further, if I append the property to my HTTP request (i.e. https://graph.microsoft.com/beta/compliance/eDiscovery/cases?$select=id,displayName,createdBy), I receive a 400 error: "Parsing OData Select and Expand failed: Could not find a property named 'createdBy' on type 'microsoft.graph.ediscovery.case'."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d80c8a8-833f-91dd-e1b8-05a1d0ead096
* Version Independent ID: 0c3fe7f9-9ce3-3b9c-dfe2-a2e436e433c8
* Content: [List cases - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/ediscovery-case-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/ediscovery-case-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/ediscovery-case-list.md)
* Product: **ediscovery**
* Technology: **microsoft-graph**
* GitHub Login: @mahage-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@ninacchen is that something we should be publishing as a known issue? https://developer.microsoft.com/en-us/graph/known-issues/
any ETA to get this resolved? Thanks

**Comment by lramosvea** [comment]
Closing as this bug seems to be fixed now. Please feel free to reopen otherwise. Thanks.
