### ISSUE TITLE
Link in sharing invitation does not work

### ISSUE THREAD

**Issue by akih** [microsoftgraph/microsoft-graph-docs-contrib#596]
I am trying to send a sharing invitation for a DriveItem with following request:

POST `https://graph.microsoft.com/v1.0/me/drive/items/{item-id}/microsoft.graph.invite`
BODY `{"message":"Just a message","recipients":[{"email":"valid-email-address"],"requireSignIn":false,"roles":["read"],"sendInvitation":true}`

Request is completed successfully and link is sent to email but when I try to view the image it does not open. It breafly shows an error page that says something like:
`error loading /drives/me/items/root/items?filter=takenDateTime+ge+1899-12-31T00:00:00:000Z&orderby=photo/takenDateTime+desc&expand=tags,thumbnails&top=100`

One strange thing in response data is field "expirationDateTime":"0001-01-01T00:00:00Z". Documentation states that this field is available on OneDrive for Business, SharePoint, and premium personal OneDrive accounts. If I set `expirationDateTime` to my request I get "Account Upgrade is required for this operation" -error.

Also the link that opens from the email contains `allmyphotos` at the end which sounds a bit strange.

I have been successfully sent sharing invitations with similar requests before so I am wondering if something has changed. Or is documentation outdated..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75e1562-24d6-bfaf-be46-d52ee93ffb1d
* Version Independent ID: cd35f8f6-774e-70d3-9bd5-11110ab450b1
* Content: [Send an invite to access an item - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-invite.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
