### ISSUE TITLE
Site permissions appear to be enabled for delegated permissions

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/microsoft-graph-docs-contrib#603]
In a targeted release tenant, I tested all v1.0/sites/.../permissions endpoints in Graph Explorer and discovered they worked without issue. Does this page need to be updated to reflect that delegated permissions work, or is this something I shouldn't be doing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6942ebdc-2b3b-c53d-4177-e618cfab8aae
* Version Independent ID: 30f878a7-faea-1167-3f1a-312fba1f9219
* Content: [Create permission - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-post-permissions.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @barrysh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by fowl2** [comment]
duplicate of https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/319

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
