### ISSUE TITLE
Please update roles section to include identity roles

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/microsoft-graph-docs-contrib#604]
"read" and "write" are valid values when creating permissions for identities, but "owner" does not work. Please update roles to specify to use "fullcontrol" for identity (Sites.Selected) permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1191235c-879e-dffc-82eb-4e8f7edfd29c
* Version Independent ID: 322f9be4-7921-41d8-78c2-2bdc62f916a3
* Content: [Permission - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/permission.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
