### ISSUE TITLE
Tracking changes is  sub folders works but is not documented

### ISSUE THREAD

**Issue by zemuldo** [microsoftgraph/microsoft-graph-docs-contrib#605]
[Enter feedback here]
I have a drive hierarchy that goes like this.
```shell
 root
    ....
    SubFolder
        OneNote
        Book.xlsx
            ChildFolder
             ....
```
I want to track changes in sub folders.

I am able to track changes in the SubFolder by calling `GET /me/drive/items/SubFolder -item-id/delta` and even further track changes in ChildFolder `GET /me/drive/items/ChildFolder -item-id/delta`. See the screenshot below.

![delta-on-child-folders](https://user-images.githubusercontent.com/19955045/132295162-003e299e-b542-4341-b0de-aec7d3edde5b.PNG)

However this is not documented on [Track changes for a Drive](https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http). The documentation only mentions `root` like `GET /drives/{drive-id}/root/delta`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5785f90e-b37c-c5a5-ddbc-7170307980c9
* Version Independent ID: d8b7729e-38c4-5562-7359-5e926f8d7ae4
* Content: [Sync the contents of a drive - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-delta.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
