### ISSUE TITLE
SDK examples missing for Send a new message using MIME format

### ISSUE THREAD

**Issue by mike-harris0n** [microsoftgraph/microsoft-graph-docs-contrib#612]
I am trying to implement sending of MIME format messages using the Java SDK, but unfortunately there are no examples for any of the SDKs of how to do this. It would be great if this documentation hole could be filled!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572e47b6-e504-0918-fc06-11217eea40a4
* Version Independent ID: c30fd8a1-e913-0192-7405-d55232ea3703
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-sendmail.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
This should have been fixed in the new generation of SDKs. This needs to be addressed in the code snippet generation tool: https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/2794

**Comment by fey101** [comment]
I have transferred this issue to the appropriate repo https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1949 and closed the earlier one. However, @isvargasmsft still remains as the PM there I believe.
