### ISSUE TITLE
Drive resource missing properties for Personal Drives

### ISSUE THREAD

**Issue by HenryHall** [microsoftgraph/microsoft-graph-docs-contrib#617]
When querying `/me/drives` or `/me/drives/<drive-id>`, personal drive resource data does not include most of the properties mentioned in the documentation.  I am only seeing:
- driveType: 'personal'
- id: string
- owner: IdentitySet
- quota: Quota

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd926e47-392d-8e60-a72c-bd3591417113
* Version Independent ID: 3094b7bd-9e38-20ea-71db-a4d9ea64550d
* Content: [Drive - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/drive?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/drive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/drive.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
