### ISSUE TITLE
Confusing description about what is returned in the initial delta query

### ISSUE THREAD

**Issue by kinex** [microsoftgraph/microsoft-graph-docs-contrib#619]
I don't understand what this paragraph is trying to say:

> Note: The initial request to the delta query function (no delta or skip token) will return the resources that currently exist in the collection. Resources that have been created and deleted prior to the initial delta query won't be returned. Updates made before the initial request are summarized on the resource returned as its latest state.

First you say that it returns the resources that currently exist in the collection. In the next sentence you say opposite "Resources that have been created and deleted prior to the initial delta query won't be returned.". The last sentence adds even more confusion. And what is "skip token"?

I am wondering if the behavior of `token=latest` has changed. Last time I tested it (several months ago) it returned all current files in a OneDrive folder. Now it seems to return no files. So it is unclear what is the expected behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview#delta-query-request-examples)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
