### ISSUE TITLE
Please add documentation on how to get information for subsites

### ISSUE THREAD

**Issue by AskYous** [microsoftgraph/microsoft-graph-docs-contrib#620]
I've been stuck on this forever. It would be great if you can put information on how to query for deeply rooted subsites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40227a9-4cd8-4c43-4f05-a795e42ca43f
* Version Independent ID: 6fe41792-3aa2-c498-5f6d-6d81122339e5
* Content: [Get SharePoint site by path - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-getbypath?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/site-getbypath.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-getbypath.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
