### ISSUE TITLE
Custom field valure are returned ONLY if contain value

### ISSUE THREAD

**Issue by lorenzosoncini** [microsoftgraph/microsoft-graph-docs-contrib#625]
I have made several test to recover the fields of one Sharepoint Document library with graph api:
https://graph.microsoft.com/v1.0/sites/{SiteId}/lists/{ListId}/items/{ItemId}?$expand=fields

I think it is important highlight that the answer contains the "custom" fields only if they are set. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 182645cd-d48d-da9b-7a25-0f41126bb8eb
* Version Independent ID: e58c571e-b339-88e1-e8b8-ada8457f09af
* Content: [Get listItem - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/listitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
