### ISSUE TITLE
Clarify the meaning of the data in the response

### ISSUE THREAD

**Issue by lorenzosoncini** [microsoftgraph/microsoft-graph-docs-contrib#626]
**Explain the response data**
In the response json there are:

"id": "contoso.sharepoint.com,2C712604-1370-44E7-A1F5-426573FDA80A,2D2244C3-251A-49EA-93A8-39E1C3A060FE",

the two unique identifier are? 
Site id ? Witch one is?  and the other?
Is useful clarify the meaning of the unique identifier present in the response

**Suggestion**
Can be useful make an example of URL based on public SharePoint url.
The SharePoint url is:
https://contoso.sharepoint.com/sites/TestSite

The API url is:
https://graph.microsoft.com/v1.0/sites/contoso.sharepoint.com:/sites/TestSite

Thanks
Lorenzo Soncini
Italy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d18d3f2-ae80-638c-226c-abdedf7f57ba
* Version Independent ID: e380088a-8e7f-2196-df1b-ffe86e199f12
* Content: [Get a SharePoint Site - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
