### ISSUE TITLE
Conversion to PDF does not take into account embedded fonts

### ISSUE THREAD

**Issue by markmacumber** [microsoftgraph/microsoft-graph-docs-contrib#627]
I am using the Graph API convert content API (v1) to convert my SharePoint Online hosted files (docx) into PDF files.

However, I have noticed that when I embed fonts into the Word Document as it is saved locally, when I convert the file to PDF the resulting file only contains the Calibri font (I can see this in the PDF properties within Acrobat).

The documentation does not at all address this limitation or the BETA API mention if this is supported or not... I need to know if I am doing something wrong or this is a known limitation of the API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a53d4b0e-4bf4-01a7-229c-5073dd56f45d
* Version Independent ID: 8dc763d8-6252-d6af-5be5-99b7a9277fbd
* Content: [Convert to other formats - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get-content-format.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-get-content-format.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
