### ISSUE TITLE
File conversion documentation is incorrect, doesn't explain how to work with returned streams

### ISSUE THREAD

**Issue by Perustaja** [microsoftgraph/microsoft-graph-docs-contrib#628]
The example code using the SDKs shows a stream returned, which I am receiving currently. For instance my returned response when converting an xlsx to a pdf is
Code:
```
let stream = await client.api(`/sites/mySiteId/drive/root:/path/fileName:/content?format=pdf`).get();
```

Stream response:
```
PassThrough {
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: [Object], tail: [Object], length: 1 },
    length: 3480,
    pipes: [],
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: true,
    sync: false,
    needReadable: true,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  _events: [Object: null prototype] {
    prefinish: [Function: prefinish],
    unpipe: [Function: onunpipe],
    error: [ [Function: onerror], [Function (anonymous)] ],
    close: [Function: bound onceWrapper] { listener: [Function: onclose] },
    finish: [Function: bound onceWrapper] { listener: [Function: onfinish] }
  },
  _eventsCount: 5,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: true,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: false,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    prefinished: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    errored: null,
    closed: false
  },
  allowHalfOpen: true,
  [Symbol(kCapture)]: false,
  [Symbol(kTransformState)]: {
    afterTransform: [Function: bound afterTransform],
    needTransform: true,
    transforming: false,
    writecb: null,
    writechunk: null,
    writeencoding: 'buffer'
  }
}
```
However, after these examples the response is described in terms of an http request and the stream isn't explained at all.

Making a manual axios call returns what the response section of this page describes for a copy operation, I can access headers.location as expected. However, manually calling the convert endpoint actually returns the file with a 200, not a 302 as expected.
manual call:
```
let convertRes = await axios.get(`https://graph.microsoft.com/v1.0/tenantId/sites/mySiteId/drive/root:/pathToMyFile:/content?format=pdf`, null, axiosAuthConfig);
```
```
{
  status: 200,
  ...
  data: // file buffer here
}
```

This is supposed to a return a 302 code with a link to the converted file's location correct? I can't seem to achieve the described behavior.

Can we get some documentation on how to check up on the resource in these long-running operation using the actual SDK? And some explanation as to how the stream behaves. Each operation is a bit different so other pages would likely need some extra documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a53d4b0e-4bf4-01a7-229c-5073dd56f45d
* Version Independent ID: 8dc763d8-6252-d6af-5be5-99b7a9277fbd
* Content: [Convert to other formats - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get-content-format.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-get-content-format.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
