### ISSUE TITLE
Examples are not good enough in the docs

### ISSUE THREAD

**Issue by WiredEntrepreneur** [microsoftgraph/microsoft-graph-docs-contrib#630]
The examples given here are not good enough. Feels like a half-arsed job. I have been looking to find a way to get the contents or children of a drive when we have a drive ID i.e., I am looking for the driveItems within a driveId for a SharePoint document library. But the examples given here are for one drive. Don't seem to have the same problem with onedrive retrieving driveitems.

Can retrieve all items via lists and listitems but to perform POST or add new items to the document library we need to use drives and driveitems. Seems like it is next to impossible to retrieve document library as drives and the contents s driveItems

Tried all the following but with no luck:

sites/site.sharepoint.com,<id>,<id>/drives/{drive-id}
sites/site.sharepoint.com,<id>,<id>/drives/{drive-id}/root/children
sites/site.sharepoint.com,<id>,<id>/drives/{drive-id}/root:/children
sites/site.sharepoint.com,<id>,<id>/drive/{drive-id}/children
sites/site.sharepoint.com,<id>,<id>/drive/{drive-id}:/children
sites/site.sharepoint.com,<id>,<id>/drive/{drive-id}/items
sites/site.sharepoint.com,<id>,<id>/drive/{drive-id}:/items

The examples provided, definitely are not helping here. Please amend if possible. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079ba35-dd9e-fe22-5254-2b7e0b5ab650
* Version Independent ID: 18340dad-3014-1888-7bf7-3da9af9973e7
* Content: [Get a file or folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
