### ISSUE TITLE
@microsoft.graph.conflictBehavior=rename as a query parameter

### ISSUE THREAD

**Issue by alphapiper** [microsoftgraph/microsoft-graph-docs-contrib#641]
[Enter feedback here]
please add comment to clarify use of @conflictbehaviour using query parameter.
- add @microsoft.graph.conflictBehavior=rename as a query parameter to your URI.

PUT /me/drive/items/{parent-id}:/{filename}:/content?@microsoft.graph.conflictBehavior=rename

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd91d01d-83c9-9499-b5e7-0e090b327876
* Version Independent ID: 79e4e52a-875c-9558-8643-4602f15fcd68
* Content: [Upload small files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
