### ISSUE TITLE
Graph v1.0 supports csv to pdf but beta does not. Typo in docs?

### ISSUE THREAD

**Issue by samleung314** [microsoftgraph/microsoft-graph-docs-contrib#643]
[Enter feedback here]
The [Graph v1.0 docs state](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http#format-options) that csv is a valid format for conversion to pdf but in the [Graph beta docs](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-beta&tabs=http#query-parameters), csv is not mentioned as a valid format for conversion. Only csv to jpg support is mentioned for beta. Is this still 
 a current limitation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89db15-f930-2e68-6dca-37f461d85d58
* Version Independent ID: 8dc763d8-6252-d6af-5be5-99b7a9277fbd
* Content: [Convert to other formats - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/driveitem-get-content-format.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/driveitem-get-content-format.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
