### ISSUE TITLE
conversion from potx to pdf doesn't work

### ISSUE THREAD

**Issue by jenslundgaard** [microsoftgraph/microsoft-graph-docs-contrib#647]
The documentation on your **/content** MS Graph driveItem API endpoint call states that it can convert from POTX to PDF, but this doesn't work and returns this error:
{
    "error": {
        "code": "notSupported",
        "message": "potx",
        "innererror": {
            "code": "InputFormatNotSupported"
        }
    }
}

Please make it support POTX as well as the other formats as we need that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a53d4b0e-4bf4-01a7-229c-5073dd56f45d
* Version Independent ID: 8dc763d8-6252-d6af-5be5-99b7a9277fbd
* Content: [Convert to other formats - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get-content-format.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-get-content-format.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
