### ISSUE TITLE
Python sample fails out of the box

### ISSUE THREAD

**Issue by Kasenga** [microsoftgraph/microsoft-graph-docs-contrib#65]
Hello team!
The Python samples fails out of the box.
What changes do we need to make to have the Python samples work?

![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/15863977/3260c731-17d4-4960-98f2-491a0ea78a10)

Line 18 says: "[" was not closed.
I suspect this is because of the lambda expression "=>", but I could be wrong.
How do we get this sample to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=python#request-1)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@jochemloedeman you're correct. That problem is reported in the snippet generator here: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1955.

Other than that problem, the current snippet in the doc is correct. Closing this issue as the fix needs to come from snippet generation.
