### ISSUE TITLE
Graph API SharePoint 'Get Items' Permissions Incomplete

### ISSUE THREAD

**Issue by phi1osoph0s** [microsoftgraph/microsoft-graph-docs-contrib#655]
In order to retrieve items from a SharePoint list that has "Read items that were created by the user" enabled, you need more permissions than only application-level _Sites.Read.All_ and _Sites.ReadWrite.All_ that the documentation suggests. It appears you also need _Sites.Manage.All_.

Without this permission, the API returns an empty array of values when using the example requests:

```
GET https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items
GET https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items?expand=fields
GET https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items?expand=fields(select=Column1,Column2)
```

Other lists on a SharePoint site that do not include that specific advanced setting work as the documentation suggests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e70cdc2-b1b1-183d-4ee1-6082f91018c6
* Version Independent ID: 4beee916-2de5-5594-eb6f-725edc256229
* Content: [Retrieve items from a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/listitem-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
