### ISSUE TITLE
The introduction of the endpoints page is referencing to the wrong product

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/microsoft-graph-docs-contrib#657]
Hello,
I was reading about this endpoint and found this section 'These include things like a group mailbox for conversations and a group OneDrive folder for documents and files.'

OneDrive to my understanding is a service connected with a individual and not a Microsoft 365 Group. I assume you are mean SharePoint in this case?

Thank you for your feedback,
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb18386c-dc40-87d2-a200-1e1f314ecd3f
* Version Independent ID: 931e3c54-1276-3b3a-f3bd-7ecf104ba5e4
* Content: [Endpoint resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/endpoint?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/endpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/endpoint.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
