### ISSUE TITLE
Link to sample code for teams app installation life cycle using Tabs

### ISSUE THREAD

**Issue by Trinetra-MSFT** [microsoftgraph/microsoft-graph-docs-contrib#662]
Add sample code link to [teamsAppInstallation](https://docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0) page.

Following sample code needs to be linked
Sample Code Name: [AppInstallationLifeCycle](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-app-installation-lifecycle/csharp)

Language Used: C#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89adfcbc-8b92-e7b4-de4e-e400eee215de
* Version Independent ID: 28007918-26b0-ac78-f863-64f012ad0d6f
* Content: [teamsAppInstallation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/teamsappinstallation.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @AkJo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
We are closing the issue as the document is already updated.
