### ISSUE TITLE
Need Example for updating Hyperlink Field

### ISSUE THREAD

**Issue by SWARUP-Selvaraj** [microsoftgraph/microsoft-graph-docs-contrib#663]
# Need PATCH example involving Hyperlink Field

I am receiving '**Invalid Request**' error when trying to patch with a **hyperlink** field data.
```javascript
{
    "HyperlinkField": {
                       "Description": "Update List", 
                       "Url": "https://docs.microsoft.com/en-us/graph/api/listitem-update?view=graph-rest-1.0&tabs=http"
                      }
}
```

An **example API PATCH** request involving **Hyperlink field** will be Appreciated.

[Similar requests in community](https://techcommunity.microsoft.com/t5/power-apps-power-automate/updating-a-hyperlink-field-both-url-and-description-using-flow/m-p/204268)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7f72f3-34ce-d831-52a3-078001054164
* Version Independent ID: 0cec1a6c-6e7c-825f-287c-0fab22298ab3
* Content: [Update listItem - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/listitem-update.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
