### ISSUE TITLE
GET drive-item not returning image facet for .jfif files.

### ISSUE THREAD

**Issue by zemuldo** [microsoftgraph/microsoft-graph-docs-contrib#665]
[Enter feedback here]
As per the docs, all image type drive items return image facet but .jfif files dont return the facet. See the sample request-response below.

```shell
GET https://graph.microsoft.com/v1.0/me/drives/b!wwjsekZWnk-CvRJTdifO8aylAz8p6S9Om1pAaCTz8xKNo6qPD6RCQLJwN3vtMtht/items/01TLIPQRIYXK7PS4A63JCJNGBMHSTBOMVH/children?select=id,image,name

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('2f43e7ac-7ef9-44de-8518-2c8d0f0668c6')/drives('b%21wwjsekZWnk-CvRJTdifO8aylAz8p6S9Om1pAaCTz8xKNo6qPD6RCQLJwN3vtMtht')/items('01TLIPQRIYXK7PS4A63JCJNGBMHSTBOMVH')/children",
    "value": [
        {
            "@odata.etag": "\"{591D4F8D-33BB-4E5A-BA52-50F277535E7C},6\"",
            "id": "01TLIPQRMNJ4OVTOZTLJHLUUSQ6J3VGXT4",
            "name": "photo1.jfif"
        },
        {
            "@odata.etag": "\"{D7D45573-0A6B-409D-B207-0EE6FB9559E0},6\"",
            "id": "01TLIPQRLTKXKNO2YKTVALEBYO435ZKWPA",
            "name": "photo2.jpeg",
            "image": {}
        }
    ]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079ba35-dd9e-fe22-5254-2b7e0b5ab650
* Version Independent ID: 18340dad-3014-1888-7bf7-3da9af9973e7
* Content: [Get a file or folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
