### ISSUE TITLE
How to receive correct permissions list for "Shared with me" item?

### ISSUE THREAD

**Issue by 23W** [microsoftgraph/microsoft-graph-docs-contrib#667]
There are no information about receiving Permissions for "Shared with me" items. It's unclear can i use shared item Id, that is received by `GET /me/drive/sharedWithMe` request, in `GET /me/drive/items/{shared-item-id}/permissions` or i have to extract remoteItem facet values of shared item and use it Id and drive Id in request `GET /drives/{remotItem-parentReference-drive-id}/items/{remotItem-id}/permissions` so as to receive correct list of permission for shared with me item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbac80e5-ae35-b804-addd-53ccaf49e693
* Version Independent ID: b2a13be1-7783-38c2-c318-1261847240fa
* Content: [List who has access to a file - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-list-permissions.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
