### ISSUE TITLE
Would be nice if you told us what the thrre things that comprise the ID are!

### ISSUE THREAD

**Issue by russgove** [microsoftgraph/microsoft-graph-docs-contrib#669]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d18d3f2-ae80-638c-226c-abdedf7f57ba
* Version Independent ID: e380088a-8e7f-2196-df1b-ffe86e199f12
* Content: [Get a SharePoint Site - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
