### ISSUE TITLE
You need read permissions on the root site of the sharepoint tenant 

### ISSUE THREAD

**Issue by martinvillysson** [microsoftgraph/microsoft-graph-docs-contrib#672]
To run this API call you need READ/Visitor permissions on the Root site of the SharePoint tenant since this seems to be a proxy for the following api endpoint: 
`{
"Description": "Execute HTTP request",
"Uri": "https://tenant.sharepoint.com/_api/v2.0/sites?search=",
"HttpMethod": "GET",
"TargetWorkloadId": "Microsoft.FileServices"
}`
Without READ/Visitor permissions I got 404 Not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a2afc08-28e8-349c-ce6c-c0460113cdc8
* Version Independent ID: 883fbf22-d581-a676-1a10-369a7a4c09fc
* Content: [Search for sites - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-search.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
