### ISSUE TITLE
Byte range in docs

### ISSUE THREAD

**Issue by chrissyast** [microsoftgraph/microsoft-graph-docs-contrib#673]
![image](https://user-images.githubusercontent.com/31564153/111357846-97c36400-8681-11eb-8d66-ac77f8e02d6f.png)

I am a bit confused by this example in the docs...

Firstly, why would someone upload a 128 byte file as a session rather than a [normal upload](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-beta&tabs=http) ? Then, why would they break up the upload into such small chunks? And lastly, if `the size of each byte range MUST be a multiple of 320 KiB (327,680 bytes).`, why is a 26 byte range acceptable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dc3c7fe-d3b3-5bc0-2efc-28886a0cb49b
* Version Independent ID: da81af46-492e-a5a7-78e5-ae217d6f1c11
* Content: [Resumable file upload - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
