### ISSUE TITLE
Custom columns do not get created when creating list. Outdated documentation?

### ISSUE THREAD

**Issue by Samnan** [microsoftgraph/microsoft-graph-docs-contrib#675]
Checked and confirmed the post data is same as that specified in the documentation, however list gets created but does not contain the specified columns.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb2875d7-98df-2c37-5ce8-29d890938e6a
* Version Independent ID: c32f6075-dfc5-f32f-1c70-4de265a91274
* Content: [Create a SharePoint List - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/list-create?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/list-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/list-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
