### ISSUE TITLE
Recent files API not supported for team sites

### ISSUE THREAD

**Issue by SuiteDan** [microsoftgraph/microsoft-graph-docs-contrib#678]
From what I can see the recent files API returns a 501 Not Implemented error if you try to run it on a sharepoint site that was setup as a Team site, it wasn't obvious because we did most of our testing on a communication site. It should really be documented on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f1b1d0-d602-2a30-2014-106b1b3f0103
* Version Independent ID: e3067bea-8af3-d0bc-e479-4408c33441ea
* Content: [List Recent Files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/drive-recent?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/drive-recent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/drive-recent.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
