### ISSUE TITLE
Hidden libraries retrieval - a little more help

### ISSUE THREAD

**Issue by UMAknow-Patrick** [microsoftgraph/microsoft-graph-docs-contrib#679]
Hi there,
The line that states 

> Drives with the system facet are hidden by default. To list them, include system in your $select statement.

is a bit dry for users who want to find hidden libraries.
May I suggest you emphasize by providing an example, like:

For example, in SharePoint, to retrieve the **Site Assets** or **Site Pages** libraries, use the following: 
`GET /sites/{siteId}/drives?$select=id,name,webUrl,driveType,system`

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9fe6149-3ba5-fd90-3fc8-1f352780ceca
* Version Independent ID: d2d6361b-e961-11b3-c11c-e1ce26254dea
* Content: [List Drives - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/drive-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/drive-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/drive-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
