### ISSUE TITLE
Review who is assigned to the issues

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#6814]
This is a general feedback. 

It happens very often that the issues are assigned to a user who is not active or her/his last contribution into this repository is more than year ago.

I'm almost 100% sure that those questions will be never answered.

Examples:

https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues?q=assignee%3AJeremyKelley+is%3Aopen

https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues?q=assignee%3Aabheek-das+is%3Aopen

I don't want to spam other users with "kindly reminders" but maybe if you can review the process who is the best person to provide the answer...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Microsoft Graph overview - Microsoft Graph](https://learn.microsoft.com/en-us/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Issues have been reassigned.
