### ISSUE TITLE
Show default and maximum page size of each API on the respective documentation page

### ISSUE THREAD

**Issue by ingmaramzan** [microsoftgraph/microsoft-graph-docs-contrib#689]
It would help to also list the default and maximum page size of each API on the API page. I'm looking for this information, where can I get it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 182645cd-d48d-da9b-7a25-0f41126bb8eb
* Version Independent ID: e58c571e-b339-88e1-e8b8-ada8457f09af
* Content: [Get listItem - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
