### ISSUE TITLE
set Multiple Lookup Id  values in a field

### ISSUE THREAD

**Issue by yagcioe** [microsoftgraph/microsoft-graph-docs-contrib#694]
I found a way to enter multiple LookupId's in a field which is not documented:

The Solution was metioned [here](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/7724)

PATCH https://graph.microsoft.com/v1.0/.../ListItem/fields
body:
`{
{
    "TestLookupId@odata.type": "Collection(Edm.String)",
    "TestLookupIdl": ["11","12" ]
}
}`

This is working for the field called Test.

It took quite a while to figure this out ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1af3c661-dca5-dc61-0708-be97b7223d2d
* Version Independent ID: 7a8b8bfc-6a52-debf-df7d-fca6046fe89e
* Content: [FieldValueSet - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/fieldvalueset?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/fieldvalueset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/fieldvalueset.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
