### ISSUE TITLE
Converting XLS to PDF is not in A4 format

### ISSUE THREAD

**Issue by acouvreur** [microsoftgraph/microsoft-graph-docs-contrib#699]
[Enter feedback here]
When converting an XLS file the height and width are 216x279 instead of the wanted A4 format 210x297.
The doc does not specify this implicit conversion. Is it customizable ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a53d4b0e-4bf4-01a7-229c-5073dd56f45d
* Version Independent ID: 8dc763d8-6252-d6af-5be5-99b7a9277fbd
* Content: [Convert to other formats - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get-content-format.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-get-content-format.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
