### ISSUE TITLE
Java example for updating a file is missing content() call

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [microsoftgraph/microsoft-graph-docs-contrib#704]
The Java example for updating a file is missing a `content()` call. The correct code should be
```
IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

byte[] stream = Base64.getDecoder().decode("The contents of the file goes here.");
	graphClient.me().drive().items("{item-id}").content()
	.buildRequest()
	.put(stream);
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd91d01d-83c9-9499-b5e7-0e090b327876
* Version Independent ID: 79e4e52a-875c-9558-8643-4602f15fcd68
* Content: [Upload small files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by maisarissi** [comment]
The Java code snippet is missing from the docs after the new released of Microsoft Graph Java v6 version. You can follow this [issue](https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1949) for tracking.

**Comment by lramosvea** [comment]
Closing as tihs will be tracked in the bug mentioned above.
