### ISSUE TITLE
No details on using the links having password

### ISSUE THREAD

**Issue by vskvarma** [microsoftgraph/microsoft-graph-docs-contrib#712]
If there is a password protection for a sharing link, how do we pass the password with the HTTP call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ba86235-48d8-aff9-4673-b326cfb743bb
* Version Independent ID: 73dd3f74-bdd5-ac2d-ce99-866e78f5649d
* Content: [Access shared items - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/shares-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/shares-get.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
