### ISSUE TITLE
There is no documentation on which PDF standard it follows

### ISSUE THREAD

**Issue by vskvarma** [microsoftgraph/microsoft-graph-docs-contrib#713]
Please let us know which PDF/a standard it follows. example., ISO 19005-1

Having problems with numbers and date formats when converting excel which gives data in English-US formatting.

For more information see https://stackoverflow.com/questions/65133918/microsoft-graph-problems-with-numbers-and-date-formats-when-converting-excel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a53d4b0e-4bf4-01a7-229c-5073dd56f45d
* Version Independent ID: 8dc763d8-6252-d6af-5be5-99b7a9277fbd
* Content: [Convert to other formats - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get-content-format.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-get-content-format.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
