### ISSUE TITLE
Property 'hasPassword' appears to be available for OneDrive Business in 1.0 and Beta endpoints despite disclaimer

### ISSUE THREAD

**Issue by damiarnold** [microsoftgraph/microsoft-graph-docs-contrib#719]
Despite the disclaimer mentioned for the 'hasPassword' property in Permissions only applying to OneDrive **Personal**, I am seeing correct data coming back for this property based on the setting of an anonymous link with a password that is actually set in OneDrive for business file systems.

Best I can tell, the 'hasPassword' property and the ability to set the password were both added to the 1.0 endpoint back in April 2020, but it is unclear in the Changelog as to when or if the disclaimer ever applied to OneDrive Personal vs. ODB and Document Libraries.

Note that I have not yet tested whether this behavior is correct for Document Libraries, but that is my next exploration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e509d4f0-a240-05a8-1d12-291a0a1685bc
* Version Independent ID: 322f9be4-7921-41d8-78c2-2bdc62f916a3
* Content: [permission resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/permission.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
