### ISSUE TITLE
No documentation on the permissions that the calling user have to the file

### ISSUE THREAD

**Issue by vskvarma** [microsoftgraph/microsoft-graph-docs-contrib#721]
If I have created a file and want to check the file's permissions for myself they are not showing up.

Please look at this [SO thread](https://stackoverflow.com/questions/64648780/how-to-determine-if-the-caller-has-permissions-to-edit-a-onedrive-file-using-msg?noredirect=1#comment114493956_64648780). Please let us know if this doesn't work or it may work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1191235c-879e-dffc-82eb-4e8f7edfd29c
* Version Independent ID: 322f9be4-7921-41d8-78c2-2bdc62f916a3
* Content: [Permission - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/permission.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
