### ISSUE TITLE
Java code snippet

### ISSUE THREAD

**Issue by devagnanam** [microsoftgraph/microsoft-graph-docs-contrib#723]
[One of the ask from a developer customer is to include Java code sample for this in the documentation, along with lines of Javascript/C#.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a426c56-c822-0291-9b6d-55f6dc577d47
* Version Independent ID: 5f7d5689-24fe-10b5-945f-fc5023fe3cea
* Content: [Create plannerTask - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/planner-post-tasks?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/planner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/planner-post-tasks.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
Hi. Thanks for raising this issue.

The java code snippet is available [in the graph docs](https://learn.microsoft.com/en-us/graph/api/planner-post-tasks?view=graph-rest-1.0&tabs=java#request).
