### ISSUE TITLE
Upload large files with an upload session: specifying fileSize for the item as per docs result in 400 

### ISSUE THREAD

**Issue by timdiggins** [microsoftgraph/microsoft-graph-docs-contrib#725]
If you include a "fileSize" property of any size when creating an upload session (as per the docs provided on both https://docs.microsoft.com/en-gb/graph/api/resources/driveitemuploadableproperties but more importantly the examples implied by https://docs.microsoft.com/en-gb/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#request-body), then you get a 400.

![Resumable_file_upload_-_Microsoft_Graph_v1_0___Microsoft_Docs](https://user-images.githubusercontent.com/18395/98546863-3df3fd00-228f-11eb-99f7-0e311a98e88f.png)

Also: The docs at https://docs.microsoft.com/en-gb/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#request-body also confusingly only supplies the contents of the "item" property: 

FYI You also get a 400 if you include `"@odata.type": "microsoft.graph.driveItemUploadableProperties",` in the "item" object as per https://docs.microsoft.com/en-gb/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#request

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e6ce1c2-6f62-ccf4-3816-87d2c4eadc95
* Version Independent ID: da81af46-492e-a5a7-78e5-ae217d6f1c11
* Content: [Resumable file upload - Microsoft Graph v1.0](https://docs.microsoft.com/en-gb/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#create-an-upload-session)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
