### ISSUE TITLE
Clarify if Files permissions apply to OneDrive only or to SPO as well

### ISSUE THREAD

**Issue by itishnitsa** [microsoftgraph/microsoft-graph-docs-contrib#726]
Microsoft support engineer assured us that Files permissions apply only to OneDrive, while Sites permissions apply to SharePoint. The documentation for Files permissions doesn't specifically mention it (other than in the examples). Please clarify if an application that was granted Files permission could access files stored in SharePoint that a signed-in user has access to.
Please add clarity to the term "User files". Does "user files" mean files stored in OneDrive, or files that user has access to in both OneDrive and SharePoint?
If you grant Admin consent to Application permissions for Files.ReadWrite.All (Allows the app to read, create, update, and delete all files in all site collections without a signed in user.), will that application be able to modify ALL files across All OneDrive sites, or all files across SharePoint as well?
These details are critical.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
