### ISSUE TITLE
Are Application Permissions supported in creating List or is it a document bug?

### ISSUE THREAD

**Issue by vskvarma** [microsoftgraph/microsoft-graph-docs-contrib#729]
We are trying to create a list on our site and we are using the below call to create list with App only token. We have checked in jwt.ms and the token has the permission sites.readwrite.all according to the documentation but still we are getting 403 Forbidden error.

POST https://graph.microsoft.com/v1.0/sites/soaadteam.sharepoint.com,c1178396-d845-46fa-bc0c-453d2951dad5,19ee9a1e-001d-48f1-9ee8-b0adfde54e45/lists

Request Body:
{
  "displayName": "Books",
  "columns": [
    {
      "name": "Author",
      "text": { }
    },
    {
      "name": "PageCount",
      "number": { }
    }
  ],
  "list": {
    "template": "genericList"
  }
}

![image](https://user-images.githubusercontent.com/65310468/96878846-ebe26780-1498-11eb-8488-bd1eedc12915.png)

Is it really supported or its a document bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb2875d7-98df-2c37-5ce8-29d890938e6a
* Version Independent ID: c32f6075-dfc5-f32f-1c70-4de265a91274
* Content: [Create a SharePoint List - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/list-create?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/list-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/list-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
