### ISSUE TITLE
Add link to Share information as that's a convenient manner to get a DriveItem for any given SharePoint url pointing to a file

### ISSUE THREAD

**Issue by jansenbe** [microsoftgraph/microsoft-graph-docs-contrib#730]
Translating a SharePoint URL (regular document URL or sharing link) to a DriveItem is quite often needed...and enumerating Drives is not the best solution here. Would be good to link to the Share documentation here as that's a super easy manner to realize this scenario: https://docs.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079ba35-dd9e-fe22-5254-2b7e0b5ab650
* Version Independent ID: 18340dad-3014-1888-7bf7-3da9af9973e7
* Content: [Get a file or folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
