### ISSUE TITLE
Document How to Create New Files

### ISSUE THREAD

**Issue by conradbeach** [microsoftgraph/microsoft-graph-docs-contrib#731]
The [Create a new folder in a drive](https://docs.microsoft.com/en-us/graph/api/driveitem-post-children) documentation page only describes and demonstrates how to create new folders. However, the API can be used to create files in a very similar way:

```http
POST /me/drive/root/children
Content-Type: application/json

{
  "name": "New File",
  "file": { },
  "@microsoft.graph.conflictBehavior": "rename"
}
```

I think it would be helpful if this page was updated to demonstrate how to create files as well.

Does this page intentionally only document how to create folders because it's not intended to create files in the way I demonstrated? Is there a similar page that describes creating files? (I searched for one but didn't find it.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15b3e81f-2199-a155-a4ca-2b6f0c11f7ba
* Version Independent ID: 4b20c6a4-68f1-6fc5-7cd3-1e24ab2fcf5f
* Content: [Create a new folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-post-children.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-post-children.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
