### ISSUE TITLE
No documentation on listitem attachments

### ISSUE THREAD

**Issue by Mentate** [microsoftgraph/microsoft-graph-docs-contrib#737]
There is no document on how to upload files as attachments for list items. Also there is a picture field type that I cannot find any documentation on. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e00d6372-f1f5-58ea-0fdf-90496cc68abf
* Version Independent ID: 82a66768-cf64-369a-944f-fb6c282b340b
* Content: [listItem resource - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/listitem.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
