### ISSUE TITLE
How can we filter?

### ISSUE THREAD

**Issue by andifandrich** [microsoftgraph/microsoft-graph-docs-contrib#738]
Please provide examples on how to filter the list of returned items.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e70cdc2-b1b1-183d-4ee1-6082f91018c6
* Version Independent ID: 4beee916-2de5-5594-eb6f-725edc256229
* Content: [Retrieve items from a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-list?view=graph-rest-1.0&tabs=http&source=docs)
* Content Source: [api-reference/v1.0/api/listitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
