### ISSUE TITLE
Reg.: Java SDK API not working. But working fine with postman - NCDS creation

### ISSUE THREAD

**Issue by samrajcse** [microsoftgraph/microsoft-graph-docs-contrib#74]
When I am creating new NCDS, same API working fine with postman and not working with java SDK. Followed the steps as per the documentation.

**Postman Screenshot:**

<img width="663" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/696988/69950f08-5eb2-4169-a804-c71d8f2cf4ad">

Java code snippet:
```
EdiscoveryNoncustodialDataSource ediscoveryNoncustodialDataSource = new EdiscoveryNoncustodialDataSource();
		SiteSource dataSource = new SiteSource();
		Site site = new Site();
		site.webUrl = siteUrl;
		dataSource.site = site;
		ediscoveryNoncustodialDataSource.dataSource = dataSource;

		EdiscoveryNoncustodialDataSource ediscoveryNoncustodialDataSourceResponse = graphClient.security().cases().ediscoveryCases(caseId).noncustodialDataSources().buildRequest().post(ediscoveryNoncustodialDataSource);
		printNcdsInfo(ediscoveryNoncustodialDataSourceResponse);
```
	
Error log:

Jun 21, 2023 2:13:15 PM com.microsoft.graph.logger.DefaultLogger setLoggingLevel
INFO: Setting logging level to DEBUG
Jun 21, 2023 2:13:17 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[sendRequestInternal] - 408Graph service exception
Jun 21, 2023 2:13:17 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: BadRequest
Error message: @odata.type is Required in "dataSource" but not present

POST https://graph.microsoft.com/v1.0/security/cases/ediscoveryCases/19f38994-ac5c-44ea-a053-b15d98e333da/noncustodialDataSources
SdkVersion : graph-java/v5.61.0
SdkVersion : graph-java/v5.61.0
[...]

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
Exception in thread "main" com.microsoft.graph.http.GraphServiceException: Error code: BadRequest
Error message: @odata.type is Required in "dataSource" but not present

POST https://graph.microsoft.com/v1.0/security/cases/ediscoveryCases/19f38994-ac5c-44ea-a053-b15d98e333da/noncustodialDataSources
SdkVersion : graph-java/v5.61.0
SdkVersion : graph-java/v5.61.0
[...]

400 : Bad Request
[...]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4da24fb-414b-ad34-5689-d6adf9532b45
* Version Independent ID: bdf751ef-8177-12fa-62dd-218c222d37fa
* Content: [Create nonCustodialDataSources - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/security-ediscoverycase-post-noncustodialdatasources?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/security-ediscoverycase-post-noncustodialdatasources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/security-ediscoverycase-post-noncustodialdatasources.md)
* Product: **ediscovery**
* Technology: **microsoft-graph**
* GitHub Login: @SeunginLyu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
Hi @samrajcse we launched the new [Microsoft Graph Java v6 version](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v6.1.0). You can check more info about the new version in the [v6 announcement blog post](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/).

Please, reopen if the issue is still happening with v6.
