### ISSUE TITLE
Permissions needed for Teams sites needs to be clarified

### ISSUE THREAD

**Issue by MushyMiddle** [microsoftgraph/microsoft-graph-docs-contrib#748]
It seems that the permissions needed for getting Teams (group) sites isn't as simple as you state in the docs.  I have a global admin account in my tenant, and it can only see *some* of the Teams sites - many of them return 403 errors like:

`{  "error": {    "code": "accessDenied",    "message": "Access denied",    "innerError": {      "date": "2020-09-21T18:54:54",      "request-id": "1cc690db-e971-47f9-afdc-2f5ba5bffcac",      "client-request-id": "1cc690db-e971-47f9-afdc-2f5ba5bffcac"    }  }}`

Between two global admins, some common Teams sites cannot be obtained, but each admin is able to get a couple sites that the other cannot.  It *seems* like one factor may be that the admin has to also be either an owner or member of the Teams group in order to be able to get the site via the API.

Please clarify the requirements.

Further, if I do this in Graph Explorer, I get the same 403 error, but it says I need to consent to the additional permissions:

Forbidden - 403 - 579ms. You need to consent to the permissions on the Modify permissions tab

...but all of the permissions show as consented (I use Graph Explorer a lot, so that's no surprise):

![image](https://user-images.githubusercontent.com/32469479/93891138-16ce7580-fcb9-11ea-953f-c6ca215d32b4.png)

The API response JSON for the Graph Explorer request:

`{
    "error": {
        "code": "accessDenied",
        "message": "Access denied",
        "innerError": {
            "date": "2020-09-22T13:45:03",
            "request-id": "72bbadd6-dff6-4898-9dad-f66a8c5df91f",
            "client-request-id": "927dd615-6dd4-2ee0-71ff-efce37f2e2c3"
        }
    }
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9172b5-ac6d-173b-323a-05359e59a5e0
* Version Independent ID: e380088a-8e7f-2196-df1b-ffe86e199f12
* Content: [Get a SharePoint Site - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/site-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
