### ISSUE TITLE
There is no way to enumerate all site collections by geo

### ISSUE THREAD

**Issue by cnlike** [microsoftgraph/microsoft-graph-docs-contrib#750]
[Enter feedback here]
please add a way to enumerate all site collections by geo, please refer CSOM way:
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-sites#enumerate-site-collections

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7646ca28-c189-e84b-15af-6693dac77f5c
* Version Independent ID: df13ef64-7b81-8f5c-7949-5b18eece44fc
* Content: [Enumerate sites - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/site-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/site-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
