### ISSUE TITLE
ODATA filtering on lists and listitems is not working consistently ~ update documentation to indicate which fields support $filter

### ISSUE THREAD

**Issue by jansenbe** [microsoftgraph/microsoft-graph-docs-contrib#757]
Using $filter on a list query (e.g. `https://graph.microsoft.com/v1.0/sites/{siteid}/lists?$filter=displayName eq 'My List'`) only works when filtering on the displayName property...all others seem to fail with below error. Would be good to indicate in the docs which properties support $filter, a bit like is done for [users](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta) and [groups](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta)

```json
{
    "error": {
        "code": "invalidRequest",
        "message": "The provided filter statement is not supported",
        "innerError": {
            "date": "2020-09-07T18:43:43",
            "request-id": "044ec60c-4e7d-4d65-90a1-a20d8d08ee2f"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d0ccff7-e177-0d55-d5c5-1fb9cf728638
* Version Independent ID: 8955ee30-5dc2-43f3-105d-78d8baf6d727
* Content: [List the SharePoint lists in a site - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/list-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/list-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/list-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
