### ISSUE TITLE
Request limit not mentioned

### ISSUE THREAD

**Issue by nickalbrecht** [microsoftgraph/microsoft-graph-docs-contrib#758]
This page should explicitly mention that the request limit for SendMail cannot pass 4MB. If it does (assumedly due to file attachments), link off to pages elsewhere in the docs for details how to send mail that have large attachments. Specifically                             https://docs.microsoft.com/en-us/graph/outlook-large-attachments and/or https://docs.microsoft.com/en-us/graph/sdks/large-file-upload

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572e47b6-e504-0918-fc06-11217eea40a4
* Version Independent ID: c30fd8a1-e913-0192-7405-d55232ea3703
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Thanks.

**Comment by nickalbrecht** [comment]
I still don't see any mention of the nuances of SendMail vs UploadSession in the documentation? Or are you saying that the underlying API has been changed/fixed somehow and the documentation doesn't need to be altered any more? The page detailing how to attach large files still shows a different process than a simple SendMail. I'm not sure what has change by looking at the documentation that would indicate this is fixed?
