### ISSUE TITLE
Incorrect information of the page

### ISSUE THREAD

**Issue by wonderplayer** [microsoftgraph/microsoft-graph-docs-contrib#765]
The page is saying, that by this URL I will be able to receive specific list item fields.
https://graph.microsoft.com/v1.0/sites/contoso.sharepoint.com:/sites/TestSite:/lists/BSD/items?expand=fields(select=YesNo,Currency)
I've executed this as GET request in Graph explorer and in reality, I get the following error:
`{
    "error": {
        "code": "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
        "message": "The expression \"fields(select\" is not valid.",
        "innerError": {
            "date": "2020-08-25T12:04:16",
            "request-id": "04392c98-915c-4018-ab71-c226daaeb5cd"
        }
    }
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e70cdc2-b1b1-183d-4ee1-6082f91018c6
* Version Independent ID: 4beee916-2de5-5594-eb6f-725edc256229
* Content: [Retrieve items from a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-list?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/listitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
