### ISSUE TITLE
The permmissions doc doesn't explain why removing a permmission may silently fail

### ISSUE THREAD

**Issue by naugtur** [microsoftgraph/microsoft-graph-docs-contrib#767]
It seems possible to make a delete request that succeeds but does nothing

Owners role permission can't be removed in sharepoint and is silently failing for me. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbac80e5-ae35-b804-addd-53ccaf49e693
* Version Independent ID: b2a13be1-7783-38c2-c318-1261847240fa
* Content: [List who has access to a file - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-list-permissions.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
