### ISSUE TITLE
expand vs $expand - varying behaviour when expanding sharepointIds

### ISSUE THREAD

**Issue by jimmywim** [microsoftgraph/microsoft-graph-docs-contrib#775]
[This page](https://docs.microsoft.com/en-us/graph/query-parameters) says that the `$` is required on v1 and optional on beta.

However, on the current v1.0, the `$` appears optional.

When you omit $ on `expand=sharepointIds`, this works, but if you include it, e.g. `$expand=sharepointIds` then you get the following error:

`Parsing OData Select and Expand failed: Property 'sharepointIds' on type 'microsoft.graph.listItem' is not a navigation property or complex property. Only navigation properties can be expanded.`

This normally wouldn't be a huge issue (I'd just omit the `$`), but the current (3.9.0) Microsoft.Graph SDK always includes the $, so the requests are always failing.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cae3149-c915-eee0-29da-5f5d515c3019
* Version Independent ID: 334d5d8f-79ec-6063-a026-c09a2f764b9a
* Content: [driveItem resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-gb/graph/api/resources/driveitem?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/driveitem.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
