### ISSUE TITLE
cTag changes on rename

### ISSUE THREAD

**Issue by LingerIT** [microsoftgraph/microsoft-graph-docs-contrib#782]
When using a /delta call to pull changes on a drive the cTag isn't formatted as described nor does it work as described.
Documentation suggests it should be in the form:
"cTag": "aYzpENDY0OEYwNkM5MUQ5RDNEITU0OTI3LjI1Ng"

However in practice it comes out as:
"cTag": ""c:{F77A5ED4-547F-4722-A791-89FA8C16D688},1"",

So there's extract "c:" at the beginning a a number at the end.

If the item is renamed the whole cTag changes, but only the number at the end appears to change.
Should I be splitting up the string that is returned and assuming the part in {} is the indicator for content changes?
What does the "C:" and the number at the end mean?

Or should I just rely on the presence of a hash (XOrHash) to determine if the file has actually changed?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cae3149-c915-eee0-29da-5f5d515c3019
* Version Independent ID: 334d5d8f-79ec-6063-a026-c09a2f764b9a
* Content: [driveItem resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/driveitem.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
