### ISSUE TITLE
There's no description about how to use the $search parameter when querying SharePoint Online lists/libraries

### ISSUE THREAD

**Issue by abiarge** [microsoftgraph/microsoft-graph-docs-contrib#783]
Hi,
I've been trying to use the $search parameter to implement searchs in SharePoint Online managed properties so as to search for words in indexed columns.
I understand that this is the correct approach based on the docs, as the $filter only admits the "startswith" operation, even though, through managed properties, you can search in SharePoint Online in a "contains" fashion.

Also, I understand that using the $search param is the right approach, as the Search API targets the whole organization through Microsoft Search and I only need to search for items inside a SharePoint Online list or document library.

I see no details of this in the docs, nor in the $search documentation here.

Thanks in advance,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#expand-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
