### ISSUE TITLE
Url life time

### ISSUE THREAD

**Issue by Ptelea** [microsoftgraph/microsoft-graph-docs-contrib#792]
The url parameter of the Thumbnail resource type seems to expire within 24 hours. It might be a good idea to mention this somewhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34278783-5c78-7257-bb3b-469d0046743d
* Version Independent ID: 35192842-4fc6-b17d-d228-4e1edcfc5035
* Content: [Thumbnail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/thumbnail?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/thumbnail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/thumbnail.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
