### ISSUE TITLE
Please add a section called "getting files by URL"

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/microsoft-graph-docs-contrib#799]
I've visited this page probably 50 times in the last three months, and I've never noticed /shares/{share-id}, which appears to be one of the most important endpoints for this resource. I've been telling my customers to resolve a site ID, then resolve a library ID, then resolve a folder ID, then get a drive item ID when I could have told them to just use /shares instead.

This page desperately needs a dedicated section to help folks figure out how to use URLs to resolve drive and drive item IDs with as few requests as possible. The second table under "Commonly accessed resources" is great, but definitely needs more visibility. Additionally, I'd recommend moving /shares/{share-id} to the second table (or its own area in the new section). Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc8c9d10-59cf-de2d-0bcf-338bc2591581
* Version Independent ID: e7c2c05b-2f62-1358-b746-9e2f119ee957
* Content: [Working with files in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/onedrive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/onedrive.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @Lauragra
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
