### ISSUE TITLE
Reg.: Java SDK for create case search not working

### ISSUE THREAD

**Issue by samrajcse** [microsoftgraph/microsoft-graph-docs-contrib#80]
Hi Team,

I am trying to create Search with JAVA beta SDK and I am getting this error.

> 
> Exception in thread "main" com.microsoft.graph.http.GraphServiceException: Error code: BadRequest
> Error message: At least one data source is required.
> 
> POST https://graph.microsoft.com/beta/security/cases/ediscoveryCases/aab456e7-07fe-4416-a6bd-a2339cc80600/searches
> SdkVersion : graph-java/v0.73.0
> SdkVersion : graph-java/v0.73.0

POST URL: https://graph.microsoft.com/beta/security/cases/ediscoveryCases/aab456e7-07fe-4416-a6bd-a2339cc80600/searches

Payload used in postman working fine:
{
    "displayName": "Sam Postman1",
    "description": "Sam Post man1",
    "contentQuery": "(title:\"keyword\")",
    "custodianSources@odata.bind": [
        "https://graph.microsoft.com/beta/security/cases/ediscoveryCases/aab456e7-07fe-4416-a6bd-a2339cc80600/custodians/aab456e7-07fe-4416-a6bd-a2339cc80600/userSources/43313742-3541-3941-3442-323144363044"
    ]
}

But As per the documentation I am trying to create via Java sdk throws error.

```
private static void createCaseSearch(String caseId, String custodianId, String userSourceId) {
		EdiscoverySearch ediscoverySearch = new EdiscoverySearch();
		ediscoverySearch.displayName = "Sam-Search-API "+new Date();
		ediscoverySearch.description = "Sam Search API desc "+new Date();
		ediscoverySearch.contentQuery = "(title:\"keyword\")";
		
		String jsonFormat="[\r\n"
				+ "        \"https://graph.microsoft.com/beta/security/cases/ediscoveryCases/aab456e7-07fe-4416-a6bd-a2339cc80600/custodians/aab456e7-07fe-4416-a6bd-a2339cc80600/userSources/43313742-3541-3941-3442-323144363044\"\r\n"
				+ "    ]";
		System.out.println(jsonFormat);
		ediscoverySearch.additionalDataManager().put("custodianSources@odata.bind", new JsonPrimitive(jsonFormat));
		
	EdiscoverySearch ediscoverySearchResponse=	graphClient.security().cases().ediscoveryCases(caseId).searches()
			.buildRequest()
			.post(ediscoverySearch);

	printEdiscoverySearch(ediscoverySearchResponse);
	}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7a39ea3-1613-73bd-845b-372a3b4f533b
* Version Independent ID: 5ee3fc3f-dce2-80bc-aa11-82b930ed37f0
* Content: [Create searches - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/security-ediscoverycase-post-searches?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/security-ediscoverycase-post-searches.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-ediscoverycase-post-searches.md)
* Product: **ediscovery**
* Technology: **microsoft-graph**
* GitHub Login: @SeunginLyu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
Hi @samrajcse, as mentioned in other issue raised by you, we launched the new Microsoft Graph Java v6 version for both [v1](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v6.1.0) and [beta](https://github.com/microsoftgraph/msgraph-beta-sdk-java/releases/tag/v6.1.0) libraries.

Please, reopen if the issue is still happening with v6.
