### ISSUE TITLE
Update example request to GET /drives/{drive-id}/items/{item-id}/analytics/allTime

### ISSUE THREAD

**Issue by Sbounardjian** [microsoftgraph/microsoft-graph-docs-contrib#802]
The current example `GET /drives/{drive-id}/items/{item-id}/analytics` returns 200 with an empty response. 
According to a [user on stackoverflow](
https://stackoverflow.com/questions/54462099/endpoint-get-analytics-returning-empty-response), the request requires "adding /lastSevenDays or /AllTime" to get data.
`GET /drives/{drive-id}/items/{item-id}/analytics/allTime`
If this is correct, please update this page. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc23aedb-c478-2515-0d37-a3683897eebc
* Version Independent ID: 60536091-1ce7-fde8-9e39-115517304400
* Content: [Get itemAnalytics - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/itemanalytics-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/itemanalytics-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/itemanalytics-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @daspek
* Microsoft Alias: **dspektor**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed now. Thanks.
