### ISSUE TITLE
Show how to get the drive item of the AppRoot Folder

### ISSUE THREAD

**Issue by TheJoeFin** [microsoftgraph/microsoft-graph-docs-contrib#805]
I'm trying to enumerate the children of a folder in the special folder AppRoot, but the docs show drive ID listed, but what is the drive ID of the AppRoot? Docs should show real world code examples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18dfd099-0d73-55e4-56ec-d9129b83aa07
* Version Independent ID: 5705a946-2c25-0d04-a297-01ccb21d7284
* Content: [List the contents of a folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/driveitem-list-children.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-list-children.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
