### ISSUE TITLE
"parentReference" documentation is not present

### ISSUE THREAD

**Issue by mridul111998** [microsoftgraph/microsoft-graph-docs-contrib#806]
When we list subsites of a particular site then it returns a field named "parentReference". There is no documentation provided for that in list subsites page and it is not present in this as well https://docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0#properties
Can anyone explain what is expected in this field?

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2b58b7-f671-c0c7-c9af-be3ebeff4ca0
* Version Independent ID: 81e2536b-50e0-f3d9-cc1b-321db028e539
* Content: [List the subsites for a SharePoint site - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-list-subsites?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-list-subsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-subsites.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
