### ISSUE TITLE
listitem-list.md

### ISSUE THREAD

**Issue by Code-Padawan** [microsoftgraph/microsoft-graph-docs-contrib#808]
Getting the following error when trying to do the example for selecting columns for expand field. 
 "The expression \"fields(select\" is not valid." 

Attempted URL: https://graph.microsoft.com/v1.0/sites/98bd718b-1c84-428c-ab4b-f812f885f695/lists/2d942658-91e0-4f20-a9d7-de19a94868fd/items?expand=fields(select=EventDate)

Would also be nice to see filtering options. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2524650e-06e7-dc8c-b2ae-0c2fbffdb541
* Version Independent ID: 3eb41d73-2b60-1459-e921-20403004655c
* Content: [Retrieve items from a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
