### ISSUE TITLE
Format parameter is not required

### ISSUE THREAD

**Issue by egmfrs** [microsoftgraph/microsoft-graph-docs-contrib#810]
We used this for building print functionality in our app. if you actually want to print files that are already pdf or non supported formats, just remove ?format=pdf from the request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59cfb473-0783-09cb-3c88-96f884d76e06
* Version Independent ID: 9992b18b-299d-6863-c06f-8bacb7ff2962
* Content: [Convert to other formats - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get-content-format.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-get-content-format.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
