### ISSUE TITLE
example mention owner but API does not return owner attribute

### ISSUE THREAD

**Issue by piyushrajput** [microsoftgraph/microsoft-graph-docs-contrib#815]
[Enter feedback here]

The example on the page displays owner info for the site
`{
  "id": "contoso.sharepoint.com,2C712604-1370-44E7-A1F5-426573FDA80A,2D2244C3-251A-49EA-93A8-39E1C3A060FE",
  "owner": {
    "user": {
      "displayName": "Daron Spektor",
      "id": "5280E7FE-DC7A-4486-9490-E790D81DFEB3"
    }
  },
  "displayName": "OneDrive Team Site",
  "name": "1drvteam",
  "createdDateTime": "2017-05-09T20:56:00Z",
  "lastModifiedDateTime": "2017-05-09T20:56:01Z",
  "webUrl": "https://contoso.sharepoint.com/teams/1drvteam"
}`

but API does not return owner property at all and there is no property owner in the list of properties for the site object. Am I missing something?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c881f34-7d5a-f599-6a42-b7d83628f052
* Version Independent ID: dd1aa2b5-55fa-9114-7bf4-6dd0b887d1ca
* Content: [Get a SharePoint Site - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/site-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
