### ISSUE TITLE
Document that OneDrive may modify uploaded files

### ISSUE THREAD

**Issue by tomyl** [microsoftgraph/microsoft-graph-docs-contrib#817]
Something that isn't obvious is that OneDrive may modify the file you just uploaded, at least for Office files uploaded to SharePoint/Team drives, meaning that the drive item and your local file may end up having different sizes. It comes as a great surprise if you (incorrectly) think of OneDrive as a blob store. Is this behavior documented anywhere? Specifically I would like to know if the modification is guaranteed to be synchronous i.e. is the size returned in the PUT response final or do I have to monitor the file for a while?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92fb8c7-4409-d945-57dd-5d6fc4010051
* Version Independent ID: f77c05bd-2688-bd4e-1f8f-f18feb3a8639
* Content: [Upload small files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
