### ISSUE TITLE
Specific mention of Files tabs in Teams would be beneficial

### ISSUE THREAD

**Issue by SplatManDK** [microsoftgraph/microsoft-graph-docs-contrib#819]
Interacting with File tabs in Teams is increasingly important because Teams is being positioned for more and more use cases. A small description (or reference to another article) about how to get lists of drive resources associated with a user, their friendly names, etc. would be helpful. Especially as end-users may be associated with many teams, and each may have many file tabs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc8c9d10-59cf-de2d-0bcf-338bc2591581
* Version Independent ID: e7c2c05b-2f62-1358-b746-9e2f119ee957
* Content: [Working with files in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/onedrive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/onedrive.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @Lauragra
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
