### ISSUE TITLE
Get a site resource. The explanation and example doesn't match

### ISSUE THREAD

**Issue by javieralvarezchiang** [microsoftgraph/microsoft-graph-docs-contrib#82]
I landed on this page due a request for information and noticed that the explanations and the example don't match. Either there's one explanation missing that matches the example (the most likely scenario) or the example belongs to a different page. This is a minor issue, but I bet it could cause confusion in some readers.

explanations in the page:
GET /sites/root
GET /sites/contoso.sharepoint.com
GET /sites/{hostname}:/{server-relative-path}
GET /groups/{group-id}/sites/root

(notice that there's no explanation on getting a site by id)

example:
GET https://graph.microsoft.com/v1.0/sites/{site-id}

As an additional detail, the request of information is from someone who is trying to get the site-id. I don't have more information, but obviously they are using one of the explanations that don't have an example associated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d792f6b-8c07-bb1e-1d8c-f0f779951e0b
* Version Independent ID: dd1aa2b5-55fa-9114-7bf4-6dd0b887d1ca
* Content: [Get a SharePoint Site - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&amp%3Btabs=http&tabs=http#request)
* Content Source: [api-reference/v1.0/api/site-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
