### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by itsorch** [microsoftgraph/microsoft-graph-docs-contrib#821]
/sites?search={query} doesn't make sense to anyone. I have tried to use every query string variation available and can't make this work, i'm trying to search for sitenames using flow and so the following isn't working (where Transport is a variable in Flow):
search={Transport in displayName} 
search="Transport in displayName"
search={displayName:Transport}
search="displayName:Transport"
I have even tried all of these as:
sites?$search=

search={Transport}  =returns results where transport could be anywhere (in the name, description or anywhere in the site)

Can we have some examples showing exactly how you have constructed your search as you don't seem to have followed any standards here, and I also need to be able to search based on one property not just search all of the sites contents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5159efcf-058c-7bf8-3bd4-a680224b72b6
* Version Independent ID: f94e77f3-c166-cc46-de80-b4ca5e8e2803
* Content: [Search for sites - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/site-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-search.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
