### ISSUE TITLE
Query site security groups

### ISSUE THREAD

**Issue by ronlib** [microsoftgraph/microsoft-graph-docs-contrib#822]
It seems like there is no way to get information about the security groups of a SharePoint site using the Graph API.
Is there a way to do that?
If not, it would be very helpful to have that, as currently we are resolving to creating a SharePoint add-in to get this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217852fe-79b1-a74c-3ff5-c059f4e7ca47
* Version Independent ID: 170e578f-ddd3-857c-f137-7cb3508aeefe
* Content: [site resource - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
