### ISSUE TITLE
API response doesn't match documentation for DriveItem resource createdBy, lastModifiedBy 

### ISSUE THREAD

**Issue by dcakirkaya** [microsoftgraph/microsoft-graph-docs-contrib#824]
According to the information on this page createdBy & lastModifiedBy are of "microsoft.graph.identitySet" type, however the responses from API (v1.0) seem to be a different type (containing email instead of user id and no thumbnails information). 

	• Response of https://graph.microsoft.com/v1.0/me/drive/sharedWithMe

{ … 
            "createdBy": {
                "user": {
                    "email": "###",
                    "displayName": "###"
                }
            },
            "lastModifiedBy": {
                "user": {
                    "email": "###",
                    "displayName": "###"
                }
            }
..
}

	• The response of the SharedWithMe is supposed to be "DriveItem" type with createdBy, lastModifiedBy defined as 
"createdBy": {"@odata.type": "microsoft.graph.identitySet"},
"lastModifiedBy": {"@odata.type": "microsoft.graph.identitySet"},
 
	• microsoft.graph.identitySet 
{
  "application": {"@odata.type": "microsoft.graph.identity"},
  "device": {"@odata.type": "microsoft.graph.identity"},
  "user": {"@odata.type": "microsoft.graph.identity"}
}
	•  microsoft.graph.identity  --&gt; There's no "email" property here, but just (user) id .
{
  "displayName": "string",
  "id": "string",
  "thumbnails": { "@odata.type": "microsoft.graph.thumbnailSet" }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cae3149-c915-eee0-29da-5f5d515c3019
* Version Independent ID: 334d5d8f-79ec-6063-a026-c09a2f764b9a
* Content: [driveItem resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/driveitem.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
