### ISSUE TITLE
Attendee emailAddress doesn't always return an actual email

### ISSUE THREAD

**Issue by zmh** [microsoftgraph/microsoft-graph-docs-contrib#825]
We began adding support for Microsoft Outlook calendars within our application, and imported events successfully. However, upon further inspection of [the attendee object](https://docs.microsoft.com/en-us/graph/api/resources/attendee?view=graph-rest-1.0), specifically the [emailAddress object's address field](https://docs.microsoft.com/en-us/graph/api/resources/emailaddress?view=graph-rest-1.0), we realized that `address` is always a string but of non-standard format, which is incredibly unorthodox and confusing.

So far, we've seen 3 types of responses in the `address` field:

1. An email address, like `"jane@outlook.com"`
2. What appears to be a name, like `"Jane Doe"`
3. A combination of name and email with angle brackets, like `"Jane Doe <jane@outlook.com>"`

Note that these were all from 1 person's email account, so it's not like it's an account setting or anything.

Is this expected, and if so, can it be better documented? And if not expected, can we please understand whether it's a known issue and a fix is coming? Addresses should be, well, addresses 😁

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c564bd3c-9773-d2c1-76bc-02714e138043
* Version Independent ID: e1005cc1-813d-d865-8208-8f18c9c1bd4e
* Content: [emailAddress resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/emailaddress?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/emailaddress.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/emailaddress.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by p0lygun** [comment]
Bump, we had an even weird case where `address` field of `emailAddress` is missing. this emailAddress is the one under 
`{"@odata.type": "microsoft.graph.attendee"}`, 

data received,
```json
{
  "emailAddress": {
    "name": "John Doe"
  },
  "status": {
    "response": null,
    "time": "0001-01-01T00:00:00Z"
  },
  "type": "required"
}
```
