### ISSUE TITLE
Make permissions management documentation greate again!

### ISSUE THREAD

**Issue by Damag3d** [microsoftgraph/microsoft-graph-docs-contrib#826]
No info about roles, about corresponding SP roles, about SP inheritance. Please add more samples and explanations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75e1562-24d6-bfaf-be46-d52ee93ffb1d
* Version Independent ID: cd35f8f6-774e-70d3-9bd5-11110ab450b1
* Content: [Send an invite to access an item - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-invite.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
