### ISSUE TITLE
Optional query parameters

### ISSUE THREAD

**Issue by ashleywb** [microsoftgraph/microsoft-graph-docs-contrib#827]
The documentation refers to 'Optional query parameters' are available.  if I try and run the following
$expand=ListItem($expand=Fields($select%20=Field1,Field2,Field3)) 
I get the following error :
"code": "badArgument",
 "message": "One of the provided arguments is not acceptable.",

If I run the following on 
/drives/{DRIVEID}/root/children it works as expected. Are there limitations on what you can expand on etc?
Thanks
       

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5785f90e-b37c-c5a5-ddbc-7170307980c9
* Version Independent ID: d8b7729e-38c4-5562-7359-5e926f8d7ae4
* Content: [Sync the contents of a drive - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-delta.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
