### ISSUE TITLE
What about permissions

### ISSUE THREAD

**Issue by Damag3d** [microsoftgraph/microsoft-graph-docs-contrib#828]
Does copy also copies permissions? I understand it cannot be guaranteed, but does it try to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d887c2a6-40ba-675b-7b09-a7a3fffe17f5
* Version Independent ID: 03692ea1-b802-f768-a3bc-04a846b6771a
* Content: [Copy a file or folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-copy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-copy.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
