### ISSUE TITLE
Examples are misleading or incorrect or need more details

### ISSUE THREAD

**Issue by mcqueene** [microsoftgraph/microsoft-graph-docs-contrib#829]
The examples are either incorrect or misleading and need more clarification on exactly what situation they can be used. Given the examples you would think to upload a new file to SharePoint the format would be "PUT /sites/{site-id}/drive/items/{parent-id}:/{filename}:/content" however this appears to only work for the default Documents folder only as if you try to use the the drive-id of any other document library for the parent-id it fails. Plus it fails to include the syntax example where a folder can be added although this only creates that folder in the default Documents folder. It would seem the only purpose of that syntax is the default Documents folder of a SharePoint site, but this is also not clear. If you want to upload to a particular document library in SharePoint the syntax I finally found to work would be "PUT /drives/{drive-id}/items/{parent-id}:/{filename}:/content". This syntax does't have the reference to the site at all as one might expect when working with SharePoint. This syntax could be confused as being specific to OneDrive, which it might also work for, but it isn't exactly known. The section that lists the various commands should at least be enhanced to indicate when each sample is intended to be used. This same can be applied to the other examples.

PUT /drives/{drive-id}/items/{parent-id}:/{filename}:/content
PUT /groups/{group-id}/drive/items/{parent-id}:/{filename}:/content
PUT /me/drive/items/{parent-id}:/{filename}:/content
PUT /sites/{site-id}/drive/items/{parent-id}:/{filename}:/content
PUT /users/{user-id}/drive/items/{parent-id}:/{filename}:/content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92fb8c7-4409-d945-57dd-5d6fc4010051
* Version Independent ID: f77c05bd-2688-bd4e-1f8f-f18feb3a8639
* Content: [Upload small files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
