### ISSUE TITLE
Quota permissions

### ISSUE THREAD

**Issue by tlingenf** [microsoftgraph/microsoft-graph-docs-contrib#832]
The quota is assigned at the site object and therefore one of the site permissions (Sites.Read.All, Sites.ReadWrite.All) is required to retrieve quota values. The File access permissions will return empty quota values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db852ccb-b0b8-41ce-0eb4-5996079374a1
* Version Independent ID: 598c4f75-f2b0-25cf-81f3-6aac3ce7a573
* Content: [Get Drive - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/drive-get?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/drive-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/drive-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
