### ISSUE TITLE
Application permissions ... not working

### ISSUE THREAD

**Issue by cirpka** [microsoftgraph/microsoft-graph-docs-contrib#842]
The sites/root command seems not work from the application context (ResourceNotFound message). In https://docs.microsoft.com/en-us/graph/permissions-reference there is a tiny remark stating "Sites permissions are valid only on work or school accounts. " while in the section above as well as in the permissions reference just referenced application scoped permissions are mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d792f6b-8c07-bb1e-1d8c-f0f779951e0b
* Version Independent ID: dd1aa2b5-55fa-9114-7bf4-6dd0b887d1ca
* Content: [Get a SharePoint Site - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/site-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
