### ISSUE TITLE
Documentation inconsistent with API behavior - mail and proxyAddresses properties

### ISSUE THREAD

**Issue by franciscopgomes** [microsoftgraph/microsoft-graph-docs-contrib#8421]
The "mail and proxyAddresses" section of this document mentions the following:

proxyAddresses are unique across directory objects (users, groups, and organizational contacts). If a user's mail property conflicts with one of the proxyAddresses of another object, you'll successfully update the mail property; however, the new mail value won't be added to the proxyAddresses collection.

This doesn't seem to be true, when attempting to update a user's mail property with a value that is present in another user's proxyAddresses collection, MS Graph replies with a 400 and neither the proxyAddresses nor the mail properties are updated for this user. Here is an example response from MS Graph in this case:

{
    "error": {
        "code": "Request_BadRequest",
        "message": "Another object with the same value for property proxyAddresses already exists.",
        "details": [
            {
                "code": "ObjectConflict",
                "message": "Another object with the same value for property proxyAddresses already exists.",
                "target": "proxyAddresses"
            },
            {
                "code": "ConflictingObjects",
                "message": "Another object with the same value for property proxyAddresses already exists.",
                "target": "User_26eb6756-af5f-4f2c-a901-39b73e42be5b"
            }
        ],
        "innerError": {
            "date": "2023-08-17T08:11:07",
            "request-id": "1bf26bd5-e576-462c-acaf-934efeb6e483",
            "client-request-id": "524a4f17-38b1-1cee-bd30-06202e3f8645"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#mail-and-proxyaddresses-properties)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @franciscopgomes for raising this issue. Unfortunately, this forum is only for documentation-related issues but [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/266/microsoft-graph-users-api) is the best forum to answer this functionality question so I recommend that you raise this question there. You may be requested for a request ID for investigation. 

No updates identified for the documentation for now, but the docs will be updated when new information is available. Closing this issue here.
