### ISSUE TITLE
Example for adding resource role scopes to accessPackages 

### ISSUE THREAD

**Issue by tmocanu** [microsoftgraph/microsoft-graph-docs-contrib#8424]
[Enter feedback here]

There is no example on jow to add/assign Groups/Apps to an accessPackage resourceRoleScope. The example on the documentation is only for SharePoint. 

We are looking for the following functionality in Graph v1.0 
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/104973595/b4117fd4-0c16-4d09-970f-ae5738661558)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f330348c-18fd-8497-fa11-c68753891776
* Version Independent ID: 0f2c168f-8357-ab3f-96c3-381aa04c980f
* Content: [Create resourceRoleScope - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/accesspackage-post-resourcerolescopes?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/accesspackage-post-resourcerolescopes.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/accesspackage-post-resourcerolescopes.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
Thanks for your feedback, additional examples have been added to this article.
