### ISSUE TITLE
Permanent delete - wrong return type and description

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#8425]
The table in the section [Methods](https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0#methods) shows incorrect return type and description for **permanent delete**.

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/7744844/56cd9313-ae4f-4873-aa55-df63219f893f)

The **permanent delete** is also missing in the left menu **API v1.0/beta reference** -> **Files** -> **Drive items**

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/7744844/afc5db7f-3b7a-4706-883c-097981bad5d5)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cae3149-c915-eee0-29da-5f5d515c3019
* Version Independent ID: 334d5d8f-79ec-6063-a026-c09a2f764b9a
* Content: [driveItem resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/driveitem.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The issue have been fixed. I'm going to close this item. Thanks for your understanding.
