### ISSUE TITLE
Error code: BadRequest Error message: Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by CameronCowles1** [microsoftgraph/microsoft-graph-docs-contrib#8429]
Within the past couple of days, I've been getting a lot of the above error for various requests, mostly for the list hosted contents endpoint.  If it's relevant, we're still using the 0.62.0-SNAPSHOT.  Would upgrading the version be enough to stop seeing this error, and if not, do you know what's causing it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce8529a5-0f26-729a-e68a-a5baa2a7c8d6
* Version Independent ID: a5a4b836-22c8-8d6f-9af5-2e84a0ed423f
* Content: [List hostedContents - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&tabs=java#optional-query-parameters)
* Content Source: [api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/chatmessage-list-hostedcontents.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Can you pull a trace and share client-request-Id and timestamp for the failed calls? They are in headers of response

**Comment by CameronCowles1** [comment]
Sorry about the delay, I have 3 sets of headers here for requests I just made:

client-request-id : 6d28b8c1-cab1-45c8-acad-7aa997948242
request-id : c62e1478-c493-447a-99a3-ac0b06907ccb
Date : Fri, 18 Aug 2023 21:04:50 GMT

client-request-id : c1017290-1dea-4438-a675-6ccdd5209f6f
request-id : 882177eb-f119-4efa-a72b-5267ded58e34
Date : Fri, 18 Aug 2023 21:06:14 GMT

client-request-id : 4582b777-3a63-4044-b0ae-eb9ef0c4fde3
request-id : c2debd69-3e8b-4238-bc3a-7a23424a8c75
Date : Fri, 18 Aug 2023 21:06:42 GMT

**Comment by CameronCowles1** [comment]
Ah, I don't think they do, or at least some of them don't.  Would that cause the error I found above?

**Comment by RamjotSingh** [comment]
I think it is, will fix on our side to not throw error as well!

**Comment by CameronCowles1** [comment]
Ah, thank you!  For context, the messages not having the hosted contents was previously not causing errors as far as I know (the code I'm using hasn't been changed in a few months as far as I can tell).

**Comment by sayali-MSFT** [comment]
@CameronCowles1 - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by CameronCowles1** [comment]
Sorry, I am still encountering this issue.  There are requests as recent as 5 days ago still encountering the "Value cannot be null. (Parameter 'source')" error.

**Comment by sayali-MSFT** [comment]
@CameronCowles1 - Can you please share client-request-Id and timestamp for the failed calls?

**Comment by sarritalhami** [comment]
I am also getting this error: 
```
"error" => array:3 [▼
    "code" => "BadRequest"
    "message" => "Value cannot be null. (Parameter 'source')"
    "innerError" => array:3 [▼
      "date" => "2023-11-28T02:15:49"
      "request-id" => "746e8a5a-5d09-422e-95f2-d8450c200376"
      "client-request-id" => "746e8a5a-5d09-422e-95f2-d8450c200376"
    ]
  ]
```
