### ISSUE TITLE
Why can I not send Teams Chat Messages as Application? Is this a decision or not yet implemented?

### ISSUE THREAD

**Issue by beggarboy** [microsoftgraph/microsoft-graph-docs-contrib#8432]
I just spent 3 hours trying to implement a Teams Chat method for our company-internal mailing library, spending 2 hours of that on headaches why my call is not going through, only to discover this in the MSDN:
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/8734961/f3040555-6eda-4574-abff-abd45673bf9b)

I sincerely hope this is coming in very near update and **this is simply not yet done**, because the current implementation feels like it's missing a leg.

If this is a decision that it shouldn't be allowed on Application level... why?
What are we scared of here? Discord has a huge bot infrastructure and they found a way to manage it too.

I hate being this blunt with respected devs, but I sincerely hope this is not a permanent decision, because it feels really dumb being able to create a chat, even have that listed in the Graph Explorer 4, but not being able to send a chat message. You couldn't have baited me harder into wasting my time on implementation here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd20894e-4782-6c3f-aa89-a9c3b75c0bba
* Version Independent ID: 27b8eca1-ad6a-2881-a029-8d392c470b78
* Content: [Send message in a chat - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/chat-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
It is something that hasn't been implemented yet. We will have some update over the next ~9 months.

**Comment by beggarboy** [comment]
Thanks for the update @RamjotSingh on the situation. Appreciate it.
