### ISSUE TITLE
request recommendations for more than 20 identities

### ISSUE THREAD

**Issue by cchapin2020** [microsoftgraph/microsoft-graph-docs-contrib#8433]
[Enter feedback here]
The last paragraph says that there is a limit of 20 federated identity credentials can be added per application object. What is the recommendation if there is a need for more than 20 credentials? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd2c231-5d5c-f5c2-ce5b-9e66b890745b
* Version Independent ID: 1eb57d56-5c8a-0984-ef01-972576dee1d2
* Content: [Overview of federated identity credentials in Azure Active Directory - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0#design-considerations)
* Content Source: [api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/federatedidentitycredentials-overview.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @nickludwig
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nickludwig** [comment]
Hey @cchapin2020 - unfortunately there isn't much in terms of a workaround here. The two options at hand are either... a) split management of the scenario across multiple app registrations or managed identities or b) if you're trying to authorize AKS workloads, you can consider using AKS Pod Identity until we have a native solution built (though Pod Identity is being retired in September 2024, so this isn't particularly recommended). 

I can assure you we are both well aware of this limitation, and actively working on solutions for this.

I'm going to leave this issue open for a few days for any follow-up you may have. If I don't hear anything back, I'll go ahead and close it.

**Comment by cchapin2020** [comment]
Thanks @nickludwig - it seems that option A is the path that I should recommend to my customer with the "were working on it". Hopefully that will help lessen the cus satisfaction issue -

**Comment by nickludwig** [comment]
Sounds good. I'm going to go ahead and close the issue. Feel free to re-open if you have more to add.
