### ISSUE TITLE
Audit Basic Claims

### ISSUE THREAD

**Issue by ld0614** [microsoftgraph/microsoft-graph-docs-contrib#8444]
I'm currently trying to assess a large environment for the use of the user.mail attribute as such was looking at the documentation https://learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?tabs=http%2Cpowershell-script#step-3-configure-claims-mapping. It would be really useful to understand the code needed to review and/or modify the basic claims. For reference I'm talking about claims surfaced through the following GUI

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/20439950/db28ecae-91b1-4ccb-b819-3eb1aa230c46)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9067ae9-89d0-5854-7327-856d930e7712
* Version Independent ID: e0ed6a1b-34bc-55a2-b4ca-61fe3f8ca367
* Content: [Use Microsoft Graph APIs to configure SAML-based single sign-on - Microsoft Graph](https://learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?tabs=powershell%2Cpowershell-script)
* Content Source: [concepts/application-saml-sso-configure-api.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/application-saml-sso-configure-api.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @ld0614 for raising this issue. Unfortunately, this forum is only for documentation-related issues but [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/306/microsoft-graph-extensions-api) is the best forum to get help with code so I recommend that you raise this question there. 

No doc updates identified for now, but we'll update the documentation when we get new information. Closing this issue here.

**Comment by ld0614** [comment]
Hi @FaithOmbongi 

I was mentioning what I was doing primarily to provide additional context relating to the documentation request. My belief is that the document named Automate SAML-based SSO configuration is missing key information as it does not cover the automation to basic claim mapping which is something that can be done via the portal and IMO fits into the spirit of the current documentation/document title.

**Comment by FaithOmbongi** [comment]
Thanks for the additional context @ld0614. I'll reopen this issue to allow for further investigation and doc updates that will address your feedback.

cc @AllisonAm

**Comment by AllisonAm** [comment]
Hi! Today, you can only use claims mapping policies to programmatically manipulate claims for a given application. Basic claims are only able to be edited manually via the portal. The documentation covers only the claims mapping policies, as that's the only automatable/programmatic option. As we change this, we'll ensure we update this article.
