### ISSUE TITLE
The update of a web part fails when the page contains a "Quick Links" web part

### ISSUE THREAD

**Issue by lucmoco** [microsoftgraph/microsoft-graph-docs-contrib#8455]
I'm using this endpoint to update a text web parts _A_ in a SharePoint page.

Most of the time the update is successful, but if there is in the page anywhere a web part _B_ of type "Quick Links" AND _B_ contains a link of type "OneDrive", "Site" or "Upload", the MS Graph operation fails with a 500 error, and the result's JSON is:

```
{
    "error": {
        "code": "generalException",
        "message": "General exception while processing",
        "innerError": {
            "date": "2023-08-23T13:00:53",
            "request-id": "c36588f3-f4b3-40eb-9e88-cc4140182892",
            "client-request-id": "0a119314-f895-a614-71f6-580bcc9e16cb"
        }
    }
}
```

If _B_ contains only links of types "Stock images" and "From a link", the update of _A_ succeeds.

I could reproduce the problem in various site collections and various pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01c52929-64b2-9659-bdd5-ae6154cfbc9f
* Version Independent ID: 8ee8c226-6ca3-c8ef-4d3c-553b89e18382
* Content: [Update webPart - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/webpart-update?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/webpart-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/webpart-update.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @sangle7
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sangle7** [comment]
Acked, let me take a look on it

**Comment by sangle7** [comment]
@lucmoco  Thank you for the detailed and valuable information! There's a bug related to the web part itself as well the the API. The fix is checked in and would take up to 4 weeks to deploy. In the mean time, you can use the 'update-page' method hich involves sending the complete content of a page as payload,  as an alternative.
