### ISSUE TITLE
Code snippet for SynchronizationSecretKeyStringValuePair  doesn't compile

### ISSUE THREAD

**Issue by murali1008** [microsoftgraph/microsoft-graph-docs-contrib#8456]
Hi,
We would like to save the JWT to application's provisioning service configuration. For accomplishing this we make a call to /synchronization/secrets endpoint using MS Graph SDK 5.23.0 and GraphServiceClient 2.13.3. The line 5 of C# snippet doesn't compile and  produces the following error 
“The type or namespace name 'SynchronizationSecretKeyStringValuePair' does not exist in the namespace 'Microsoft.Graph.ServicePrincipals.Item.Synchronization.Secrets' (are you missing an assembly reference?)”

Can you please let me know if this is known bug? If yes, when this will be fixed?

Thanks

Best Regards,
Krish

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec4abba4-77ce-eba4-d87f-589751e1aa46
* Version Independent ID: 08448972-b76d-6f9b-8a4d-282f235d73ba
* Content: [Add synchronization secrets - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/synchronization-serviceprincipal-put-synchronization?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/synchronization-serviceprincipal-put-synchronization.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/synchronization-serviceprincipal-put-synchronization.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @ArvindHarinder1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrueastman** [comment]
Metadata issue fixed https://github.com/microsoft/OpenAPI.NET.OData/issues/423
