### ISSUE TITLE
Permissions required for accessing shared items

### ISSUE THREAD

**Issue by xiaokangz88** [microsoftgraph/microsoft-graph-docs-contrib#8467]
[Enter feedback here]
Is application permission of **Files.Read** sufficient for an app to get shared items? I don't understand why Files.ReadWrite.All is required if my app only needs to read shared items.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49f0e42a-0fc2-905d-b105-0b3de895e351
* Version Independent ID: 340a3a14-6067-15bb-3be3-a789caa31a44
* Content: [Access shared items - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/shares-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/shares-get.md)
* Product: **files**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
