### ISSUE TITLE
There is a situation that status 429 does not contains any Retry-After header

### ISSUE THREAD

**Issue by landall** [microsoftgraph/microsoft-graph-docs-contrib#8469]
if a Onedrive for Business/Sharepoint is blocked for FraudThrottled, any related api will return 429 without any Retry-After http header.
If you visit the Sharepoint from Browser, it will jump to https://xxxx-my.sharepoint.com/_layouts/15/FraudThrottle.htm#2052
This tenant may be created by some invalid ways. (for example, a false university to get a free Office A1 plan with unlimited licenses)

method:GET /me/drive
Array
(
    [Transfer-Encoding] => Array
        (
            [0] => chunked
        )

    [Content-Type] => Array
        (
            [0] => application/json
        )

    [Strict-Transport-Security] => Array
        (
            [0] => max-age=31536000
        )

    [request-id] => Array
        (
            [0] => 286e4a12-c3cf-4275-87c1-3c4736c22308
        )

    [client-request-id] => Array
        (
            [0] => 286e4a12-c3cf-4275-87c1-3c4736c22308
        )

    [x-ms-ags-diagnostic] => Array
        (
            [0] => {"ServerInfo":{"DataCenter":"Korea Central","Slice":"E","Ring":"3","ScaleUnit":"003","RoleInstance":"SE1PEPF00000A3C"}}
        )

    [Date] => Array
        (
            [0] => Fri, 25 Aug 2023 16:42:48 GMT
        )

)

Response Body:
{"error":{"code":"BadRequest","message":"Unable to retrieve user's mysite URL.","innerError":{"date":"2023-08-25T16:50:02","request-id":"39d53fb0-4045-4712-8841-b7339685e7a6","client-request-id":"39d53fb0-4045-4712-8841-b7339685e7a6"}}}

This situation is not mentioned in the API Docs.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8df32e5f-8ccb-0c93-28d9-02392f9c7256
* Version Independent ID: 4aadd084-fb61-e89b-f63f-3b71622636b7
* Content: [Microsoft Graph throttling guidance - Microsoft Graph](https://learn.microsoft.com/en-us/graph/throttling?source=docs)
* Content Source: [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/throttling.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Hi @landall - Unfortunately, this forum is only for documentation-related issues but [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/274/microsoft-graph-files-api) is the best forum to answer this functionality question so I recommend that you raise this question there. You may be requested for a request ID for investigation. Closing this issue here.
