### ISSUE TITLE
Issue with service principal add password

### ISSUE THREAD

**Issue by nukala29** [microsoftgraph/microsoft-graph-docs-contrib#8471]
The Cutsomer used this endpoint on the Service principal(servicePrincipals/{id})  and he successfully added the secret and got the access token.
He complained that he didn't see in the UI manifest for the Service principal he expects to show how the application manifest shows this value.

The issue of not populating the secret value is by design, we used to have that feature previously(3 years) in the UI to add the secret to the Enterprise applications(service principal).
We removed that feature and made an update to the app registration so we recommend the user who does stuff with the app registration(applications) has to be done under the application object only.

Maybe a good idea to add the above note to the new customer to use the application object only to add a password

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17cf0c2e-27a3-b1cb-d309-b73a103d9d9e
* Version Independent ID: 711d36bb-8e59-79ef-8b0f-3fa21184da48
* Content: [application: addPassword - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-addpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/application-addpassword.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @nukala29 for raising this issue. We have this note in the response section of the article:

<img width="599" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/14026935/3cc02c78-83ed-4181-b7f6-94f14aa853f8">

and also in the [passwordCredential resource doc](https://learn.microsoft.com/en-us/graph/api/resources/passwordcredential?view=graph-rest-1.0).

<img width="544" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/14026935/58f1170f-6169-4efc-a0c4-54b0290d9971">

I hope this helps.
