### ISSUE TITLE
last sign-in date update on the users endpoint

### ISSUE THREAD

**Issue by nukala29** [microsoftgraph/microsoft-graph-docs-contrib#8472]
[Enter feedback here]
Adding this note to sign activity on this page will help a lot of customers 
Asd per the ebwlo doc
https://learn.microsoft.com/en-us/azure/active-directory/reports-monitoring/howto-manage-inactive-user-accounts#what-you-need-to-know
The last sign-in date and time shown on this tile may take up to 6 hours to update, which means the date and time may not be current. If you need to see the activity in near real-time, select the See all sign-ins link on the Sign-ins tile to view all sign-in activity for that user.

This confused a lot of customers to use the user endpoint to get the sign-in activity fells they get inaccurate results
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
Thank you for the feedback.
