### ISSUE TITLE
Additional Application permission required

### ISSUE THREAD

**Issue by ilLeoIT** [microsoftgraph/microsoft-graph-docs-contrib#8474]
[Enter feedback here]

Hi all,
I notice that to execute the request the application needs in addition to the "EntitlementManagement.ReadWrite.All" permission it also required the "Group.ReadWrite.All" application permission. Without this permission the app receive error HTTP 400 Bad Reuest with following message:

{
    "error": {
        "code": "CallerNotResourceOwner",
        "message": "The caller is not the resource owner.",
        "details": [],
        "innerError": {
            "date": "2023-08-26T08:13:38",
            "request-id": "2f4aa79a-8f72-4bd1-8526-xxxxxxxxxxxx",
            "client-request-id": "2f4aa79a-8f72-4bd1-8526-xxxxxxxxxxx"
        }
    }
}

May I suggest to add this note into the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cfcc5c6-4741-070d-9fa6-f6520ec8858f
* Version Independent ID: 0099c1ef-875d-0a7c-29f9-fcd420cb3aa0
* Content: [Create accessPackageResourceRequest - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-resourcerequests?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/entitlementmanagement-post-resourcerequests.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/entitlementmanagement-post-resourcerequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
Thanks for reporting, we will be adding this to the permissions section of the article in the documentation.
