### ISSUE TITLE
Page lacks example for assigning TokenLifetime policy to a ServicePrincipal

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs-contrib#8489]
Page only has example assigning TokenLifetime policy to an Application object.  It lacks example for assigning the policy to a ServicePrincipalObject

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eacd922d-78d7-b319-912b-5a583b846115
* Version Independent ID: d3b1e758-9c81-0f20-792f-df516bce4b9f
* Content: [Assign tokenLifetimePolicy - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/application-post-tokenlifetimepolicies?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-tokenlifetimepolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/application-post-tokenlifetimepolicies.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
My apologies @bachoang for dropping the ball on this issue. Thank you for highlighting this missing documentation. I've raised a PR to add the missing documentation.
