### ISSUE TITLE
complete toggle missing

### ISSUE THREAD

**Issue by phpremco** [microsoftgraph/microsoft-graph-docs-contrib#849]
There is a special function to set a task to completed, but you're unable to 'toggle' this back to incompleted with this or a different function. This is illogical, it took me a while to figure out i have to send the status notStarted with a patch to trigger the completedDateTime to empty itself ( this also takes many minutes to update itself within microsoft todo making it look like it never worked ). Please find a better way of dealing with this, or document this a little better please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2774991-b6c1-b22c-4d5d-dd97c17719b3
* Version Independent ID: bbf28b1d-d76f-6b78-1569-66e60c217ffd
* Content: [outlookTask: complete - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/outlooktask-complete?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/outlooktask-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlooktask-complete.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
As of August 2022, this API is deprecated: (https://learn.microsoft.com/en-us/graph/api/outlooktask-complete?view=graph-rest-beta&tabs=http)
