### ISSUE TITLE
Possible values for dataLocationCode

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#8494]
It would be useful to known what are possible values for dataLocationCode, what are the geographic region codes for where this site collection resides.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be046269-3155-dc77-b91c-d9b925367303
* Version Independent ID: a2b105bb-860b-c8ed-6b51-5e22e9caefca
* Content: [SiteCollection - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/sitecollection?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/sitecollection.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/sitecollection.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
