### ISSUE TITLE
What is the recommended strategy for ISVs handling cloud instances?

### ISSUE THREAD

**Issue by SonOfJesseAsSnekithan** [microsoftgraph/microsoft-graph-docs-contrib#850]
Thanks for the video and details. 
As per your video, following are required : Separate App ID for each instance of Cloud, End point for OAuth redirect URL, end-point for accessing Graph API 
In the above video, you showed defining different end points for each national cloud, how does it dynamically inject specific endpoints during run time from appsettings.json? If the documentation covers Microsoft recommended approach for doing this, that would be appreciated.

Just guessing the approach -- is it addressed by DevOps build process in deployment stage (or) Single binary includes different end points for each localization that refers to national cloud (global, US gov, Germany, China) endpoints based on the localization settings for Germany and China, do you handle US Government case separately? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2dbd263-9afd-aa90-cb50-bbadfc424cc2
* Version Independent ID: 63aaf699-609e-b4dd-bd02-9f891e09db8d
* Content: [National cloud deployments - Microsoft Graph](https://docs.microsoft.com/en-us/graph/deployments)
* Content Source: [concepts/deployments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/deployments.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
@SonOfJesseAsSnekithan, the topic https://learn.microsoft.com/en-us/graph/deployments now contains the information you previously requested.
