### ISSUE TITLE
Production availability

### ISSUE THREAD

**Issue by philippklautke** [microsoftgraph/microsoft-graph-docs-contrib#8503]
When will these Endpoints be available as non BETA Endpoints?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db1d76fb-ab96-0d74-ae88-b80a5dc23e0a
* Version Independent ID: 05ab9e81-b409-de3f-ca65-316d6f008c6c
* Content: [Create assignmentScheduleRequest - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/privilegedaccessgroup-post-assignmentschedulerequests?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/beta/api/privilegedaccessgroup-post-assignmentschedulerequests.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/privilegedaccessgroup-post-assignmentschedulerequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @ilyalushnikov
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @philippklautke for your inquiry. Yes, they will, soon, but I can't provide an ETA 🙂. Please look out for the changes in the [changelog ](https://developer.microsoft.com/en-us/graph/changelog/?search=) or in the [Microsoft Entra](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/bg-p/Identity) blog.
