### ISSUE TITLE
Add a Graph Connector code sample reference in this page

### ISSUE THREAD

**Issue by MuyangAmigo** [microsoftgraph/microsoft-graph-docs-contrib#8506]
Hey team!

I'm from Teams Toolkit team, where we build dev tools to support developers extending Teams platform. We have had a code sample available for Graph Connector + a Teams application + Simplified Admin experience: https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/graph-connector-bot

Wondering if we can include the reference to this code sample in the documentation here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e78732e2-a7ba-cb9d-015f-64a697286f92
* Version Independent ID: e78732e2-a7ba-cb9d-015f-64a697286f92
* Content: [Enable the Simplified Admin Experience for your Microsoft Graph connector in the Teams Admin Center - Microsoft Graph](https://learn.microsoft.com/en-us/graph/connecting-external-content-deploy-teams)
* Content Source: [concepts/connecting-external-content-deploy-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/connecting-external-content-deploy-teams.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @monaray
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Hi, please reach out to @monaray97  who seems to be the author of the doc to check if this information can get added to the doc. Thanks.
