### ISSUE TITLE
How to download a malicious file by Graph API?

### ISSUE THREAD

**Issue by landall** [microsoftgraph/microsoft-graph-docs-contrib#8510]
The SPO is set by PowerShell Cmdlet. 
DisallowInfectedFileDownload is False.

But I cannot download the file content by Graph API.
Is there a way to download it forcely? Just like [Get-SPOMalwareFileContent](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/get-spomalwarefilecontent) cmdlet of Powershell?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01fa814a-c3b6-d48a-b724-a63e948bbffd
* Version Independent ID: f417cf48-5780-ebf4-1470-1bf0855d62c1
* Content: [Download a file - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/driveitem-get-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
