### ISSUE TITLE
Data field mismatch for message struct 

### ISSUE THREAD

**Issue by gpit2286** [microsoftgraph/microsoft-graph-docs-contrib#852]
categories is listed on this page as a member of message but not on the metadata document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dd382e4-95b6-3ccf-6a15-02d0cc7ed841
* Version Independent ID: 276cebbe-10bc-100e-f9b1-51b2ba30c64b
* Content: [message resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/message.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
PR https://github.com/microsoftgraph/microsoft-graph-docs-contrib/pull/9254 fixes this issue.

**Comment by Danielabom** [comment]
Contacted the person who owns the documentation. Awaiting info.

**Comment by lramosvea** [comment]
Closing as this seems to be fixed now. Thanks.
