### ISSUE TITLE
Scopes

### ISSUE THREAD

**Issue by AndrewR66** [microsoftgraph/microsoft-graph-docs-contrib#8521]
I can't find documentation for scopes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aef52833-8b23-b9cd-4337-73eec3c34f4d
* Version Independent ID: 9b012e4f-93b3-bda8-0e35-1c9c6326295c
* Content: [Create a Microsoft Graph client - Microsoft Graph](https://learn.microsoft.com/en-us/graph/sdks/create-client?tabs=csharp)
* Content Source: [concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/sdks/create-client.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by DMoenks** [comment]
Scopes (or [permissions](https://learn.microsoft.com/en-us/graph/permissions-overview) in general) are described earlier on in the same documentation, as part of the initial sections of the _Develop_ chapter. As the documentation is structured into  _Explore_, _Learn_ and _Develop_ chapters, each of those quite possibly build upon knowledge from earlier chapters and sections without necessarily cross-referencing those each time a specific concept is applied.

**Comment by AndrewR66** [comment]
Thanks, you're right, I found it.

man. 4. sep. 2023, 17:17 skrev Dominik Mönks ***@***.***>:
