### ISSUE TITLE
Add max filesize supported to this page

### ISSUE THREAD

**Issue by jenslundgaard** [microsoftgraph/microsoft-graph-docs-contrib#8522]
Hi, could you please add to this page what the maximum filesize is for the MSoffice-to-PDF conversion.
It seems that sometimes it works up to around 150MB but other times it only seems to work for filesizes up to 100MB.

Also, if it is in this range then could you please consider increasing it as many real-world powerpoints are much bigger than this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59cfb473-0783-09cb-3c88-96f884d76e06
* Version Independent ID: 9992b18b-299d-6863-c06f-8bacb7ff2962
* Content: [Convert to other formats - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get-content-format.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/driveitem-get-content-format.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
