### ISSUE TITLE
Error in the documentation for group member list

### ISSUE THREAD

**Issue by romain-leonard** [microsoftgraph/microsoft-graph-docs-contrib#8524]
Hi,

The Important message on the top of the page is wrong.
> This API has a known issue where service principals are not listed as group members in v1.0. Use this API on the beta endpoint instead or the /groups/{id}?members API.

The right endpoint for beta is not `/groups/{id}?members`, but `/groups/{id}/members`

Still, I do not understand why the v1.0 has not been fixed.

Regards,
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51a32b12-951e-ff94-a7b8-c014968ce6cf
* Version Independent ID: fea401c3-ce70-d7ce-4bae-c112308a711a
* Content: [List group members - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/group-list-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @romain-leonard for catching this error. I've raised a PR to fix the reference.
Unfortunately, I'm unable to provide an ETA for when the issue will be fixed in v1.0. We're trying to avoid any breaking changes because of existing dependencies.
