### ISSUE TITLE
Invalid example for the owners property?

### ISSUE THREAD

**Issue by apcsb** [microsoftgraph/microsoft-graph-docs-contrib#8526]
The example for the *owners* property usage of filter
> /groups?$filter=startsWith(displayName,'Role')&$select=id,displayName&$expand=owners($select=id,userPrincipalName,displayName)

does not actually filter by owners - it filters by DisplayName of the group itself.

In fact, attempting to filter by owners results in error
> Property 'owners' does not exist as a declared property or extension property.

Either there is a bug in the API or the example needs to be updated to show how to filter by owners.

Here's an example that works:
> https://graph.microsoft.com/beta/groups?$expand=owners($filter=id eq '{GUID}')

But I can't figure out an example for $count in this scenario, My attempts with $it/$this result in 
> Parsing OData Select and Expand failed: The next token in a CountSegmentNode must be a collection.

I also can't figure out why this doesn't work, it should accoring to ODATA spec
> https://graph.microsoft.com/beta/groups?$expand=owners($select=id,displayName,odata.Type)&$filter=owners/any(o:o/id eq '{GUID}')
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47d54936-0289-3e4c-0a34-1d01b4919db2
* Version Independent ID: 953200ad-c9af-a80d-7bc2-836a25ddc273
* Content: [group resource type - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/resources/group.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @apcsb for raising this issue. Support for `$filter` for the **owners** relationship is with `$count` as documented. What you're referencing is the example that shows `$expand` owners with nested `$select`. I hope this clarifies the description.

**Comment by apcsb** [comment]
Hi @FaithOmbongi How should I interpret "supports $count as documented" if the example in the doc does not include $count?
> $filter/(/$count eq0) 
does not work throwing an error I mentioned. Can you provide a working example?

**Comment by FaithOmbongi** [comment]
Hi @apcsb - Support for $count is as highlighted.

<img width="473" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/14026935/566ccca5-6da4-4fe3-9efb-3f8127675dcc">

Unfortunately, the page is limited, and we can't add all possible examples. But you'll find syntax information for these $count patterns in the [$filter article: syntax for using the $filter OData query parameter](https://learn.microsoft.com/en-us/graph/filter-query-parameter?tabs=http#for-a-collection-of-primitive-types). For the groups API and for the **owners** relationship, some examples would be (select to try it in Graph Explorer):

[GET https://graph.microsoft.com/v1.0/groups?$filter=owners/$count eq 0&$count=true
ConsistencyLevel: eventual](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%3F%24filter%3Downers%2F%24count%2Beq%2B0%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)

[GET https://graph.microsoft.com/v1.0/groups?$filter=owners/$count ne 1&$count=true
ConsistencyLevel: eventual](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%3F%24filter%3Downers%2F%24count%2Bne%2B1%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)

Remember to add both `$count=true` query parameter and the **ConsistencyLevel** header.
