### ISSUE TITLE
How to get "/me/drive/sharedWithMe" in C#

### ISSUE THREAD

**Issue by MaartenGhijsens** [microsoftgraph/microsoft-graph-docs-contrib#8530]
What drive ID should I provide in "_client.Drives["{drive-id}"].SharedWithMe" using the .NET SDK (C#) to get same result as "/me/drive/sharedWithMe"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9ff916-e1b7-c60b-bf05-2c5976617ad7
* Version Independent ID: 092666d9-dfd3-44f9-9571-bc67f45c4842
* Content: [drive: sharedWithMe - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/drive-sharedwithme?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/drive-sharedwithme.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/drive-sharedwithme.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
