### ISSUE TITLE
Update deviceRegistrationPolicy document is not consistent with API behavior

### ISSUE THREAD

**Issue by ArseniBorisovs-Agio** [microsoftgraph/microsoft-graph-docs-contrib#8532]
The "Request Body" section states:

> In the request body, supply only the values for properties that should be updated. Existing properties that are not included in the request body will maintain their previous values or be recalculated based on changes to other property values.

However, if I try to send a PUT request without the `userDeviceQuota` field (just an example, this happens with all the other attributes I've tried as well)

I get a 400 status with the following error message:

`{"error":{"code":"invalid_request","message":"Tenant registration policy is missing a value for quota","innerError":{"date":"removed_for_privacy","request-id":"removed_for_privacy","client-request-id":"removed_for_privacy"}}}`

The only way I have had this endpoint successfully apply is if _all_ attributes are included in the call

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 697546b9-deee-2f52-5c41-26fd268d6805
* Version Independent ID: 20880732-40b0-cb28-645e-d5ae97fada21
* Content: [Update deviceRegistrationPolicy - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/deviceregistrationpolicy-update.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @myra-ramdenbourg
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ArseniBorisovs-Agio for raising this issue. Yes, you're right. The API uses the PUT method which requires all updatable properties to be included in the request body, as also shown in the example provided. I've raised a PR to update the request body description.

On another note, are you aware of upcoming breaking changes to the deviceRegistrationPolicy APIs? Please refer to this blog for more information: [Important: Update to deviceRegistrationPolicy Resource Type for MS Graph Beta API Version](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/important-update-to-deviceregistrationpolicy-resource-type-for/ba-p/3912000).
