### ISSUE TITLE
 lifecycleNotificationUrl is also validated

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/microsoft-graph-docs-contrib#8534]
Doc needs to be updated to also mention that the "lifecycleNotificationUrl" is also validated
https://learn.microsoft.com/en-us/graph/change-notifications-delivery-webhooks?tabs=http#notificationurl-validation

Doc currently states only the notificationUrl is validated

The implementation to return the validationToken needs to occur on both notificationUrl and lifecycleNotificationUrl
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Microsoft Graph overview - Microsoft Graph](https://learn.microsoft.com/en-us/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @willfiddes for this valid suggestion. I've raised a PR to update the documentation.
