### ISSUE TITLE
Graph API permissions

### ISSUE THREAD

**Issue by GermanEZI** [microsoftgraph/microsoft-graph-docs-contrib#8536]
I'm writing an Console application.

It needs to upload a file to one of our SharePoint locations.

What is the minimal permission that will be needed in order to upload a file?

From what I can tell, I won't need more than Files.ReadWrite.All

I would experiment myself, but I have limited access to Azure Portal and I have to request that permissions be applied.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 986fb32a-c9aa-fbad-12b2-30eef3d9f7b1
* Version Independent ID: 722992d5-18ee-5499-b2a6-440ac705d40a
* Content: [Create a SharePoint List - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/list-create?view=graph-rest-1.0&source=recommendations&tabs=http)
* Content Source: [api-reference/v1.0/api/list-create.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/list-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
