### ISSUE TITLE
Using solution name in withDisambiguation

### ISSUE THREAD

**Issue by Rafaelki** [microsoftgraph/microsoft-graph-docs-contrib#8538]
Hi
In the "Usage in SharePoint Framework web parts with React"
1. The "React SharePoint Web Part Sample" link is broken, it goes to File not found
2. In the code, the comment over withDisambiguation says "Use the solution name to ensure unique tag names". But a solution can have several web parts, each one, by default, in a different bundle. Should we put the solution name or the web part name / bundle name?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f78e36fd-f57f-df4a-bb00-c9651376c163
* Version Independent ID: f78e36fd-f57f-df4a-bb00-c9651376c163
* Content: [Microsoft Graph Toolkit component disambiguation - Microsoft Graph](https://learn.microsoft.com/en-gb/graph/toolkit/customize-components/disambiguation)
* Content Source: [concepts/toolkit/customize-components/disambiguation.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/toolkit/customize-components/disambiguation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @gavinbarron
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by gavinbarron** [comment]
Thanks for raising this @Rafaelki 

We relocated our samples recently and clearly missed updating these docs, my apologies for that.
As to your question on the naming, I recommend the solution name as these should be unique in a given tenant, disambiguating down to the web part level should not be necessary.
