### ISSUE TITLE
Was expecting information for the GraphServiceClient

### ISSUE THREAD

**Issue by DrGriff** [microsoftgraph/microsoft-graph-docs-contrib#8539]
Be nice if there were some demos/code samples for when using the Microsoft.Graph.GraphServiceClient.  The http call from Postman is fine, but most of Microsoft's documentation suggests using this GraphServiceClient.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7e1ac6d-b2ee-c495-3194-f2895e26945e
* Version Independent ID: 73f817df-a829-e265-c932-7ae8b3f3e918
* Content: [Paging Microsoft Graph data in your app  - Microsoft Graph](https://learn.microsoft.com/en-us/graph/paging)
* Content Source: [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @DrGriff for your suggestion. I've raised a PR to request for the code samples to be autogenerated for the two GET examples in the article.

**Comment by FaithOmbongi** [comment]
Code snippets are now available in the paging article; Closing this issue
