### ISSUE TITLE
Not clear what licenses are required to use the MS Graph security API

### ISSUE THREAD

**Issue by mauromalara** [microsoftgraph/microsoft-graph-docs-contrib#8548]
I don’t see what licenses are required to use this API.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b188e759-5fbf-263b-2c02-dfe84ff76570
* Version Independent ID: 126a6c11-daba-6a78-2232-2e1a470816b3
* Content: [Use the Microsoft Graph security API - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/security-api-overview.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by DMoenks** [comment]
As far as I know, using the API isn't subject to licensing per se, but the products accessible by means of this API, such as Defender or Purview, need to be licensed for content to be available
