### ISSUE TITLE
Stuck at step5

### ISSUE THREAD

**Issue by enad** [microsoftgraph/microsoft-graph-docs-contrib#8552]
Unfortunately, I can't get past step 5. I can't get New Access Token either from Web 
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/978102/7b1ed697-35b7-46b9-800f-21a67536027e)
And from the desktop app which shows just a blank white screen after hitting  the get new access token button. I wish you added a troubleshooting note to the article. 
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://learn.microsoft.com/en-us/graph/use-postman)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
You're missing a tenant ID and client ID in that URL. Re-verify that you've done the steps in **Step 4: Configure authentication**.

**Comment by enad** [comment]
seems to be a transient issue. Tried this again and it worked. Note:  no changes done.
