### ISSUE TITLE
/users/{id}/joinedTeams request endpoint for admin users

### ISSUE THREAD

**Issue by TiagoBrenck** [microsoftgraph/microsoft-graph-docs-contrib#857]
Issue:
The docs says that: 

_With user delegated permissions this operation only works for the 'me' user. With application permissions, it works for all users by specifying the specific user id. ('me' alias is not supported with application permissions)_

However if I am signed-in with an admin account (and using delegated permissions), I am able to use the `/users/{id}/joinedTeams` passing a user id as param.

The issue could either be: 

- the docs is missing a statement saying that admin accounts can also use the `/users/{id}/joinedTeams` endpoint, or 
- there is a bug on graph api allowing admins to use the `/users/{id}/joinedTeams` endpoint with delegated permissions.

Article:
https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http

**Comment by Prasad-MSFT** [comment]
Hi @jessiechan27 - Could you please help here?

**Comment by Prasad-MSFT** [comment]
Hi @jessiechan27 - Could you please help here?

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Thanks.
