### ISSUE TITLE
Teams attendanceInterval joinDateTime/leaveDateTime are sometimes null

### ISSUE THREAD

**Issue by ngiessel** [microsoftgraph/microsoft-graph-docs-contrib#8572]
Sometimes, either field can be null.
This hasn't happened to me during testing, only now that I've had the first few hundred attendees with several intervals each imported into my app.

Are there known circumstances that cause this, that could be added to the docs? Can we expect this to be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53bb12de-56da-a75c-0f03-ab9c2849ca50
* Version Independent ID: 669ad2e8-3828-d359-d02a-25427587427e
* Content: [attendanceInterval resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/attendanceinterval.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/attendanceinterval.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @awang119
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yuyaolian-msft** [comment]
Hi @ngiessel could you please share an example request and response body, as well as the full response header? Thanks!
