### ISSUE TITLE
TypeScript batch request examples show invalid use of fetch

### ISSUE THREAD

**Issue by halljus** [microsoftgraph/microsoft-graph-docs-contrib#8576]
The TypeScript examples for creating batch requests with the SDK show creating a new `Request` with a path-relative URL to the Graph API endpoint you want. But a Node `Request` does not accept path-relative URLs (throws with an "Invalid URL" error). The example code even mentions `Request` coming from a fetch polyfill like node-fetch, but node-fetch states right in their documentation that [URLs must be absolute](https://github.com/node-fetch/node-fetch#fetchurl-options). If you attempt to provide an absolute URL (using `https://graph.microsoft.com/v1.0` as the base), the Graph API responds with a 400 Bad Request and rejects with: `GraphError: Invalid batch payload format.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0c6b539-d4f6-168f-2574-2e54c7cbcb56
* Version Independent ID: 0d1e3dfd-f3f3-2acf-6b31-d2c22d318fad
* Content: [Use the Microsoft Graph SDKs to batch requests - Microsoft Graph](https://learn.microsoft.com/en-us/graph/sdks/batch-requests?tabs=csharp)
* Content Source: [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/sdks/batch-requests.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@halljus the snippet in that topic comes from a working code sample here: https://github.com/microsoftgraph/msgraph-snippets-typescript/blob/main/src/snippets/batchRequests.ts

The `Request` objects used to build the batch aren't actually executed, they're serialized into the payload of a request sent to `https://graph.microsoft.com/v1.0/batch`.

**Comment by halljus** [comment]
> The `Request` objects used to build the batch aren't actually executed, they're serialized into the payload of a request sent to `https://graph.microsoft.com/v1.0/batch`.

@jasonjoh That's not been my experience, at least when used in a loader or action of a [Remix](https://remix.run/) app (which runs on the server, not in the browser). If I use a relative URL like in the example, it errors with `Error: Invalid URL`, which leads me to believe it is being evaluated.

Regardless, if the docs are accurate, I suppose this discussion belongs elsewhere?

**Comment by jasonjoh** [comment]
You should report your error and how you're hitting it in the JavaScript SDK repo here: https://github.com/microsoftgraph/msgraph-sdk-javascript.

**Comment by halljus** [comment]
Will do, thanks.
