### ISSUE TITLE
Preferred language ISO 639-1 example

### ISSUE THREAD

**Issue by Johaney-s** [microsoftgraph/microsoft-graph-docs-contrib#8577]
The preferred language hint (ISO 639-1, for example en-US) in the User object section is confusing as ISO 639-1 code would be 'en'. I believe it is the same case as reported here: https://github.com/MicrosoftDocs/azure-docs/issues/69512

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Johaney-s for highlighting this error. I've raised a PR to align the description for **preferredLanguage** in the users API with the IT admin description.
