### ISSUE TITLE
B2C Doesn't support filter "Contains"

### ISSUE THREAD

**Issue by MichaHoefer** [microsoftgraph/microsoft-graph-docs-contrib#8578]
Using the Filter "Contains" as described in the documentation leads to the error:

Message: Filter operator 'Contains' is not supported.

https://learn.microsoft.com/en-us/graph/filter-query-parameter?tabs=http

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca630f7c-e88d-3b10-4ed1-3574dd415ad2
* Version Independent ID: ca630f7c-e88d-3b10-4ed1-3574dd415ad2
* Content: [Use the filter query parameter to filter a collection of objects - Microsoft Graph](https://learn.microsoft.com/en-us/graph/filter-query-parameter?tabs=http)
* Content Source: [concepts/filter-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/filter-query-parameter.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @MichaHoefer for raising this issue. Unfortunately, there's limited support for the `contains` operator today across Microsoft Graph. In fact, for Microsoft Graph APIs for Microsoft Entra features, only a few of the Identity Governance APIs support the operator. There's this note in the linked article:

<img width="521" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/14026935/4af80ca8-eb3a-44f0-bd29-5a60a8fdf435">

To request that one of the directory objects support this operator, you can file the request through this form https://aka.ms/MsGraphAADSurveyDocs. For other APIs, you can submit a feature request through the [Microsoft Graph feedback forum](https://aka.ms/graphfeedback).
