### ISSUE TITLE
Graph Create a new item in a list with Person field

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/microsoft-graph-docs-contrib#858]
This [Doc](https://docs.microsoft.com/en-us/graph/api/listitem-create?view=graph-rest-1.0&tabs=http)
Explains how to add an item with text and numeric fields.

Issue: there is no example of how to add a Person field 
I tried:
{ "fields": {"Title":"Test the Kicker 3",
			 "ProjectNumber":"Test.003",
			"Practice":"Test the Kicker Practice",
			"Manager": { "user": {"@odata.type": "microsoft.graph.identity",
				                  "id": "d661d903-3fd0-496e-a356-cb96ecd10e60"}
				        }
			}
}
But I get error:
A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.

Article:https://docs.microsoft.com/en-us/graph/api/listitem-create?view=graph-rest-1.0&tabs=http

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
