### ISSUE TITLE
Incorrect documentation for PATCH with Stream type

### ISSUE THREAD

**Issue by ranok** [microsoftgraph/microsoft-graph-docs-contrib#8580]
The example for the logo does not work (trying it for the customCSS), and the advice of setting the Accept-Language header does not fix the error:
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/66790/d683b9b3-7d3b-41f0-a009-29cbdb41eb4e)

This is also [unresolved here](https://learn.microsoft.com/en-us/answers/questions/407715/update-organizationalbrandingproperties)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9498062-4520-3212-3d50-647abfdeb19c
* Version Independent ID: 20f09b39-a723-a509-82a0-5a10fe106a68
* Content: [Update organizationalBranding - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/organizationalbranding-update.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @quievey
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @quievey - Can you advise here? Thanks.

**Comment by quievey** [comment]
@ranok PATCH only works for updating String data types such as signInPageText or usernameHintText. Stream data types like backgroundLogo are updated using the PUT method. Please see https://learn.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-1.0&tabs=http#http-request

cc @FaithOmbongi

**Comment by ranok** [comment]
Thanks @quievey, I will try that. The documentation in this page (Example 2) uses a PATCH for an image (Stream type) and should this be fixed.

**Comment by ranok** [comment]
Submitted a fix in #8588

**Comment by FaithOmbongi** [comment]
Thank you @ranok. I've pushed a few commits and approved your PR for merging.

**Comment by ranok** [comment]
Thanks @FaithOmbongi , is there anything else I need to do for the PR (add labels for review, etc.)?

**Comment by FaithOmbongi** [comment]
Hi @ranok - No need to. I've already added the appropriate labels. Thanks.

**Comment by ranok** [comment]
I have replied, and it looks good to merge once you've completed your review.

**Comment by quievey** [comment]
Thank you @FaithOmbongi and @ranok

**Comment by FaithOmbongi** [comment]
The documentation is now up to date
Thank you @ranok
