### ISSUE TITLE
Incorrect redirection of activity feed hyper link

### ISSUE THREAD

**Issue by Meghana-MSFT** [microsoftgraph/microsoft-graph-docs-contrib#8583]
[Activity feed](https://learn.microsoft.com/en-us/graph/teams-concept-overview#:~:text=your%20web%20service.-,Activity%20feed,-Engage%20users%20via) hyper link redirects to Conversation basics which is an incorrect redirection. It should redirect to [Send activity feed notifications to users in Microsoft Teams - Microsoft Graph | Microsoft Learn](https://learn.microsoft.com/en-us/graph/teams-send-activityfeednotifications?tabs=http).  

Please change [Activity feed](https://learn.microsoft.com/en-us/graph/teams-concept-overview#:~:text=your%20web%20service.-,Activity%20feed,-Engage%20users%20via) hyper link to [Send activity feed notifications to users in Microsoft Teams - Microsoft Graph | Microsoft Learn](https://learn.microsoft.com/en-us/graph/teams-send-activityfeednotifications?tabs=http).  

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/81138249/ab7a408e-af8b-4a6d-b08a-44ba00ae700b)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba4f5720-3eb2-fe1d-472e-497d1449f97b
* Version Independent ID: eaa22434-4691-77e2-8905-bf6d7e9e0bef
* Content: [Overview for using Microsoft Teams, Shifts, and Viva Learning to foster teamwork - Microsoft Graph](https://learn.microsoft.com/en-us/graph/teams-concept-overview)
* Content Source: [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/teams-concept-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update the above hyperlink.

**Comment by v-sdhakshina** [comment]
Updated the document through PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/22808.

**Comment by Meghana-MSFT** [comment]
Closing this as the doc has been updated.
