### ISSUE TITLE
Resource does not exist or one of its queried reference-property objects are not present

### ISSUE THREAD

**Issue by chopard-vde** [microsoftgraph/microsoft-graph-docs-contrib#8586]
Hello,

https://graph.microsoft.com/beta/applications/ (or 1.0) does not return the full list of applications.
There are a few issues already talking about that and the closest solution that I found is to use filter in the query like applications?$filter=appId eq '{application-id}'.
The problem is, filters work well when you know which app you're looking for, but how can you make it work to retrieve a complete list of current applications ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 919bb3aa-ba23-8410-caa8-2ce2381f4c32
* Version Independent ID: 6f8a5769-f02e-ad63-820c-d2afdf93fb93
* Content: [Get application - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/application-get.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @chopard-vde for raising this issue.

The API might not return all applications on the first page (the default page size when you don't use `$top` is 100 applications per page), but it should include an @odata.nextLink with a link to the next page of data. And the maximum you can request for per page with `$top` is 999 records. It definitely needs further investigation if there's contrary behavior.

> There are a few issues already talking about that

If you don't mind, can you share the links to allow me to do a bit more research on this?

**Comment by chopard-vde** [comment]
Hello,

Thank you for your response, you're right I haven't noticed the top parameter, it's all good for me thank you very much!

**Comment by FaithOmbongi** [comment]
Thanks for confirming @chopard-vde. I'll proceed to close this issue.
