### ISSUE TITLE
Activity feed-Notify a user about an event using custom topic.

### ISSUE THREAD

**Issue by v-nikhilsoma** [microsoftgraph/microsoft-graph-docs-contrib#8594]
In example 2, sending an activity feed notification with a custom topic doesn't work and throws a conflict error.
The specified request payload always leads to an AAD App ID conflict error.
Fix for this: Please update the document to use the "teamsAppId" parameter value in the request payload.
Note: teamsAppId is an appCatalogId of a [teamsApp](https://learn.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0)
{
    "topic": {
        "source": "text",
        "value": "Deployment Approvals Channel",
        "webUrl": ""
    },
    "activityType": "deploymentApprovalRequired",
    "previewText": {
        "content": "New deployment requires your approval"
    },
   "**teamsAppId**": "",
    "templateParameters": [
        {
            "name": "deploymentId",
            "value": "6788662"
        }
    ]
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9948c753-b761-228d-4915-9c26b47dd6a3
* Version Independent ID: 5b4f132c-3409-885d-9a1a-848bcd7c3c7c
* Content: [userTeamwork: sendActivityNotification - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/userteamwork-sendactivitynotification.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @eddie-lee-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by eddie-lee-msft** [comment]
Ack. We will update the docs.

**Comment by Meghana-MSFT** [comment]
A workitem has been created for this by engineering team.

**Comment by Meghana-MSFT** [comment]
Document has been updated hence closing the issue here.
