### ISSUE TITLE
'Microsoft Entra admin enter' link is incorrect

### ISSUE THREAD

**Issue by seanke** [microsoftgraph/microsoft-graph-docs-contrib#8596]
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/34672648/d952b2b6-e3f1-4433-9e94-1dbf9ea73a39)

The Microsoft Entra admin enter link goes to the Azure Portal and not the Entra admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf9ff3a-a9db-3996-731a-0fdc3fcd103a
* Version Independent ID: 034a7f02-2a99-ffbc-e818-653bb8d72ba5
* Content: [Register your app with the Azure AD v2.0 endpoint - Microsoft Graph](https://learn.microsoft.com/en-us/graph/auth-register-app-v2)
* Content Source: [concepts/auth-register-app-v2.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/auth-register-app-v2.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @seanke for catching this oversight. I've raised a PR to fix the link.
