### ISSUE TITLE
mgc me get- not exist

### ISSUE THREAD

**Issue by hilays** [microsoftgraph/microsoft-graph-docs-contrib#8597]
"me get" not working 
I didn't find any other way to get this information

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8af119-3334-c38f-668f-3af29c640cb3
* Version Independent ID: 8e8af119-3334-c38f-668f-3af29c640cb3
* Content: [Get started with the Microsoft Graph command-line interface (CLI) - Microsoft Graph](https://learn.microsoft.com/en-us/graph/cli/get-started)
* Content Source: [concepts/cli/get-started.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/cli/get-started.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks for reporting this. The CLI team removed the `me` command (https://github.com/microsoftgraph/msgraph-cli/issues/278) after this topic was written. I've updated the topic. The changes should be published later today.
