### ISSUE TITLE
GET rows/{index} Parameter does not work.

### ISSUE THREAD

**Issue by danielszabo** [microsoftgraph/microsoft-graph-docs-contrib#8599]
Sending a Get request to url 

  `".../me/drive/items/{id}/workbook/tables/{id|name}/rows/{index}"` 

to retrieve a single row from an Excel table doesn't work.   However, sending a Get request to 

  `".../me/drive/items/{id}/workbook/tables/{id|name}/rows/itemAt(index={index})"`

does indeed work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff7abfd7-29c8-0a8a-1063-b093750ba3f7
* Version Independent ID: d3a4dc11-a453-6606-b621-f45dd107284c
* Content: [Get TableRow - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/tablerow-get.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MartinM85** [comment]
Any update on this? @Lauragra @jasonjoh 
Is it a bug (for months) or some feature?
