### ISSUE TITLE
Activity feed notifications in the new Teams client fail for apps in the company portal

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/microsoft-graph-docs-contrib#8600]
We are using the Graph API to send Teams activity feeds to a user. We use the Teams deep link feature to redirect users to our application. All Teams versions (Browser, Client, Mobile) work without issues except the “New Teams client.”

The new client starts a redirect but fails with the error message that the app does not exist.

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/18241305/dadef8e1-3b5a-4291-a69a-76ba49a9ba14)

After conducting additional troubleshooting, I can confirm that we've identified a bug, and I believe I've pinpointed its root cause.

1) **App in the Microsoft Store**: Everything is functioning as expected. You can continue to utilize deep links to the app as we've been doing. In the payload, simply include the webUrl that was previously used. For example, if the app ID configured in the Teams App Manifest is "55f70393-3d6b-447b-94cf-2cc74b7f360f," the webUrl should be:
"webUrl": "[https://teams.microsoft.com/l/entity/55f70393-3d6b-447b-94cf-2cc74b7f360f/yourtarget"](https://teams.microsoft.com/l/entity/55f70393-3d6b-447b-94cf-2cc74b7f360f/yourtarget%22)
2) **App in the Company Store**: Unfortunately, this is currently not functioning properly. If you have an app with the app manifest ID "55f70393-3d6b-447b-94cf-2cc74b7f360f," using the URL:
"webUrl": "[https://teams.microsoft.com/l/entity/55f70393-3d6b-447b-94cf-2cc74b7f360f/yourtarget"](https://teams.microsoft.com/l/entity/55f70393-3d6b-447b-94cf-2cc74b7f360f/yourtarget%22)
will result in an exception. It appears that the new client no longer considers the externalId property, as the old client did. To make it work, you'll need to use the teamsApp/id property in your deep link URL instead, like this:
"webUrl": "[https://teams.microsoft.com/l/entity/b969ff5a-2171-41ea-9364-0ba1920e3264/yourtarget"](https://teams.microsoft.com/l/entity/b969ff5a-2171-41ea-9364-0ba1920e3264/yourtarget%22)

You can see the payload for an app installed on a user from the company store

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/18241305/2b55d49c-1c2b-4876-a6bd-05b162a5e3d1)

This behavior presents a challenge since it necessitates obtaining additional Graph permissions dynamically. As a Teams Developer, your usual knowledge is limited to the app ID provided in the manifest. Since the behavior is only happening in the new teams client, I believe this is an application bug.

Thank you for your feedback,
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aef120b3-03b9-cca1-9479-05720e6fd9ef
* Version Independent ID: 0cf32a73-043a-6b34-f71c-a8d3bd410bf7
* Content: [Send activity feed notifications to users in Microsoft Teams - Microsoft Graph](https://learn.microsoft.com/en-us/graph/teams-send-activityfeednotifications?tabs=http)
* Content Source: [concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/teams-send-activityfeednotifications.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nivedipa-MSFT** [comment]
@plamber - Thanks for reporting your issue. We will check this and update you soon.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by plamber** [comment]
Hello @ChetanSharma-msft,
I missed your notification. I just wanted to inform you that the product group team fixed this issue in the latest client release. Now, everything works as expected.

Thank you,
Patrick
