### ISSUE TITLE
Supported resource paths column is not uniform across all rows in the table.

### ISSUE THREAD

**Issue by Meghana-MSFT** [microsoftgraph/microsoft-graph-docs-contrib#8601]
Supported resource paths has bulleted points only for first 2 rows, rest all rows do not have the bullets.

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/81138249/6cdaeefe-0192-4aa7-8063-c035eae33b82)

Please remove/add bullet points across all rows for [Supported resource paths column](https://learn.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview#:~:text=Supported%20resource%20paths).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21ab1d41-2c00-5ae0-de45-0cae5e34467e
* Version Independent ID: 0869760b-8852-d5af-b219-2523ea9f5618
* Content: [Change notifications for Microsoft Teams resources - Microsoft Graph](https://learn.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview)
* Content Source: [concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/teams-change-notification-in-microsoft-teams-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @anandab-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update the above table.

**Comment by v-sdhakshina** [comment]
Updated the doc through pull request #22725

**Comment by Meghana-MSFT** [comment]
Doc has been updating, closing this issue.
