### ISSUE TITLE
Documentation for New-MgPolicyClaimMappingPolicy commandlet is wrong

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs-contrib#8602]
The feedback is not for this page.  It's for the following Microsoft Graph PowerShell documentation page.  I can't put feedback on the PowerShell page since there is no option, hence putting it here since the command wraps this REST call.

Problem page:
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/new-mgpolicyclaimmappingpolicy?view=graph-powershell-1.0

That page said one can provide the "Description" Property when using the command.  This is wrong.  We checked the internal source and the "Description" property is not part of the ClaimsMappingPolicy object.  Please remove the 'Description' field.

https://learn.microsoft.com/en-us/graph/api/resources/claimsmappingpolicy?view=graph-rest-beta#properties does not have description property
and attempts to add description property results in an error per https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2272

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bf61863-c6f6-0881-d88b-7cfc16238e9d
* Version Independent ID: 2aaf62db-0157-22ce-57bd-029e02ef8d59
* Content: [claimsMappingPolicy resource type - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/claimsmappingpolicy?view=graph-rest-beta#properties)
* Content Source: [api-reference/beta/resources/claimsmappingpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/resources/claimsmappingpolicy.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @paulgarn
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @bachoang for raising this issue. I see it relates to the Microsoft Graph PowerShell content, please file it [here in the SDK repo](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues) because the information on the PowerShell page is generated directly from the schema. I'll close the issue here.

cc @msewaweru for visibility.
