### ISSUE TITLE
eTag is provided in the example but not in the endpoint

### ISSUE THREAD

**Issue by kyle-begovich-glean** [microsoftgraph/microsoft-graph-docs-contrib#8604]
eTag is shown in example on https://learn.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http but when hitting the postman endpoint for this, it does not show up

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ccfedc34-43c1-d07a-249f-a105967a7730
* Version Independent ID: 3af5bde5-0179-4cd7-eacd-a903f3cb106b
* Content: [Get a driveItem resource - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/driveitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kyle-begovich-glean** [comment]
for extra clarity here, I'm using a non-delegated auth flow and me/drives/root is not available/possible.

calling with root gives me the following keys:
https://graph.microsoft.com/v1.0/drives/{{DRIVE_ID}}/items/root 
- "@odata.context"
- "createdDateTime"
- "id"
- "lastModifiedDateTime"
- "name"
- "webUrl"
- etc.

while calling the same endpoint but with an item id that is not root gives me more data, in particular the eTag which is what I'm looking for:
https://graph.microsoft.com/v1.0/drives/{{DRIVE_ID}}/items/{{ITEM_ID}}
- "@odata.context"
- "createdDateTime"
- **"eTag"**
- "id"
- "lastModifiedDateTime"
- "name"
- "webUrl"
- **"cTag"**
- etc.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
