### ISSUE TITLE
malformed JSON returned when querying $batch for user events with limited permissions

### ISSUE THREAD

**Issue by BloodyRain2k** [microsoftgraph/microsoft-graph-docs-contrib#8605]
I'm working on a SharePoint App that uses the Graph API to access some functions of Exchange.
In this case, checking a couple calendars for read access to the events in them.
And as I was randomly going through the network requests today, I noticed that I have been requesting *every* field for that simple access check. But since I didn't need any field to begin with, I added `$select=id` to the request, to cut down on the response size.

And this is where everything started breaking "randomly", and I've spent the last few hours trying to track down *what* is breaking.

The problem: if a `$batch` request for a shared calendar's events fails while also providing a `$select`, the returned JSON is malformed and breaks literally everything that tries to parse it.
This is what the response looks like, the matching `]` for the "value" property is nowhere to be found.
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/1014362/a85d29fe-d509-49eb-961c-752d80cb954e)

And each calendar that returns an error compounds that error. Meaning each error opens their "value" array, but none ever close any.
BUT this error happens only IF a `$select` is used, with the exception being `$select=*`. That does not cause the error either.

Here's the minimal setup I've used to recreate that error in the Graph Explorer, so the used libraries of the App and such could be ruled out as problem sources:

The requirement for causing the request to return 403 is simply *any* shared calendar, for which the user making the request does *not* have the Outlook permission `Read: Full Details`.

Request Body:
```
{
    "requests": [
        {
            "id": "1",
            "method": "GET",
            "url": "/users/{USER}/events?$top=1&$select=id",
            "headers": {}
        }
    ]
}
```
sent with `POST` to `https://graph.microsoft.com/v1.0/$batch`

The result is as shown above. Not even returning an error, it just shows a little red box with "400".
That's how much the response breaks parsers.
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/1014362/c19764a2-ad3c-463d-a252-5f54a76e3a3e)

And this only happens in this odd edge-case.
If the `$select` is absent, it just returns a normal error or *all* fields for the found events, as expected.
But is the `$select` is added to cut down on the returned fields, it suddenly forgets to add the closing `]` for "values".
Although my theory is that it was never meant to open an array for "values" in the first place.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e33b4529-dfaa-b051-a73e-fa7312e911f5
* Version Independent ID: 55111137-63ad-3408-9295-ef44128aed14
* Content: [Combine multiple requests in one HTTP call using JSON batching - Microsoft Graph](https://learn.microsoft.com/en-us/graph/json-batching)
* Content Source: [concepts/json-batching.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/json-batching.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
