### ISSUE TITLE
Duplicate entry in Methods table (Documentation error)

### ISSUE THREAD

**Issue by eliavlivneh** [microsoftgraph/microsoft-graph-docs-contrib#8606]
There is a duplicate row in the Methods table -
`[List appRoleAssignments granted to users, groups, and client service principals for a resource service principal](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-list-approleassignedto?view=graph-rest-1.0)` appears twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba2d096-43e1-c42d-a258-e31f76d2c5f2
* Version Independent ID: de382dbd-ef59-9a2e-dad0-aefd5f97555b
* Content: [appRoleAssignment resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/approleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/approleassignment.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @eliavlivneh for catching this documentation error. I've raised a PR to resolve it.
