### ISSUE TITLE
Replacement for deprecated fields AzureBlobContainer and AzureBlobToken

### ISSUE THREAD

**Issue by andrewbunk** [microsoftgraph/microsoft-graph-docs-contrib#8607]
Hello,

I am looking to automate some eDiscovery exports but I noticed that these fields: AzureBlobContainer and AzureBlobToken are both deprecated and there isn't any information about their replacements.

Please provide info for how you can programmatically automate eDiscovery exports to Azure Blobs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c1ea8e5-de45-a9da-5b79-f810e3deed5a
* Version Independent ID: 89ef0ca8-64cb-e75f-5fda-7b6deb55d031
* Content: [ediscoveryReviewSet: export - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/security-ediscoveryreviewset-export?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/security-ediscoveryreviewset-export.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/security-ediscoveryreviewset-export.md)
* Product: **ediscovery**
* Technology: **microsoft-graph**
* GitHub Login: @SeunginLyu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by SeunginLyu** [comment]
-  There are no replacements for AzureBlobContainer and AzureBlobToken  fields. You must download the exported content and we currently don't support exporting data into your own Azure blobs.
- The getDownloadUrl method is deprecated and will stop returning data on April 30th, 2023. Please use the new exportFileMetadata property returned by the [Get caseOperation](https://learn.microsoft.com/en-us/graph/api/security-caseoperation-get?view=graph-rest-beta) API instead.
