### ISSUE TITLE
Admin privilege required but not documented

### ISSUE THREAD

**Issue by mbukovich** [microsoftgraph/microsoft-graph-docs-contrib#8612]
This query requires admin privilege to complete successfully; however, this is not documented. Could we have some clarity on whether the admin requirement is intentional? If so, could the docs be updated to reflect accurate admin privilege needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7645532-b61a-7f2a-6c75-8b00be68496d
* Version Independent ID: c6dc90eb-5cb9-3655-6496-a63fdb27d5ea
* Content: [Create settings - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-post-settings?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/group-post-settings.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @mbukovich for raising this issue. Yes, you're right - the API requires the caller to have some Azure AD built-in roles. From the [Azure AD built-in roles reference](https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference?toc=%2Fgraph%2Ftoc.json), these are the authorized callers:

- Azure AD Joined Device Local Administrator - READ BASIC groupSetting, groupSettingTemplate
- Groups Administrator - Create/Manage groupSetting like naming and expiration policies
- Authentication Policy Administrator - Update the custom banned passwords list
- Directory Readers - READ BASIC groupSetting, groupSettingTemplate
- Directory Writers - WRITE groupSetting, groupSettingTemplate
- Global Reader - READ groupSetting, groupSettingTemplate
- User Administrator- UPDATE groupSetting, READ groupSetting/groupSettingTemplate

I'll raise a PR to update the documentation.
