### ISSUE TITLE
Application permissions are supported when listing delegatedAdminRelationships

### ISSUE THREAD

**Issue by damable-nuvolex** [microsoftgraph/microsoft-graph-docs-contrib#8613]
This endpoint's documentation states that application permissions are not supported:

Permission type | Permissions (from least to most privileged)
-- | --
Delegated (work or school account) | DelegatedAdminRelationship.Read.All, DelegatedAdminRelationship.ReadWrite.All
Delegated (personal Microsoft account) | Not supported.
Application | Not supported.

However, the permissions **DelegatedAdminRelationship.Read.All** and **DelegatedAdminRelationship.ReadWrite.All** do exist as application permissions, and can be assigned to an Azure Application:
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/89210540/8cb649b4-2f30-4908-a7f8-68ac8ac03788)

I was able to list delegatedAdminRelationships using an access token obtained with this application, therefore I think it must a documentation error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e60aef4d-9ddb-d16c-d765-964a126e3199
* Version Independent ID: 94544d60-7d1c-1d77-5371-fcf3a7437825
* Content: [List delegatedAdminRelationships - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/tenantrelationship-list-delegatedadminrelationships.md)
* Product: **customer-relationship-management**
* Technology: **microsoft-graph**
* GitHub Login: @koravvams
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by koravvams** [comment]
Hi @damable-nuvolex, Updated the documentation. Thanks.
