### ISSUE TITLE
for python ChatMessage and ItemBody seems to be missing the backend SDK in the Teams chat

### ISSUE THREAD

**Issue by vst212** [microsoftgraph/microsoft-graph-docs-contrib#8614]
for python ChatMessage and ItemBody seems to be missing the backend SDK
request_body = ChatMessage(
                body = ItemBody(
                    content = "Hello World",
                ),
                
            )

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f96d4903-13f7-c489-82b2-ce79d8b77540
* Version Independent ID: 7bf7c3d2-7693-7d24-e9c0-6f0c51cb1eaa
* Content: [Send chatMessage in a channel or a chat - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/chatmessage-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
@vst212 -Could you please elaborate your requirement and share the repro steps, so that we can try it from our end.
