### ISSUE TITLE
C# sample to look at the response

### ISSUE THREAD

**Issue by snitkjaer** [microsoftgraph/microsoft-graph-docs-contrib#8616]
Can you please add basic response parsing to the C# sample?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96729dcd-71c6-8693-3673-4a15d81f4ab8
* Version Independent ID: c720f364-97b7-ff12-092f-e0b04e822081
* Content: [syncDevice action - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/intune-devices-manageddevice-syncdevice?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-syncdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/intune-devices-manageddevice-syncdevice.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @jaiprakashmb
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrueastman** [comment]
Thanks for raising this @snitkjaer 

This specific API returns a 204 http response with no response body. The SDK will therefore not have a return object in such a scenario. Any chance you can confirm if there was something else you were looking to obtain from the response?
