### ISSUE TITLE
Documentation doesn't match C# in practise

### ISSUE THREAD

**Issue by samneefs** [microsoftgraph/microsoft-graph-docs-contrib#8624]
The examples (2 & 3) on the page [Update user](https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=csharp) mention C# code like this:
`var result = await graphClient.Users["{user-id}"].PatchAsync(requestBody);`

The above example can't be compiled.
However the following does work.
`var result = await graphClient.Users["{user-id}"].Request().UpdateAsync(requestBody);`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrueastman** [comment]
Thanks for raising this @samneefs 

Any chance you can confirm the version of the SDK you are using? The code samples show that they are for version 5.x.
`// Code snippets are only available for the latest version. Current version is 5.x`

**Comment by samneefs** [comment]
We use version 4.45 of the SDK.
Thanks for the clarification.

I didn't notice the version in the comment; I only saw the version of "Microsoft Graph REST API" on the top left.

**Comment by andrueastman** [comment]
Thanks for confirming. Closing this one for now.
