### ISSUE TITLE
Missing reference to permission EntitlementMgmt-SubjectAccess.ReadWrite

### ISSUE THREAD

**Issue by derekharkin** [microsoftgraph/microsoft-graph-docs-contrib#8633]
EntitlementMgmt-SubjectAccess.ReadWrite is not listed but does grant permisison to make these delagated calls
EntitlementMgmt-SubjectAccess.ReadWrite is only listed in one place in the docs - in the Graph Permissions Reference
It is not mentioned on any other page - https://learn.microsoft.com/en-gb/search/?terms=%22EntitlementMgmt-SubjectAccess.ReadWrite%22

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c739f11d-e6a7-1041-e988-dc746e017b64
* Version Independent ID: 226de03e-39a1-db87-f8f2-1fc553694b47
* Content: [Create accessPackageAssignmentRequest - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @derekharkin for your patience. The permission isn't yet available for any APIs. Once it's made available, we'll update the corresponding documentation that require it and add a changelog entry to mention the new permission. 

Closing this issue here.
