### ISSUE TITLE
Graph API for getting hostedcontent is not working on 21Vianet

### ISSUE THREAD

**Issue by qquiuc** [microsoftgraph/microsoft-graph-docs-contrib#8634]
Hi Team,

We are working with a migration product and we need to migrate the teams messages from one team to another,
[Get chatMessageHostedContent - Microsoft Graph v1.0 | Microsoft Learn](https://learn.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&tabs=http) it’s marked as supported for 21vianet but it won’t work from our tenant.
![WXWorkCapture_16958660055799](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/18695819/e737032d-5dd3-402b-a0af-3bd8da389eb7)
  “apacavepoint.onmicrosoft.com”

Attached with the fiddler record.
And another question “https://github.com/microsoftgraph/msgraph-metadata/blob/master/schemas/v1.0-Mooncake.csdl ” is this document shows that we have supported the 21Vianet?

Anyway, please help to confirm if we have already supported “Team Graph API” for 21vianet, and please help to resolve this API issue.

---
[21VianetHostedContent.zip](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/files/12744711/21VianetHostedContent.zip)

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f67cabe4-bade-9a07-90ec-15adaeab3de2
* Version Independent ID: dfbbddfe-f113-1ae1-9d21-77ab976ddc20
* Content: [Get chatMessageHostedContent - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/chatmessagehostedcontent-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abshar-teams** [comment]
Ack

**Comment by abshar-teams** [comment]
@qquiuc , its a documentation bug. I will work on fixing it. The  Get chatMessageHostedContent is supported in Gallatin, but it only works in Delegated context, not application context.
