### ISSUE TITLE
Unuseless code

### ISSUE THREAD

**Issue by Mirel-UO251579** [microsoftgraph/microsoft-graph-docs-contrib#8638]
[Enter feedback here]
For GraphServiceClient the object DeviceCodeCredential is not acceptable
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/74071636/aa01419e-e611-4acc-aafc-9ef4abd424da)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aef52833-8b23-b9cd-4337-73eec3c34f4d
* Version Independent ID: 9b012e4f-93b3-bda8-0e35-1c9c6326295c
* Content: [Create a Microsoft Graph client - Microsoft Graph](https://learn.microsoft.com/en-us/graph/sdks/create-client?tabs=csharp)
* Content Source: [concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/sdks/create-client.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@Mirel-UO251579 what version of Microsoft.Graph are you using? The snippet in this topic is for the latest major version, which is 5.x.
