### ISSUE TITLE
Example for updating Lookup Fields

### ISSUE THREAD

**Issue by aaronlabeau** [microsoftgraph/microsoft-graph-docs-contrib#864]
The current example doesn't seem to work with Lookup Fields that are linked to a different list.  What is the format to update a Lookup Field?  Usually the lookup makes multiple columns on the back end so there isn't clear documentation on which column they should use too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec4e338a-772e-0fc8-cff2-14d5a2f0d173
* Version Independent ID: 01362b8b-5f0b-4a40-d21f-0d27012c7311
* Content: [Update listItem - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-update?view=graph-rest-1.0&tabs=objc#feedback)
* Content Source: [api-reference/v1.0/api/listitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-update.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
