### ISSUE TITLE
Add signInActivity throttling limit to documentation

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/microsoft-graph-docs-contrib#8653]
In the section https://learn.microsoft.com/en-us/graph/throttling-limits#identity-and-access-reports-service-limits

There is another undocumented throttling limit we need to add here.

If pulling the signInActivity on a single user like this...
https://graph.microsoft.com/v1.0/users/{USER_ID}?$select=signInActivity

There is a throttling limit of 10 requests per 1 minute

We should also add signInActivity to the list in this section. As if you list users and have signInActivity in the select will also hit this normal AAD Reporting API throttling limit. For example...
https://graph.microsoft.com/v1.0/users/?$filter=signInActivity/lastSignInDateTime gt 2023-09-02T00:00:00Z&$select=id,userPrincipalName,signInActivity

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Version Independent ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Content: [Microsoft Graph service-specific throttling limits - Microsoft Graph](https://learn.microsoft.com/en-us/graph/throttling-limits)
* Content Source: [concepts/throttling-limits.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/throttling-limits.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Hi @egreenberg14 - Can you confirm these limits? Thanks.

**Comment by egreenberg14** [comment]
Hi @FaithOmbongi, I'll look into this and update the docs as needed.

**Comment by egreenberg14** [comment]
@willfiddes -- I question why you're querying the signinactivity endpoint 10 times in one minute. Why do you need multiple requests to get the data for a given user?

**Comment by egreenberg14** [comment]
Closed this because it's not aligned with the APIs use-case
