### ISSUE TITLE
C# example is incorrect

### ISSUE THREAD

**Issue by ajweber** [microsoftgraph/microsoft-graph-docs-contrib#8657]
C# example is missing the .Request() method - required.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69e3ab60-0af1-e537-d9cf-c23415dd1dc6
* Version Independent ID: 7bc60c80-43f9-88ec-fc3e-030bf0dface6
* Content: [List who has access to a file - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/driveitem-list-permissions.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrueastman** [comment]
Thanks for raising this @ajweber 

Any chance you confirm the version of the SDK you are using? At the moment, snippets in the documentation are for the latest version of the SDK as captured in the comment. 

```cs
// Code snippets are only available for the latest version. Current version is 5.x
```

**Comment by andrueastman** [comment]
Closing as v5 samples do not use the `Request()` method.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#removal-of-request-from-the-fluent-api
