### ISSUE TITLE
CreateDateTime field in the response does not match the documentation

### ISSUE THREAD

**Issue by nmahajan-jpmc** [microsoftgraph/microsoft-graph-docs-contrib#8661]
[Enter feedback here]
Documentation say that the createDateTime will be exact upto 6 decimal places within the second but the actual response is always in seconds and the decimals are ignored.

Response from the API : 2014-01-01T00:00:00Z. 
Response expected as per documentation: 2014-01-01T00:00:00.123456Z

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06e7697f-b03a-3282-ebd8-748b65dde87d
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http#response)
* Content Source: [api-reference/v1.0/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/signin-list.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @egreenberg14
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @nmahajan-jpmc for raising this issue. I've repro'd the same behavior you're seeing. I'll raise a PR to update the documentation.
