### ISSUE TITLE
Sites.Selected is now available for SharePoint, not just Graph

### ISSUE THREAD

**Issue by davidwilborn** [microsoftgraph/microsoft-graph-docs-contrib#8662]
This page states "The Sites.Selected application permission is available only in the Microsoft Graph API" But this is no longer accurate, Sites.Selected is now available for SharePoint APIs: 
https://devblogs.microsoft.com/microsoft365dev/updates-on-controlling-app-specific-access-on-specific-sharepoint-sites-sites-selected

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9edcc46d-c145-fad7-a54c-52c21f05ab7c
* Version Independent ID: 8b6bcf33-b048-2d3c-33b5-5a3dd5d25a75
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://learn.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/permissions-reference.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The page has been updated. I'm going to close this item. Thanks for your understanding.
