### ISSUE TITLE
There is an unresolved merge

### ISSUE THREAD

**Issue by vigneshtrace** [microsoftgraph/microsoft-graph-docs-contrib#8665]
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/133641497/19a3a250-7096-40be-92a9-7ac50a138d4f)

And I was looking for if there are any list delta APIs available for both calls and online meetings in your release pipeline, and may I know the ETA?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 148eb2e9-1b76-469f-ea6e-02dd51b71058
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create onlineMeeting - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @awang119
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by awang119** [comment]
We do have a delta notification for graph presence api that's on the roadmap for CY24Q1. None for calls or online meetings at the moment.
