### ISSUE TITLE
Text refers to six workflows when there are eight in the associated list:

### ISSUE THREAD

**Issue by mlibenocg** [microsoftgraph/microsoft-graph-docs-contrib#8668]
"Workflow templates
"Azure AD provides the following **six** predefined workflow templates..."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4143b7b5-d3c0-92d8-7c4c-20501882ac79
* Version Independent ID: ce051969-7527-c70c-cbd1-218900834aee
* Content: [Overview of Lifecycle Workflows APIs - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/identitygovernance-lifecycleworkflows-overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/identitygovernance-lifecycleworkflows-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/identitygovernance-lifecycleworkflows-overview.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @AlexFilipin
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @mlibenocg for catching the error. I've raised a PR to fix the reference.
