### ISSUE TITLE
Please update the doc with below note for clear understanding.

### ISSUE THREAD

**Issue by v-shde** [microsoftgraph/microsoft-graph-docs-contrib#867]
"The dataLocationCode will currently be returned by the "beta" endpoint of the API. We're looking into graduating this to 1.0. Unfortunately no ETA right now but you can see how it returns the data with the "beta" endpoint today."
May be this can be specified in the existing doc for clear understanding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217852fe-79b1-a74c-3ff5-c059f4e7ca47
* Version Independent ID: 170e578f-ddd3-857c-f137-7cb3508aeefe
* Content: [site resource - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
