### ISSUE TITLE
List role management policies response unclear

### ISSUE THREAD

**Issue by BenjaminZ** [microsoftgraph/microsoft-graph-docs-contrib#8674]
Given a response of the list role management policies, how do I tell which one is to allow users to raise PIM and be added as a member of a group or raise a PIM and become a owner of the group?

The polices seem identical except for the ids.

```json
{
	"@odata.context": "https://graph.microsoft.com/beta/$metadata#policies/roleManagementPolicies",
	"value": [
		{
			"id": "Group_15c69beb-dd5e-4a05-81f3-9f50ffaab1b7_97f9ac6d-3925-4af4-a821-fc23d1a36ecb",
			"displayName": "Group",
			"description": "Group",
			"isOrganizationDefault": false,
			"scopeId": "15c69beb-dd5e-4a05-81f3-9f50ffaab1b7",
			"scopeType": "Group",
			"lastModifiedDateTime": null,
			"lastModifiedBy": {
				"displayName": null,
				"id": null
			}
		},
		{
			"id": "Group_15c69beb-dd5e-4a05-81f3-9f50ffaab1b7_707a26f7-e617-480f-b112-673623e184e8",
			"displayName": "Group",
			"description": "Group",
			"isOrganizationDefault": false,
			"scopeId": "15c69beb-dd5e-4a05-81f3-9f50ffaab1b7",
			"scopeType": "Group",
			"lastModifiedDateTime": null,
			"lastModifiedBy": {
				"displayName": null,
				"id": null
			}
		}
	]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 855c0d8c-16bb-3e41-7cea-cd7c1089d910
* Version Independent ID: 397f5638-b568-7690-c21d-148912b93049
* Content: [List roleManagementPolicies - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/policyroot-list-rolemanagementpolicies?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/policyroot-list-rolemanagementpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/policyroot-list-rolemanagementpolicies.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @rkarim-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by weijie-lin** [comment]
@FaithOmbongi , @BenjaminZ 
You can query List roleManagementPolicyAssignments API to see each the policy id is associated to member or owner in the response. https://learn.microsoft.com/en-us/graph/api/policyroot-list-rolemanagementpolicyassignments?view=graph-rest-beta&tabs=http#example-3-retrieve-details-of-all-role-management-policy-assignments-for-pim-for-groups

cc: @ilyalushnikov
