### ISSUE TITLE
Title shows some code, wrong generated title

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#8677]
This page shows me

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/7744844/1162e3e7-4d13-4562-8e9b-7ff8b40d7221)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f884845-3be7-e835-8f04-efbe1dddb465
* Version Independent ID: 44343904-b495-cf3c-4017-6a88742f7f30
* Content: [title: 'Range resource type'
description: 'Range represents a set of one or more contiguous cells such as a cell, a row, a column, block of cells, etc.'
ms.localizationpriority: high
author: 'lumine2008'
ms.prod: 'excel'
doc_type: resourcePageType - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/range?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/range.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/range.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks for reporting @MartinM85! I've fixed this on our end, changes should show up later today.
