### ISSUE TITLE
How to get the quota of the total tenant for SharePoint Online?

### ISSUE THREAD

**Issue by landall** [microsoftgraph/microsoft-graph-docs-contrib#868]
Because the free space of a site is not the free space we can use, I think the free space is the minimal between the free quota of a site and the free quota of the total tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 264d21e6-769e-9a35-80b7-681a7060a3c2
* Version Independent ID: c430818f-ce11-f080-6c6c-25943efabcef
* Content: [Working with SharePoint sites in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/sharepoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/sharepoint.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @rgregg
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
