### ISSUE TITLE
The Java example is missing on plannertaskdetails-update

### ISSUE THREAD

**Issue by oneick** [microsoftgraph/microsoft-graph-docs-contrib#8681]
The Java example is missing, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b028fb35-808d-e08c-37ab-0845c0e5df18
* Version Independent ID: 64125169-a127-0f95-2763-a1afe1ee674f
* Content: [Update plannerTaskDetails - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/plannertaskdetails-update?vieplannertaskdetails-update?view=graphw=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/plannertaskdetails-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/plannertaskdetails-update.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
Hi. Thanks for raising this issue.

The code snippets has been updated based on the new [Microsoft Graph Java v6 version](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v6.1.0) and this documentation page has now Java example.
You can also check more info about the new version in the [v6 announcement blog post](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/).

**Comment by oneick** [comment]
Thanks! But is it possible that the new example is wrong in terms of PlannerChecklistItem? There is no PlannerChecklist**Item** in the com.microsoft.graph.models anymore. Or am I totally wrong? The hole thing of setting a Checklist to a task is a bit complicated since V6
