### ISSUE TITLE
Example 2

### ISSUE THREAD

**Issue by jcoolsen** [microsoftgraph/microsoft-graph-docs-contrib#8684]
Example 2 returns an empty list.
GET https://graph.microsoft.com/v1.0/sites

It will return a list with this query instead:
GET https://graph.microsoft.com/v1.0/sites?search=

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b05ccb12-48fb-7f65-a695-0846564d2bc2
* Version Independent ID: 769c63c0-4981-7506-8320-56beafaa8770
* Content: [List sites - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/site-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-list.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/site-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
