### ISSUE TITLE
Cannot Resume Access Package assignment using "resume" callback API endpoint

### ISSUE THREAD

**Issue by brolifen** [microsoftgraph/microsoft-graph-docs-contrib#8687]
When trying to resume an Access Package request using the API endpoint in the doc (in this case using custom extensions) the following error is thrown:

{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "date": "2023-10-09T05:15:46",
            "request-id": "4a385d8a-d3df-4a1b-8097-cdb14a74ac5c",
            "client-request-id": "a90591d1-7d6f-89a0-dcb1-942959a867a0"
        }
    }
}

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/20615514/4d91c983-54ec-45ac-813c-dbfad426bbcd)
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/20615514/804f7b4b-408d-434f-945c-d9ae95bec33c)

Tenant: All
Permissions: EntitlementManagement.ReadWrite.All
API Endpoints: v1 and beta

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b677ab4d-6693-0823-0027-0584176e49d4
* Version Independent ID: 3dec53ce-dccb-2e4b-83a6-a224ce00c6a2
* Content: [accessPackageAssignmentRequest: resume - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-resume?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/accesspackageassignmentrequest-resume.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/accesspackageassignmentrequest-resume.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @vikama-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by AlexFilipin** [comment]
@brolifen could you please open a support case via the Microsoft Entra or Azure portal for this issue. Feel free to message me the support case id to alexander.filipin @ microsoft.com and I will ensure it gets close attention from our product engineer team next to our regular support teams.

**Comment by FaithOmbongi** [comment]
Closing this issue as the customer has been advised to file a support case.
