### ISSUE TITLE
Useless documentation

### ISSUE THREAD

**Issue by RuanAlesi** [microsoftgraph/microsoft-graph-docs-contrib#8688]
What's the sense to search for an item if the item ID is required???

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de33ed18-c074-a734-0b01-648888cb94aa
* Version Independent ID: 9fa15051-394e-d4ce-4687-c93be0ca8b80
* Content: [Search for files - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/driveitem-search.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/driveitem-search.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by bas-eenhoorn** [comment]
Do you mean the id's in the urls? (/drives/{drive-id}/root/...). Its the ID of the drive (or group or site) you want to search in. You need to specify at least a site or drive to search in.

Or do you mean the C# example? Because it does show an example using driveItemId, which is indeed not necessary for searching.

Also, if someone from the graph team reads this, the python example is missing a closing ) at the end after {q}': .search(q='{q}'.get()

**Comment by jvalente-salemstate** [comment]
@RuanAlesi I may be misunderstanding but if you don't have the ID on hand, you could get it with a list drives/users/sites/groups request.

**Comment by RuanAlesi** [comment]
@jvalente-salemstate I might was not that clear, I'm talking about the C# example:
`await graphClient.Drives["{drive-id}"].Items["{driveItem-id}"].SearchWithQ("{q}").GetAsync();`
But I've already figured it out: let's consider that I'm searching for an item called 'foo.txt'. Trying the HTTP example via Postman works perfectly. So I presumed that having the Drive entity would be enough to search via C#, but this piece of code `Items["{driveItem-id}"]` doesn't make any sense - well, I don't have the item. Actually "root" is the item ID expected considering searching on all directories - as the HTTP example.
Therefore, I would suggest use this example on C# to make it completely comparable with HTTP.
`await graphClient.Drives["myDriveID"].Items["root"].SearchWithQ("foo.txt").GetAsync();`

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
