### ISSUE TITLE
While trying to create a resource for metered Graph API using the az resource create --resource-group cmdlet fails consistently

### ISSUE THREAD

**Issue by JSP-Neto** [microsoftgraph/microsoft-graph-docs-contrib#8690]
Hello everyone, everything good?

I need to use the Metered MSteams API and I cannot perform the command in cloud azure powershell.

I opened a ticket on the azure portal 3 days ago and no one helps me 🤔.

(InternalServerError) S2S33101: Failed to get token from tokenEndpoint: 'https://login.windows.net/1fb81c63-5daf-4103-866d-fa9bf6XXXXXX/oauth2/v2.0/token', clientId: 'e3b317b2-ee2c-4eb2-ab20-c166ef7fe246', resource: 'https://graph.microsoft.com//.default', activityId: '0e0650da-bcb5-4bf8-bc7c-022b3aba25b0'.'.

Same issue here:
#929 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b356f4b8-50b3-7ff6-8c3f-a5210b027c7c
* Version Independent ID: b356f4b8-50b3-7ff6-8c3f-a5210b027c7c
* Content: [Enable metered APIs and services in Microsoft Graph - Microsoft Graph](https://learn.microsoft.com/en-us/graph/metered-api-setup?tabs=azurecloudshell)
* Content Source: [concepts/metered-api-setup.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/metered-api-setup.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
