### ISSUE TITLE
reference to Exchange Online photos should be deprecated 

### ISSUE THREAD

**Issue by tdoan1** [microsoftgraph/microsoft-graph-docs-contrib#8695]
The article still refers to "HD photos on Exchange Online" when user photo management with the Exchange Online cmdlets is being retired. 
https://m365admin.handsontek.net/exchangepowershell-retirement-of-tenant-admin-cmdlets-to-get-set-and-remove-userphotos/

More recent guidance for the size and dimensions of image files to be uploaded to Entra ID user accounts is needed. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d517bc8-e757-3822-848a-bf6b65d456b5
* Version Independent ID: ed8cafa6-65b9-fe58-57b3-3d57676fae46
* Content: [Update profilePhoto - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/profilephoto-update.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Thanks.
