### ISSUE TITLE
Pagination support for directoyrole/members

### ISSUE THREAD

**Issue by lennaylennay2** [microsoftgraph/microsoft-graph-docs-contrib#8696]
In parent docs we see this 

`Not all resources or relationships support paging. For example, queries against [directoryRoles](https://learn.microsoft.com/en-us/graph/api/resources/directoryrole) do not support paging. This includes reading role objects themselves as well as role members.`
but i see no mention here. 
It would seem like getting role members would often require pagination as roles are limited?

 ---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d957b152-584e-7427-4479-1892dc0bf10a
* Version Independent ID: c83b37f7-e0a9-7a69-4bee-21bcc73a27ab
* Content: [List members of a directory role - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/directoryrole-list-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directoryrole-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/directoryrole-list-members.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @DougKirschner
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @lennaylennay2 for your patience. I've received confirmation that API returns up to 1000 objects and doesn't support pagination. I'll add this information to the article.

Recommendation: Have you considered using the [List roleAssignments API](https://learn.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&tabs=http) instead? It has better support for query capabilities.
