### ISSUE TITLE
Add API permission requirement for adding SharePoint site resources to Catalog

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/microsoft-graph-docs-contrib#8699]
There are additional requirements depending on the resources you want to add to a catalog. SharePoint is another common one to be added. And this does require SharePoint site API permissions. Adding "Sites.FullControl.All" helped resolve the error "CallerNotResourceOwner" 

Not sure if there is a lesser privileged API permission to.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cfcc5c6-4741-070d-9fa6-f6520ec8858f
* Version Independent ID: 0099c1ef-875d-0a7c-29f9-fcd420cb3aa0
* Content: [Create accessPackageResourceRequest - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-post-resourcerequests?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/entitlementmanagement-post-resourcerequests.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/entitlementmanagement-post-resourcerequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
Thanks, we will add this permission requirement to the article.
