### ISSUE TITLE
Documentation indicates false support of SchemaExtension for multiple types

### ISSUE THREAD

**Issue by ramsessanchez** [microsoftgraph/microsoft-graph-docs-contrib#8700]
I believe there is an issue with the statement that SchemaExtensions are supported by various types when in fact it is simply 'Extensions' which are supported by those types. In the V1.0 metadata there is no indication that any types support a navigation property of type 'SchemaExtension' or that they support a property of type 'SchemaExtension'. Rather the following types all support a navigation property of type "Collection(graph.extension)". Furthermore, 'SchemaExtension' is not a child type of 'Extension' so the documentation should not be suggesting the support of SchemaExtension. 

types: 
user
group
administrativeUnit
application
contact
device
event
message
organization
post

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: debeb911-8b51-4cc0-6ff0-8b489781e2cb
* Version Independent ID: 4ef96056-db6f-35ae-646a-963f356a7da8
* Content: [schemaExtension resource type (schema extensions) - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/schemaextension.md)
* Product: **extensions**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ramsessanchez for raising this issue. Collection(graph.extension) isn't the same as schemaExtension. Rather, it's the base type for [open extensions](https://learn.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0).

The schema doesn't explicitly mention the object types that support schemaExtension; rather, they are described in the **targetTypes** propertyof a schemaExtension.

Hope this resolves the issue.
