### ISSUE TITLE
Documentation states 200 response when API returns 204 -No content

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/microsoft-graph-docs-contrib#8701]
Follow up from https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/738

Testing from Graph Explorer, API returns 204 when documentation states 200. What is the actual expected API response?

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/6464005/9723cd4f-c189-4223-8ccf-3ffdd228eb24)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5336679e-ed8e-eb90-bf58-1312981abcdf
* Version Independent ID: 6bba4f49-5c94-cf19-3d41-439d8607189c
* Content: [Update androidManagedAppProtection - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/intune-mam-androidmanagedappprotection-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/intune-mam-androidmanagedappprotection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/intune-mam-androidmanagedappprotection-update.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @jaiprakashmb
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dansmitt** [comment]
@jaiprakashmb can we speed this up if we open a case? Would be cool to get some feedback.

**Comment by jaiprakashmb** [comment]
@dansmitt:
This is by design patch calls associated with androidmanagedappprotection does return 204 - No-Content.
We will get the documentation fixed during our next doc release.
