### ISSUE TITLE
GA release

### ISSUE THREAD

**Issue by medhabhatt** [microsoftgraph/microsoft-graph-docs-contrib#8704]
[Enter feedback here]
Hi,  When can we expect GA release for this API since the current 1.0 version does not provide the 'isPrivileged=true' flag in JSON response.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99f1ee9b-84ea-c3ea-c0cf-85e29af8eefe
* Version Independent ID: 8825363c-e462-5503-0ba5-d83698251af4
* Content: [List roleDefinitions - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&preserve-view=true&branch=pr-en-us-18827&tabs=http)
* Content Source: [api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/rbacapplication-list-roledefinitions.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @DougKirschner
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @medhabhatt for asking this question. Unfortunately, we don't have an ETA for general availability of the privileged roles feature. You can monitor the Microsoft Graph changelog for updates to the feature. Closing this issue here because it's not a doc-related issue.
