### ISSUE TITLE
segment and media portions of this api are not working as illustrated in this documentation

### ISSUE THREAD

**Issue by vmanju123** [microsoftgraph/microsoft-graph-docs-contrib#8707]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ea05ebd-305b-fdf2-3a05-29d4c7d75ef0
* Version Independent ID: 5ee61d29-e1a7-f4de-7221-ddccbaacbef1
* Content: [List callRecord sessions - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/callrecords-session-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/callrecords-session-list.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/callrecords-session-list.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @mcm223
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vmanju123** [comment]
segment and media portion of this api response is not working as expected, something wrong in api syntax

**Comment by mcm223** [comment]
@vmanju123 Can you please provide more detail? What specifically appears incorrect in the response compared to the documentation?

**Comment by mcm223** [comment]
@vmanju123 Without additional detail I'm afraid I can't assist you. Please feel free to reopen if you have further questions or concerns.
