### ISSUE TITLE
Update List Item documentations lacks information for complex columns

### ISSUE THREAD

**Issue by Mentate** [microsoftgraph/microsoft-graph-docs-contrib#871]
Issue: Update List item doesn't give an example on how to update a complex column in a list. For example, I am trying to add users to a "Person or Group" column, but I don't know how the JSON should be formatted. I've tried to match the formatting that was used to do this with the SharePoint REST API, but that only returns errors. Any guidance in the documentation for columns other than primitive types would be very helpful. 

Article: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-update.md

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
