### ISSUE TITLE
Add member with specified visibleHistoryStartDateTime won't work

### ISSUE THREAD

**Issue by qquiuc** [microsoftgraph/microsoft-graph-docs-contrib#8712]
Hi Team
We tried to add a members in to a chat with specified visibleHistoryStartDateTime, but after we add this user, the time has been changed in the response, which cause the user saw some message that they shouldn't see.
The time we pointed in the request "2023-10-14T07:54:51.138Z" but the time in the response is 
2023-10-14T07:54:46.605Z
here is the members and messages form the chat, and the system event message that recording the adding progress.
Please help to confirm if this is the except behavior?
Members:
{
  "@odata.context": "https://microsoftgraph.chinacloudapi.cn/v1.0/$metadata#chats('19%3Agal%3A5d81a831258840a0a954a25ae0d9b71a%40thread.v2')/members",
  "@odata.count": 6,
  "value": [
    {
      "@odata.type": "#microsoft.graph.aadUserConversationMember",
      "id": "MCMjMCMjNmI5NDBmZmQtODk1OS00ZmUyLWExZjQtMDY1MGRmNzM2Mjg1IyMxOTpnYWw6NWQ4MWE4MzEyNTg4NDBhMGE5NTRhMjVhZTBkOWI3MWFAdGhyZWFkLnYyIyM4OTY5MTk1MS05ZGE4LTQ4MjQtODVhZS1mNTAwZmY2Yzk4ZDY=",
      "roles": [
        "owner"
      ],
      "displayName": "User 4_FLY",
      "visibleHistoryStartDateTime": "2023-10-14T07:54:37.377Z",
      "userId": "89691951-9da8-4824-85ae-f500ff6c98d6",
      "email": "fly@apacavepoint.partner.onmschina.cn",
      "tenantId": "6b940ffd-8959-4fe2-a1f4-0650df736285"
    },
    {
      "@odata.type": "#microsoft.graph.aadUserConversationMember",
      "id": "MCMjMCMjNmI5NDBmZmQtODk1OS00ZmUyLWExZjQtMDY1MGRmNzM2Mjg1IyMxOTpnYWw6NWQ4MWE4MzEyNTg4NDBhMGE5NTRhMjVhZTBkOWI3MWFAdGhyZWFkLnYyIyMxOGVhOTI5MC00ZmE0LTRiYjQtODdjYi0zY2FmYmMwMWM4ZTg=",
      "roles": [
        "owner"
      ],
      "displayName": "TC Place",
      "visibleHistoryStartDateTime": "2023-10-14T07:54:37.377Z",
      "userId": "18ea9290-4fa4-4bb4-87cb-3cafbc01c8e8",
      "email": "TCplaceHolder@apacavepoint.partner.onmschina.cn",
      "tenantId": "6b940ffd-8959-4fe2-a1f4-0650df736285"
    },
    {
      "@odata.type": "#microsoft.graph.aadUserConversationMember",
      "id": "MCMjMCMjNmI5NDBmZmQtODk1OS00ZmUyLWExZjQtMDY1MGRmNzM2Mjg1IyMxOTpnYWw6NWQ4MWE4MzEyNTg4NDBhMGE5NTRhMjVhZTBkOWI3MWFAdGhyZWFkLnYyIyM2MzQ4N2Y1Zi01NzhhLTQ5YWItOTE0Ni04YWFjOWY5OTVlYzE=",
      "roles": [
        "owner"
      ],
      "displayName": "FLYUser",
      "visibleHistoryStartDateTime": "2023-10-14T07:54:37.377Z",
      "userId": "63487f5f-578a-49ab-9146-8aac9f995ec1",
      "email": "Elsa_FLY@apacavepoint.partner.onmschina.cn",
      "tenantId": "6b940ffd-8959-4fe2-a1f4-0650df736285"
    },
    {
      "@odata.type": "#microsoft.graph.aadUserConversationMember",
      "id": "MCMjMCMjNmI5NDBmZmQtODk1OS00ZmUyLWExZjQtMDY1MGRmNzM2Mjg1IyMxOTpnYWw6NWQ4MWE4MzEyNTg4NDBhMGE5NTRhMjVhZTBkOWI3MWFAdGhyZWFkLnYyIyM1OTIxOTUwNS1kM2YyLTQ0NmMtOTE2NS02NGZkOTVjNzg0ZmQ=",
      "roles": [
        "owner"
      ],
      "displayName": "Ella",
      "visibleHistoryStartDateTime": "0001-01-01T00:00:00Z",
      "userId": "59219505-d3f2-446c-9165-64fd95c784fd",
      "email": "alexw@apacavepoint.partner.onmschina.cn",
      "tenantId": "6b940ffd-8959-4fe2-a1f4-0650df736285"
    },
    {
      "@odata.type": "#microsoft.graph.aadUserConversationMember",
      "id": "MCMjMCMjNmI5NDBmZmQtODk1OS00ZmUyLWExZjQtMDY1MGRmNzM2Mjg1IyMxOTpnYWw6NWQ4MWE4MzEyNTg4NDBhMGE5NTRhMjVhZTBkOWI3MWFAdGhyZWFkLnYyIyMxZGQ5MWFlNi01YTBhLTRkZDQtYmRmZC1hZjNmODBiYWU4ZWI=",
      "roles": [
        "owner"
      ],
      "displayName": "EllaUser2",
      "visibleHistoryStartDateTime": "0001-01-01T00:00:00Z",
      "userId": "1dd91ae6-5a0a-4dd4-bdfd-af3f80bae8eb",
      "email": "JosieEmail@apacavepoint.partner.onmschina.cn",
      "tenantId": "6b940ffd-8959-4fe2-a1f4-0650df736285"
    },
    {
      "@odata.type": "#microsoft.graph.aadUserConversationMember",
      "id": "MCMjMCMjNmI5NDBmZmQtODk1OS00ZmUyLWExZjQtMDY1MGRmNzM2Mjg1IyMxOTpnYWw6NWQ4MWE4MzEyNTg4NDBhMGE5NTRhMjVhZTBkOWI3MWFAdGhyZWFkLnYyIyM1MjA0ZWIwOC1iMDUwLTQ3ZTUtYWUwMy05NDBjNGZhMjliYTQ=",
      "roles": [
        "owner"
      ],
      "displayName": "User 8_FLY",
      "visibleHistoryStartDateTime": "2023-10-14T07:54:46.605Z",
      "userId": "5204eb08-b050-47e5-ae03-940c4fa29ba4",
      "email": "Josie@apacavepoint.partner.onmschina.cn",
      "tenantId": "6b940ffd-8959-4fe2-a1f4-0650df736285"
    }
  ]
}

Messages:
{
  "@odata.context": "https://microsoftgraph.chinacloudapi.cn/v1.0/$metadata#chats('19%3Agal%3A5d81a831258840a0a954a25ae0d9b71a%40thread.v2')/messages",
  "@odata.count": 5,
  "value": [
    {
      "id": "1697270091159",
      "replyToId": null,
      "etag": "1697270091159",
      "messageType": "unknownFutureValue",
      "createdDateTime": "2023-10-14T07:54:51.159Z",
      "lastModifiedDateTime": "2023-10-14T07:54:51.159Z",
      "lastEditedDateTime": null,
      "deletedDateTime": null,
      "subject": null,
      "summary": null,
      "chatId": "19:gal:5d81a831258840a0a954a25ae0d9b71a@thread.v2",
      "importance": "normal",
      "locale": "en-us",
      "webUrl": null,
      "from": null,
      "channelIdentity": null,
      "policyViolation": null,
      "body": {
        "contentType": "html",
        "content": "<systemEventMessage/>"
      },
      "attachments": [],
      "mentions": [],
      "reactions": [],
      "eventDetail": {
        "@odata.type": "#microsoft.graph.membersAddedEventMessageDetail",
        "visibleHistoryStartDateTime": "2023-10-14T07:54:51.138Z",
        "members": [
          {
            "id": "5204eb08-b050-47e5-ae03-940c4fa29ba4",
            "displayName": null,
            "userIdentityType": "aadUser"
          }
        ],
        "initiator": {
          "device": null,
          "user": null,
          "application": {
            "@odata.type": "#microsoft.graph.teamworkApplicationIdentity",
            "id": "6b940ffd-8959-4fe2-a1f4-0650df736285_8b82fdb8-59e1-47a7-8b23-8be83db0ae82",
            "displayName": null,
            "applicationIdentityType": "aadApplication"
          }
        }
      }
    },
    {
      "id": "1697270090876",
      "replyToId": null,
      "etag": "1697270090876",
      "messageType": "unknownFutureValue",
      "createdDateTime": "2023-10-14T07:54:50.876Z",
      "lastModifiedDateTime": "2023-10-14T07:54:50.876Z",
      "lastEditedDateTime": null,
      "deletedDateTime": null,
      "subject": null,
      "summary": null,
      "chatId": "19:gal:5d81a831258840a0a954a25ae0d9b71a@thread.v2",
      "importance": "normal",
      "locale": "en-us",
      "webUrl": null,
      "from": null,
      "channelIdentity": null,
      "policyViolation": null,
      "body": {
        "contentType": "html",
        "content": "<systemEventMessage/>"
      },
      "attachments": [],
      "mentions": [],
      "reactions": [],
      "eventDetail": {
        "@odata.type": "#microsoft.graph.membersAddedEventMessageDetail",
        "visibleHistoryStartDateTime": "0001-01-01T00:00:00Z",
        "members": [
          {
            "id": "1dd91ae6-5a0a-4dd4-bdfd-af3f80bae8eb",
            "displayName": null,
            "userIdentityType": "aadUser"
          }
        ],
        "initiator": {
          "device": null,
          "user": null,
          "application": {
            "@odata.type": "#microsoft.graph.teamworkApplicationIdentity",
            "id": "6b940ffd-8959-4fe2-a1f4-0650df736285_8b82fdb8-59e1-47a7-8b23-8be83db0ae82",
            "displayName": null,
            "applicationIdentityType": "aadApplication"
          }
        }
      }
    },
    {
      "id": "1697270090527",
      "replyToId": null,
      "etag": "1697270090527",
      "messageType": "unknownFutureValue",
      "createdDateTime": "2023-10-14T07:54:50.527Z",
      "lastModifiedDateTime": "2023-10-14T07:54:50.527Z",
      "lastEditedDateTime": null,
      "deletedDateTime": null,
      "subject": null,
      "summary": null,
      "chatId": "19:gal:5d81a831258840a0a954a25ae0d9b71a@thread.v2",
      "importance": "normal",
      "locale": "en-us",
      "webUrl": null,
      "from": null,
      "channelIdentity": null,
      "policyViolation": null,
      "body": {
        "contentType": "html",
        "content": "<systemEventMessage/>"
      },
      "attachments": [],
      "mentions": [],
      "reactions": [],
      "eventDetail": {
        "@odata.type": "#microsoft.graph.membersAddedEventMessageDetail",
        "visibleHistoryStartDateTime": "0001-01-01T00:00:00Z",
        "members": [
          {
            "id": "59219505-d3f2-446c-9165-64fd95c784fd",
            "displayName": null,
            "userIdentityType": "aadUser"
          }
        ],
        "initiator": {
          "device": null,
          "user": null,
          "application": {
            "@odata.type": "#microsoft.graph.teamworkApplicationIdentity",
            "id": "6b940ffd-8959-4fe2-a1f4-0650df736285_8b82fdb8-59e1-47a7-8b23-8be83db0ae82",
            "displayName": null,
            "applicationIdentityType": "aadApplication"
          }
        }
      }
    },
    {
      "id": "1697270090173",
      "replyToId": null,
      "etag": "1697270090173",
      "messageType": "message",
      "createdDateTime": "2023-10-14T07:54:50.173Z",
      "lastModifiedDateTime": "2023-10-14T07:54:50.173Z",
      "lastEditedDateTime": null,
      "deletedDateTime": null,
      "subject": null,
      "summary": null,
      "chatId": "19:gal:5d81a831258840a0a954a25ae0d9b71a@thread.v2",
      "importance": "normal",
      "locale": "en-us",
      "webUrl": null,
      "channelIdentity": null,
      "policyViolation": null,
      "eventDetail": null,
      "from": {
        "application": null,
        "device": null,
        "user": {
          "@odata.type": "#microsoft.graph.teamworkUserIdentity",
          "id": "63487f5f-578a-49ab-9146-8aac9f995ec1",
          "displayName": "FLYUser",
          "userIdentityType": "aadUser",
          "tenantId": "6b940ffd-8959-4fe2-a1f4-0650df736285"
        }
      },
      "body": {
        "contentType": "html",
        "content": "<div><div><span style=\"font-size:1.2rem\"><b>User 4_FLY</b><span style=\"margin-left:1rem\">2023-10-14 7:53:00 AM (UTC)</span></span><br><div>\n<p>Test share message</p>\n</div></div><br><div><span style=\"font-size:1.2rem\"><b>User 4_FLY</b><span style=\"margin-left:1rem\">2023-10-14 7:53:05 AM (UTC)</span></span><br><div>\n<p>i will add a member</p>\n</div></div><br>\n</div>"
      },
      "attachments": [],
      "mentions": [],
      "reactions": []
    },
    {
      "id": "1697270077539",
      "replyToId": null,
      "etag": "1697270077539",
      "messageType": "unknownFutureValue",
      "createdDateTime": "2023-10-14T07:54:37.539Z",
      "lastModifiedDateTime": "2023-10-14T07:54:37.539Z",
      "lastEditedDateTime": null,
      "deletedDateTime": null,
      "subject": null,
      "summary": null,
      "chatId": "19:gal:5d81a831258840a0a954a25ae0d9b71a@thread.v2",
      "importance": "normal",
      "locale": "en-us",
      "webUrl": null,
      "from": null,
      "channelIdentity": null,
      "policyViolation": null,
      "body": {
        "contentType": "html",
        "content": "<systemEventMessage/>"
      },
      "attachments": [],
      "mentions": [],
      "reactions": [],
      "eventDetail": {
        "@odata.type": "#microsoft.graph.membersAddedEventMessageDetail",
        "visibleHistoryStartDateTime": "2023-10-14T07:54:37.482Z",
        "members": [
          {
            "id": "89691951-9da8-4824-85ae-f500ff6c98d6",
            "displayName": null,
            "userIdentityType": "aadUser"
          },
          {
            "id": "18ea9290-4fa4-4bb4-87cb-3cafbc01c8e8",
            "displayName": null,
            "userIdentityType": "aadUser"
          },
          {
            "id": "63487f5f-578a-49ab-9146-8aac9f995ec1",
            "displayName": null,
            "userIdentityType": "aadUser"
          }
        ],
        "initiator": {
          "device": null,
          "user": null,
          "application": {
            "@odata.type": "#microsoft.graph.teamworkApplicationIdentity",
            "id": "6b940ffd-8959-4fe2-a1f4-0650df736285_8b82fdb8-59e1-47a7-8b23-8be83db0ae82",
            "displayName": null,
            "applicationIdentityType": "aadApplication"
          }
        }
      }
    }
  ]
}
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06f63954-ef8d-6a56-c5b1-5196030824c6
* Version Independent ID: 07b1c430-89b4-94c2-4b60-cfc0fa2bb677
* Content: [Add member to a chat - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/chat-post-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @anandjo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
@qquiuc - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
@qquiuc - We tried to repro this issue and observed that it is working fine at our end. The `visibleHistoryStartDateTime` is same in both request and response.
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/62237649/f242b6b3-786f-4f2b-940d-037410299f66)
Request Body:
```
{
    "@odata.type": "#microsoft.graph.aadUserConversationMember",
    "user@odata.bind": "https://graph.microsoft.com/v1.0/users/f5906683-9ab4-4a47-9933-701ffe80145d",
    "visibleHistoryStartDateTime": "2023-09-18T23:51:43.255Z",
    "roles": [
        "owner"
    ]
}
```
Response:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#chats('19%3A7c58552b73744f8baca72f895604c29c%40thread.v2')/members",
    "@odata.count": 4,
    "@microsoft.graph.tips": "Use $select to choose only the properties your app needs, as this can lead to performance improvements. For example: GET chats('<key>')/members?$select=displayName,roles",
    "value": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "MCMjMCMjNGFkNTk5NTYtMGY4OC00Yjg4LWE5ZDAtNTcwYjZlYjRlNjZiIyMxOTo3YzU4NTUyYjczNzQ0ZjhiYWNhNzJmODk1NjA0YzI5Y0B0aHJlYWQudjIjIzc1ZjlmZDZiLWJlYmQtNDAzOS1iNTc2LTJjN2M4N2IxZjViMQ==",
            "roles": [
                "owner"
            ],
            "displayName": "Adele Vance",
            "visibleHistoryStartDateTime": "0001-01-01T00:00:00Z",
            "userId": "75f9fd6b-bebd-4039-b576-2c7c87b1f5b1",
            "email": "AdeleV@M365x17798679.OnMicrosoft.com",
            "tenantId": "4ad59956-0f88-4b88-a9d0-570b6eb4e66b"
        },
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "MCMjMCMjNGFkNTk5NTYtMGY4OC00Yjg4LWE5ZDAtNTcwYjZlYjRlNjZiIyMxOTo3YzU4NTUyYjczNzQ0ZjhiYWNhNzJmODk1NjA0YzI5Y0B0aHJlYWQudjIjIzFkZDUwYmE3LWU1YmQtNDZlYS1iMzRlLTgwYTQxNTE0OGRlNw==",
            "roles": [
                "owner"
            ],
            "displayName": "Alex Wilber",
            "visibleHistoryStartDateTime": "0001-01-01T00:00:00Z",
            "userId": "1dd50ba7-e5bd-46ea-b34e-80a415148de7",
            "email": "AlexW@M365x17798679.OnMicrosoft.com",
            "tenantId": "4ad59956-0f88-4b88-a9d0-570b6eb4e66b"
        },
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "MCMjMCMjNGFkNTk5NTYtMGY4OC00Yjg4LWE5ZDAtNTcwYjZlYjRlNjZiIyMxOTo3YzU4NTUyYjczNzQ0ZjhiYWNhNzJmODk1NjA0YzI5Y0B0aHJlYWQudjIjI2NlOWRlZjMzLWQ3ZmMtNDQ0Yy04NzI4LWJlMWY5NWU2YjZmMg==",
            "roles": [
                "owner"
            ],
            "displayName": "MOD Administrator",
            "visibleHistoryStartDateTime": "0001-01-01T00:00:00Z",
            "userId": "ce9def33-d7fc-444c-8728-be1f95e6b6f2",
            "email": "admin@M365x17798679.onmicrosoft.com",
            "tenantId": "4ad59956-0f88-4b88-a9d0-570b6eb4e66b"
        },
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "MCMjMCMjNGFkNTk5NTYtMGY4OC00Yjg4LWE5ZDAtNTcwYjZlYjRlNjZiIyMxOTo3YzU4NTUyYjczNzQ0ZjhiYWNhNzJmODk1NjA0YzI5Y0B0aHJlYWQudjIjI2Y1OTA2NjgzLTlhYjQtNGE0Ny05OTMzLTcwMWZmZTgwMTQ1ZA==",
            "roles": [
                "owner"
            ],
            "displayName": "Allan Deyoung",
            "visibleHistoryStartDateTime": "2023-09-18T23:51:43.255Z",
            "userId": "f5906683-9ab4-4a47-9933-701ffe80145d",
            "email": "AllanD@M365x17798679.OnMicrosoft.com",
            "tenantId": "4ad59956-0f88-4b88-a9d0-570b6eb4e66b"
        }
    ]
}
```

**Comment by Prasad-MSFT** [comment]
@qquiuc - Do you have any further query on this?

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
