### ISSUE TITLE
Please add code examples for retrieving items by path

### ISSUE THREAD

**Issue by lmastin** [microsoftgraph/microsoft-graph-docs-contrib#8715]
There are HTTP requests listed for retrieving items by path; e.g.:

`GET /drives/{drive-id}/root:/{item-path}`

However, there are no code examples provided demonstrating how to make the same request via, for instance, C#.

(Examples are given for retrieving the item collection of a root folder; but this isn't overly helpful, as root folders are handled in a unique way. There are also examples elsewhere in the documentation for retrieving items by item-id; but one imagines most developers are going to be looking up items first and foremost by path.)

It would be very helpful if code examples could be provided demonstrating the process for retrieving items by path.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ccfedc34-43c1-d07a-249f-a105967a7730
* Version Independent ID: 3af5bde5-0179-4cd7-eacd-a903f3cb106b
* Content: [Get a driveItem resource - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/driveitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lmastin** [comment]
I stumbled across my own documentation request while trying to solve this issue again; so I thought I would leave a working example here for those in the same predicament:

`var item = await graphClient.Drives["driveId"].Root.ItemWithPath("Folder/Subfolder/File.ext").GetAsync() ;`

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
