### ISSUE TITLE
SkipToken is not a property under query QueryParameters

### ISSUE THREAD

**Issue by joshbinney** [microsoftgraph/microsoft-graph-docs-contrib#8718]
SkipToken is not a property under query QueryParameters in the latest Micrsoft.Graph library. How can we get around this for now?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7e1ac6d-b2ee-c495-3194-f2895e26945e
* Version Independent ID: 73f817df-a829-e265-c932-7ae8b3f3e918
* Content: [Paging Microsoft Graph data in your app  - Microsoft Graph](https://learn.microsoft.com/en-us/graph/paging?tabs=http)
* Content Source: [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by joshbinney** [comment]
Hi any update on this? It's holding up some important development for us.

**Comment by andrueastman** [comment]
Thanks for raising this @joshbinney,

The snippet generated here is incorrect and should be according to the guidance provided [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#skiptoken-and-deltatoken-query-parameters-in-delta-requests).

In this case the correct way to use the nextLink from the url is to do something like this. 

```cs
var usersResponse = await graphClient.Users.WithUrl("https://graph.microsoft.com/v1.0/users?$top=5&$skiptoken=skiptoken=RFNwdAIAAQAAAD8...AAAAAAAA").GetAsync();
```

We'll keep this open as we resolve the snippet generation issue here.

**Comment by joshbinney** [comment]
Thank you!
