### ISSUE TITLE
Download a file in another format: Version v1.0 download pptm as pdf not working

### ISSUE THREAD

**Issue by traveling-developer** [microsoftgraph/microsoft-graph-docs-contrib#872]
When trying to download a pptm file as pdf with the graph api v1.0 it returns a not supported error (InputFormatNotSupported). The documentation says it should work but sadly it does not.
Is this a wrong implementation or a wrong documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59cfb473-0783-09cb-3c88-96f884d76e06
* Version Independent ID: 9992b18b-299d-6863-c06f-8bacb7ff2962
* Content: [Convert to other formats - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get-content-format.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-get-content-format.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
