### ISSUE TITLE
Client credentials provider section not available

### ISSUE THREAD

**Issue by nitelite** [microsoftgraph/microsoft-graph-docs-contrib#8728]
The table at the top of the page links to a Client Credientals Provider section in the document, but that section does not seem to exist at the moment.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4537f77e-a8e8-e3f1-9cc4-2fd930db7ada
* Version Independent ID: 46396fa2-f7e2-322e-5e76-f9e2d17d1b48
* Content: [Choose a Microsoft Graph authentication provider - Microsoft Graph](https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=csharp)
* Content Source: [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/sdks/choose-authentication-providers.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Thanks
