### ISSUE TITLE
Access to OData is disabled - What specific policy is needed?

### ISSUE THREAD

**Issue by GauravES** [microsoftgraph/microsoft-graph-docs-contrib#8731]
[Enter feedback here]

Docs on this page say that if "Access to OData is disabled."  
If the Microsoft Graph API calls from your app return this error, work with the Exchange Online administrator for the organization to ensure that your app has permission to access the mailbox resource.

Can you please clarify exactly what permissions are needed?

Scenario:   Use an App to send notifications emails with sender set as donotreply@customer.com.  This mailbox is a sharedmailbox.
We have granted the App the mail permissions.
We created a group and applied a policy such as shown in example (New-ApplicationAccessPolicy -AppId e7e4dbfc-046f-4074-9b3b-2ae8f144f59b -PolicyScopeGroupId EvenUsers@contoso.com -AccessRight RestrictAccess -Description "Restrict this app to members of distribution group EvenUsers."

Are there specific considerations for shared mailboxes that are different than those for regular users?

Additionally,  is it required for the sender address to be a regular mailbox or shared mailbox?  We just want an alias on which we do not wish to receive replies. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca1eed2-d0ca-11de-4f25-f09865605a0f
* Version Independent ID: 9fd423e0-86e4-b7e4-9249-1bacb51e81ad
* Content: [Limiting application permissions to specific Exchange Online mailboxes - Microsoft Graph](https://learn.microsoft.com/en-us/graph/auth-limit-mailbox-access)
* Content Source: [concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/auth-limit-mailbox-access.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @SuryaLashmiS
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by gauchj** [comment]
If your group is really a distribution group, that might be the issue. Some sources say that a mail enabled security group is required.
