### ISSUE TITLE
Missing property for language

### ISSUE THREAD

**Issue by jlxq0** [microsoftgraph/microsoft-graph-docs-contrib#8737]
How can I get the language of a page in an environment with multiple site languages?

(I'm aware that this might not only be missing in the documentation but in the actual result – happy to have the issue moved to the correct place.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54e3e5eb-7666-72ba-b2f4-7db35d292159
* Version Independent ID: 5240b940-e117-278e-7a05-682916369b92
* Content: [sitePage resource type - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/sitepage?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/sitepage.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/resources/sitepage.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @sangle7
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by divyachapan** [comment]
@jlxq0 : Right now the language construct is not part of the page data model. This is in our backlog. When we support getting the  page language, we also want to support setting page language - in line with modern multilingual page publishing set up.

We are actively working on getting to GA (V1.0) with the current Pages API beta experience. Appreciate your input for our next set of work! Stay tuned.
