### ISSUE TITLE
question

### ISSUE THREAD

**Issue by muhammadhassanzadeh** [microsoftgraph/microsoft-graph-docs-contrib#8740]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e380713-8a99-fca5-7a98-4096bcab9c57
* Version Independent ID: 088ac63e-886e-71f2-bc9b-36f25f93305a
* Content: [Create a new entry in a SharePoint list - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/listitem-create?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/listitem-create.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/listitem-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by muhammadhassanzadeh** [comment]
how can I add a new row to hyperlinkorpicture column
I use URL and description 
using graph Api and endpoint 
but it keeps giving error 
i have tried to change column formatting using patch but that doesn't work either

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
