### ISSUE TITLE
 microsoft-graph-docs-contrib

### ISSUE THREAD

**Issue by yueyuecompany23** [microsoftgraph/microsoft-graph-docs-contrib#8746]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e64b996c-9981-08f0-055a-811e58fc6018
* Version Independent ID: 527fca4c-6331-febc-12e9-e5bd02c70fa2
* Content: [Get started with Microsoft Graph Toolkit - Microsoft Graph](https://learn.microsoft.com/en-us/graph/toolkit/get-started/overview?tabs=html)
* Content Source: [concepts/toolkit/get-started/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/toolkit/get-started/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @sebastienlevert
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sebastienlevert** [comment]
@yueyuecompany23 can you help me understand the feedback? Or maybe this wasn't meant to be an issue? Thanks!

**Comment by sebastienlevert** [comment]
Closing as no feedback from author.
