### ISSUE TITLE
Wrong method used in Python SDK examples when getting planner plan by plan id

### ISSUE THREAD

**Issue by lmitlaender** [microsoftgraph/microsoft-graph-docs-contrib#8748]
In the below documentation page "by_plan_id" is used as the method to get a planner plan by plan id.
However this method doesn't exist. The proper method should be using "by_planner_plan_id".

So the code example should be changed from
```
# THE PYTHON SDK IS IN PREVIEW. FOR NON-PRODUCTION USE ONLY

graph_client = GraphServiceClient(request_adapter)

result = await graph_client.planner.plans.by_plan_id('plannerPlan-id').buckets.get()
```
To:
```
# THE PYTHON SDK IS IN PREVIEW. FOR NON-PRODUCTION USE ONLY

graph_client = GraphServiceClient(request_adapter)


result = await graph_client.planner.plans.by_planner_plan_id('plannerPlan-id').buckets.get()
```
Instead.

If I read the contribution guidelines correctly these examples are auto generated (python wasn't explicitly mentioned but I assume python is included), so I haven't changed it myself.
I assume the same mistake might be happening in other auto generated samples using this method.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41fcd104-c491-d371-6417-bb46c9445d7c
* Version Independent ID: 778d4ad7-fb16-660c-f7b8-dea16652f42f
* Content: [List buckets - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/plannerplan-list-buckets?view=graph-rest-1.0&tabs=python)
* Content Source: [api-reference/v1.0/api/plannerplan-list-buckets.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/plannerplan-list-buckets.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed now. Thanks.
