### ISSUE TITLE
Download does not work

### ISSUE THREAD

**Issue by Swil** [microsoftgraph/microsoft-graph-docs-contrib#875]
The endpoint  /me/drive/items/{item-id}/content does not result in a 302 when submitted from the PHP SDK. Instead a status 200 is returned, which does not include a downloadUrl. In order to download the file content I had to use /me/drive/items/{item-id} to get the DriveItem including the property @microsoft.graph.downloadUrl and then use curl to get the contents of the file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01fa814a-c3b6-d48a-b724-a63e948bbffd
* Version Independent ID: f417cf48-5780-ebf4-1470-1bf0855d62c1
* Content: [Download a file - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-get-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
