### ISSUE TITLE
GitHub Link 404

### ISSUE THREAD

**Issue by adamfowlerit** [microsoftgraph/microsoft-graph-docs-contrib#8751]
Hi,
The link https://github.com/OfficeDev/microsoft-graph-docs/issues against the GitHub linked word, links to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28f291cb-b55b-4b55-c42a-cec61e5c4384
* Version Independent ID: afc8208d-990b-098f-0508-fcd5745d35e6
* Content: [Microsoft Graph REST API beta endpoint reference - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-beta&preserve-view=true)
* Content Source: [api-reference/beta/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/overview.md)
* Product: **non-product-specific**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this seems to be fixed now. Thanks.
