### ISSUE TITLE
not escaping quotations in "java"

### ISSUE THREAD

**Issue by hughobrienikea** [microsoftgraph/microsoft-graph-docs-contrib#8758]
In the java code you need to replace the line of code

definitionList.add("{"TokenLifetimePolicy":{"Version":1,"AccessTokenLifetime":"8:00:00"}}"); 

with 

definitionList.add("{\"TokenLifetimePolicy\":{\"Version\":1,\"AccessTokenLifetime\":\"8:00:00\"}}");

because you are not escaping the quotation marks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6906bc8-5a61-59cb-9489-6d08791f3995
* Version Independent ID: e3f234c4-34d5-4e7f-8cf6-a79f22852295
* Content: [Create tokenLifetimePolicy - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/tokenlifetimepolicy-post-tokenlifetimepolicies?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/tokenlifetimepolicy-post-tokenlifetimepolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/tokenlifetimepolicy-post-tokenlifetimepolicies.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @lujiangfeng666
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by hughobrienikea** [comment]
THere is also a problem with teh formatting of THIS web page to enter the "Problem."

THe bottom line is this "the java code does not work", it is incorrect because you are not escaping the quotation marks. I.e. 66 and 99 quotation marks. You need to have a back slash i.e. a     \    before each quotation mark.

**Comment by FaithOmbongi** [comment]
Hi @ramsessanchez - I no longer find your alias to reassign this issue to you. Can you try to join the [Graph docs contributors team](https://repos.opensource.microsoft.com/MicrosoftGraph/teams/graph-docs-contributors) to resolve the issue? Thanks.

**Comment by maisarissi** [comment]
Hello. Thanks for raising this issue.

The code snippets has been updated based on the new [Microsoft Graph Java v6 version](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v6.1.0) and it has now \ before each quotation mark.
You can also check more info about the new version in the [v6 announcement blog post](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/).
