### ISSUE TITLE
Permission is missing for appliedConditionalAccessPolicies attribute

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs-contrib#8761]
The signIn event has a property called appliedConditionalAccessPolicies.  In order to read this particular field, you would also need Policy.Read.All permisison otherwise it will return null for this field.  The documentation for this only mentions AuditLog.Read.All and Directory.Read.All.  Need to add a note for the addtional permission for that particular property

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61cf8069-b779-ea2a-c02a-c8efd2e18019
* Version Independent ID: 9a912f06-6ffd-d5c9-de30-66c8fff1d578
* Content: [signIn resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/signin.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @egreenberg14
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @bachoang for raising this issue. And yes, you're right. Please see [the List signIns article: Viewing applied conditional access (CA) policies in sign-ins](https://learn.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http#viewing-applied-conditional-access-ca-policies-in-sign-ins) for more details on this.
