### ISSUE TITLE
Minumum allowed time for the lifetime (tested in java) is 10 minutes. WHy is this not docuemnted ?

### ISSUE THREAD

**Issue by hughobrienikea** [microsoftgraph/microsoft-graph-docs-contrib#8765]
Minumum allowed time for the lifetime (tested in java) is 10 minutes. WHy is this not docuemnted ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6906bc8-5a61-59cb-9489-6d08791f3995
* Version Independent ID: e3f234c4-34d5-4e7f-8cf6-a79f22852295
* Content: [Create tokenLifetimePolicy - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/tokenlifetimepolicy-post-tokenlifetimepolicies?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/tokenlifetimepolicy-post-tokenlifetimepolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/tokenlifetimepolicy-post-tokenlifetimepolicies.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @lujiangfeng666
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @hughobrienikea for raising this issue. Please see the [Properties of a token lifetime policy definition](https://learn.microsoft.com/en-us/graph/api/resources/tokenlifetimepolicy?view=graph-rest-1.0#properties-of-a-token-lifetime-policy-definition) section in the main resource article that indicates this information.
