### ISSUE TITLE
Advanced Query EndsWith: PowerShell example is not rendered correctly.

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/microsoft-graph-docs-contrib#8766]
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/15258962/12fd99ad-154f-4a2c-99d3-12592764343c)

Update: It seems to be an issue translating the URL encoding and affects all SDKs. We can't change the example to `https://graph.microsoft.com/beta/users?$filter=endsWith(userPrincipalName,'#EXT#@microsoft.onmicrosoft.com')` because 1) the query won't work if the # character isn't encoded (silent fail) 2) we recommend the # character be encoded in URLs. See [Encoding query parameters](https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http#encoding-query-parameters).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36cbb5db-1ff4-a7b9-819a-4efb704007ce
* Version Independent ID: 7e6f3bbd-f364-0ff8-2e14-977860bd7ff9
* Content: [Advanced query capabilities on Microsoft Entra ID objects - Microsoft Graph](https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http)
* Content Source: [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/aad-advanced-queries.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by jasonjoh** [comment]
Thanks for reporting @JustinGrote. Reported this in the snippet generation repo, closing here.
