### ISSUE TITLE
Accesing Special AppRoot folder on OneDrive Business account requires Files.ReadWrite.All permission

### ISSUE THREAD

**Issue by NLLAPPS** [microsoftgraph/microsoft-graph-docs-contrib#877]
As per title, I have implemented OneDrvie access in my app with MsGraph Java SDK.
I request "Files.ReadWrite.AppFolder", "User.Read", "offline_access", "openid" and only use special app folder for access.

It works fine on personal OneDrive accounts. Unfortunately, I get access denied error if I test it on OneDrive Business accounts. I have to request "Files.ReadWrite.All" permisison in order to be able to access to special app folder.

**Comment by Digipom** [comment]
@PaoloPia I'm not the OP, but we still receive some complaints about this one from time to time.

**Comment by ShaneOss** [comment]
Wow, we're almost in 2024 and still no documented solution. I had one years ago and integrated it into MS-TL, which is on the Microsoft Store. I am considering open sourcing it for the sake of it. Just haven't had the time to dedicate to it of late.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your comprehension.

**Comment by PaoloPia** [comment]
Hi @NLLAPPS, yes you can try with issues list of the Java SDK, if you like. I was suggesting the forum so that you can get support from the whole community, but up to you! Thanks!
