### ISSUE TITLE
Get userRegistrationDetails - Authentication_RequestFromNonPremiumTenantOrB2CTenant

### ISSUE THREAD

**Issue by hootyjeremy** [microsoftgraph/microsoft-graph-docs-contrib#8777]
I have been needing to find a way in PowerShell (using the Graph API SDK) to determine if users in my different tenants are registered with MFA. I had been using the older MsolService and AzureAD endpoints but I'm moving to Graph and I found this method, **Get-MgReportAuthenticationMethodUserRegistrationDetail**, which will give me **isMfaRegistered** which is exactly what I need but it errors out with a **Authentication_RequestFromNonPremiumTenantOrB2CTenant**.

The document makes no mention of the command needing premium access so it was a disappointment when I finally found the tool I needed but I won't be able to use because most of my tenants are not premium of B2C.

Could the documentation be very clear about what subscription levels are needed to use the commands/requests?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c4d243a-16a8-59d6-d55c-253e7e21889d
* Version Independent ID: a71a13ad-87e1-5bc3-4ef2-af924c8b84ae
* Content: [Get userRegistrationDetails - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/userregistrationdetails-get?view=graph-rest-1.0&tabs=powershell)
* Content Source: [api-reference/v1.0/api/userregistrationdetails-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/userregistrationdetails-get.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @kvenkit
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
My apologies @hootyjeremy for dropping the ball on this issue. I've raised a PR to add a link for license information for the reporting APIs.
