### ISSUE TITLE
Error when trying to create a folder named "forms"

### ISSUE THREAD

**Issue by JSilverdrake** [microsoftgraph/microsoft-graph-docs-contrib#8779]
Ran into a problem when trying to create a subfolder using this code in PowerShell:

    $authHeaders = "<my authentication headers>"
    $DriveId = "<my drive id>"
    $path ="/General/Test"
    $folderName = "forms"
    $Uri = [uri]::EscapeUriString("https://graph.microsoft.com/v1.0/drives/$DriveId/root:${path}:/children")
    $Form = @{
        'name' = $folderName
        'folder' = @{}
        '@microsoft.graph.conflictBehavior' = "rename"
    }
    $Result = Invoke-WebRequest -Uri $Uri -Method Post -Headers $authHeaders -ContentType 'application/json' -Body (ConvertTo-Json $Form)

This code gives me the error:
"code":"invalidRequest","message":"Name is reserved for list forms folder."
Any other foldername works fine with this code.

According to the documentation at https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa the name is not allowed in the root but I am trying to create it as a subfolder.

Creating the folder manually in the same location in OneDrive works fine.

Regards
Joakim

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9069032a-3cb9-37df-9ef5-3901aad572e0
* Version Independent ID: 37fce8f3-cd7c-2450-b1ee-95956653d179
* Content: [Create a new folder - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-post-children.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/driveitem-post-children.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
