### ISSUE TITLE
Describe which templates are supported in list

### ISSUE THREAD

**Issue by zamazan4ik** [microsoftgraph/microsoft-graph-docs-contrib#878]
Please describe all templates which are suuported for "template" field in "list" entity. Now you describe only part of them and for end user (e.g. for me) isn't clear which templates exactly are supported.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc5a9ce-652e-1dc5-c3a8-8b9e342efafb
* Version Independent ID: 04c8824e-5e0c-0086-a972-97f3a890ab47
* Content: [List - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
