### ISSUE TITLE
REQUESTS ARE NOT EXAMPLES - THEY ARE SYNTAX

### ISSUE THREAD

**Issue by anwarmahmood1** [microsoftgraph/microsoft-graph-docs-contrib#8781]
syntax:
Get-MgSiteListItem -SiteId $siteId -ListId $listId -ExpandProperty "fields(select=Name,Color,Quantity)"

example:

```
$ContosoIceCreamSiteID = '[please provide an example; either a GUID, or how to get the GUID]'
$ContosoIceCreamSiteFlavorsID = '[please provide an example; either a GUID, or how to get the GUID]'

Get-MgSiteListItem -SiteId $ContosoIceCreamSiteID -ListId $ContosoIceCreamFlavorsID -ExpandProperty "fields(select=name,allergens,vegan)"
```

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2524650e-06e7-dc8c-b2ae-0c2fbffdb541
* Version Independent ID: 3eb41d73-2b60-1459-e921-20403004655c
* Content: [Retrieve items from a SharePoint list - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/listitem-list?view=graph-rest-1.0&tabs=powershell)
* Content Source: [api-reference/v1.0/api/listitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/listitem-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
