### ISSUE TITLE
Wrong example for filtering users by authentication methods

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#8786]
The [example](https://learn.microsoft.com/en-us/graph/api/authenticationmethodsroot-list-userregistrationdetails?view=graph-rest-1.0&tabs=http#optional-query-parameters) shows that you can filter user registration details by `methodsRegistered` which is a collection, so the query in example will never work

    /reports/userRegistrationDetails?$filter=methodsRegistered eq 'email'

The correct example should be with `any`

    /reports/userRegistrationDetails?$filter=methodsRegistered/any(x:x eq 'email')

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21801e97-c4a8-f381-c80a-1f2fd1da7de6
* Version Independent ID: e79dd7b7-4e27-06c6-744d-5b3b8aac39df
* Content: [List userRegistrationDetails - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/authenticationmethodsroot-list-userregistrationdetails?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/authenticationmethodsroot-list-userregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/authenticationmethodsroot-list-userregistrationdetails.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @kvenkit
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @MartinM85 for pointing out this error. I've raised a PR to fix the example.
