### ISSUE TITLE
Remove link to PPE from prod docs

### ISSUE THREAD

**Issue by madansr7** [microsoftgraph/microsoft-graph-docs-contrib#8792]
The following page has a reference to PPE in the request/response example. 

https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/samlorwsfedexternaldomainfederation-list-domains.md

**Comment by madansr7** [comment]
@FaithOmbongi FYI

**Comment by FaithOmbongi** [comment]
Thank you @madansr7. I've raised a PR to fix the issue.
