### ISSUE TITLE
Incomplete documentaion or possibly incorrect behaviour for delta queries

### ISSUE THREAD

**Issue by meain** [microsoftgraph/microsoft-graph-docs-contrib#8794]
Graph API seems to return unexpected response if a folder was deleted a recreated mid way through fetching delta pages. I am not sure if this is the indented behaviour and we are just missing documentation or the behaviour itself is incorrect and so filling it here.

Assuming we are paginating delta responses, if the user deletes and recreates a folder with the same name, we never get a folder deletion entry in delta, but just the new folder(updated id).

**Repro**

Assuming folder structure:
- root
  - item0
  - folder (id1)
    - item1
    - item2

Steps:
- Start delta query (first page gets us root and item0)
- Second delta page (root, folder[id1], item1)
- ... User deletes and recreates folder and files in it ...
- Third page (folder[id2])

At this point, if the user deletes and recreates folder with the same, I would either expect the delta API to either return nothing more or just a delete or a delete plus new entries, but it just returns the new entries (ie fodler[id2]) without a delete entry in between.

*The API returns just a deleted entry if we started the delta off of a previous delta link.*

Let me know if you need any more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5785f90e-b37c-c5a5-ddbc-7170307980c9
* Version Independent ID: d8b7729e-38c4-5562-7359-5e926f8d7ae4
* Content: [driveItem: delta - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http#scanning-permissions-hierarchies)
* Content Source: [api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/driveitem-delta.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
