### ISSUE TITLE
Links doesn't work in word file preview

### ISSUE THREAD

**Issue by Romjol** [microsoftgraph/microsoft-graph-docs-contrib#8795]
Hello,

After have had a preview url for a word file, I put my url in iframe. 
If my word file content has a link to somewhere in the same document or on internet web page, this link does not work in previewing.
If I open this same file in O365, this link work. 
My word file is storaged on SharePoint Online
If I try with different file, I have the same issue.

Could you help me please ?

Romain

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 399338a3-4d90-4c9b-b3e6-a7aaf970eec5
* Version Independent ID: 22fb7721-70f4-92af-db16-42967cd0043d
* Content: [driveItem: preview - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-preview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/driveitem-preview.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
