### ISSUE TITLE
Please add/modify a note to clarify configurableTab requirement

### ISSUE THREAD

**Issue by marianocalero** [microsoftgraph/microsoft-graph-docs-contrib#8796]
Right now, this doc just states:

> Adds (pins) a [tab](https://learn.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-1.0) to the specified [channel](https://learn.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0) within a [team](https://learn.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0). The corresponding app must already be [installed in the team](https://learn.microsoft.com/en-us/graph/api/team-list-installedapps?view=graph-rest-1.0).

Updated to reflect configurableTab requirement for Teams App Manifest:  

> Adds (pins) a [tab](https://learn.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-1.0) to the specified [channel](https://learn.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0) within a [team](https://learn.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0). The corresponding app must already be [installed in the team](https://learn.microsoft.com/en-us/graph/api/team-list-installedapps?view=graph-rest-1.0) and must have a configurableTabs section defined in its manifest.

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/68557521/2d896786-84c2-4f4b-be72-c357f3f03665)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: feddb622-23f9-430a-1235-c72e614f455b
* Version Independent ID: 349d6f59-c24d-94e7-ca5e-7b660d8a5345
* Content: [Add tab to channel - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/channel-post-tabs?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/channel-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/channel-post-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to update this in the documentation?

**Comment by v-sdhakshina** [comment]
Updated the documents through PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/23101

**Comment by Meghana-MSFT** [comment]
Document has been updated, we are closing this issue. Please reach out to us if you have any queries.
