### ISSUE TITLE
Permissions require some clarification

### ISSUE THREAD

**Issue by efuertesvalencia** [microsoftgraph/microsoft-graph-docs-contrib#880]
As per https://docs.microsoft.com/en-us/graph/permissions-reference#permission-scenarios the Group.Read.All will give read access to all documents in all Office 365 groups. Having granted Group.Read.All application permissions to a registered app will eventually give you read access to all their files and app will be able to use: GET /groups/{group-id}/drive/items/{item-id}/children without any issues. Should this page be updated to include that info?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18dfd099-0d73-55e4-56ec-d9129b83aa07
* Version Independent ID: 5705a946-2c25-0d04-a297-01ccb21d7284
* Content: [List the contents of a folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-list-children.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-list-children.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
