### ISSUE TITLE
Add app roles (Optional) step fails with "Property appRoles on the service principal does not match the application object"

### ISSUE THREAD

**Issue by LijuV-MSFT** [microsoftgraph/microsoft-graph-docs-contrib#8801]
```
Import-Module Microsoft.Graph.Applications

$params = @{
	appRoles = @(
		@{
			allowedMemberTypes = @(
				"User"
			)
			displayName = "User"
			id = "8774f594-1d59-4279-b9d9-59ef09a23530"
			isEnabled = $true
			description = "User"
			value = $null
			origin = "Application"
		}
		@{
			allowedMemberTypes = @(
				"User"
			)
			displayName = "msiam_access"
			id = "e7f1a7f3-9eda-48e0-9963-bd67bf531afd"
			isEnabled = $true
			description = "msiam_access"
			value = $null
			origin = "Application"
		}
		@{
			allowedMemberTypes = @(
				"User"
			)
			description = "Admin,WAAD"
			displayName = "Admin,WAAD"
			id = "3a84e31e-bffa-470f-b9e6-754a61e4dc63"
			isEnabled = $true
			value = "arn:aws:iam::212743507312:role/accountname-aws-admin,arn:aws:iam::212743507312:saml-provider/WAAD"
		}
		@{
			allowedMemberTypes = @(
				"User"
			)
			description = "Finance,WAAD"
			displayName = "Finance,WAAD"
			id = "7a960000-ded3-455b-8c04-4f2ace00319b"
			isEnabled = $true
			value = "arn:aws:iam::212743507312:role/accountname-aws-finance,arn:aws:iam::212743507312:saml-provider/WAAD"
		}
	)
}

Update-MgServicePrincipal -ServicePrincipalId $servicePrincipalId -BodyParameter $params
```

This steps fails with 

```
Update-MgServicePrincipal : Property appRoles on the service principal does not match the application object.
At line:1 char:1
+ Update-MgServicePrincipal -ServicePrincipalId $servicePrincipalId -Bo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ServicePrinci...vicePrincipal }:<>f__AnonymousType2`2) [Update-MgSe
   rvicePrincipal_Update1], RestException`1
    + FullyQualifiedErrorId : Request_BadRequest,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgServicePrincipal_Update1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9067ae9-89d0-5854-7327-856d930e7712
* Version Independent ID: e0ed6a1b-34bc-55a2-b4ca-61fe3f8ca367
* Content: [Use Microsoft Graph APIs to configure SAML-based single sign-on - Microsoft Graph](https://learn.microsoft.com/en-us/graph/application-saml-sso-configure-api?tabs=powershell%2Cpowershell-script#create-a-claims-mapping-policy)
* Content Source: [concepts/application-saml-sso-configure-api.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/application-saml-sso-configure-api.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Hi @LijuV-MSFT - Unfortunately, this forum is only for documentation-related issues but [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) is the best forum to answer this functionality question. I recommend that you raise this question there. You may be requested for a request ID for investigation. Closing this issue here.
