### ISSUE TITLE
Who can be a member of an administrative unit

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#8805]
The doc says that only user, group, or device can be added as a member of an administrative unit.

I've tried to add an application and it was added. I'm able to list the app in the members.

Are there any unexpected consequences when an application is added to an administrative unit?

Probably service principal and organization contact can be added to an administrative unit.

Could you please update the doc and mention that also application or other resources which can be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7da5a264-1674-dc75-0fc9-9af6ce2d7f8a
* Version Independent ID: ed0f3e90-2388-aaf8-9a1c-6274826ec56e
* Content: [Add a member - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/administrativeunit-post-members.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @DougKirschner
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by DMoenks** [comment]
Maybe the primary documentation on [administrative units](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/administrative-units#currently-supported-scenarios) provides clarity, as it lists the supported scenarios and the options available with administrative units. As those seem to be limited to users, groups and devices at the moment, stating that only users, groups and devices can be added might be untrue on the one hand but intentionally on the other, keeping support in mind 🤔

**Comment by FaithOmbongi** [comment]
Thank you @MartinM85 for raising this issue. Currently, only users, groups, and devices as members are officially supported. Please don't take any production dependency on any other behavior.
