### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by gi-joe-moto** [microsoftgraph/microsoft-graph-docs-contrib#881]
This page should document how to put data into "typed" fields like Hyperlink.  Otherwise we have to guess how to format the request via trail and error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1af3c661-dca5-dc61-0708-be97b7223d2d
* Version Independent ID: 7a8b8bfc-6a52-debf-df7d-fca6046fe89e
* Content: [FieldValueSet - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/fieldvalueset?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/fieldvalueset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/fieldvalueset.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
