### ISSUE TITLE
Broken Link for the Build your own connector

### ISSUE THREAD

**Issue by arjunumenon** [microsoftgraph/microsoft-graph-docs-contrib#8810]
When you click on the link **Build your own connectors** link in the section [Include custom external data in search experience](https://learn.microsoft.com/en-us/graph/search-concept-overview#include-custom-external-data-in-search-experience), we are getting a broken link. 

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/10369964/8310e9fd-a009-4f60-a1dd-032194870fa2)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a854a342-c67a-d53f-6b95-3d7366ac3f0e
* Version Independent ID: 81581c12-a7a8-706f-ec0d-e2471baef2ca
* Content: [Microsoft Search API in Microsoft Graph overview - Microsoft Graph](https://learn.microsoft.com/en-us/graph/search-concept-overview)
* Content Source: [concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/search-concept-overview.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @snlraju-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this has been fixed. Thanks.
