### ISSUE TITLE
replies@odata.nextLink and replies@odata.count are missing from the result of the List Channel Messages request

### ISSUE THREAD

**Issue by a2o2juzi** [microsoftgraph/microsoft-graph-docs-contrib#8819]
[Enter feedback here]

Hi team,

We call the list channel messages API and get channel message delta API, and use the '$expand=replies' query parameter to obtain messages and replies in the channel.

The channel I tested contains some main messages with 2000 replies, but the results obtained through the API are not complete.

Some of the main messages elements (with 2000 replies) contain 1000 replies, replies@odata.count And replies@odata.nextLink ; 
Some main messages elements (with 2000 replies) contain 1000 replies, and replies@odata.nextLink But lacking replies@odata.count ;
Some main messages elements (with 2000 replies) only contain 1000 replies and are missing **replies@odata.nextLink** And replies@odata.count

Due to the attribute that should have been returned‘ replies@odata.nextLink ’Missing, some message replies will be missed.

API
GET https://graph.microsoft.com/v1.0/teams/{teamId}/channels/{channelId}/messages?$top=50&$expand=replies
GET https://graph.microsoft.com/v1.0/teams/{teamId}/channels/{channelId}/messages/delta?$top=50&$expand=replies

Response Headers:
Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 6aa8c4a6-640f-4cdc-a7c1-1e8753b342f2
client-request-id: 6aa8c4a6-640f-4cdc-a7c1-1e8753b342f2
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"E","Ring":"5","ScaleUnit":"004","RoleInstance":"BL02EPF00009A94"}}
OData-Version: 4.0
Date: Wed, 15 Nov 2023 09:21:16 GMT

Response Body:
[Uploading response.json…]()

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f76da6b3-3840-afe5-2c53-dc256e678a8d
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@a2o2juzi - Engineering team ran multiple tests with replychain with 1000+ replies, still seeing odata properties as expected. Could you please let us know if you have a consistent repro of this issue?

**Comment by a2o2juzi** [comment]
@Meghana-MSFT I'm not sure if only one message in your Engineering team's test data has 1000+replies. 
 I can still reproduce this problem. The test data in my channel is as follows:
 Total message count: 19
- Message with 2000+ replies      count: 4 (1 message normal,  3 message lack  **replies@odata.count** And **replies@odata.nextLink**)
- Message no  replies                   count: 10
- Message with 1 reply                 count: 4   (2 meesage  lack  **replies@odata.count** )
- Message with 2 reply                 count: 1



![p1](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/24663348/744807ca-c2b7-4f45-99db-2c1233754e9a)
 
GET https://graph.microsoft.com/v1.0/teams/32c143ab-0a46-467f-b2ef-fe004b1437ff/channels/19:dsorTbXmcac0DebYwKag5vcirBgAx23EgNkz8nNGQPc1@thread.tacv2/messages?$Top=50&$expand=replies
200
3.67 s
Network
Request Headers
Prefer: include-unknown-enum-members
Authorization: Bearer ...
User-Agent: PostmanRuntime/7.35.0
Accept: */*
Cache-Control: no-cache
Postman-Token: c22cfd8d-9796-49c0-87b5-e016781de2fa
Host: graph.microsoft.com
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Response Headers
Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: c8aa47ae-a4ea-4277-b3de-3d0e1ff81b11
client-request-id: c8aa47ae-a4ea-4277-b3de-3d0e1ff81b11
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":"MN1PEPF0000F500"}}
OData-Version: 4.0
Date: Mon, 27 Nov 2023 06:17:00 GMT
Response Body
[response (1).json](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/files/13470741/response.1.json)

**Comment by ChetanSharma-msft** [comment]
Hello @a2o2juzi - Engineering team is able to repro it and looking into it.
We will let you know if there is any update.
