### ISSUE TITLE
create list in o365 has a different syntax

### ISSUE THREAD

**Issue by ofunk** [microsoftgraph/microsoft-graph-docs-contrib#882]
creating a list on a site is using the "sites" value.
if you create a list in a 0365 group or team it is no longer sites - but groups value + sites after the groupID like
https://graph.microsoft.com/beta/groups/{groupID]/sites/roo/lists

and having "just" ---roo--- instead of roots is although helpful to see in documentation. this is different from sites in syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81819094-9573-5f8d-90b2-a9a6cf5bc894
* Version Independent ID: 722992d5-18ee-5499-b2a6-440ac705d40a
* Content: [Create a SharePoint List - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/list-create?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/list-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/list-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
