### ISSUE TITLE
Confusing Example 3 : Create a role assignment with application scope

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#8821]
The response for the third example

```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#roleManagement/directory/roleAssignments/$entity",
    "@odata.id": "https://graph.microsoft.com/v2/22350cac-d84b-466b-8c2c-f9326746709a/roleAssignments/kl2Jm9Msx0SdAqasLV6lw516k2sxx1tGqEQtW1NowWEQEx5mdr2VR4mnjzyPhVv8-1",
    "id": "kl2Jm9Msx0SdAqasLV6lw516k2sxx1tGqEQtW1NowWEQEx5mdr2VR4mnjzyPhVv8-1",
    "principalId": "6b937a9d-c731-465b-a844-2d5b5368c161",
    "principalOrganizationId": "22350cac-d84b-466b-8c2c-f9326746709a",
    "resourceScope": "/661e1310-bd76-4795-89a7-8f3c8f855bfc",
    "directoryScopeId": "/661e1310-bd76-4795-89a7-8f3c8f855bfc",
    "roleDefinitionId": "9b895d92-2cd3-44c7-9d02-a6ac2d5ea5c3"
}
```

has confusing value for
- `@odata.context` - contains `beta`
- `@odata.id` - it's missing in other examples in the response, also value `v2` is strange
- `principalOrganizationId` - no such property exists on [unifiedRoleAssignment](https://learn.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0) resource
- `resourceScope` - no such property exists on [unifiedRoleAssignment](https://learn.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0) resource

Could you confirm that `"directoryScopeId": "/661e1310-bd76-4795-89a7-8f3c8f855bfc"` in the request is correct? Based on the example 2 where the `directoryScopeId` for an administrative unit is `/administrativeUnits/5d107bba-d8e2-4e13-b6ae-884be90e5d1a`, I would expect the `directoryScopeId` for an application like `/applications/661e1310-bd76-4795-89a7-8f3c8f855bfc` not `/661e1310-bd76-4795-89a7-8f3c8f855bfc`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0bf7715-a6da-0edd-67ec-f21432a18c52
* Version Independent ID: 2ab9b38e-ac79-9678-38aa-123280514b0d
* Content: [Create unifiedRoleAssignment - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/rbacapplication-post-roleassignments.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @DougKirschner
* Microsoft Alias: **MSGraphDocsVteam**](https://learn.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0)](https://learn.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0)

**Comment by FaithOmbongi** [comment]
Thank you @MartinM85 for raising this issue.

The first three issues you've caught are oversights from promoting the docs from beta to v1. I've taken an action item to clean up and correct the docs.
Let me investigate the fourth issue and get back to you.

**Comment by FaithOmbongi** [comment]
Thank you @MartinM85 for your patience. 

For this issue

> Could you confirm that `"directoryScopeId": "/661e1310-bd76-4795-89a7-8f3c8f855bfc"` in the request is correct? Based on the example 2 where the `directoryScopeId` for an administrative unit is `/administrativeUnits/5d107bba-d8e2-4e13-b6ae-884be90e5d1a`, I would expect the `directoryScopeId` for an application like `/applications/661e1310-bd76-4795-89a7-8f3c8f855bfc` not `/661e1310-bd76-4795-89a7-8f3c8f855bfc`

Yes, this is the correct syntax for an application scope. The syntax for application scope isn't prefixed with `/applications/`; instead, it has the pattern `/resourceapp-objectID`.

In the meantime, I'll work on addressing the other doc inconsistencies that you highlighted.
