### ISSUE TITLE
Missing query options example from AADR impacted resources

### ISSUE THREAD

**Issue by madansr7** [microsoftgraph/microsoft-graph-docs-contrib#8822]
The following API supports query filter parameters of $count but customers keep asking about it. 
So, it would be helpful to include an example that demonstrates how someone can get the count of impacted resources. 

https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/impactedresource-get.md

Impacted resource count query looks like 
https://graph.microsoft.com/beta/directory/recommendations/{id}/ImpactedResources/$count

**Comment by FaithOmbongi** [comment]
Thank you @madansr7 for raising this issue. And yes, you're right. `$count` is supported as a URL segment like you specified in your example. I've raised a PR to update the documentation.
