### ISSUE TITLE
Error while sending mail from drafts folder. Error Code: ErrorNonExistentMailBox

### ISSUE THREAD

**Issue by dineshR86** [microsoftgraph/microsoft-graph-docs-contrib#8823]
Getting ErrorNonExistentMailBox error when trying to send a draft message.  This is occurring randomly. When we try to send the same draft message after some time it works. Any idea what is causing this issue?

used graph api send draft message end point for sending the draft message. 

![GraphAPI-SendRequest](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/37539383/4cc6227c-218f-46d9-a453-f4e002b056cb)
<img width="332" alt="Flow-History" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/37539383/18b46d21-98c0-4785-8d0d-a208c0415499">
![GetDrafts](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/37539383/9ad38a5a-fea4-4d73-862f-3d290fa8efce)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c23caac-3e70-3e8b-5e9e-3846024104c3
* Version Independent ID: 39249e4d-3279-5012-3ad9-c137ae69fe7f
* Content: [message: send - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/message-send.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @SuryaLashmiS 
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kandharithirumalreddy** [comment]
Getting the same issue as well. Any Idea?

**Comment by kandharithirumalreddy** [comment]
any update on this issue, it's become crucial in order to send email using Graph API?

**Comment by SuryaLashmiS** [comment]
Can you please share the exact API endpoints used?

**Comment by kandharithirumalreddy** [comment]
@SuryaLashmiS 

Used below graph end point to send email
https://graph.microsoft.com/v1.0/users/{UserId}/messages/{MessageId}/send

**Comment by kandharithirumalreddy** [comment]
Hi @SuryaLashmiS 

Do you need any other information?

**Comment by kandharithirumalreddy** [comment]
Hi @SuryaLashmiS 

Any update on this issue?

**Comment by kandharithirumalreddy** [comment]
Hi @SuryaLashmiS 

It's occurring randomly not every time. If we send the same draft message after 10 or 20 mins then will get the success.

 Endpoint ==> https://graph.microsoft.com/v1.0/users/{UserId}/messages/{MessageId}/send
 
 Passing the {MessageId} and {UserId} to the above endpoint.
 
 Tried by using power automate and SDK. It's behaving the same in both the cases.

**Comment by kandharithirumalreddy** [comment]
Hi @SuryaLashmiS

Any update on this issue?
