### ISSUE TITLE
How to create an itemAttachment which is a contact or message?

### ISSUE THREAD

**Issue by julieting27** [microsoftgraph/microsoft-graph-docs-contrib#883]
According to the Graph API document [1], an itemAttachment is a contact, event, or message that's attached to another event, message, or post.

However, this document [2] only shows the way to attach an event with another event, but miss the example when itemAttachment is a contact, message, or message with a fileAttachment.

How to create an itemAttachment which is a contact, message or message with a fileAttachment?

Ref. 
[1] https://docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0
[2] https://docs.microsoft.com/en-us/graph/api/event-post-attachments?view=graph-rest-1.0&tabs=http#example-item-attachment

**Comment by maisarissi** [comment]
Hello :)

You can see the [attachment resource documentation](https://learn.microsoft.com/en-us/graph/api/resources/attachment?view=graph-rest-1.0#methods) to find all methods you can use to add an attachment, such as [adding an attachement to an existing event](https://learn.microsoft.com/en-us/graph/api/event-post-attachments?view=graph-rest-1.0&tabs=http) and much more.
