### ISSUE TITLE
Does metering apply for Recording and Transcripts API when using delegated tokens?

### ISSUE THREAD

**Issue by GauravES** [microsoftgraph/microsoft-graph-docs-contrib#8833]
[Enter feedback here]

Does metering apply for Recording and Transcripts API when using delegated tokens?  We have an app that will retrieve the transcript from a meeting created by User A  using their delegated token.   Will the cost apply here for User A to download the transcript or recording via the Graph API?

The page mentions pricing for App - not clear if that extends to App Permissions or to Delegated Permissions as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01f880b9-2394-f540-9b06-bcddbe40bfa8
* Version Independent ID: 22de9e03-e917-bcc6-abd7-ebfb3a0cdec8
* Content: [Payment models and licensing requirements for Microsoft Teams APIs - Microsoft Graph](https://learn.microsoft.com/en-us/graph/teams-licenses#payment-requirements-for-meeting-apis)
* Content Source: [concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/teams-licenses.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
@GauravES - Yes, the APIs to fetch meeting transcript and recording content are indeed metered APIs. This means that there is a cost associated with their usage, regardless of whether you're using delegated tokens or not. The cost applies to the usage of the API itself, not to the user who created the meeting or to the specific token used.

**Comment by GauravES** [comment]
Ok, good to know.
Feedback to your pricing team:  A recording that is free to view or download or available to be shared at no cost from the creator's OneDrive should not cost _**via a delegated token**_ for the same user via an API.

**Comment by Prasad-MSFT** [comment]
@GauravES - We have communicated the feedback to concerned team. Thanks!

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
