### ISSUE TITLE
Incorrect example of Retrieve the count of deleted user objects using Microsoft Graph SDK for Java

### ISSUE THREAD

**Issue by alifruliarso** [microsoftgraph/microsoft-graph-docs-contrib#8834]
### Incorrect example 

![ScreenshotIncorrectExampleMSGraphSDKJava](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/971037/efed8a3a-684f-4392-aaf4-b16781f19d05)

## The correct example for getting deleted User
```java
UserCollectionPage user = graphServiceClient.directory().deletedItemsAsUser()
                .buildRequest(requestOptions).select("id,displayName,deletedDateTime")
                .orderBy("deletedDateTime asc").get();
```

## The correct example for getting deleted Group
```java
GroupCollectionPage group =
                graphServiceClient.directory().deletedItemsAsGroup().buildRequest().get();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ddf76efc-5ca2-e829-1604-fa858179858a
* Version Independent ID: bbf2d629-8795-3d87-76de-f147489e4942
* Content: [List deletedItems (directory objects) - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/directory-deleteditems-list.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/directory-deleteditems-list.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @maisarissi - Please help to investigate this issue. @ramsessanchez, I can't find your alias in the linked aliases so I'm unable to assign the issue to you.

**Comment by maisarissi** [comment]
The code snippet was updated based on the new [v6 version](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v6.1.0). You can check more info about the new version in the [v6 announcement blog post](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/).
