### ISSUE TITLE
Has the color changed?

### ISSUE THREAD

**Issue by cglong** [microsoftgraph/microsoft-graph-docs-contrib#884]
According to this page, the official color for OneNote is `#80397B`, but when I use modern OneNote clients (web, Mac and UWP), the color seems to instead be `#7719AA`. I just wanted to check and see if these guidelines are still accurate 🙂

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b99818-d7ac-4077-dae6-2bf687dd68b1
* Version Independent ID: 306456fa-7404-293b-162f-6fea79947442
* Content: [Branding guidelines for OneNote API developers  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/onenote-branding#feedback)
* Content Source: [concepts/onenote-branding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/onenote-branding.md)
* Product: **onenote**
* Technology: **microsoft-graph**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
@cglong, thank you for sharing your feedback. Our guidelines have not changed and the color code you mentioned is not in our docs,  feel free to download OneNote's branding guidelines [here] (https://www.microsoft.com/en-us/download/details.aspx?id=42977&134b2bb0-86c1-fe9f-d523-281faef41695=1).
