### ISSUE TITLE
broken python code

### ISSUE THREAD

**Issue by ErikApption** [microsoftgraph/microsoft-graph-docs-contrib#8840]
GetByIdsPostRequestBody does not seem to exist in the python SDK except in the generated folder but it is totally unclear how to use that. As-is the python code example is unusable

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 652f070a-a126-9add-13db-e35250b8b86c
* Version Independent ID: d256be5b-8466-385f-32a4-2d9fd9a89886
* Content: [directoryObject: getByIds - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/directoryobject-getbyids?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directoryobject-getbyids.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/directoryobject-getbyids.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks for reporting this @ErikApption. I've logged this issue against our snippet generation tool here: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1954, closing here.

The correct import for this snippet would be:

```python
from msgraph.generated.directory_objects.get_by_ids.get_by_ids_post_request_body import GetByIdsPostRequestBody
```
