### ISSUE TITLE
Download mechanism unclear

### ISSUE THREAD

**Issue by danielboteanu** [microsoftgraph/microsoft-graph-docs-contrib#8845]
There is a spelling error at step 2 where `discovery.Download.Read` should likely be `eDiscovery.Download.Read`.

Step 4 is unclear.

The description talks about "export it to your storage account" but does not point to the mechanism to achieve this.

An example of actual queries for this section would be helpful.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 436a1fd6-577d-193d-41d8-b6858e15c336
* Version Independent ID: acacb40a-ce73-200a-ea93-f1711d1c98d7
* Content: [Get caseOperation - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/security-caseoperation-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/security-caseoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/security-caseoperation-get.md)
* Product: **ediscovery**
* Technology: **microsoft-graph**
* GitHub Login: @SeunginLyu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by SeunginLyu** [comment]
hi @danielboteanu, we are working on streamlining the export / download APi documentation with more details. Thanks.
