### ISSUE TITLE
Incomplete Documentation for Conditional Access Policies' Target Applications (MicrosoftAdminPortals)

### ISSUE THREAD

**Issue by jnicholls** [microsoftgraph/microsoft-graph-docs-contrib#8848]
The Graph API documentation states that the `includeApplications` and `excludeApplications` properties of the `conditionalAccessApplications` resource type can include `Office365`, `All` (in the case of `includeApplications`), or a list of client IDs.

However, I am receiving a new undocumented value, `MicrosoftAdminPortals`. According to the KB article [Conditional Access: Target resources](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-cloud-apps) which was last updated recently on 2023-11-09, in addition to `Office 365` there is also `Microsoft Azure Management` and `Microsoft Admin Portals` application groups. I am not certain if these groups are very new to Conditional Access policies, but they are coming back in Graph API results and are not documented in the Graph API docs accordingly (neither the 1.0 nor the Beta APIs). This is a case where the API itself is inheriting data models from other products in a way that can break clients' compatibility, such as this case where my client has an algebraic sum type with the possible expected values representing a Conditional Access policy's target applications.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd3d0df8-e41b-af67-97ac-a99f2163e061
* Version Independent ID: 0a9fe363-b5d7-2eaa-8d69-186c20afc869
* Content: [conditionalAccessApplications resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/conditionalaccessapplications?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/conditionalaccessapplications.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/conditionalaccessapplications.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @lisaychuang
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @jnicholls for raising this issue. I'm investigating internally and will get back to you once I identify all the required doc updates. Thank you for your patience.

**Comment by lisaychuang** [comment]
@gregkmsft please share latest status & relevant PR for API doc updates related to Admin portals. Thanks!

**Comment by FaithOmbongi** [comment]
Closing this issue in readiness for deactivation of GitHub issues. See this post for more information https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/9146.

Tracking the internal lines for resolution.
