### ISSUE TITLE
lastUpdatedDateTime property meaning

### ISSUE THREAD

**Issue by codeX004** [microsoftgraph/microsoft-graph-docs-contrib#8849]
The property "lastUpdatedDateTime" represents in fact the last timestamp the user object itself has been updated, but not the registration details for the user, right? Would be great to have that clearly stated in the docs, as I was assuming it's the timestamp the user changed his/her registration methods. 

Is there any timestamp for that populated or do i need to parse the audit logs for the corresponding activity?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5772ab5c-c7cd-6968-fb9f-4a708f57dca6
* Version Independent ID: 7d221f54-e79e-1ef5-8d1f-a88114055ac1
* Content: [userRegistrationDetails resource type - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/userregistrationdetails?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/userregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/resources/userregistrationdetails.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @egreenberg14
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by egreenberg14** [comment]
Closing this per my last comment.
