### ISSUE TITLE
Add client upload use case to Resumable Upload with tempauthtoken

### ISSUE THREAD

**Issue by dennisameling** [microsoftgraph/microsoft-graph-docs-contrib#885]
The following is [mentioned](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#remarks) in the docs:

> Including the Authorization header when issuing the PUT call may result in a HTTP 401 Unauthorized response. The Authorization header and bearer token should only be sent when issuing the POST during the first step. It should be not be included when issueing the PUT.

The `uploadUrl` that is returned in the `POST` request looks like this:

`https://MYDOMAIN.sharepoint.com/sites/MYSITE/_api/v2.0/drive/items/MYITEM/uploadSession?guid='GUID'&path='~tmpDE_testFile.pdf'&overwrite=True&rename=False&dc=0&tempauth=eyJ0e....`

As you can see in the URL, there is a tempauth token (JSON Web Token), so anyone with this link can upload file chunks to this URL (until the URL expires). This is convenient in a scenario where the server requests an upload session/URL from Microsoft Graph, then sends this URL including its tempauth token to the client (e.g. a JavaScript front-end application) which can then upload the actual file to OneDrive. So, instead of 

`Client --> Server --> OneDrive`

the upload will be

`Client --> OneDrive`

... which reduces overhead and often increases speed of the file transfer, since the developer's server doesn't need to be in between anymore. Please consider adding information about this scenario to the docs. Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c42d74d1-8c6f-5282-9fba-30fdd6449362
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [Resumable file upload - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
