### ISSUE TITLE
Please list all the roles a user account must have to successfully call appRoleAssignment API

### ISSUE THREAD

**Issue by zhenyar** [microsoftgraph/microsoft-graph-docs-contrib#8851]
Please list all the roles that can successfully call this API.  User Administrator, Global Administrator?  This call gets 403 when made with an account that only has an Intune Service Administrator role.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8e535a1-f0e1-eb8f-8b34-365b43d38ad6
* Version Independent ID: 2f1ad830-0642-5cc5-982d-a2b4f75f8f80
* Content: [Grant an appRoleAssignment for a service principal - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-post-approleassignedto.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/serviceprincipal-post-approleassignedto.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @zhenyar for raising this issue. According to the [RBAC documentation](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference), users with the following roles can complete this API operation:
- User Administrator
- Application Administrator
- Cloud Application Administrator
- Directory Synchronization Accounts
- Directory Writers
- Hybrid Identity Administrator
- Identity Governance Administrator
- Partner Tier1 Support (deprecated and to be retired at any time)
- Partner Tier2 Support (deprecated and to be retired at any time)
- Privileged Role Administrator

I'll raise a PR to add this information to the documentation.

**Comment by zhenyar** [comment]
Are you sure the above list of roles is correct?  I'm trying to call this API with a User Administrator role, and I'm getting 403 back.  I do recall it worked in one scenario, but is not working in another.  I'm trying to figure out why.

**Comment by zhenyar** [comment]
I found out that assigning a custom app role to a group works with User Administrator role, but assigning an existing app role to the service principal for the Graph app requires Global Administrator role.  It would be great if these details were clarified in the documentation.  Thanks!

**Comment by zhenyar** [comment]
I don't see any documentation changes.  Why was this issue closed as completed, @Lauragra?

**Comment by FaithOmbongi** [comment]
> Are you sure the above list of roles is correct? I'm trying to call this API with a User Administrator role, and I'm getting 403 back. I do recall it worked in one scenario, but is not working in another. I'm trying to figure out why.

Hi @zhenyar , if you're experiencing a different behavior from what's documented in the role-based access control documentation, please file a bug at  [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) so that the functionality can be further investigated, any caveats identified and documented. You may be requested for a request ID for investigation.
