### ISSUE TITLE
Resumable upload returns @content.downloadUrl instead of @microsoft.graph.downloadUrl

### ISSUE THREAD

**Issue by dennisameling** [microsoftgraph/microsoft-graph-docs-contrib#886]
When doing a [Resumable Upload](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0) to the Graph API, we get back the old `@content.downloadUrl` that was replaced back in 2016/2017 by `@microsoft.graph.downloadUrl`. The docs on this page [indicate ](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#completing-a-file) that a `DriveItem` is returned, but a `DriveItem` should have a `@microsoft.graph.downloadUrl`. This is quite confusing, so would be great if you can either pass this on to backend teams and/or to update the docs on this point. Thanks in advance!

**Regular upload:**
`PUT v1.0/groups/GROUP_ID/drive/items/ITEM_ID:/FILENAME.pdf:/content`

```json
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#groups('GROUP_ID')/drive/items/$entity",
  "@microsoft.graph.downloadUrl": "https://MYORG.sharepoint.com/sites/MYSITE/_layouts/15/download.aspx?UniqueId=ID_HERE&Translate=false&tempauth=ey..."
}
```

**Resumable upload:**
`POST /v1.0/groups/GROUP_ID/drive/items/FOLDER_ID:/FILENAME.pdf:/createUploadSession`
then
`PUT https://MYORG.sharepoint.com/sites/MYSITE/_api/v2.0/drive/items/ITEM_ID/uploadSession?guid='GUID'&path='~tmpF2_FILENAME.pdf'&overwrite=False&rename=True&dc=0&tempauth=eyJ...`
```json
{
  "@odata.context": "https://MYORG.sharepoint.com/sites/MYSITE/_api/v2.0/$metadata#items/$entity",
  "@content.downloadUrl": "https://MYORG.sharepoint.com/sites/MYSITE/_layouts/15/download.aspx?UniqueId=ID_HERE&Translate=false&tempauth=ey..."
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c42d74d1-8c6f-5282-9fba-30fdd6449362
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [Resumable file upload - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
