### ISSUE TITLE
Application permissions supported for user resource?

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs-contrib#8860]
The Permissions table in the document indicates that application permissions are not supported?

Supported resource | Delegated (work or school account) | Delegated (personal Microsoft account) | Application
-- | -- | -- | --
user | User.ReadWrite.All | Not supported. | Not supported.

Yet the text below seems to claim the opposite?

> To restore deleted users: User Administrator. However, to restore users with privileged administrator roles:
In delegated scenarios, the app must be assigned the Directory.AccessAsUser.All delegated permission, and the calling user must also be assigned a higher privileged administrator role as indicated in [Who can perform sensitive actions?](https://learn.microsoft.com/en-us/graph/api/resources/users#who-can-perform-sensitive-actions).
**In app-only scenarios** and in addition to being granted the User.ReadWrite.All application permission, the app must be assigned a higher privileged administrator role as indicated in [Who can perform sensitive actions?](https://learn.microsoft.com/en-us/graph/api/resources/users#who-can-perform-sensitive-actions).

Can you please double-check the document and clarify this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a29674bb-758c-119f-1b65-8fc968f2a91d
* Version Independent ID: 2f86af0c-8ed0-16f1-674c-91c6ebfb045d
* Content: [Restore deleted item (directory object) - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-restore?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/directory-deleteditems-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/directory-deleteditems-restore.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**Supported resource	Delegated (work or school account)	Delegated (personal Microsoft account)	Application
[administrativeUnit](https://learn.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta)	AdministrativeUnit.ReadWrite.All	Not supported.	AdministrativeUnit.ReadWrite.All
[application](https://learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta)	Application.ReadWrite.All	Not supported.	Application.ReadWrite.OwnedBy
[group](https://learn.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta)	Group.ReadWrite.All	Not supported.	Not supported.
[servicePrincipal](https://learn.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta)	Application.ReadWrite.All	Not supported.	Application.ReadWrite.OwnedBy
[user](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta)	User.ReadWrite.All	Not supported.	Not supported.

**Comment by FaithOmbongi** [comment]
Thank you @michevnew for catching this error. I've raised a PR to fix the Application column.
