### ISSUE TITLE
link not functoning (404)

### ISSUE THREAD

**Issue by jSvorstol** [microsoftgraph/microsoft-graph-docs-contrib#8863]
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/95748251/5778851b-c61b-496e-9996-209b65c7ca4e)
link marked with blue circle returns 404 page not found.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d489b596-8db6-6b4e-7271-77a6fb735c37
* Version Independent ID: afc8208d-990b-098f-0508-fcd5745d35e6
* Content: [Microsoft Graph REST API v1.0 endpoint reference - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/overview.md)
* Product: **non-product-specific**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this has been fixed already. Thanks.
