### ISSUE TITLE
Teams service limits information for Bulk API - POST https://graph.microsoft.com/v1.0/teamwork/sendActivityNotificationToRecipients

### ISSUE THREAD

**Issue by sagarM-MSFT** [microsoftgraph/microsoft-graph-docs-contrib#8868]
Hello Team,

As per documentation we don't see service limit information for [Send notifications to multiple users in bulk](https://learn.microsoft.com/en-us/graph/api/teamwork-sendactivitynotificationtorecipients)

Could you please update appropriate information for same.

Documentation reference - https://learn.microsoft.com/en-US/graph/throttling-limits#microsoft-teams-service-limits 

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/85691087/ffd2e113-60b1-4787-bdef-06a47f0841b5)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Version Independent ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Content: [Microsoft Graph service-specific throttling limits - Microsoft Graph](https://learn.microsoft.com/en-US/graph/throttling-limits#microsoft-teams-service-limits)
* Content Source: [concepts/throttling-limits.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/throttling-limits.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
We will check this internally and get the doc updated if required. Thank you.

**Comment by Meghana-MSFT** [comment]
The document has been updated, hence closing this issue.
