### ISSUE TITLE
Sites search API in multi-geo tenant & missing results should be explained

### ISSUE THREAD

**Issue by pfresnay** [microsoftgraph/microsoft-graph-docs-contrib#887]
Issue: 
In a multi-geo tenant, doc does not explain how to call graph.
Correct request is :
/sites/tenantgeolocated.sharepoint.com/sites?search=blabla

search does not return all results, especially teams sites : doc should details search algorithm & limited results.

Article:
https://docs.microsoft.com/fr-fr/graph/api/site-search

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
