### ISSUE TITLE
Unable to get "info" attribute from Azure AD for user or a group

### ISSUE THREAD

**Issue by NWH-SAmin5** [microsoftgraph/microsoft-graph-docs-contrib#8873]
Unable to get "info" attribute from Azure AD for user or a group

This attribute "info" is getting synced from on-premises AD to Azure AD
https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/reference-connect-sync-attributes-synchronized

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a73e08e0-aa5c-dde2-6e05-240052049a67
* Version Independent ID: aa0adc0e-5c50-3a2f-ab01-152f8f3d92e3
* Content: [Get group - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/group-get.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @NWH-SAmin5 for raising this issue. The Microsoft Graph group entity doesn't expose an **info** property. If it's a feature you expect in Graph, it's not supported today. You can file an issue at [Microsoft Graph Q&A](https://askgraph) and get advise whether to file a feature request if the feature should be available in Microsoft Graph.
