### ISSUE TITLE
List user usageRights is not returning any values

### ISSUE THREAD

**Issue by pheidler** [microsoftgraph/microsoft-graph-docs-contrib#8879]
This call is working in Graph Explorer, but fails in an SPFx Teams Tab context with the same permission scopes (i.e User.Read). Decoding the JWT token from the Teams context confirmed that the required permissions were present. 

**Request URL**
https://graph.microsoft.com/beta/users/{userId}/usageRights

**Graph explorer response**
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('{userId}')/usageRights",
    "value": [
        {
            "id": ...,
            "catalogId": ...,
            "serviceIdentifier": ...,
            "state": "active"
        }
    ]
}
```
**Teams Tab Response**

```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('{userId}')/usageRights",
    "value": []
}
```

Both calls were made from the same user (work or school account). 

Are there any additional permissions that are required? Or am I missing something in my license management configuration?

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9203bac4-8263-a37a-8028-01a7f722587d
* Version Independent ID: 112e0d4b-2f35-c724-2dfc-02e205a7bc49
* Content: [List user usageRights - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/user-list-usagerights.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jeeshnair
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by BenjaminZ** [comment]
I'm having a similar problem for another api [List eligibilityScheduleRequests](https://learn.microsoft.com/en-us/graph/api/privilegedaccessgroup-list-eligibilityschedulerequests?view=graph-rest-1.0&tabs=http). Was working early last week.

**Comment by pheidler** [comment]
Turns out it was an issue with the license configuration. The tenant that owns the app wasn't linked to the publisher account.

**Comment by gruering** [comment]
Hi @pheidler 
We are struggling with the same problem. We have already added the tenant but our license check still fails. Was there a waiting time after you have added the tenant or did this fix the issue immediately?

**Comment by pheidler** [comment]
@gruering This fixed the issue immediately.

**Comment by gruering** [comment]
Thank you for the prompt feedback @pheidler. We still cannot make the call work outside our tenant. Do you use this code in an SPFx WebPart? Can you share some code snippet?
We are using the following code in a webpart:
```
    this.props.context.msGraphClientFactory
      .getClient('3')
      .then((client: MSGraphClientV3): void => {
        client
          .api('/me/usageRights')
          .version('beta')
          .get((error, response: any, rawResponse?: any) => {
            // handle the response
        });
      });
```

**Comment by pheidler** [comment]
Yes, this looks right. What response are you getting? By "outside our tenant", are you referring to end users in a different tenant?

**Comment by gruering** [comment]
Yes, for licensed end users in a different tenant the response is always empty:
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('80021c1a-f495-4cc2-9e8b-b1156aea6b09')/usageRights",
    "value": []
}
```
However. when I sign in to graph explorer with the same user I can successfully retrieve the license information: 
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('80021c1a-f495-4cc2-9e8b-b1156aea6b09')/usageRights",
    "@microsoft.graph.tips": "Use $select to choose only the properties your app needs, as this can lead to performance improvements. For example: GET me/usageRights?$select=catalogId,serviceIdentifier",
    "value": [
        {
            "id": "63c3da63-119d-4dd7-8d11-792b53901c73",
            "catalogId": "DZH315Z0GC0Q:0002",
            "serviceIdentifier": "softforgeag1695645633211.sf-checklists-offer.sf-checklists-userplan1",
            "state": "active"
        }
    ]
}
```
With have included the following permissions in our webpart configuration:
```
          "webApiPermissionRequests": [
               {
                    "resource": "Microsoft Graph",
                    "scope": "User.Read"
               }
          ],
```

**Comment by pheidler** [comment]
@gruering Ah ok, unfortunately I won't be much help. At the moment, I've only tested in my own tenant. I'll let you know if I run into the same issue with external tenants.

**Comment by raclettierer** [comment]
Any news? we have the same problem

**Comment by jeeshnair** [comment]
Hi ,

Is it possible to make a call with empty results and give the date and time
of the call ( also mention time zone ) . I can check to see why you see
empty in one case and not empty in the other.

**Comment by gruering** [comment]
Hi @jeeshnair 
I have made a call to the usageRights API via our SPFx webpart at **Fri, 02 Feb 2024 16:32:32 GMT**.
- Client Request id 3ac15cd3-b9a9-440d-b56f-82b2d8357e3e
- Request id is 3ac15cd3-b9a9-440d-b56f-82b2d8357e3e

And I also called the API via Graph Explorer at **Fri, 02 Feb 2024 16:38:25 GMT**
- Client Request id f944eb42-f06d-f39b-c8c7-299801dcf0ce
- Request id 72861a80-2761-46c3-911d-996294130071

Both calls made with the same user but only the graph explorer call has returned data.

Thanks,
Beat
