### ISSUE TITLE
Skip token not in golang SDK  method UsersRequestBuilderGetQueryParameters{}

### ISSUE THREAD

**Issue by JaeTLDR** [microsoftgraph/microsoft-graph-docs-contrib#8881]
Using the page to build a paging MSGraph go client, the Skiptoken property on the  `users.UsersRequestBuilderGetQueryParameters{}` doesn not contain a field for skiptoken.

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/26292620/3823b3e7-47d1-4382-b0fa-35f0f1b44fc6)
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/26292620/40ff6c0a-7d6b-4a66-8774-191b3c2bb33a)

Additionally I am unable to read the documentation on https://pkg.go.dev/github.com/microsoftgraph/msgraph-sdk-go/users due to the length of the documentation, do you have an alternate site generated with go doc available?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7e1ac6d-b2ee-c495-3194-f2895e26945e
* Version Independent ID: 73f817df-a829-e265-c932-7ae8b3f3e918
* Content: [Paging Microsoft Graph data in your app  - Microsoft Graph](https://learn.microsoft.com/en-us/graph/paging?tabs=go)
* Content Source: [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JaeTLDR** [comment]
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/26292620/ca0c0a4c-143b-42c6-bedc-46cde7f7b72b)

**Comment by FaithOmbongi** [comment]
Thank you @JaeTLDR for raising this issue. Unfortunately, this forum is only for documentation-related issues but you can file this issue at the [Java SDK repo](https://github.com/microsoftgraph/msgraph-sdk-java/issues). Closing this issue here.

**Comment by JaeTLDR** [comment]
But the documentation is incorrect? also this is for Go not Java

**Comment by FaithOmbongi** [comment]
> But the documentation is incorrect? also this is for Go not Java

My apologies. Here's the [Go SDK repo](https://github.com/microsoftgraph/msgraph-sdk-go) to file the issue.

The code snippets are autogenerated through an automated SDK process. So these SDK issues can only be fixed upstream.

**Comment by baywet** [comment]
@FaithOmbongi all the snippets generated for this HTTP request are wrong. They shouldn't instruct users to parse the next link so they can get the skip token. Can you create an issue on the devx API repository please?

@JaeTLDR here is what you want to do instead


```go
users, err := graphClient.Users().WithUrl(oDataNextLink).Get(context.Background(), nil)
```

Where the odata next link is the property on the result for the past request.

**Comment by JaeTLDR** [comment]
Thank  you @baywet and @FaithOmbongi 
I will get this in my code now
