### ISSUE TITLE
$filter & $select used concurrently does not work on /pages/microsoft.graph.sitePage

### ISSUE THREAD

**Issue by jarryd-mtn** [microsoftgraph/microsoft-graph-docs-contrib#8887]
When trying to use $select concurrently with $filter, I receive a HTTP 200 with an empty value array.

```
GET https://graph.microsoft.com/beta/sites/xxx.sharepoint.com,{{GUID}}/pages/microsoft.graph.sitePage?$filter=lastModifiedDateTime+ge+2023-10-01T05:22:13Z+and+promotionKind+eq+'newsPost'&$orderby=lastModifiedDateTime+desc
``` 

![Error](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/85690140/9b354e31-2540-435e-b04f-a19d5670cb26)

When using $Filter I receive a 200 response and suggests using $Select

![Screenshot 2023-12-06 180456](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/85690140/aa853120-0ee1-45aa-aee9-0bc2ea41d5ae)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0922533d-b396-4bd5-8258-7ce6f2a5b4b0
* Version Independent ID: d1719bc1-65aa-d4e6-24d1-524f35c4ee21
* Content: [List SitePage - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/sitepage-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @sangle7
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sangle7** [comment]
@jarryd-mtn thanks for reporting this. We've checked in a fix and the code should be deployed in 3~4 weeks
