### ISSUE TITLE
Document the maximum length of delegatedAdminRelationship.displayName

### ISSUE THREAD

**Issue by Viajaz** [microsoftgraph/microsoft-graph-docs-contrib#8891]
delegatedAdminRelationship.displayName has a maximum string length of 50 but it is not documented.
Also see: https://learn.microsoft.com/en-us/graph/api/resources/delegatedadminrelationship?view=graph-rest-1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b385560d-8ce5-9ff1-ab49-4b04994bee9a
* Version Independent ID: 205dbb6b-53b7-9470-55d4-0450f9156934
* Content: [Create delegatedAdminRelationship - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/tenantrelationship-post-delegatedadminrelationships?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/tenantrelationship-post-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/tenantrelationship-post-delegatedadminrelationships.md)
* Product: **partner-customer-administration**
* Technology: **microsoft-graph**
* GitHub Login: @koravvams
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by koravvams** [comment]
Hi @Viajaz, we have updated the documentation to include maximum length supported for display name.
