### ISSUE TITLE
Misalignment between pagination documentation

### ISSUE THREAD

**Issue by erionpc** [microsoftgraph/microsoft-graph-docs-contrib#8892]
This page 
https://learn.microsoft.com/en-us/graph/paging?tabs=csharp
and this page 
https://learn.microsoft.com/en-us/graph/sdks/paging?tabs=csharp
provide conflicting information regarding how to implement paging of Graph data in C# code.

https://learn.microsoft.com/en-us/graph/paging?tabs=csharp mentions using the "SkipToken" property which doesn't exist in the SDK, whereas https://learn.microsoft.com/en-us/graph/sdks/paging?tabs=csharp mentions using the PagingIterator. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7e1ac6d-b2ee-c495-3194-f2895e26945e
* Version Independent ID: 73f817df-a829-e265-c932-7ae8b3f3e918
* Content: [Paging Microsoft Graph data in your app  - Microsoft Graph](https://learn.microsoft.com/en-us/graph/paging?tabs=http)
* Content Source: [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @jasonjoh - Can you assist here? Thanks.

**Comment by jasonjoh** [comment]
Yes, I'll clean this up and make them consistent.

**Comment by jasonjoh** [comment]
This update should be published shortly.
