### ISSUE TITLE
The "Files and lists service limits" section does not show any limits

### ISSUE THREAD

**Issue by diegodru** [microsoftgraph/microsoft-graph-docs-contrib#8893]
The `Files and lists service limits` section states:

"The preceding information applies to the following resources"

but there is no limit information shown

![scr-shot 2023-Dec-07@08h26m02s](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/56616239/47fc26b1-eb64-4197-a95a-7d3ee0d8b008)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Version Independent ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Content: [Microsoft Graph service-specific throttling limits - Microsoft Graph](https://learn.microsoft.com/en-us/graph/throttling-limits)
* Content Source: [concepts/throttling-limits.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/throttling-limits.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @diegodru for raising this issue. The limits info is defined in the linked documentation https://learn.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.

Hope this helps.
