### ISSUE TITLE
Incorrect Warning Banner 

### ISSUE THREAD

**Issue by bwya77** [microsoftgraph/microsoft-graph-docs-contrib#8899]
As of November 22nd the Microsoft Graph CLI is no longer in preview and is now generally available. I recommend removing the warning on this page stating that it is still in preview. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3be63768-c95c-f1f5-8d77-f40688637448
* Version Independent ID: 3be63768-c95c-f1f5-8d77-f40688637448
* Content: [Install the Microsoft Graph command-line interface (CLI) - Microsoft Graph](https://learn.microsoft.com/en-us/graph/cli/installation?tabs=macos)
* Content Source: [concepts/cli/installation.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/cli/installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks for reporting! A fix for this will be published today.
