### ISSUE TITLE
planId for HTTP request should be updated

### ISSUE THREAD

**Issue by TobiasAT** [microsoftgraph/microsoft-graph-docs-contrib#8901]
I think there is a documentation error for the HTTP request. planId should be the ID of the plan, not the word. 

From my testing the following HTTP request works.

` POST https://graph.microsoft.com/beta/planner/plans/<planId>/moveToContainer`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e134f866-5db3-4388-1295-c7323b94237c
* Version Independent ID: 23d996c6-ffe3-58ef-bee3-2be151a8acb5
* Content: [plannerPlan: moveToContainer - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/plannerplan-movetocontainer?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/plannerplan-movetocontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/plannerplan-movetocontainer.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @vasrinwork
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vasrinwork** [comment]
#[https://github.com/microsoftgraph/microsoft-graph-docs/pull/23207](url)

**Comment by vasrinwork** [comment]
Will be addressed in this PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/23207
