### ISSUE TITLE
Undocumented feature (maybe a bug) in the file uploading API

### ISSUE THREAD

**Issue by landall** [microsoftgraph/microsoft-graph-docs-contrib#8903]
The API for uploading a file to SharePoint/OneDrive works not exactly as the document says.
 
When we upload some files to SharePoint/OneDrive, the file will be modified in the progress of uploading and the file size is 11-12 bytes bigger than the original.
Hashsum is not matched too.

I check about 1,000,000 files and find a situation about the bug.
Some jpeg files are modified.
I compared these files with the uploaded ones by HEX editor and php codes.
The desnity in jpeg header is 96 x 96, in EXIF is 72 x 72.
After uploading,  the desity in jpeg header become 72 x 72 and APP1 part of jfif increased 12 bytes.

Some one else reports some Office files is modified but I meet no example.

I think this is not a good feature and I don't want my file be modified by SharePoint.
 
Can you explain what is happening in the process of  this API.

OneDrive client of Win10 seems not triggering it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d92fb8c7-4409-d945-57dd-5d6fc4010051
* Version Independent ID: f77c05bd-2688-bd4e-1f8f-f18feb3a8639
* Content: [Upload small files - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Unfortunately this repo is for keeping track of issues or new contributions in the Microsoft Graph docs and not to provide help about how to use Microsoft Graph. You should rely on the Microsoft Graph support area (https://developer.microsoft.com/en-us/graph/support) for this kind of questions. I'm going to close this item. Thanks for your understanding.
