### ISSUE TITLE
Python script missing for Simulation users page

### ISSUE THREAD

**Issue by yadavgaurav121** [microsoftgraph/microsoft-graph-docs-contrib#8908]
Missing python script for simulation users page : 

https://learn.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-1.0&tabs=http

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2b69207-8abe-22d5-b0ca-06fc659514e3
* Version Independent ID: ca111e9c-ca15-4d88-334d-7c2e52d3873c
* Content: [List simulationUsers - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/usersimulationdetails-list.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @stuartcl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this will be tracked in https://github.com/microsoftgraph/msgraph-metadata/issues/531
