### ISSUE TITLE
channelMembershipType is wrong for shared channels in v1.0

### ISSUE THREAD

**Issue by NielsNet** [microsoftgraph/microsoft-graph-docs-contrib#8909]
According to the docs (https://learn.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0#channelmembershiptype-values) there is a ChannelMembershipType `shared` for shared channels and `unknownFutureValue` that is not supposed to be used.  
However during development (using the dev toolkit) I noticed those values seem to have been mixed up.  
When creating a shared channel through Teams UI:
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/30441612/89ec6f76-cd36-4d7e-a209-8c47c2aea882)

And then requesting it using the path `/v1.0/teams/{team-id}/channels` or `/v1.0/teams/{team-id}/channels/{channel-id}` (manually, trough the Java SDK or even in the graph explorer) the attribute "membershipType" is `unknownFutureValue`:
```json
{
        "id": "redacted",
        "createdDateTime": "2023-12-07T16:07:06.282Z",
        "displayName": "Beispielkanal",
        "description": null,
        "isFavoriteByDefault": null,
        "email": null,
        "tenantId": "...",
        "webUrl": "https://teams.microsoft.com/l/channel/...",
        "membershipType": "unknownFutureValue"
}
```

When using the beta Endpoint this bug is not present:
```json
{
        "id": "redacted",
        "createdDateTime": "2023-12-07T16:07:06.282Z",
        "displayName": "Beispielkanal",
        "description": null,
        "isFavoriteByDefault": null,
        "email": null,
        "tenantId": "...",
        "webUrl": "https://teams.microsoft.com/l/channel/...",
        "filesFolderWebUrl": "...",
        "membershipType": "shared",
        "moderationSettings": null
}
```
However there is no known issue regarding this bug in the 1.0 version.

Related entries from the graph api changelog:
- https://developer.microsoft.com/en-us/graph/changelog/?search=7136eafa-67cc-4703-8dbb-520d68ff9125
- https://developer.microsoft.com/en-us/graph/changelog/?search=a63f2e0f-a55e-43b2-9583-5b92ca3c0526

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75f86208-723e-a0c9-2cce-3e681dfa7b9c
* Version Independent ID: dc38068e-3b39-1352-117d-e770485b7b70
* Content: [channel resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0#channelmembershiptype-values)
* Content Source: [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/channel.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Dinesh-MSFT** [comment]
Hello @NielsNet - Thanks for raising a query. 
We will look into it and let you know the updates.

**Comment by Dinesh-MSFT** [comment]
Hello @NielsNet - We tried to repo your issue and we are also facing the same issue.
We will check with engineering team whether it is byDesign behavior in v1.0or not and we will let you know the updates.

**Comment by ChetanSharma-msft** [comment]
Hello @NielsNet - If you design your application to handle unknown members as well, you can opt-in to receive those members by using an HTTP Prefer request header: 
**Prefer: include-unknown-enum-members**

We have tested and it is working with v1.0 Graph API as well.

Reference doc: https://learn.microsoft.com/en-us/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations

Please check and let us know if you still face the issue.

Also, please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
