### ISSUE TITLE
sortOrderIndex is mentioned as response value in v1.0 

### ISSUE THREAD

**Issue by TimScholzESC** [microsoftgraph/microsoft-graph-docs-contrib#8910]
sortOrderIndex is mentioned as response value in v1.0 .
But its only in the response of the beta endpoint

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: feddb622-23f9-430a-1235-c72e614f455b
* Version Independent ID: 349d6f59-c24d-94e7-ca5e-7b660d8a5345
* Content: [Add tab to channel - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/channel-post-tabs?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/channel-post-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and update the doc.

**Comment by v-sdhakshina** [comment]
Updated the doc through pull request https://github.com/microsoftgraph/microsoft-graph-docs/pull/23449.

**Comment by Meghana-MSFT** [comment]
Document has been updated, hence closing this issue.
