### ISSUE TITLE
Cannot create document library tab

### ISSUE THREAD

**Issue by LukasNespor** [microsoftgraph/microsoft-graph-docs-contrib#8914]
Cannot create tab pointing to SharePoint document library using SPN. I know that it was working on 11/16/2023 when our integration created tab successfully for the last time. Next try om 5/12/2023 failed and is failing since.

### Roles in in access token
```
[
    "User.ReadWrite.All",
    "Group.ReadWrite.All",
    "Notes.Read.All",
    "Directory.Read.All",
    "User.Read.All",
    "TeamMember.ReadWrite.All",
    "ChannelMember.ReadWrite.All",
    "Notes.ReadWrite.All",
    "ChannelMessage.Read.All"
]
```

### Request
```
POST https://graph.microsoft.com/v1.0/teams/{team-id}/channels/{channel-id}/tabs
Content-Type: application/json
Authorization: Bearer xxx

{
  "configuration": {
    "contentUrl": "https://tenant.sharepoint.com/teams/extranet/Shared%20Documents",
    "entityId": ""
  },
  "displayName": "Extranet",
  "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.files.sharepoint"
}
```

### Response
```
HTTP/1.1 502 Bad Gateway
Transfer-Encoding: chunked
Content-Type: application/json
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 7c48d909-dee0-497f-bdf9-5f169ecaa172
client-request-id: 7c48d909-dee0-497f-bdf9-5f169ecaa172
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Germany West Central","Slice":"E","Ring":"5","ScaleUnit":"005","RoleInstance":"FR3PEPF00000368"}}
Date: Wed, 13 Dec 2023 11:17:59 GMT
Connection: close

{
  "error": {
    "code": "BadGateway",
    "message": "Failed to execute backend request.",
    "innerError": {
      "date": "2023-12-13T11:18:00",
      "request-id": "7c48d909-dee0-497f-bdf9-5f169ecaa172",
      "client-request-id": "7c48d909-dee0-497f-bdf9-5f169ecaa172"
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configure the built-in tab types in Microsoft Teams - Microsoft Graph](https://learn.microsoft.com/en-us/graph/teams-configuring-builtin-tabs)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
@LukasNespor - We tried to repro this issue at our end and its working perfectly fine. We are able to create document library tab.
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/62237649/c773a76e-84a2-485c-8345-006e061d5072)
