### ISSUE TITLE
Spelling error on the table of contents for service activity

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs-contrib#8915]
For https://learn.microsoft.com/en-us/graph/api/resources/serviceactivity?view=graph-rest-beta&preserve-view=true the table of contents says "Microsoft Entra service activiy"

Also in the topic the wording of "A placeholder for the Microsoft Entra service activity URL." is a bit odd...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d670218-1b1e-68a8-d15b-481ca449a09e
* Version Independent ID: 0f211647-4b73-0a05-aea5-32ece7bcbceb
* Content: [serviceActivity resource type - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/serviceactivity?view=graph-rest-beta&preserve-view=true)
* Content Source: [api-reference/beta/resources/serviceactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/resources/serviceactivity.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @Zacharypeng
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @dkershaw10 for raising this issue. The documentation seems to be correct now.
