### ISSUE TITLE
Required vs Optional params?

### ISSUE THREAD

**Issue by L-P-G** [microsoftgraph/microsoft-graph-docs-contrib#8918]
When creating an object via POST. Are all the parameters in the example required? Which ones are optional?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04504a62-d768-a27c-d4f9-64092a6b2edd
* Version Independent ID: 29741af4-f851-5a0c-3eca-c836120f5172
* Content: [Create managedDevice - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/intune-devices-manageddevice-create?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-create.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/intune-devices-manageddevice-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @jaiprakashmb
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jaiprakashmb** [comment]
There are couple of things to consider when determining if the property is required or not,
1. All the "read-only" properties are (auto)generated by backend services (called computed property values) so they are not needed to be passed with request body.
2. Additional you can also check the entity metadata which has **Nullable="false"** that indicates if the properties that are marked as required.

As example
```
<EntityType Name="managedDevice" BaseType="graph.entity">   
       <Property Name="autopilotEnrolled" Type="Edm.Boolean" **Nullable="false"** />                
       <Property Name="bootstrapTokenEscrowed" Type="Edm.Boolean" **Nullable="false"** />
       <Property Name="chassisType" Type="graph.chassisType" **Nullable="false"** />           
</EntityType>
```
