### ISSUE TITLE
Incorrect Go snippet generated for GET /groups/delta

### ISSUE THREAD

**Issue by vijmax** [microsoftgraph/microsoft-graph-docs-contrib#8920]
The GoLang examples are incorrect. For most of the samples provided the SDK does not have equivalent functions itself.
Somehow Microsoft has a knack of making simple API's ultra complicated with junk documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e89b9ed-663c-3639-9d0d-9aad705920f3
* Version Independent ID: b003a86a-f78f-05eb-e67d-54bb5ca0f2b1
* Content: [group: delta - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/group-delta.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vijmax** [comment]
For example ... check this piece of code given as example ...
requestParameters := &graphgroups.GroupsDelta()RequestBuilderGetQueryParameters{
	Select: [] string {"displayName","description","mailNickname"},
}

There is no function called GroupsDelta() not struct like RequestBuilderGetQueryParameters.
The API's also dont seem to work, we never get deltaLink in the response in go sdk. However when using http APIs everything works as documented.

**Comment by jasonjoh** [comment]
@vijmax thanks for the feedback. This appears to be a problem with our automated snippet generation process getting these particular snippets (Request 2 and Request 3) wrong. I'm assigning this to an engineer from the snippet generator team.

The correct snippet for Request 2 would be:

```go
requestParameters := &groups.DeltaRequestBuilderGetQueryParameters{
	Select: []string{"displayName", "description", "mailNickname"},
}

configuration := &groups.DeltaRequestBuilderGetRequestConfiguration{
	QueryParameters: requestParameters,
}

delta, err := graphClient.Groups().Delta().Get(context.Background(), configuration)
if err != nil {
	fmt.Printf("Error: %v", err)
}
```

> The API's also dont seem to work, we never get deltaLink in the response in go sdk. However when using http APIs everything works as documented.

In my testing, the API works the same both via HTTP (in Graph Explorer) and via the SDK. The `@odata.deltaLink` is only returned after you follow all of the `@odata.nextLink` values to get all of the pages. In other words, if there is an `@odata.nextLink`, there will not be an `@odata.deltaLink`. More details on this [here](https://learn.microsoft.com/en-us/graph/delta-query-overview).

One way you could approach this is like so:

```go
requestParameters := &groups.DeltaRequestBuilderGetQueryParameters{
	Select: []string{"displayName", "description", "mailNickname"},
}

configuration := &groups.DeltaRequestBuilderGetRequestConfiguration{
	QueryParameters: requestParameters,
}

delta, err := graphClient.Groups().Delta().Get(context.Background(), configuration)
if err != nil {
	log.Fatalf("Error getting groups: %v", err)
}

for {
	for _, group := range delta.GetValue() {
		fmt.Printf("%s\n", *group.GetDisplayName())
	}

	nextPageUrl := delta.GetOdataNextLink()
	if nextPageUrl != nil {
		delta, err = graphClient.Groups().Delta().
			WithUrl(*nextPageUrl).
			Get(context.Background(), nil)
		if err != nil {
			log.Fatalf("Error getting groups: %v\n", err)
		}
	} else {
		deltaLinkUrl := delta.GetOdataDeltaLink()
		fmt.Printf("Delta link: %s", *deltaLinkUrl)
		break
	}
}
```

**Comment by vijmax** [comment]
Awesome support. 
Thank you for the swift response. The solution provided works as expected.
