### ISSUE TITLE
Filtering by catalogId is not supported, you should probably mention why on the document page

### ISSUE THREAD

**Issue by lispercat** [microsoftgraph/microsoft-graph-docs-contrib#8922]
I would expect the API to filter based on catalogId just like on all other members but it doesn't work:
GET https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignments?$expand=target,accessPackage&$filter=catalogId eq '1afa8ced-6f74-4d8e-8411-cd12c8337027'

Fails with the message 
{
  "error": {
    "code": "InvalidFilter",
    "message": "OData query is invalid: Filter 'catalogId Equals 1afa8ced-6f74-4d8e-8411-cd12c8337027 is not supported. .",
    "details": [],
    "innerError": {
      "date": "2023-12-14T19:27:42",
      "request-id": "b9e141b0-9b2c-451e-9ba7-998f9e6ca8ec",
      "client-request-id": "b9e141b0-9b2c-451e-9ba7-998f9e6ca8ec"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62495d1c-009b-4c87-30d5-b3c415f967b5
* Version Independent ID: c3b9c844-417f-14d2-c887-b708de640c1f
* Content: [List accessPackageAssignments - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-list-accesspackageassignments?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/entitlementmanagement-list-accesspackageassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/entitlementmanagement-list-accesspackageassignments.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @lispercat for raising this issue. Unfortunately, the API doesn't support filtering by the catalogId property today. This request has been forwarded to the feature team for consideration. cc @markwahl-msft .
