### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by GlennQLS** [microsoftgraph/microsoft-graph-docs-contrib#8923]
Please add PowerAutomate tab example.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 523b3456-9ec1-f405-a9f6-cf1e15b5a0b7
* Version Independent ID: a534e0cf-9e6d-5d85-0915-8c817569a989
* Content: [Delete a user - Microsoft Graph API - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-delete?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/user-delete.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @GlennQLS for this request. Power Automate isn't an SDK so we might now be able to add the tab as requested.  You can explore the [Microsoft 365 & Power Platform Community](https://pnp.github.io/#community) to find samples for Power Automate.
