### ISSUE TITLE
Example contains an infinite loop

### ISSUE THREAD

**Issue by JasonSheats** [microsoftgraph/microsoft-graph-docs-contrib#8927]
Need to add an "else { break; }" to the end of the if statement to break out of the while loop.  Otherwise it loops infinitely on the last messages received.

var messages = await graphClient.Me.Messages
    .GetAsync(requestConfiguration =>
    {
        requestConfiguration.QueryParameters.Top = 10;
    });

while (messages?.Value != null)
{
    foreach (var message in messages.Value)
    {
        Console.WriteLine(message.Subject);
    }

    // If OdataNextLink has a value, there is another page
    if (!string.IsNullOrEmpty(messages.OdataNextLink))
    {
        // Pass the OdataNextLink to the WithUrl method
        // to request the next page
        messages = await graphClient.Me.Messages
            .WithUrl(messages.OdataNextLink)
            .GetAsync();
    }
    else
    {   // If OdataNextLink IS null or empty, then break out of the loop.
        break;
     }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d558deeb-3492-230e-b2d9-8d9efeb6f97f
* Version Independent ID: bb2e0da9-acb9-0ffa-7fb6-d1bb534bfd20
* Content: [Page through a collection using the Microsoft Graph SDKs - Microsoft Graph](https://learn.microsoft.com/en-us/graph/sdks/paging?tabs=csharp)
* Content Source: [concepts/sdks/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/sdks/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks @JasonSheats!
