### ISSUE TITLE
Is it possible to populate Sponsor(s) through API driven Inbound Provisioning?

### ISSUE THREAD

**Issue by MithunChopda** [microsoftgraph/microsoft-graph-docs-contrib#8929]
The Azure Active Directory Schema Editor (when Schema Editor is enforced true) does not display the Sponsors field for mapping to Source for API Driven Inbound Provisioning.

Manually adding this field as Multi Value Referenced field to AAD schema and mapping it to enterprise2.0 User schema field "Sponsors" 
upsets the Bulk Upload's user mapping logic. This leads to Updates been determined as Create and Sync fails with error "user with specified external id already exists"

The Graph API too doesn't list Sponsors on User object without using $expand. So what is the correct way for sending Sponsor's information in the Bulk Upload payload?

The Graph API allows updating Sponsors on single user using a  OData Reference Url referencing a User.

This syntax is similar to how Manager is updated except that Manager is NOT a multi-valued field.

Bulk Upload allows updating Manager field (it's present on Enterprise User schema). Is Sponsors also a part of Enterprise2.0 Schema?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac4d4d1-2b44-bbdb-2c0d-876db41f2ebb
* Version Independent ID: 4caffc91-aa2d-a46c-ce9d-dc8190316fe0
* Content: [Add sponsor - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/user-post-sponsors?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-post-sponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/user-post-sponsors.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @sadia353
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @MithunChopda for raising this issue. Unfortunately, this forum is only for documentation-related issues but [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) is the best forum to answer this functionality question so I recommend that you raise this question there. Closing this issue here.
