### ISSUE TITLE
Reference to a nonexistent "Assets section"

### ISSUE THREAD

**Issue by carlo-quinonez** [microsoftgraph/microsoft-graph-docs-contrib#8930]
The docs mention the CLI is available from the "Assets section" in the docs. I could not find the Assets section.

I was able to download the CLI from the Github repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3be63768-c95c-f1f5-8d77-f40688637448
* Version Independent ID: 3be63768-c95c-f1f5-8d77-f40688637448
* Content: [Install the Microsoft Graph command-line interface (CLI) - Microsoft Graph](https://learn.microsoft.com/en-us/graph/cli/installation?tabs=macos)
* Content Source: [concepts/cli/installation.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/cli/installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Hi @carlo-quinonez thanks for reaching out. The doc is referring to the **Assets** section of the GitHub releases page. I'll tweak the text a bit to make that more explicit.

**Comment by jasonjoh** [comment]
Updates to the doc will be published today.
