### ISSUE TITLE
Filtering by appRoleId not supported?

### ISSUE THREAD

**Issue by reespozzi** [microsoftgraph/microsoft-graph-docs-contrib#8934]
I have been querying via Graph API to try and return appRoleAssignments for a given group based on an appRoleId

A request looks like this, and I've tried with and without the `'` and with just the direct value like in the docs:

```
  const response = await fetch(
    `https://graph.microsoft.com/v1.0/groups/${groupId}/appRoleAssignments?$filter=appRoleId eq '${some-guid}'`,
    {
      method: "GET",
      headers: {
        ...
      },
    },
  );
```

A response contains this error:

```
  error: {
    code: 'Request_BadRequest',
    message: 'Invalid filter clause appRoleId: System.Guid',
```

I found this online: https://learn.microsoft.com/en-us/answers/questions/603125/how-to-filter-approleassignments-based-on-approleid -- can the docs be reflected to update what's compatible with filtering?
If it is possible, can it be made more clear how to achieve this and what the error means? 

This is not the same as raised in https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/1783 -- The documentation should be improved to reflect the lack of a feature, rather than guiding users to think it's possible

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9258fed6-3de6-6c70-babe-b9595b205c85
* Version Independent ID: dbc979c2-dfdb-a252-f57e-9790375f6f9e
* Content: [List appRoleAssignments granted to a user - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-list-approleassignments?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/user-list-approleassignments.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @reespozzi for raising this issue. Unfortunately, Microsoft Graph doesn't support filtering on **appRoleId** today. You can submit a feature request through the [Microsoft Graph feedback forum](https://aka.ms/graphfeedback) and other developers can amplify your voice so that the suggestion can be considered for feature development.

On another note, yes, if filtering were supported, the correct syntax would be the unquoted value, `/users/{id}/appRoleAssignments?$filter=appRoleId eq GUID-Value`, because appRoleId is a GUID and not a String type.

**Comment by reespozzi** [comment]
```
can the docs be reflected to update what's compatible with filtering?
```
@FaithOmbongi

**Comment by psignoret** [comment]
@reespozzi The [**appRoleAssignment**](https://learn.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0) resource type identifies all properties that can be used in `$filter`, and which operators they support. If a property doesn't say it's supported with `$filter`, then it's not.
