### ISSUE TITLE
Correct URL in docs for sensitivity Label or error in the API?

### ISSUE THREAD

**Issue by wobba** [microsoftgraph/microsoft-graph-docs-contrib#8935]
I see that `/me/informationprotection/sensitivityLabels` is working while `/me/security/informationProtection/sensitivityLabels` is not working. And the API works on both v1.0 and beta.

Is the docs or API wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea41611-4cd5-c01e-1acc-29ee0098e8c3
* Version Independent ID: 49abf984-3cfe-07cc-5c70-ad22a4402226
* Content: [Get sensitivityLabel - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/security-sensitivitylabel-get?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/security-sensitivitylabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/security-sensitivitylabel-get.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @tommoser
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PedroMordeP** [comment]
I'm trying to use from documentation the

`GET beta/me/security/informationprotection/sensitivitypabels`

I'm getting 400 Bad Request

I have the necessary delegated consent "_InformationProtectionPolicy.Read_" on the access token but I'm not sure what is missing to get this to work or is something on the API

In Graph Explorer is working but when I make a request from my application it doesn't. If I use others API URL it works like 

`GET beta/me`

Need to know if is something on the API used outside the Graph Explorer !?

**Comment by tommoser** [comment]
`/me/security/informationProtection/sensitivityLabels` is the correct API and should be working. It's available only under /beta.

The other API is used by first-party services only and should be under beta and /v1.0.
