### ISSUE TITLE
Wrong Permissions in docs for TeamworkTagMember

### ISSUE THREAD

**Issue by NielsNet** [microsoftgraph/microsoft-graph-docs-contrib#8948]
In the docs it sais under [permissions](https://learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&tabs=http#permissions), that the `Least privileged permissions` for listing TagMembers is `TeamworkTag.ReadWrite` (or `TeamworkTag.ReadWrite.All` for applications) and that the `Higher privileged permissions` are `TeamworkTag.Read` and `TeamworkTag.Read.All`

This should be switched since `ReadWrite` contains modifiing access whilst `Read` is restricted to readonly access.  
The same error is present on all docs related to the TeamworkTag (except update and delete, since there `write` permissions are rightfully required and the only option)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1a3251b-aff3-8c8b-d13a-fd408b4a5759
* Version Independent ID: 162ae8cf-8143-605a-08a9-4be5835a4641
* Content: [List teamworkTagMembers - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/teamworktagmember-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Vikram-MSFT** [comment]
Hii @RamjotSingh- Could you please help here to update the document as suggested?

**Comment by Lauragra** [comment]
@NielsNet , thanks for filing this issue. We have implemented a fix and will publishing it today so I'm now resolving this issue.
