### ISSUE TITLE
Permanently delete an item

### ISSUE THREAD

**Issue by jmshal** [microsoftgraph/microsoft-graph-docs-contrib#895]
The docs note that this endpoint moves the item to the recycle bin, but is there a way to permanently delete the item via the Graph REST API?

> Note that deleting items using this method will move the items to the recycle bin instead of permanently deleting the item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98a9738f-f173-3acb-5979-334920d5bde5
* Version Independent ID: 9d44372e-2e74-2d7c-771b-dc156cbf592b
* Content: [Delete a file or folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-delete?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-delete.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
