### ISSUE TITLE
Update required permissions - needs Directory.AccessAsUser.All

### ISSUE THREAD

**Issue by franciscopgomes** [microsoftgraph/microsoft-graph-docs-contrib#8951]
POSTing to /domains/{id}/federationConfiguration fails with a 403 if the calling user is a Security Administrator and the app has Domain.ReadWrite.All. The calling app also needs Directory.AccessAsUser.All for this to work. Can we update the docs to reflect this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc45e9cc-5d66-5d5e-13d7-f9629b478bd8
* Version Independent ID: 1cdec7f7-c9ae-9afb-e857-51a335067471
* Content: [Create internalDomainFederation - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/domain-post-federationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/domain-post-federationconfiguration.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @rahul-nagraj
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Similar to https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/1511, https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8747, https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8725, and also tracked via engineering bug 2359161 that's assigned to Avinash.

**Comment by FaithOmbongi** [comment]
UPDATE: Since fixing the issue is taking a bit longer than we hoped, I've documented a known issue and added a note in the documentation for the affected WRITE operations recommending *Directory.AccessAsUser.All* as a temporary workaround.

Please be on the lookout for when the issue is fixed so you can remove the use of the permission which is too highly privileged.

**Comment by cnotin** [comment]
@FaithOmbongi thx for the reply! I was just having the same issue 👀
I can't seem to find the known issue on https://developer.microsoft.com/en-us/graph/known-issues, or is it somewhere else? I'm not seeing the workaround on https://learn.microsoft.com/en-us/graph/api/domain-post-federationconfiguration?view=graph-rest-1.0&tabs=http either, or am I missing it?
I'm looking for the best way to follow that fix 🙏
