### ISSUE TITLE
[Documentation] Kindly document what all card actions supported for messages send by Graph API.

### ISSUE THREAD

**Issue by ChetanSharma-msft** [microsoftgraph/microsoft-graph-docs-contrib#8955]
Kindly document what all card actions supported for messages send by Graph API.

We don't have any note in the document that talks about what card actions are supported while sending the message by Graph API.

So, we can either mention a note in this documentation or in below documentaiton:
https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=json

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: caa6130b-e7ac-9795-9593-f0cef62ff0d4
* Version Independent ID: 7bf7c3d2-7693-7d24-e9c0-6f0c51cb1eaa
* Content: [Send chatMessage in a channel or a chat - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&tabs=http#example-4-file-attachments&preserve-view=true)
* Content Source: [api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/chatmessage-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
As per engineering team, only "OpenUrl" card action is supported by Graph API since rest of others require Bots.

**Comment by Meghana-MSFT** [comment]
@surbhigupta12 - Could you please help to add this note in the doc - https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&tabs=http#example-4-file-attachments&preserve-view=true

Note : "OpenUrl" card action is supported by Graph API since rest of others require Bots.

**Comment by Meghana-MSFT** [comment]
The document has been updated, hence closing this issue.
