### ISSUE TITLE
Document creating and populating multi-value directory extensions

### ISSUE THREAD

**Issue by rmmason** [microsoftgraph/microsoft-graph-docs-contrib#8956]
It would be great if you could add an example or hint at how to create and populate values for directory extensions that can take multiple values. At present it is clear that they are supported but I'm at a loss as to how I would go about implementing these. 

It is also unclear if for instance I chose to define a multi-value directory extension as a string type if the 256 character maximum would apply to each value or the combined set of values so it would be good if this could also be made clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9ba2e9-2111-5815-e18b-1158eb9140d2
* Version Independent ID: 22d7b10f-f484-8b91-98da-39aa63478dd6
* Content: [Add custom data to resources using extensions - Microsoft Graph](https://learn.microsoft.com/en-us/graph/extensibility-overview?tabs=http)
* Content Source: [concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/extensibility-overview.md)
* Product: **extensions**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @rmmason for raising this issue.
- The following snippet shows a sample syntax to add a multivalue directory extension of String type to a user object

```json
{
    "accountEnabled": true,
    "displayName": "...",
    "mailNickname": "...",
    "userPrincipalName": "...",
    "passwordProfile": {..
    },
    "extension_b7b1c57b532f40b8b5ed4b7a7ba67401_jobGroupTracker": [
        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis,.",
        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,."
    ]
}
```

I'll raise a PR to show a sample in the doc.

- For the 2nd Q: The 256-character length for String types applies to a single string value in the collection, as you can note from the preceding example I provided.
