### ISSUE TITLE
Allow Existing Issues without activity to be commented or otherwise to remain open.

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/microsoft-graph-docs-contrib#8958]
https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/444#event-11293241118
@PaoloPia 

This policy of requiring a new issue creation for a long existing but still active issue is asinine, it reeks of wanting to meet some sort of "closed issues" metric and is actively hostile to contributors, creating unnecessary extra work.

Please let us just bump the issue for activity, this policy ends up being less about cleanup and more about alienating those who want to help.

Thank you.

**Comment by Jaykul** [comment]
Well, let's see, how can we make it _harder_ ...

**Comment by kilasuit** [comment]
🤞 this approach will have a rethink across not just this repo but others across Microsoft in 2024.
