### ISSUE TITLE
Inconsistent Information about callTranscript

### ISSUE THREAD

**Issue by minimaximus** [microsoftgraph/microsoft-graph-docs-contrib#8959]
the callTranscript resource page shows the object definition as

{
  "content": "Stream",
  "createdDateTime": "DateTimeOffset",  
  "id": "String (identifier)",
  "meetingId": "String",
  "meetingOrganizer": "IdentitySet",
  "metadataContent": "Stream",
  "transcriptContentUrl": "String"
}

but the GET Transcript call returns the following:

HTTP/1.1 200 OK
Content-type: application/json

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('ba321e0d-79ee-478d-8e28-85a19507f456')/onlineMeetings('MSo1N2Y5ZGFjYy03MWJmLTQ3NDMtYjQxMy01M2EdFGkdRWHJlQ')/transcripts/$entity",
    "id": "MSMjMCMjNzU3ODc2ZDYtOTcwMi00MDhkLWFkNDItOTE2ZDNmZjkwZGY4",
    "meetingId": "MSo1N2Y5ZGFjYy03MWJmLTQ3NDMtYjQxMy01M2EdFGkdRWHJlQ",
    "createdDateTime": "2021-09-17T06:09:24.8968037Z",
    "transcriptContentUrl": "https://graph.microsoft.com/v1.0/$metadata#users('ba321e0d-79ee-478d-8e28-85a19507f456')/onlineMeetings('MSo1N2Y5ZGFjYy03MWJmLTQ3NDMtYjQxMy01M2EdFGkdRWHJlQ')/transcripts/('MSMjMCMjNzU3ODc2ZDYtOTcwMi00MDhkLWFkNDItOTE2ZDNmZjkwZGY4')/content",
    "meetingOrganizer": {
        "application": null,
        "device": null,
        "user": {
            "@odata.type": "#Microsoft.Teams.GraphSvc.teamworkUserIdentity",
            "id": "ba321e0d-79ee-478d-8e28-85a19507f456",
            "displayName": null,
            "userIdentityType": "aadUser",
            "tenantId": "cd6cee19-2d76-4ee0-8f47-9ed12ee44331",
        }
    }
}

and not the actual calTranscript object. Even appending the URL with /content only returns the VTT data.
Is there a way to return the callTranscript object as a stream, which implies that it can be accessed in real-time during the meeting?

I created a subscription to the meeting transcripts resource, but I only receive a notfication once the meeting is ended, and cannot view the transcript during the meeting, which is the desired outcome.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 519a4b94-7379-4649-0e3f-b0fe6918fda2
* Version Independent ID: d1732c1a-8bd7-a23a-4e03-c726a4540e26
* Content: [Get callTranscript - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/calltranscript-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @v-sdhakshina
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and update the doc.

**Comment by Meghana-MSFT** [comment]
Apologies for the delay, currently there is no way to do this, engineering team is working on a feature to allow bot access real-time transcript. But there is no ETA/Timeline to share.
