### ISSUE TITLE
Failure when attempting to enumerate Schedule Instances for user

### ISSUE THREAD

**Issue by kjebu** [microsoftgraph/microsoft-graph-docs-contrib#8970]
I'm attempting to use the Get-MgIdentityGovernancePrivilegedAccessGroupEligibilityScheduleInstance Powershell cmdlet (v2.11.1) and have issues which I do not find a good explanation for.

I have granted 'PrivilegedEligibilitySchedule.ReadWrite.AzureADGroup' permissions to 'Microsoft Graph Powershell' as mandated by the documentation.  The app registration used by the script has also been granted this permission (Application)

If I run the following command
```
Get-MgIdentityGovernancePrivilegedAccessGroupEligibilityScheduleInstance -Filter "GroupId eq 'a7eaea0c-7be3-4e63-9e42-9d80d44be926'"
```
I get the following response, which is what I expect:
```
EndDateTime           Id                                                                               StartDateTime          AccessId EligibilityScheduleId                                                            GroupId                              MemberType PrincipalId
-----------           --                                                                               -------------          -------- ---------------------                                                            -------                              ---------- -----------
3/11/2024 12:00:10 PM a7eaea0c-7be3-4e63-9e42-9d80d44be926_member_8f5f0027-dcff-4a9a-a6f2-c40e35ecf5f2 10/4/2023 11:00:51 AM  member   a7eaea0c-7be3-4e63-9e42-9d80d44be926_member_da921a1b-2377-4d14-8bbe-c525e151eeb2 a7eaea0c-7be3-4e63-9e42-9d80d44be926 direct     8f5f0027-dcff-4a9a-a6f2-c40e35ecf5f2
4/21/2024 5:40:03 AM  a7eaea0c-7be3-4e63-9e42-9d80d44be926_member_12f420a1-2e95-48ef-a74b-d4fdc4279a94 10/26/2023 5:40:19 AM  member   a7eaea0c-7be3-4e63-9e42-9d80d44be926_member_f991693b-3f08-4ade-bff1-15a098f6e572 a7eaea0c-7be3-4e63-9e42-9d80d44be926 direct     12f420a1-2e95-48ef-a74b-d4fdc4279a94
6/16/2024 6:10:33 AM  a7eaea0c-7be3-4e63-9e42-9d80d44be926_member_4541ad43-dea4-4ef7-8676-e4c8bd396ec1 12/21/2023 11:43:35 AM member   a7eaea0c-7be3-4e63-9e42-9d80d44be926_member_e0421f96-d4c5-43c4-9434-2deeee73281f a7eaea0c-7be3-4e63-9e42-9d80d44be926 direct     4541ad43-dea4-4ef7-8676-e4c8bd396ec1
```

However if I run the following command (PrincipalID is from the first entry in the response above)

```
Get-MgIdentityGovernancePrivilegedAccessGroupEligibilityScheduleInstance -Filter "PrincipalId eq '8f5f0027-dcff-4a9a-a6f2-c40e35ecf5f2'"
```
I get the following error response:
```
Get-MgIdentityGovernancePrivilegedAccessGroupEligibilityScheduleInstance_List: Attempted to perform an unauthorized operation.

Status: 403 (Forbidden)
ErrorCode: UnauthorizedAccessException
Date: 2024-01-02T08:58:03

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : cf29a19b-6e79-4e42-b7c8-4d63c45ba848
client-request-id             : 569b5dc0-e598-46a6-86b7-9a04950f648a
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Sweden Central","Slice":"E","Ring":"5","ScaleUnit":"002","RoleInstance":"GV3PEPF00000BF8"}}
Date                          : Tue, 02 Jan 2024 08:58:03 GMT
```

What other permissions do I require to be able to execute the last query?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed38b352-5663-922a-edce-d3805a8f3427
* Version Independent ID: f6af9659-83a7-cbe9-04f1-b9c6622cb691
* Content: [Get privilegedAccessGroupEligibilityScheduleInstance - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/privilegedaccessgroupeligibilityscheduleinstance-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/privilegedaccessgroupeligibilityscheduleinstance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/privilegedaccessgroupeligibilityscheduleinstance-get.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @ilyalushnikov
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
My apologies for my delayed acknowledgment of this issue @kjebu. 

Unfortunately, this forum is only for documentation-related issues but [Microsoft Graph Q&A](https://aka.ms/askgraph) is the best forum to investigate functionality issues so I recommend that you raise this question there. You may be requested for a request ID (which is available in the failed response you shared) for investigation. Closing this issue here.
