### ISSUE TITLE
Broken link: "Microsoft Graph fundamentals"

### ISSUE THREAD

**Issue by aaronjones1** [microsoftgraph/microsoft-graph-docs-contrib#8972]
The "Microsoft Graph fundamentals" link in the "See also" section is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8b9905a-5314-eab9-5c97-0d6672529ad7
* Version Independent ID: d8b9905a-5314-eab9-5c97-0d6672529ad7
* Content: [Build interactive apps by using Microsoft Graph APIs - Microsoft Graph](https://learn.microsoft.com/en-us/graph/patterns/interactive-applications)
* Content Source: [concepts/patterns/interactive-applications.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/patterns/interactive-applications.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @OlgaPodo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @aaronjones1 for filing this issue. I've raised a PR to fix the link.
