### ISSUE TITLE
Missing PHP documentation details maybe?

### ISSUE THREAD

**Issue by Teejer** [microsoftgraph/microsoft-graph-docs-contrib#8974]
I'm trying to create a Temporary Access Pass Authentication Method using the api in php, but I'm getting this error "Uncaught Error: Class "TemporaryAccessPassAuthenticationMethod" not found in ...". I've tried adding 

`use Microsoft\Graph\Generated\Model\TemporaryAccessPassAuthenticationMethod;`

but that didn't make a difference. What am I missing? Other functions are working. It seems like maybe something is missing from the documentation maybe? Or is this a bug? I've got the same issue with adding phone methods.

```
function addAzureTempAccessPassGraph($username){
    
    try{
        $graphServiceClient = getAzureGraphServiceClient();
		
		$requestBody = new TemporaryAccessPassAuthenticationMethod();
		$requestBody->setLifetimeInMinutes(480);
		$requestBody->setIsUsableOnce(false);

		$result = $graphServiceClient->users()->byUserId($username)->authentication()->temporaryAccessPassMethods()->post($requestBody)->wait();



		return $result;

	
	} catch (Exception $e){

        	return $e;
        
    }
    
    
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65e90eb8-e279-2ed3-e519-e21037f16478
* Version Independent ID: 05f403fa-7fe8-0d4f-68d4-009181fc2132
* Content: [Create temporaryAccessPassMethod - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/authentication-post-temporaryaccesspassmethods?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @tilarso
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Teejer** [comment]
well I figured my issue out.
`use Microsoft\Graph\Generated\Model\TemporaryAccessPassAuthenticationMethod;`
should be 
`use Microsoft\Graph\Generated\Models\TemporaryAccessPassAuthenticationMethod;`

**Comment by FaithOmbongi** [comment]
Thank you @Teejer for identifying the problem. I'll proceed to close this issue.
