### ISSUE TITLE
Least/Higher Privilege Swapped

### ISSUE THREAD

**Issue by jbnable** [microsoftgraph/microsoft-graph-docs-contrib#8975]
The Least Privileged section of the table is swapped with the Higher Privileged section. Read/Write is higher than Read.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa296054-6c96-8bdb-c170-cbf094f058d5
* Version Independent ID: 5e781010-697d-10e9-f448-da588612d590
* Content: [Get teamworkTag - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/teamworktag-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and update the doc.

**Comment by ChetanSharma-msft** [comment]
Hello @RamjotSingh - Please help to check and update the documentation.

**Comment by v-sdhakshina** [comment]
Raised pull request https://github.com/microsoftgraph/microsoft-graph-docs/pull/23343 to update the documents.

**Comment by Meghana-MSFT** [comment]
PR has been raised to update the doc, changes will reflect in the doc once the PR is merged.

**Comment by Lauragra** [comment]
@jbnable , thanks for filing this issue; we have merged the docs PR and the fix will go live today.
