### ISSUE TITLE
User Principal Name field says "(Unknown)"

### ISSUE THREAD

**Issue by PaulFeaser** [microsoftgraph/microsoft-graph-docs-contrib#8980]
[Enter feedback here]
the User Principal Name field says "(Unknown)" for everything as of Dec 22, 2023.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d5bc441-99d4-0e12-cd62-214e4c78d3d4
* Version Independent ID: e5770dea-769f-47dc-6c3b-12b49ca3aaf6
* Content: [reportRoot: getMailboxUsageDetail - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/reportroot-getmailboxusagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/reportroot-getmailboxusagedetail.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @sarahwxy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by DanielBradley1** [comment]
I don't get this issue. Can you post an example of the request you made? (not the result or any data..)

**Comment by PaulFeaser** [comment]
> I don't get this issue. Can you post an example of the request you made? (not the result or any data..)

This is an issue with /reports/getEmailActivityUserDetail
/reports/getMailboxUsageDetail in the DoD cloud.  A ticket has been opened and being worked.
