### ISSUE TITLE
WithUrl is no longer a valid option as a method on GetAsync

### ISSUE THREAD

**Issue by hopsusa** [microsoftgraph/microsoft-graph-docs-contrib#8981]
The 'WithUrl' example does not appear to be valid based on the latest SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d558deeb-3492-230e-b2d9-8d9efeb6f97f
* Version Independent ID: bb2e0da9-acb9-0ffa-7fb6-d1bb534bfd20
* Content: [Page through a collection using the Microsoft Graph SDKs - Microsoft Graph](https://learn.microsoft.com/en-us/graph/sdks/paging?tabs=csharp)
* Content Source: [concepts/sdks/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/sdks/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
@jasonjoh, can you assist here? Thanks.

**Comment by darrelmiller** [comment]
@hopsusa WithUrl should still be available.  I see 8.8K implementations of WithUrl in the latest SDK code https://github.com/search?q=repo%3Amicrosoftgraph%2Fmsgraph-sdk-dotnet%20WithUrl&type=code  
Can you share the specific example where you are not seeing WithUrl available?
Removing this would be a breaking change and if we did remove it, there should be a major version bump.

**Comment by jasonjoh** [comment]
`WithUrl` is present in the latest major version of the C#, Go, and PHP SDKs.
