### ISSUE TITLE
problem provisioning sharepoint folder

### ISSUE THREAD

**Issue by Ballzer0** [microsoftgraph/microsoft-graph-docs-contrib#8982]
quote: _When you create a private/shared channel, the SharePoint site might fail to provision. If the site fails to provision after 5 minutes, use the [Get filesFolder](https://learn.microsoft.com/en-us/graph/api/channel-get-filesfolder) API to trigger provisioning._

This does not seem to work, i have repeatedly tried to call the "get-files-folder" API for days and months for some teams rooms. The only thing that seems to solve the problem is if a user navigates to the private team-channel in question, and manually clicks the "files" tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create channel - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Ballzer0** [comment]
This is honestly the same issue. https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/4452

This needs to get escalated. It was fine that this was a little buggy in 2020 when teams was a brand new product, but not being able to pre-provision our rooms with the correct setup in 2024 is honestly unacceptable.

If it cant be fixed, a suitable workaround should at least be added to the documentation.

The previous issue did not get solved. They added an internal process to get their employees to click the "files tab"
<img width="473" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/28560729/44a22e05-19ef-4ab3-9367-3b00b1754aa4">

**Comment by ChetanSharma-msft** [comment]
Hello @Ballzer0 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
We checked this at our end and it is working fine at our end. Sharepoint site gets created as soon as we create a private channel. 

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/81138249/8d7cd841-703a-459f-b2a2-2e1c5779dc31)

**Comment by Ballzer0** [comment]
> We checked this at our end and it is working fine at our end. Sharepoint site gets created as soon as we create a private channel.
> 
> ![image](https://private-user-images.githubusercontent.com/81138249/297004186-8d7cd841-703a-459f-b2a2-2e1c5779dc31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NzM0ODgsIm5iZiI6MTcwNTU3MzE4OCwicGF0aCI6Ii84MTEzODI0OS8yOTcwMDQxODYtOGQ3Y2Q4NDEtNzAzYS00NTlmLWIyYTItMmUxYzU3NzlkYzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEwMTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMjU5NzIxNGE4NGVlODFkMWJmYWQwNTliNTE0YzYzYTkzOTk4N2MyY2RhNjJjYWZmOGJmZTlhNGM5MDVkODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BYXmB0lUmgJrW9HKkcSpZa9PWTb6mUKGhE8ysaihpaY)
> 
> If the site provisioning is delayed due to failures, there are different ways that trigger site provisioning for the private channel, one of which is visiting the Files tab. In such a case, the site provisioning gets retriggered (which you observed as well) followed by the channel membership (members + admins) sync to the site in a background operation. If this also encounters failures, we have a user-triggered background periodic sync (24-48 hrs) from the client that will sync channel membership to the channel site. That will eventually sync the membership to the site.
> 
> Let me know if that is not happening for you, if so please share the logs including the team id, channel id, tenant id.

Its still an issue on our end.. the screenshot you took is of the "files tab" that means you have visited it already.

* Can you find the drive via the graph api, without ever having visited the site manually?
* Do you have an email or something where i can share logs and diagnostic information? Its against our policy to share these details online

**Comment by Meghana-MSFT** [comment]
Please share these details at [microsoftteamsdev@microsoft.com](mailto:microsoftteamsdev@microsoft.com).

**Comment by Ballzer0** [comment]
> Please share these details at [microsoftteamsdev@microsoft.com](mailto:microsoftteamsdev@microsoft.com).

just sent you an email with our diagnostic information. Just titled the email with "Github issue 8982"

**Comment by Ballzer0** [comment]
according to the documentation. the provisioning of sharepoint resources should have been "self healing" as my requests to the "Get filesFolder" should have fixed the issue.
<img width="480" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/28560729/a2fea761-ca41-49cc-b2fb-e1f288119a0b">

but this does not seem to be working.

**Comment by Ballzer0** [comment]
> @Ballzer0 - Thank you for additional details, could you also share the request id and timestamp for channel creation. Looks like you shared request id for accessing sharepoint folder. Please share the channel creation logs as well.

unfortunetly i dont have that request id. We only have logs of failed requests.

**Comment by Ballzer0** [comment]
> > @Ballzer0 - Thank you for additional details, could you also share the request id and timestamp for channel creation. Looks like you shared request id for accessing sharepoint folder. Please share the channel creation logs as well.
> 
> unfortunetly i dont have that request id. We only have logs of failed requests.

@Meghana-MSFT  is this issue just going to die since i cant find any channel creation logs?

**Comment by Meghana-MSFT** [comment]
We shared the details shared by you with engineering team. We will follow up and get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @Ballzer0 - Thanks for sharing the information.
We will look into it and let you know the updates.
