### ISSUE TITLE
Device.ReadWrite.All permissions incorrect for application auth

### ISSUE THREAD

**Issue by DanielBradley1** [microsoftgraph/microsoft-graph-docs-contrib#8986]
Device.ReadWrite.All shows the following description for application permissions:

Allows the app to read and write all device properties without a signed-in user. Does not allow device creation, device deletion or update of device alternative security identifiers.

This is not true, Device.ReadWrite.All **does** support the device delete action.

Thank you
Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9edcc46d-c145-fad7-a54c-52c21f05ab7c
* Version Independent ID: 8b6bcf33-b048-2d3c-33b5-5a3dd5d25a75
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://learn.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/permissions-reference.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @DanielBradley1 for raising this issue.

@SanDeo-MSFT, @myra-ramdenbourg - The [permissions table in the Delete device API ref doc also supports the issue _Device.ReadWrite.All_ app permission supports the delete action](https://learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-1.0&tabs=http#permissions). Can you help to correct the permission description in the permissions model? Filed internal bug 2794573.

**Comment by FaithOmbongi** [comment]
I've filed internal bug 2820645 assigned to @SanDeo-MSFT. The permission descriptions are automatically generated from internal data that are also available on the Microsoft Graph service principal. So, the description can only be fixed upstream, and the changes will be propagated to the permissions reference during one of the weekly refreshes.

I'll close this task here and track it via the internal work item. Thank you @DanielBradley1.
