### ISSUE TITLE
Error in documentation - section Roles property values

### ISSUE THREAD

**Issue by WimStevens** [microsoftgraph/microsoft-graph-docs-contrib#8990]
The documentation specifies following values for the roles property: read, write, owner
The value of owner is not correct.  Should be fullcontrol

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1191235c-879e-dffc-82eb-4e8f7edfd29c
* Version Independent ID: 322f9be4-7921-41d8-78c2-2bdc62f916a3
* Content: [Permission - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/permission.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @spgraph-docs-team
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this will be tracked here: https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8945
