### ISSUE TITLE
Permission clarification

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs-contrib#8997]
Hi folks,

I know this is still in beta and all, but there seems to be a discrepancy with the required permissions. According to the current information in the document, for application permissions Directory.Read.All should be sufficient to request the report. But it results in the following:

``{"error":{"code":"Authentication_MSGraphPermissionMissing","message":"Calling principal does not have required MSGraph permissions
     | AuditLog.Read.All","innerError":{"date":"2024-01-08T09:15:19","request-id":"dabfb89f-d8ac-43e1-8f39-f15818a9f306","client-request-id":"dabfb89f-d8ac-43e1-8f39-f15818a9f306"}}}``

Adding AuditLog.Read.All does the job. But obviously, Directory.Read.All does not "contain" said scope, so it's not sufficient on its own.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9289d31-d818-9d8f-b2ad-e15fceb13c62
* Version Independent ID: c76f0fd1-f4c6-00f1-bbe4-533b2390501f
* Content: [List servicePrincipalSignInActivities - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/reportroot-list-serviceprincipalsigninactivities?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/beta/api/reportroot-list-serviceprincipalsigninactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/reportroot-list-serviceprincipalsigninactivities.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @madansr7
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by madansr7** [comment]
@Jackson-Woods can you please help.

**Comment by madansr7** [comment]
@michevnew thanks for bringing this up. The docs need an update. This API should require AuditLog.Read.All. 
I will get that updated shortly.
