### ISSUE TITLE
Expiry details for the DeltaToken Used in Delta query to track changes

### ISSUE THREAD

**Issue by kmuguda** [microsoftgraph/microsoft-graph-docs-contrib#9003]
We are currently using Delta Query to track the changes of groups and users.

We are using delta token either by getting the latest token or by following the 2 step procedure mentioned in the guidelines below.

https://learn.microsoft.com/en-us/graph/delta-query-overview

https://learn.microsoft.com/en-us/graph/delta-query-groups?tabs=http

We are able to get the track changes successfully using above two methods.

Following are the queries which we have w.r.t to Delta Token's

What is the expiry date for the delta token we got from latest token api ($deltaToken=latest) ?
What is the expiry date for the delta token we got from 2 step procedure (@odata.deltaLink) ?
is there any way to check if the token that we have got is expired or active ? any api ?
If we are using any expired token do we get any error while using it in API's or SDK's
In one of the article

https://devblogs.microsoft.com/microsoft365dev/duration-of-change-tracking-tokens-for-identity-and-education-resources/#:%7E:text=Effective%20today%2C%20delta%20links%20for,of%20thirty%20(30)%20days.

we see that expiration of delta token is 7 days.

But we did little bit experimenting and tried to use token which is 2 weeks old and it was working

So we needed clarity on expiration of deltatoken that we get in both the methods.

Can you please help us on this regard on getting the answers.

-Thanks

Krishna

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66201f1c-504b-eba2-f489-c611523fdf8d
* Version Independent ID: 5c711b4f-e234-ae03-53e5-ecd206a157ff
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://learn.microsoft.com/en-us/graph/delta-query-overview)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/delta-query-overview.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @kmuguda for raising this issue. Here's the documentation for [delta token duration for different resources](https://learn.microsoft.com/en-us/graph/delta-query-overview#token-duration). These limits apply to both methods. Also, yes, you get an error for expired tokens.

> But we did little bit experimenting and tried to use token which is 2 weeks old and it was working

I'm not sure about this but I recommend you work with the lower value of 7 days for that resource to avoid surprises. To provide a more conclusive answer whether the token worked, you'll need to file the issue at [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) and provide the request ID for further investigation.
