### ISSUE TITLE
Inconsistent information

### ISSUE THREAD

**Issue by BenWhite27** [microsoftgraph/microsoft-graph-docs-contrib#902]
This page suggests to use resumable file transfers for files larger than 10MiB however the DriveItem PUT page (https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0) states that the max upload size is 4MB for the simple upload option.

"Use resumable file transfers for files larger than 10 MiB (10,485,760 bytes)."
and
"This method only supports files up to 4MB in size."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c42d74d1-8c6f-5282-9fba-30fdd6449362
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [Resumable file upload - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
