### ISSUE TITLE
Default size is 100, maximum size is 65535, minimum is 1

### ISSUE THREAD

**Issue by jcoolsen** [microsoftgraph/microsoft-graph-docs-contrib#9021]
It turns out that if you do not specify a size for the aggregationOption, the maximum number of buckets returned are 100. The maximum value accepted by the system for size property seems to be 65535. Also 1 is the smallest size accepted.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39355919-87e3-171b-a59d-8ad16ca1e110
* Version Independent ID: 4e6080b0-fb19-437d-724b-fee466f788a3
* Content: [aggregationOption resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/aggregationoption?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/aggregationoption.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @njerigrevious
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
PR https://github.com/microsoftgraph/microsoft-graph-docs-contrib/pull/9245 fixes this issue.
