### ISSUE TITLE
Include case members in response metadata

### ISSUE THREAD

**Issue by joshammons** [microsoftgraph/microsoft-graph-docs-contrib#9027]
Please include case members metadata in the response object for this API call (or another API call if it makes more sense).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91216be2-a5b6-e2de-05c2-695a1b2766d0
* Version Independent ID: 2e4c3ac3-ea36-44b8-decf-4bb4390a6f4d
* Content: [ediscoveryCase resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/security-ediscoverycase?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/security-ediscoverycase.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/security-ediscoverycase.md)
* Product: **ediscovery**
* Technology: **microsoft-graph**
* GitHub Login: @SeunginLyu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by SeunginLyu** [comment]
hi @joshammons , thanks for your feedback. We are actively developing on a new Graph API endpoint to manage case members and role groups for a case. We don't have an ETA yet but we'll communicate via M365 roadmap once the release dates are locked in. Thanks
