### ISSUE TITLE
onlinemeetings link needs fixing in http area.

### ISSUE THREAD

**Issue by ganlbarone** [microsoftgraph/microsoft-graph-docs-contrib#9028]
The http sample on this page states onlinemeeting which is not correct, its onlinemeetings. Should be fixed  I got stuck on this due to this doc issue...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13524c81-6f56-4a14-8c03-647a8baefb97
* Version Independent ID: 58b1383d-86ed-c650-ebed-4d124a4cd9b1
* Content: [onlineMeeting: getAllTranscripts - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/onlinemeeting-getalltranscripts?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/onlinemeeting-getalltranscripts.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/onlinemeeting-getalltranscripts.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @jacobsatora
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ganlbarone** [comment]
Exactly. Was super frustrating because that little typo there caused me much strife :)

**Comment by v-sdhakshina** [comment]
Updated the doc through pull request https://github.com/microsoftgraph/microsoft-graph-docs/pull/23416

**Comment by ganlbarone** [comment]
I cant view that, but Im sure someone can and will approve your pull :)

**Comment by Prasad-MSFT** [comment]
PR has been merged. So, closing the issue.
