### ISSUE TITLE
Relationship Request status 'failed' meaning; explicit rejection?

### ISSUE THREAD

**Issue by 1nickt** [microsoftgraph/microsoft-graph-docs-contrib#9030]
Hi all, 

is there a way that the customer can explicitly reject the relationship request, or is not accepting it all they can do?
Does the 'failed' status for the request indicate that the customer rejected it? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d433d1a-290b-d150-b055-71c1e5f7a807
* Version Independent ID: a6b5d0be-d9ac-d406-d9ab-632b12a2e17a
* Content: [delegatedAdminRelationshipRequest resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/delegatedadminrelationshiprequest?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/delegatedadminrelationshiprequest.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/delegatedadminrelationshiprequest.md)
* Product: **partner-customer-administration**
* Technology: **microsoft-graph**
* GitHub Login: @koravvams
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by koravvams** [comment]
Hi @1nickt, currently, there is no option for customer to reject a relationship. "failed" status used if there is any internal processing error. Hope this helps. Thanks.
