### ISSUE TITLE
Wrong Federated identity credentials support scope

### ISSUE THREAD

**Issue by flash-me** [microsoftgraph/microsoft-graph-docs-contrib#9038]
Hello there,

the Section **Design Considerations** on the [Page](https://learn.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0#design-considerations) _"Overview of federated identity credentials in Microsoft Entra ID"_ states following: 

> Federated identity credentials are supported on applications only. [...] 

Which is... not true? We are using Federated Credentials together with **User Assigned Managed Identity** for quite some time. 

cheers
flash ⚡

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd2c231-5d5c-f5c2-ce5b-9e66b890745b
* Version Independent ID: 1eb57d56-5c8a-0984-ef01-972576dee1d2
* Content: [Overview of federated identity credentials in Microsoft Entra ID - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/federatedidentitycredentials-overview.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @nickludwig
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @flash-me for raising this issue. We'll investigate the proper endpoint for adding these credentials to managed identities and update the documentation.

**Comment by nickludwig** [comment]
Hey @flash-me - you're totally right... not sure how this went undetected. Thanks for opening the issue! I'll go ahead and submit a PR to remove that note.
