### ISSUE TITLE
Incorrect filter syntax for user

### ISSUE THREAD

**Issue by ssteiner** [microsoftgraph/microsoft-graph-docs-contrib#9043]
The page lists this filter as an example

~/users?$filter=companyName ne null

However, if you try to run this in the Graph explorer (or the .NET SDK), you'll get this response:

`
    {
        "error": {
            "code": "Request_UnsupportedQuery",
            "message": "Filter operator 'NotEqualsMatch' is not supported.",
            "innerError": {
                "date": "2024-01-22T13:06:43",
                "request-id": "87e4f0c5-b87c-48ab-9ac6-65b3ae8337ee",
                "client-request-id": "87e4f0c5-b87c-48ab-9ac6-65b3ae8337ee"
            }
        }
    }
`

So the documentation is incorrect and I'm left wondering how I can fetch all users that have a certain field not filled out (I also tried it with the 'city' attribute which is the one I actually want to filter on, but the response is the same)'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca630f7c-e88d-3b10-4ed1-3574dd415ad2
* Version Independent ID: ca630f7c-e88d-3b10-4ed1-3574dd415ad2
* Content: [Use the filter query parameter to filter a collection of objects - Microsoft Graph](https://learn.microsoft.com/en-us/graph/filter-query-parameter?tabs=http)
* Content Source: [concepts/filter-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/filter-query-parameter.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Hi @ssteiner - Please take note of the * next to the example and the explanation in the note block before the table.

<img width="538" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/14026935/fc12b1ba-4365-48e6-babe-096d94276252">

Therefore, you must add `$count=true` query string and setting the **ConsistencyLevel** header to `eventual` for the example.

I'll investigate a better way to make this disclaimer more visible.
