### ISSUE TITLE
We should document that UserPrincipalName is always returned in all-lowercase for this API

### ISSUE THREAD

**Issue by mbukovich** [microsoftgraph/microsoft-graph-docs-contrib#9049]
For the /auditLogs/signIns API, the UserPrincipalName property is returned in all-lowercase by design. This also affects filters on UserPrincipalName. 

Perhaps this can be documented here in the properties section or perhaps as a note in the "list signIns" article.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61cf8069-b779-ea2a-c02a-c8efd2e18019
* Version Independent ID: 9a912f06-6ffd-d5c9-de30-66c8fff1d578
* Content: [signIn resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/signin.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @egreenberg14
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
@egreenberg14 - Can you help validate whether this is a bug or intentional, and the case-sensitivity issue? Thanks.

**Comment by FaithOmbongi** [comment]
Closing this issue in readiness for deactivation of GitHub issues. See this post for more information https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/9146.

@egreenberg14 has confirmed this is a known issue and has an active bug to track its resolution.
