### ISSUE TITLE
B2C is not supported

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/microsoft-graph-docs-contrib#9052]
Update article to explicitly call out that B2B Invitation API should not be used or is intended for B2C user creation/invite. B2C does not have a equivalent service.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15c0170d-e214-ce6f-b7b4-589960e9962d
* Version Independent ID: bc805140-9ebe-a4ef-54e7-90f2054b8b83
* Content: [invitation resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/invitation.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/invitation.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @ppolkadots
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @willfiddes for raising this issue. Please check the first sentence on the page that mentions the scope of invitations. Let me know if this isn't adequate.

**Comment by FaithOmbongi** [comment]
Hi @willfiddes - If the description in the documentation doesn't currently address this issue, please feel free to reopen it. I'll close it for now.
