### ISSUE TITLE
Incorrect permissions for delegate scenario

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs-contrib#9059]
I know this has been reported previously for application permission scenarios, but in the delegate permissions model, RoleAssignmentSchedule.Read.Directory is also NOT sufficient to run a query, despite what the documentation currently says. Can you please address this?

None of the other read-only permissions listed in the table work either, so you might as well remove them too (RoleManagement.Read.All, RoleManagement.Read.Directory)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 820646e2-296c-2fea-4a5e-4b799188f6e0
* Version Independent ID: d153abb2-c891-54fa-9586-2026d843e56d
* Content: [List roleAssignmentScheduleRequests - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignmentschedulerequests?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/rbacapplication-list-roleassignmentschedulerequests.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/rbacapplication-list-roleassignmentschedulerequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @rkarim-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
@rkarim-ms, @mandardalvi - Can you help investigate this issue and fix any errors in the permissions model? Thanks.

**Comment by FaithOmbongi** [comment]
UPDATE: We have replicated the issues and I've filed an internal bug number 2823877, assigned to @rkarim-ms, for fixes to be done. 

The permissions information is read from an internal metadata source and the changes must be made to these sources and then cascaded to the docs.

**Comment by MartinM85** [comment]
@FaithOmbongi Great new, thanks for investigation. I see a lot of endpoints are affected and it's really confused for developers.

**Comment by FaithOmbongi** [comment]
Closing this issue in readiness for deactivation of GitHub issues. See this post for more information https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/9146.

I'm actively tracking the internal bug for resolution.
