### ISSUE TITLE
GetAllSites returns an access denied error

### ISSUE THREAD

**Issue by barisbikmaz** [microsoftgraph/microsoft-graph-docs-contrib#9064]
When I call the API "https://graph.microsoft.com/v1.0/sites/getAllSites" to list all my sites, I get the following error.

```
{
    "error": {
        "code": "accessDenied",
        "message": "Access denied",
        "innerError": {
            "date": "2024-01-29T12:03:12",
            "request-id": "06d4a0a7-385b-4a78-b75b-9ebd78fd0b5b",
            "client-request-id": "47c4bb7c-8f91-0a48-7af7-a2ab12cb31db"
        }
    }
}
```

1. I am a global SharePoint Administrator
2. I permitted the Sites.Read.All permission
3. https://graph.microsoft.com/v1.0/sites?search=* works
4. https://graph.microsoft.com/v1.0/sites?$select=displayName returns an empty array
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites(displayName)",
    "value": []
}
```
5. I have multiple site collections on my tenant
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/6338132/24907484-97b2-453d-9f4f-3e2f2e776ef9)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa6a649-138d-2848-3b9c-8cd099fef766
* Version Independent ID: 463edc49-ca62-b204-9fe6-5301d5246698
* Content: [sites: getAllSites - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/site-getallsites?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-getallsites.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/site-getallsites.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @tushar20
* Microsoft Alias: **tkanaujia**

**Comment by MartinM85** [comment]
I believe that delegated permissions are not supported and I have no reason why it was changed. I remember when this endpoint was introduced, it had support only for delegated permissions.

**Comment by MartinM85** [comment]
@jasonjoh Could you please check the commit https://github.com/microsoftgraph/microsoft-graph-docs-contrib/commit/2c095ade17381c2c4a6bcd0b815b630949d7734a
Seems like the permission table has been changed in this commit, but if it's autogenerated, there is a chance that support for delegated permissions was added by accident.

**Comment by MartinM85** [comment]
It's a bug in permissions model: https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/9059#issuecomment-1921068615
