### ISSUE TITLE
Only GET, POST, PUT, DELETE are allowed for $ref requests

### ISSUE THREAD

**Issue by mfamphlett** [microsoftgraph/microsoft-graph-docs-contrib#9069]
The documentation advises a PATCH request should be made. However, the API responds with an error advising PATCH requests are not allowed for $ref requests.

Request:
```HTTP
PATCH https://graph.microsoft.com/beta/identity/b2cUserFlows/B2C_1_new_sign_up_sign_in/userflowIdentityProviders/$ref

{
    "@odata.id": "https://graph.microsoft.com/beta/identity/identityProviders/OIDC-V1-...",
    "@odata.type": "#microsoft.graph.identityProvider"
}
```
Response:
```HTTP
{
  "error": {
    "code": "MethodNotAllowed",
    "message": "Only GET, POST, PUT, DELETE are allowed for $ref requests, but received: | PATCH",
    "innerError": {
      "date": "2024-01-30T17:47:29",
      "request-id": "ecf18dc6-7170-4a76-80fa-d2c5f9221ec1",
      "client-request-id": "711951fb-a2a6-48b3-b188-25fa6bae9286"
    }
  }
}
```

I have tried using the PUT verb but get the error `No HTTP resource was found that matches the request URI`:

```JSON
{
  "error": {
    "code": "UnknownError",
    "message": {
      "message": "No HTTP resource was found that matches the request URI | 'https: //cpim.windows.net/graph/identity/b2cUserFlows('B2C_1_new_sign_up_sign_in')/userFlowIdentityProviders/$ref'.",
      "messageDetail": "No type was found that matches the controller named | 'identity'.",
      "stackTrace": null
    },
    "innerError": {
      "date": "2024-01-30T18:39:23",
      "request-id": "15833dd9-c743-4641-98a1-f5524f464c65",
      "client-request-id": "343fdf9e-fb2b-41ef-89cd-be85a748f417"
    }
  }
}
```

However, a GET request to `https://graph.microsoft.com/beta/identity/b2cUserFlows/B2C_1_new_sign_up_sign_in/userflowIdentityProviders` is successful.

Seems like there may be 2 issues here:

1.  The documentation should say PUT not PATCH.
2.  The API endpoint appears to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff6ad13e-0a21-c437-7dbc-8c5446a6b6ff
* Version Independent ID: 58990963-f093-d61f-bd62-fa3f6afc2fc0
* Content: [Add a userFlowIdentityProvider - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/b2cidentityuserflow-userflowidentityproviders-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/b2cidentityuserflow-userflowidentityproviders-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/b2cidentityuserflow-userflowidentityproviders-update.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @namkedia
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mfamphlett** [comment]
@FaithOmbongi thanks for the update. Is there any way I can follow the progress on the bug fix? Or get a notification when it's been resolved?

**Comment by FaithOmbongi** [comment]
Hi @mfamphlett - From our engineers, the correct method is POST. Our engineers have raised this PR https://github.com/microsoftgraph/microsoft-graph-docs-contrib/pull/9097/files
