### ISSUE TITLE
The documentation needs updating on the format of the string to use.

### ISSUE THREAD

**Issue by seandhoey** [microsoftgraph/microsoft-graph-docs-contrib#907]
In regards to uploading to Document Libraries this does not work:
PUT /sites/{site-id}/drive/items/{item-id}/content
This does work:
PUT /sites/{site-id}/drives/{drive-id}/content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92fb8c7-4409-d945-57dd-5d6fc4010051
* Version Independent ID: f77c05bd-2688-bd4e-1f8f-f18feb3a8639
* Content: [Upload small files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
