### ISSUE TITLE
Select property on MS PowerShell is not working a excepted

### ISSUE THREAD

**Issue by nukala29** [microsoftgraph/microsoft-graph-docs-contrib#9070]
[Enter feedback here]
As per the belwo doc when you query the items through powershell you need add select parameter to the powershell command
It doesnt  work with out select
For example Get-MgUser -UserId $userId -Property "displayName,givenName,postalCode,identities"  this only retun the basci values like id,UPN ,mail,displayName
Get-MgUser -UserId $userId -Property "displayName,givenName,postalCode,identities" | Select displayName,givenName,postalCode,identities

https://learn.microsoft.com/en-us/powershell/microsoftgraph/use-query-parameters?view=graph-powershell-1.0#property-parameter
 lot of customer getting confuse why the data fields are not bale to reterive 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/user-get.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @nukala29 for raising this issue. Unfortunately, this forum is only for documentation-related issues for the REST API. For PowerShell issues, please file them in the [Microsoft Grap PowerShell SDK repo](https://github.com/microsoftgraph/msgraph-sdk-powershell).
