### ISSUE TITLE
Application permission for https://graph.microsoft.com/v1.0/users/{id}/memberOf

### ISSUE THREAD

**Issue by gpochtar** [microsoftgraph/microsoft-graph-docs-contrib#9076]
https://graph.microsoft.com/v1.0/users/{id}/memberOf works with Application permissions.
Docu states that this is not supported.
Please correct the docu.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9188ffdb-b7af-597d-9e0a-d92e75ff8e7d
* Version Independent ID: c4427823-3f37-dc4b-ac1e-b750cb633e23
* Content: [List a user's direct memberships - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/user-list-memberof.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @gpochtar for raising this issue. I've filed an internal bug for the issue 2823937 to be investigated and resolved.  The permissions information for the APIs is fetched from an upstream source so the fixes will be made upstream and cascaded into the docs.

**Comment by FaithOmbongi** [comment]
Closing this issue in readiness for deactivation of GitHub issues. See this post for more information https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/9146.

We'll track the issue via the internal bug.
