### ISSUE TITLE
Error get hostedcontents notes-chat

### ISSUE THREAD

**Issue by ZUS666** [microsoftgraph/microsoft-graph-docs-contrib#9078]
I'm trying to get bytes of hosted content by application.
I receive information normally from: v1.0/chats/19:teamsstream_notes_{user_id}@thread.v2/messages/{message_id}/hostedContents/{id}
but if i try to get bytes from: v1.0/chats/19:teamsstream_notes_{user_id}@thread.v2/messages/{message_id}/hostedContents/{id}/$value I get response status 403.
I checked the permissions according to the documentation(Application | Chat.Read.All, Chat.ReadWrite.All)
for example with oneOnOne chats all work normal

`{
    "error": {
        "code": "Forbidden",
        "message": "UnknownError",
        "innerError": {
            "date": "2024-02-01T12:03:46",
            "request-id": "eaa13c7c-4916-43ee-8329-17276df74097",
            "client-request-id": "eaa13c7c-4916-43ee-8329-17276df74097"
        }
    }
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f67cabe4-bade-9a07-90ec-15adaeab3de2
* Version Independent ID: dfbbddfe-f113-1ae1-9d21-77ab976ddc20
* Content: [Get chatMessageHostedContent - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/chatmessagehostedcontent-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
We checked this at our end for One-One chat and group chat, it is working fine in both cases.

Below is a screenshot for Group chat. 
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/81138249/a3581c5b-0189-4948-a23e-1b0ebcaff092)

**Comment by ZUS666** [comment]
> Could you please confirm if you are still facing this issue?

chat_id =19:teamsstream_notes_{user_id}@thread.v2
This is the user's chat with himself (notes)

**Comment by Meghana-MSFT** [comment]
Currently there is no Graph API support for chat with self.

**Comment by ZUS666** [comment]
> Currently there is no Graph API support for chat with self.

But receiving messages for example works fine. The problem is permissions. I can receive messages with application permissions, and if the message contains hosted content, it is only available with delegated permissions. I think this is strange.

**Comment by Meghana-MSFT** [comment]
We will check this internally and get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @ZUS666 - Sorry for delay in response.
We area actively checking the updates on your issue with engineering team and let you know the updates if any.

**Comment by Meghana-MSFT** [comment]
@ZUS666 - We received the following update from engineering team. 
The hosted content for self chat in application context is not currently supported.
