### ISSUE TITLE
Metadata omitted from example response

### ISSUE THREAD

**Issue by cschoder** [microsoftgraph/microsoft-graph-docs-contrib#908]
When I attempt a similar request to the example, considerable metadata about the list items is also returned.  Could this document show how to request a simple response containing only the values for list items? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2524650e-06e7-dc8c-b2ae-0c2fbffdb541
* Version Independent ID: 3eb41d73-2b60-1459-e921-20403004655c
* Content: [Retrieve items from a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/listitem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-list.md)
* Product: **sharepoint**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
