### ISSUE TITLE
Incorrect specification for `$search`

### ISSUE THREAD

**Issue by RosyGraph** [microsoftgraph/microsoft-graph-docs-contrib#9080]
The docs here give an example of using the `$search` parameter which enquotes each side of the `OR` connective. This does not seem to work for the `messages` endpoint, and the query responds with no search applied. Rather, the requester needs to enquote the entire search parameter when requesting.

I suggest changing the example here (and many other places in the docs!) to use the correct quoting syntax.

```diff
-../groups?$search="description:One" AND ("displayName:Video" OR "displayName:Drive"
+../groups?$search="description:One AND (displayName:Video OR displayName:Drive)"
```

Another point, though not directly related to this incorrect specification, the example was missing a closing parenthesis which I added ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7415c6-cfbb-27a1-109c-78aa85e69cef
* Version Independent ID: dfd0a8f0-b01d-baab-67aa-a64eb39d3224
* Content: [Use the $search query parameter in Microsoft Graph - Microsoft Graph](https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http)
* Content Source: [concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/search-query-parameter.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @ranok for raising this issue. Please note that the sample you're referencing relates only to directory (Microsoft Entra ID) objects. For messages, this is the correct part to reference [Using $search on message collections](https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http#using-search-on-message-collections) and it matches your feedback. Hope this answer clarifies the article.

**Comment by ranok** [comment]
@FaithOmbongi I'm guessing your mention of me was a mistake and you meant to mention @RosyGraph ?
