### ISSUE TITLE
(Tutorial Sample App) is disabled

### ISSUE THREAD

**Issue by jmtread** [microsoftgraph/microsoft-graph-docs-contrib#9082]
Hi There

There is a link on this page to a sample application.
When you click on the link and login I am presented with an error message that says
"(Tutorial Sample App) is disabled."

AADSTS7000112: Application '6731de76-14a6-49ae-97bc-6eba6914391e'(Tutorial Sample App) is disabled.

Perhaps it's worth removing that section of the page if the sample app can not be reactivated.

**Webpage with the issue**
https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http#use-the-microsoft-authentication-library-msal:~:text=to%20True.-,Try%3A%20You%20can%20try,-this%20for%20yourself

**Text From Page**
Try: You can try this for yourself by pasting the following request in a browser. If you sign in as a global administrator for a Microsoft Entra tenant, you will be presented with the administrator consent dialog box for the app.

https://login.microsoftonline.com/common/adminconsent?client_id=6731de76-14a6-49ae-97bc-6eba6914391e&state=12345&redirect_uri=https://localhost/myapp/permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04f96510-c628-47f8-971f-d5ba7b560efc
* Version Independent ID: f27f8646-1313-f225-b315-1ae3bc036117
* Content: [Get access without a user - Microsoft Graph](https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/auth-v2-service.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @jmtread for raising this issue. I'll remove the link because the sample app that was used for this example can't be restored for now.
