### ISSUE TITLE
More detail needed

### ISSUE THREAD

**Issue by jhoneill** [microsoftgraph/microsoft-graph-docs-contrib#909]
In common with a lot of the pages on the graph API there is a token example. How does one create an item  look up field or, as I have spent a morning on now, a field with an "AssignedTo" column which points to a user ? Getting the item returns AssignedToLookupID and if I follow the instructions at 
https://docs.microsoft.com/en-us/graph/api/resources/fieldvalueset?view=graph-rest-1.0
I can expand the fields to show AssignedTo "title" from the users list where the ID is seen. But I try assignedTo = name, title or ID from that table the request runs but the column is not set. If I include AssignedToLookupID = 14 or ="14" I get a 400 error from the server. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa7a3906-32dd-fab9-a6f4-a5f8e55429ce
* Version Independent ID: 088ac63e-886e-71f2-bc9b-36f25f93305a
* Content: [Create a new entry in a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-create?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/listitem-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-create.md)
* Product: **sharepoint**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
