### ISSUE TITLE
ReadWrite application permissions needed to list privileged access groups

### ISSUE THREAD

**Issue by glennvanrymenant** [microsoftgraph/microsoft-graph-docs-contrib#9091]
PrivilegedAccess.Read.AzureAD or PrivilegedAccess.Read.AzureADGroup are not sufficient to LIST PAGs (beta/privilegedAccess/aadGroups/resources).

Why is PrivilegedAccess.Read**Write**.AzureAD(Group) needed to simply list all PAGs?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96a6a4a5-3932-8412-8d76-6a4d14ffa4e6
* Version Independent ID: f007865b-fae1-e2fe-957f-d346888aa377
* Content: [List governanceResources - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/governanceresource-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/governanceresource-list.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/governanceresource-list.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @rkarim-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by glennvanrymenant** [comment]
*in application context

**Comment by FaithOmbongi** [comment]
Closing this issue in readiness for deactivation of GitHub issues. See this post for more information https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/9146.

We'll track the issue via the internal bug.
