### ISSUE TITLE
Example of appScope for directory provider

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#9101]
Could you please provide some examples of `appScope` for directory provider? 

For now, it's not clear whether the `appScope` can be used in context of directory provider.

Some other parts of the Graph API doc mention only `AccessPackageCatalog` as an example of `appScopeId`, but only in context of entitlement management provider.

`/AccessPackageCatalog/{catalog id}`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e310667-fe92-98e7-9612-91ea27e7dcf0
* Version Independent ID: f54ab59a-1f99-d23f-756d-03874fa857bb
* Content: [appScope resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/appscope.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi 
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @MartinM85 for raising this issue.

@markwahl-msft , @DougKirschner - Can you assist here? Thanks.

**Comment by FaithOmbongi** [comment]
I notice when [creating role assignments](https://learn.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&tabs=http#example-4-create-a-role-assignment-with-access-package-catalog-scope), appScope is the only allowed object for access package catalog. Role assignments for the directory provider seems to only support directoryScope

**Comment by markwahl-msft** [comment]
Correct, example 4 of https://learn.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&tabs=http#example-4-create-a-role-assignment-with-access-package-catalog-scope illustrates the use case where an `appscopeid` field is used when creating a role assignment.

**Comment by MartinM85** [comment]
@markwahl-msft If I want to [request role activation](https://learn.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignmentschedulerequests?view=graph-rest-1.0&tabs=http) for a user with access package catalog scope, I need to call

`https://graph.microsoft.com/v1.0/roleManagement/entitlementManagement/roleAssignmentScheduleRequests` and specify `appScopeId`

And there is no case to specify `appScopeId` when calling `https://graph.microsoft.com/v1.0/roleManagement/directory/roleAssignmentScheduleRequests`.

When calling `https://graph.microsoft.com/v1.0/roleManagement/entitlementManagement/roleAssignmentScheduleRequests` is there any role which requires `directoryScopeId`?

Maybe some remark that directory provider requires directoryScopeId and entitlementManagement provider requires appScopeId would be useful for developers.

**Comment by FaithOmbongi** [comment]
Closing this issue in readiness for deactivation of GitHub issues. See this post for more information https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/9146.

I'm following up with @markwahl-msft on the doc update request relating to this statement "Maybe some remark that directory provider requires directoryScopeId and entitlementManagement provider requires appScopeId would be useful for developers."
