### ISSUE TITLE
Cannot Get Call Transcripts after creating meeting using onlineMeeting: "This API is supported only for calendar backed OnlineMeeting"

### ISSUE THREAD

**Issue by tfischer2** [microsoftgraph/microsoft-graph-docs-contrib#9103]
I am getting an error when attempting to use the list transcripts api on a meeting created with the online meetings api:

`"No iCalUid found for the meeting. This API is supported only for calendar backed OnlineMeeting."`

There was a previous issue reported on a similar api here:  https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8869

An alternate solution was indicated there.  However, the alternate solution does not allow certain fields to be set when creating the meeting, eg 'recordAutomatically'. Is the intended behavior that Get Call Recordings/Get Transcripts api is only supported for events/calendar backed meetings? If so, it should be noted in the documentation, and that the events api must be used instead if transcript retrieval is desired.  If this is not the intended behavior, is there an estimate on the time to fix? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e28ccbb9-55d4-65c9-e5e3-5c03c017d092
* Version Independent ID: f506a874-31cb-747a-fac2-cf28622f4103
* Content: [List transcripts - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/onlinemeeting-list-transcripts?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/onlinemeeting-list-transcripts.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/onlinemeeting-list-transcripts.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @v-sdhakshina
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tfischer2** [comment]
@v-sdhakshina Any idea on this?

**Comment by ChetanSharma-msft** [comment]
Hello @tfischer2 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Prasad-MSFT** [comment]
@tfischer2 - Thanks for raising this. List Transcripts API is only supported for meetings that are backed by a calendar. You need to ensure that the meeting you are working with is created using the [Online Meetings API and is backed by a calendar](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http#example-4-create-and-enable-an-event-as-an-online-meeting). This means that the meeting should be created through a calendar integration, such as Microsoft Exchange or Outlook.


We will discuss this with engineering team and will update the document accordingly. Thanks again!

**Comment by Prasad-MSFT** [comment]
@tfischer2 - It would be great if you provide the repro steps or any recording and share the exact Get call Transcripts query used here. Also, the fiddler traces captured while reproducing the issue will be helpful.

**Comment by tfischer2** [comment]
Sure thing:

`POST https://graph.microsoft.com/v1.0/me/onlineMeetings
Content-Type: application/json
{
    "startDateTime": "2024-02-16T10:00:00.0000000-07:00",
    "endDateTime": "2024-02-16T11:00:00.0000000-07:00",
    "subject": "Non calendar backed meeting"
}`

Response:
`{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('d2cb119f-d26c-4f4e-a4b8-2691b1c051c2')/onlineMeetings/$entity",
    "id": "MSpkMmNiMTE5Zi1kMjZjLTRmNGUtYTRiOC0yNjkxYjFjMDUxYzIqMCoqMTk6bWVldGluZ19abVl5TVdReFl6Y3ROMkk1T0MwMFlqTTFMV0V3TmpBdE4ySm1ORFprTXpObE4yUTNAdGhyZWFkLnYy",
    "creationDateTime": "2024-02-15T15:29:25.4150821Z",
    "startDateTime": "2024-02-16T17:00:00Z",
    "endDateTime": "2024-02-16T18:00:00Z",
...`

`GET https://graph.microsoft.com/v1.0/me/onlineMeetings/MSpkMmNiMTE5Zi1kMjZjLTRmNGUtYTRiOC0yNjkxYjFjMDUxYzIqMCoqMTk6bWVldGluZ19abVl5TVdReFl6Y3ROMkk1T0MwMFlqTTFMV0V3TmpBdE4ySm1ORFprTXpObE4yUTNAdGhyZWFkLnYy/transcripts

Response:
{
    "error": {
        "code": "PreconditionFailed",
        "message": "No iCalUid found for the meeting. This API is supported only for calendar backed OnlineMeeting.",
        "innerError": {
            "date": "2024-02-15T15:32:07",
            "request-id": "71baa94d-f0f8-4b79-968a-f83d51944b03",
            "client-request-id": "c334bd75-cce9-b707-e7a7-649e43623e6c"
        }
    }
}`

**Comment by tfischer2** [comment]
Any thoughts on how to address the underlying problem where we cannot set the 'recordAutomatically' flag on a meeting and subsequently retrieve the transcript for that same meeting?

**Comment by Prasad-MSFT** [comment]
@tfischer2 - Could you share the fiddler trace also as mentioned above?

**Comment by tfischer2** [comment]
Sure thing.  
[create_meeting_Full.txt](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/files/14313458/create_meeting_Full.txt)
[get_transcripts_Full.txt](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/files/14313459/get_transcripts_Full.txt)

**Comment by Prasad-MSFT** [comment]
Hi @tfischer2 - We got update from engineering team that "If the online meeting is not calendar backed fetching transcript is not supported." Engineering team is working on this to support for onlineMeetings not backed by calendar, however currently there is no ETA to share.

**Comment by Prasad-MSFT** [comment]
Hi @surbhigupta12 - Until the feature is supported, could you please help here to add a note in [this page](https://learn.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http#http-request) mentioning that "The [events API](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http#example-4-create-and-enable-an-event-as-an-online-meeting) must be used instead, if transcript retrieval is desired"

**Comment by v-sdhakshina** [comment]
Updated the doc through pull request https://github.com/microsoftgraph/microsoft-graph-docs/pull/23689.

**Comment by Prasad-MSFT** [comment]
@tfischer2 - Sorry, there is no such way to be found.

**Comment by tfischer2** [comment]
Thanks for all the useful information.  How can we open a ticket with engineering to get this addressed?  It seems to me that this very useful workflow (enabling 'recordAutomatically' on a meeting, then downloading the recording/transcript) should be possible in some way.

**Comment by Prasad-MSFT** [comment]
Hi @tfischer2 - The PR has been merged and document has been updated. To achieve your requirement of enabling 'recordAutomatically' on a meeting, then downloading the recording/transcript, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).


We are closing this issue for now. Please feel free to reopen if required. Thanks!
