### ISSUE TITLE
Incorrect python documentation for create group endpoint

### ISSUE THREAD

**Issue by klittlepage** [microsoftgraph/microsoft-graph-docs-contrib#9107]
Examples 2 and 3 reference `owners@odata_bind` and `members@odata_bind`, which are incorrect, and silently ignored. Changing them to `owners@odata.bind` and `members@odata.bind`, per the curl example, correctly binds owners and members.

```python
additional_data = {
	"owners@odata_bind" : [
		"https://graph.microsoft.com/v1.0/users/26be1845-4119-4801-a799-aea79d09f1a2",
	],
	"members@odata_bind" : [
		"https://graph.microsoft.com/v1.0/users/ff7cb387-6688-423c-8188-3da9532a73cc",
		"https://graph.microsoft.com/v1.0/users/69456242-0067-49d3-ba96-9de6f2728e14",
	],
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks for reporting this @klittlepage. I've logged this issue against our snippet generation tool, closing here.
