### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by abates100** [microsoftgraph/microsoft-graph-docs-contrib#9108]
Highlighted notes states:
The PowerShell commands for the profile card properties are only available in beta. Switch to the beta profile before you run the following commands.

Why when it is available?

https://learn.microsoft.com/en-us/powershell/module/Microsoft.Graph.Identity.DirectoryManagement/Get-MgAdminPeopleProfileCardProperty?view=graph-powershell-1.0 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a0e7861-2853-262b-e5e2-05d74a11b748
* Version Independent ID: d83704be-60f2-a1ff-e5af-ec6120148603
* Content: [Add or remove custom attributes on a profile card using the profile card API - Microsoft Graph](https://learn.microsoft.com/en-us/graph/add-properties-profilecard)
* Content Source: [concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/add-properties-profilecard.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @rwaithera
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rwaithera** [comment]
@abates100 we are updating the docs, and we will remove the note as part of he update. The PowerShell commands are available in v1.0. The commands are still named the same only without the 'beta' substring.
