### ISSUE TITLE
What actually is considered "recent" by the recent files API?

### ISSUE THREAD

**Issue by nkwolf** [microsoftgraph/microsoft-graph-docs-contrib#911]
Could you define "recently used" in terms of last accessed time ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a8c752b-abbb-c5d5-e4b5-771604aea187
* Version Independent ID: 8ca45129-5a6c-a98f-775f-6dfdd3aa0b35
* Content: [List Recent Files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/drive-recent?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/drive-recent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/drive-recent.md)
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
