### ISSUE TITLE
POST /format/borders is not working

### ISSUE THREAD

**Issue by manderson0404** [microsoftgraph/microsoft-graph-docs-contrib#9110]
https://graph.microsoft.com/v1.0/users('user guid')/drive/items/"workbookid"/workbook/worksheets('ESXI')/range(address='ESXI!E3')/format/borders

My body looks like this:
{
    "id": "EdgeTop",
    "color": "#000000",
    "style": "Continuous",
    "sideIndex": "EdgeTop",
    "weight": "Thin"
}

I am able to run this URL as a get and retrieve data. 

When I attempt to use this I get the following return message: 

{
    "error": {
        "code": "UnknownError",
        "message": "{\"error\":{\"innerError\":{}}}",
        "innerError": {
            "date": "2024-02-12T01:25:49",
            "request-id": "92302e35-bfe8-4e85-9c7c-baba9ff406c7",
            "client-request-id": "e3fb991a-af65-6026-5aa4-3b2aa33e698e"
        }
    }
}

The graph explorer also tells me the method is not allowed. I tried doing it as a patch instead of a post. There was no error but it also did not do anything. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1110ea1b-fde5-8e8a-a216-9dff16c2963d
* Version Independent ID: fa4aa191-72e2-7383-0b68-7155b839d5cb
* Content: [Create RangeBorder - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/rangeformat-post-borders?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/rangeformat-post-borders.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/rangeformat-post-borders.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PanKucher** [comment]
Hello, I am facing the same issue. Getting 405 error while running POST request to create Range Border. PATCH is giving back 200 but doesn't create anything.
