### ISSUE TITLE
Microsoft Graph API TransitiveMemberOf Permissions Wrong

### ISSUE THREAD

**Issue by ZackKorman** [microsoftgraph/microsoft-graph-docs-contrib#9112]
The permissions listed on Microsoft Graph API's documentation on getting the groups a user is a member of is wrong (https://learn.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&tabs=http). It says that application permissions are not supported for that request, and that is not true. It seems this change happened three weeks ago.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Microsoft Graph overview - Microsoft Graph](https://learn.microsoft.com/en-gb/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ZackKorman for reporting this bug.

The permissions information is fetched from an internal source so I've filed an internal bug # 2835902 for the upstream source to be fixed, then the changes will be propagated downstream to the docs.

**Comment by FaithOmbongi** [comment]
Duplicate of #https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/9076
