### ISSUE TITLE
Create Chat - but with a bot (chatbot)?

### ISSUE THREAD

**Issue by GauravES** [microsoftgraph/microsoft-graph-docs-contrib#9116]
For https://learn.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-1.0&tabs=http , how does one create a one-one chat where one participant is a chatbot  (not a regular user)?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82081351-eb89-7db1-02f8-a55fea5ad7e4
* Version Independent ID: e618b7e0-a6c0-7617-fb1a-265ead8a213d
* Content: [Create chat - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-1.0&tabs=http#permissions)
* Content Source: [api-reference/v1.0/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/chat-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
Hello @GauravES - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
We cannot use Create chat Graph API to create chat with bot. While installing a bot, it automatically creates 1-1 chat as well. You can refer this doc https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#deep-link-to-a-chat-with-the-application to create a deeplink which navigates to a personal chat with the application.
