### ISSUE TITLE
Suggestion Pageiterator 

### ISSUE THREAD

**Issue by rich2099** [microsoftgraph/microsoft-graph-docs-contrib#9117]
[Enter feedback here]

I think you should add a reference to the Pageiterator example for the c# directly. https://learn.microsoft.com/en-us/graph/sdks/paging?tabs=csharp or maybe even provide the code sample directly within page, as if you don't you won't always get a list of subscriptions, even if you only have one.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c121424-d0a2-017c-e40d-3552ea66915c
* Version Independent ID: 999939fe-62c4-e17c-e0b6-d46ef100ecb5
* Content: [List subscriptions - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/subscription-list.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrueastman** [comment]
Closing this for now. Suggestion made at https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1950 so that snippet generator may incorporate the changes.
