### ISSUE TITLE
Which properties are required for specific action

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#9119]
The endpoint `POST /roleManagement/directory/roleAssignmentScheduleRequests` allows to perform several actions

- Request active and persistent role assignments for a principal, with or without expiry dates.
- Activate
- Deactivate
- Extend
- Renew 

an eligible role assignment for a principal.

The property action is always required, but it's not clear which properties are required for each specific action. What's clear that `action`, `principalId`, `roleDefinitionId` and `directoryScopeId` (in case of directory provider) is always required.

When I need to specify `justification` and `scheduleInfo`?

|action|justification|scheduleInfo|
|:-|:-|:-|
|adminAssign|required|optional
|adminRemove|not needed|not needed|
|adminUpdate|?|?|
|adminExtend|?|?|
|adminRenew|?|?|
|selfActivate|?|?|
|selfDeactivate|?|?|
|selfExtend|?|?|
|selfRenew|?|?|

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13ee771f-39b3-6943-e226-2becdfe19ad2
* Version Independent ID: 9947ee0e-3e08-294c-8dd1-fe29045a96ab
* Content: [Create roleAssignmentScheduleRequests - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignmentschedulerequests?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/rbacapplication-post-roleassignmentschedulerequests.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/rbacapplication-post-roleassignmentschedulerequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi 
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @MartinM85 for asking this question.

justification and scheduleInfo being required or optional for activations (*Update, *Assign, *Extend, *Renew) are dependent on the [PIM rules/role settings](https://learn.microsoft.com/en-us/graph/identity-governance-pim-rules-overview) for that admin role. I think they are optional for adminRemove and selfDeactivate scenarios.
