### ISSUE TITLE
API's responses are different from the documentation

### ISSUE THREAD

**Issue by nandodebem** [microsoftgraph/microsoft-graph-docs-contrib#912]
Issue: 

We've been experiencing some odd behaviors that differ a lot from what's in the API's documentation, and we would be grateful if someone could help us.

===================================================================

When posting an invite to create a permission, we are not getting that permission's ID back in the response.

See the attached file:

![invite](https://user-images.githubusercontent.com/45804665/49837756-9eedc000-fd5c-11e8-8f59-fe57f684f684.jpg)

endpoint:
https://graph.microsoft.com/v1.0/groups/id/drive/items/id/invite

===================================================================

When listing the permissions, we get only about 40 results back. It's like a default value for a number of results in a first page, but we also get no "next link" to get the next results.

endpoint:
https://graph.microsoft.com/v1.0/groups/id/drive/items/id/permissions

===================================================================

If we try to change the page size to 3, for example, we still get no "next link" to go to the next page, but we do get 3 items in the response.

endpoint:
https://graph.microsoft.com/v1.0/groups/id/drive/items/id/permissions?$top=3

===================================================================

If we change the "top" parameter to 100, it still brings us about 40 items back in the response, but we have given a lot more permissions than that, so we know we should be getting more items. Still, no "next link" to go to the next page.

endpoint:
https://graph.microsoft.com/v1.0/groups/id/drive/items/id/permissions?$top=100

===================================================================

If we use the filter parameter, we still encounter the same problems of having one default page size, and a problem that seems worse than that. Apparently, we are filtering only this first default-sized page. So if I filter by "link/webUrl" and the item was in the first default page, we get the result back. If the item was created after those first items that are in the first page, we don't get it back.

endpoint:
https://graph.microsoft.com/v1.0/groups/id/drive/items/id/permissions?$filter=link/webUrl eq 'webUrl value'

===================================================================

These problems have created an issue where we can give permissions, but in most cases, we are unable to revoke those permissions, because we need its ID to delete it.
We need either the ID to be sent to us when we first create the permission, or the filter parameter to work properly when listing permissions.

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
