### ISSUE TITLE
TCS mispelled as TLC

### ISSUE THREAD

**Issue by chaitanya-SharePoint** [microsoftgraph/microsoft-graph-docs-contrib#9120]
Hi Team,

TCS is mispelled as TLC

<img width="1173" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/28508253/e76edbf5-86d5-48c4-9e78-562d42d36606">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4b4cd89-65ce-f111-4217-bb7c8e38ff7c
* Version Independent ID: 1853b3d0-3ada-c8c2-c732-70347c6b76c1
* Content: [Microsoft Graph Data Connect overview - Microsoft Graph](https://learn.microsoft.com/en-us/graph/data-connect-concept-overview)
* Content Source: [concepts/data-connect-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/data-connect-concept-overview.md)
* Product: **data-connect**
* Technology: **microsoft-graph**
* GitHub Login: @rimisra2
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
PR https://github.com/microsoftgraph/microsoft-graph-docs-contrib/pull/9253 addresses this issue.

**Comment by lramosvea** [comment]
Closing as this has been fixed already. Thanks.
