### ISSUE TITLE
msgraph.generated.models.provision_on_demand_post_request_body

### ISSUE THREAD

**Issue by pauliusmiskinis** [microsoftgraph/microsoft-graph-docs-contrib#9123]
```
ModuleNotFoundError: No module named 'msgraph.generated.models.provision_on_demand_post_request_body'
```

Python 3.11 
msgraph-sdk 1.1.0
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84b7a2b4-1a03-27e0-99a8-4902472d4d00
* Version Independent ID: 186d9f6a-38ab-c86b-9193-a47bf17c2664
* Content: [synchronizationJob: provisionOnDemand - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provisionondemand?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/synchronization-synchronizationjob-provisionondemand.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/synchronization-synchronizationjob-provisionondemand.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @ArvindHarinder1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
The correct line should be:

```python
from msgraph.generated.service_principals.item.synchronization.jobs.item.provision_on_demand.provision_on_demand_post_request_body import ProvisionOnDemandPostRequestBody
```

I've logged this issue with our snippet generation tool, closing here.
