### ISSUE TITLE
InsufficientPrivileges - list members of chat (meetting)

### ISSUE THREAD

**Issue by sunmont** [microsoftgraph/microsoft-graph-docs-contrib#9129]
I have put all required permission listed in the document for our app,
Can you please help me to figure out what permissions we missed ?
It used to work, just happened recently

request info:

Diagnostic details: client-request-id: 1159548f-9ff5-4aae-b3c8-8ec620e8060c
request-id: 85ed9a26-2168-4a31-97db-3e694f2f9cb8
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US 3","Slice":"E","Ring":"3","ScaleUnit":"000","RoleInstance":"PH1PEPF00011247"}}
timestamp: null
failedAttempts: 0
body: {"error":{"code":"Forbidden","message":"InsufficientPrivileges","innerError":{"code":"1","message":"AclCheckFailed-The initiator 28:app:83f6ee0f-8a6f-4b55-a425-d0f393fbe0d1_7aafc2b9-45fb-4c8d-8845-be4500a6d61c is not a member of the roster 3b77d52f-ba48-4a7a-a867-a8e074d2c973 in the generic thread ***CHATID***","date":"2024-02-15T14:07:58","request-id":"85ed9a26-2168-4a31-97db-3e694f2f9cb8","client-request-id":"1159548f-9ff5-4aae-b3c8-8ec620e8060c"}}}
headers: {Transfer-Encoding=chunked, Strict-Transport-Security=max-age=31536000, Vary=Accept-Encoding, Date=Thu, 15 Feb 2024 14:07:57 GMT, Content-Type=application/json}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c1155f8-abe0-902a-2f91-8cd2fe00c567
* Version Independent ID: a88f1a96-46b9-2742-8f19-b55d25dce815
* Content: [List members of a chat - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/chat-list-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @anandjo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
Hello @sunmont - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@sunmont - We are not able to repro this issue. It is working fine at our end. We are checking this internally. We will get back to you. Thanks.

**Comment by Meghana-MSFT** [comment]
@sunmont - We received the following input from engineering teams- Tenant\user could have lost access to thread, this can happen if they were removed from the thread (in app context it can happen if no one from the calling tenant is on the roster anymore).

Could you please confirm if this is what happened in your case?
