### ISSUE TITLE
Missing Documentation: Sharepoint - Creating list item of under specific list template

### ISSUE THREAD

**Issue by sumeet-automate** [microsoftgraph/microsoft-graph-docs-contrib#913]
I am trying to create event in the event list of a sharepoint site. The documentation gave information about which endpoints to work with, but it seems like the data which needs to be sent to create event is not properly documented.

`POST https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items`

The event should be added to a list of which has template of type "events". Can you please update the document or atleast provide a sample request body which can be to create items inside specific list template types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa7a3906-32dd-fab9-a6f4-a5f8e55429ce
* Version Independent ID: 088ac63e-886e-71f2-bc9b-36f25f93305a
* Content: [Create a new entry in a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-create?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/listitem-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-create.md)
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
