### ISSUE TITLE
Missing OneDrive Query Param Docs

### ISSUE THREAD

**Issue by mlafleur** [microsoftgraph/microsoft-graph-docs-contrib#914]
The OneDrive API has some query limitations that are covered in OD docs but currently not included in the larger Graph documentation. As an example, [this section ](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/optional-query-parameters?view=odsp-graph-online#sorting-collections) on `orderBy`:

> You can use the `orderby` query string to control the sort order of the items returned from the OneDrive API. For a collection of items, use the following fields in the `orderby `parameter.
> 
> - `name`
> - `size`
> - `lastModifiedDateTime`
> 
> Note that in OneDrive for Business and SharePoint Server 2016, the `orderby` query string only works with `name` and `url`.

It seems like these nuances should be included in either the API's [overview](https://developer.microsoft.com/en-us/graph/docs/concepts/onedrive-concept-overview), the [query param](https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters), or both.

**Comment by PaoloPia** [comment]
As part of a repository clean up effort we are closing older issues. If this issue remains, please: open a new issue, reference this issue, and provide any additional details that may help in resolution. Thank you for your understanding as we work to improve our responsiveness.
