### ISSUE TITLE
MicrosoftGraphCallRecordsGetPstnCallsWithFromDateTimeWithToDateTime Not working

### ISSUE THREAD

**Issue by RupenAnjaria** [microsoftgraph/microsoft-graph-docs-contrib#9140]
Please see my code below:
```

            _clientSecretCredential = new ClientSecretCredential(tenantID, tenant.ClientId,
                                                                    tenant.ClientSecret);

            _appClient = new GraphServiceClient(_clientSecretCredential, new[] { "https://graph.microsoft.com/.default" });
            var x = await _appClient
                            .Communications
                            .CallRecords        
                   .MicrosoftGraphCallRecordsGetPstnCallsWithFromDateTimeWithToDateTime(DateTimeOffset.Parse("02/01/2024"), DateTimeOffset.Parse("02/19/2024"))
                            .GetAsync();
```

I am getting compiler warning that MicrosoftGraphCallRecordsGetPstnCallsWithFromDateTimeWithToDateTime is obsolete. Use { TypeName } instead.

Also, at runtime, this fails with error 403.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da5b82ae-fd4e-6445-be2f-d2904b919e0d
* Version Independent ID: c3fdaa61-1d7d-447d-7844-737902b786d8
* Content: [callRecord: getPstnCalls - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @williamlooney
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by SanderSade** [comment]
It seems the "Use { TypeName } instead" was [fixed two weeks ago](https://github.com/microsoftgraph/msgraph-sdk-dotnet/commit/675033b37b51a361ed6cb93778c9205734c7bdab), and GetAsGetPstnCallsWithFromDateTimeWithToDateTimeGetResponseAsync should be used instead. I presume the documentation will be updated with a new method shortly.

For 403, does the app/identity have one of the required permissions - the [documentation](https://learn.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&tabs=http) has CallRecords.Read.All. 

If this is added already and the app still gets 403, we will need more information to debug the backend - at the minimum, the tenant ID and time of queries are needed.

@RupenAnjaria

**Comment by SanderSade** [comment]
Closing, no followup from OP

**Comment by RupenAnjaria** [comment]
Sorry was working on other priority and couldn't respond.

I do have the permissions: here is the screenshot:
<img width="584" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/17281745/400fc54a-fa75-449e-9088-eb01caed3bbe">

Further, I tried the ```GetAsGetPstnCallsWithFromDateTimeWithToDateTimeGetResponseAsync``` method, but getting compiler error that the method doesn't exist:

```
            var x = await _appClient
                            .Communications
                            .CallRecords
                            .GetAsGetPstnCallsWithFromDateTimeWithToDateTimeGetResponseAsync(DateTimeOffset.Parse("02/01/2024"), DateTimeOffset.Parse("02/19/2024"))
                            .GetAsync();
```

Any documentation around this method please?

Thank you.

**Comment by SanderSade** [comment]
What version of the SDK are you using - I see [5.44.0](https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/5.44.0) released two weeks ago, which _should_ include this method.

If that is not the case, we need to reach out to the SDK team, as they own that code and documentation,

**Comment by RupenAnjaria** [comment]
I have 5.42.0 and found that below code is working:

```
            var result = await _appClient
                                .Communications
                                .CallRecords
                                .MicrosoftGraphCallRecordsGetPstnCallsWithFromDateTimeWithToDateTime(DateTimeOffset.Parse("03/01/2024"), DateTimeOffset.Parse("03/10/2024"))
                                .GetAsGetPstnCallsWithFromDateTimeWithToDateTimeGetResponseAsync();
```

Thank you (may be we should update the documentation).
