### ISSUE TITLE
Throttling Limit for this API

### ISSUE THREAD

**Issue by anant-hiver** [microsoftgraph/microsoft-graph-docs-contrib#9141]
[Enter feedback here]

Is there any kind of throttling limit for this API? It is not mentioned in the document. Sometimes the API throws `401`. It would be great if someone could add details for the same.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0169c1-e6e7-da8f-4158-5e721eae8b9a
* Version Independent ID: f2907cde-b9d7-4ba7-e813-047e5b938e50
* Content: [List messages - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/user-list-messages.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @SuryaLashmiS
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @anant-hiver - Please refer to the [Throttling limits article: Outlook service limits](https://learn.microsoft.com/en-us/graph/throttling-limits?view=graph-rest-1.0#outlook-service-limits) for more service-specific throttling limits.
