### ISSUE TITLE
typo on page: fout hours.

### ISSUE THREAD

**Issue by schalkje** [microsoftgraph/microsoft-graph-docs-contrib#9144]
fout hours. -> four

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd18eae1-0b0f-f274-f70a-6063b2928c09
* Version Independent ID: fd18eae1-0b0f-f274-f70a-6063b2928c09
* Content: [Get real-time updates for data changes by using Microsoft Graph - Microsoft Graph](https://learn.microsoft.com/en-us/graph/patterns/notifications-in-push-mode)
* Content Source: [concepts/patterns/notifications-in-push-mode.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/patterns/notifications-in-push-mode.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @OlgaPodo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
PR https://github.com/microsoftgraph/microsoft-graph-docs-contrib/pull/9244 fixes this issue.

**Comment by Danielabom** [comment]
Fix applied.
