### ISSUE TITLE
docs are for previous version of API

### ISSUE THREAD

**Issue by paulwoods222** [microsoftgraph/microsoft-graph-docs-contrib#9150]
The current version of the Java SDK is 6.2.0, the documentation is for version 5, so none of it applies.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4537f77e-a8e8-e3f1-9cc4-2fd930db7ada
* Version Independent ID: 46396fa2-f7e2-322e-5e76-f9e2d17d1b48
* Content: [Choose a Microsoft Graph authentication provider - Microsoft Graph](https://learn.microsoft.com/en-gb/graph/sdks/choose-authentication-providers?tabs=java#client-credentials-provider)
* Content Source: [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/sdks/choose-authentication-providers.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks for reporting @paulwoods222! I've unblocked the snippet updates. This should be published later today.
