### ISSUE TITLE
Support for $expand with inner $select

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#9157]
Does this endpoint support `$expand` with inner `$select`?

It's de facto standard for other endpoints that `$expand` with inner `$select` is supported. 

The query

```
https://graph.microsoft.com/v1.0/roleManagement/directory/roleAssignmentScheduleInstances?$expand=principal($select=displayName)
```
returns 

```
{
  "error": {
    "error": {
      "code": "InvalidFilter",
      "message": "The  filter is invalid.",
      "innerError": {
        "date": "2024-02-23T14:25:39",
        "request-id": "9c8c603d-a1f6-45c1-8f21-33fb7c932970",
        "client-request-id": "9c8c603d-a1f6-45c1-8f21-33fb7c932970"
      }
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2256c754-f6c0-d6e4-1eb9-af527ea6faf9
* Version Independent ID: 32367385-ba4b-df48-543d-12a2d619f7ba
* Content: [List roleAssignmentScheduleInstances - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignmentscheduleinstances?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/rbacapplication-list-roleassignmentscheduleinstances.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/rbacapplication-list-roleassignmentscheduleinstances.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi 
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @MartinM85 for raising this issue. Unfortunately, only this is supported 👉🏾 `.../roleAssignmentScheduleInstances?$expand=principal($select=id)`. Other relationships like **roleDefinition** support inner `$select` for all properties, but the principal relationship supports inner `$select` for **id** only. I've raised a PR to include this info in the documentation.

To request that this limitation be removed, you can submit a feature suggestion through the [Microsoft Graph feedback forum](https://aka.ms/graphfeedback). Other developers can amplify your voice for the suggestion to be considered for feature development.

**Comment by MartinM85** [comment]
@FaithOmbongi Thanks for the response. Obviously `$expand=principal($select=id)` doesn't make sense because principalId is returned by default by `/roleAssignmentScheduleInstances`
