### ISSUE TITLE
Schema property type: boolean collection

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#9164]
Is booleanCollection supported as one of possible types?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab0cbb92-7d68-c185-f476-beb43aaf2f37
* Version Independent ID: f52a2e44-ec0e-91d6-7aab-38daed432b20
* Content: [property resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/externalconnectors-property.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/externalconnectors-property.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @mecampos
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
Hi, @MartinM85,  booleanCollection is not supported as a type.
