### ISSUE TITLE
Application permission User.ReadWrite.All can call this /users/{ID}/revokeSignInSessions

### ISSUE THREAD

**Issue by zemuldo** [microsoftgraph/microsoft-graph-docs-contrib#9166]
[Enter feedback here]
As per this doc, Application only permissions are not supported.
However, I can call /users/{ID}/revokeSignInSessions with only application permissions user.ReadWrite.All.

Sample request logs. 
request-id ---> de859712-f864-4cfb-b0ae-24154fea726b
client-request-id" ---> de859712-f864-4cfb-b0ae-24154fea726b
Time Stamp --> Mon, 26 Feb 2024 14:20:59 GMT

Original QnA thread: https://learn.microsoft.com/en-us/answers/questions/1555410/application-permissions-able-to-revoke-user-sign-i

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4662c3f7-8566-09b3-962c-2cfcccfcfc2f
* Version Independent ID: 1cdc7db2-7c2c-9b23-16f7-05e76f588f6c
* Content: [user: revokeSignInSessions - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-revokesigninsessions.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/user-revokesigninsessions.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @zemuldo for reporting this issue.

The permissions information is read from an internal data source. I've therefore filed bug 2853435 assigned to @yyuank for the data to be fixed. The changes will be propagated downstream to the docs within 48 Hours of the fix.

I'll close this issue here since it's a product bug.
