### ISSUE TITLE
Slightly misleading description of session properties

### ISSUE THREAD

**Issue by SirAnsberry** [microsoftgraph/microsoft-graph-docs-contrib#9167]
I think the description of endDateTime and startDateTime is slightly misleading and has lead to some confusion on projects I worked on. 

If I'm wrong Im also happy to find out because I don't want to work under the wrong assumption of how this works. 

Anyway. 

endDateTime says: 
UTC time when the **last** user left the session.
My understanding is that sessions are always either peer to peer or in case of group calls user(callee) to endpoint. 
The inclusion of the word last implies there are more than 2 users tied to a session and leads to confusion where people conflate the times on a session to times on a callRecord. 

startDateTime says:
UTC time when the **first** user joined the session. 
That introduces the same issues as described above.
I.e. some assume that in a call with 3 or more users the end time will be when the last user left the call which is not the case for sessions as the session is the interaction between a callee and the group call endpoint or the person they are calling. 

I think the description should just say it's the Start/End time of the session unless I'm wrong in my understanding.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c47f184-6113-db57-0ec1-3c68176a0281
* Version Independent ID: 7de8c2bc-70c3-3ba1-d445-20fdeec6c461
* Content: [session resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/callrecords-session?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/callrecords-session.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/callrecords-session.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @mcm223
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
Contacted @mcm223 to get feedback.

**Comment by mcm223** [comment]
@SirAnsberry Thanks for reaching out! The current phrasing is intended to communicate not only when the session started/ended, but why it started and ended. In this case, a session begins when at least one participant (be it user or service) joins and a session ends when no participants remain. We'll re-evaluate the language in this document to see if there are clearer ways to communicate these concepts. Thanks again!
