### ISSUE TITLE
Content of page not actionable

### ISSUE THREAD

**Issue by SomeoneElseOSM** [microsoftgraph/microsoft-graph-docs-contrib#9168]
https://learn.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http contains a "try it" button.  When signed into the browser as an admin of the O365 tenant, the following message is displayed: "Forbidden - 403 - 1554 ms. Either the signed-in user does not have sufficient privileges, or you need to consent to one of the permissions on the Modify permissions tab".  No information is provided about how to resolve this issue.  There is a "Modify permissions tab", but nothing is modifiable in there.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 786282cc-2e01-7a67-bff8-7fdfc069d8f3
* Version Independent ID: 56775e93-d8b0-9fda-88ce-b6dd762a11c5
* Content: [List credentialUserRegistrationDetails - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @egreenberg14
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @SomeoneElseOSM for raising this issue. There are two possible reasons for the issue:
- You haven't consented to the Reports.Read.All permission. [Refer to the required permissions for the API](https://learn.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http#permissions). Apart from the "Modify permissions" tab, you can also navigate to the list of permissions via the profile avatar. See [this guide with screenshots](https://learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features#consent-to-permissions).
- You don't have the [required license to use the feature](https://learn.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta#licenses).

**Comment by FaithOmbongi** [comment]
Hi @SomeoneElseOSM - I hope my answer was satisfactory. I'll proceed to close this issue.

**Comment by SomeoneElseOSM** [comment]
Yes it was "You don't have the required license to use the feature."

Unfortunately, what is the required licence doesn't seem to be listed on the page?
