### ISSUE TITLE
Unable to open page specific feedback

### ISSUE THREAD

**Issue by ssteiner** [microsoftgraph/microsoft-graph-docs-contrib#918]
all feedback buttons on learn.microsoft.com go to https://github.com/microsoftgraph/microsoft-graph-docs and there's no such repo.. so what are we supposed to do to provide feedback?

**Comment by jasonjoh** [comment]
Please provide it here. The feedback buttons are being fixed now, our next publish should update them.

**Comment by jasonjoh** [comment]
Change has made it to the live servers. You may need to clear your cache to see the update.

**Comment by ssteiner** [comment]
I can confirm that the links work again.

**Comment by Occhioverde** [comment]
Sorry @jasonjoh to hijack this issue, but where did microsoftgraph/microsoft-graph-docs go?
It seems that the code that was there is the same hosted here, but there were issues with solutions to different problems (like microsoftgraph/microsoft-graph-docs#10206) that can no longer be found...

**Comment by jasonjoh** [comment]
@Occhioverde this is the new replacement. As part of the migration we transferred open issues, but maybe we should also bring over closed issues. Will discuss with the team.

**Comment by Occhioverde** [comment]
> maybe we should also bring over closed issues

Yeah, that would be great not only for people that, like me, saved a link to common issues to have a reference, but also to whom searches a Graph related problem on Google, opens one of the many discussions that were hosted on the old repo and gets greeted by a 404 page instead of the solution they were looking for.
