### ISSUE TITLE
allowedToReadOtherUsers - seeing different recommendations

### ISSUE THREAD

**Issue by dawander** [microsoftgraph/microsoft-graph-docs-contrib#9216]
On this page, it says the value for allowedToReadOtherUsers should NOT BE FALSE.  However, the Entra governance document here has it set to false. https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/govern/identity-baseline/azure-ad-configuration#graph-api

Not sure which one to believe at this point.  It would be great to understand potential collateral damage if set to false.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54570163-bca3-12ec-3694-d65971c50eb9
* Version Independent ID: 8304835c-5984-db10-f9fa-fa325378e231
* Content: [defaultUserRolePermissions resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/defaultuserrolepermissions?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/defaultuserrolepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/defaultuserrolepermissions.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @DougKirschner
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @dawander for asking this question. I'm following up with the feature SMEs for clarification and will get back to you.

**Comment by FaithOmbongi** [comment]
Hi @dawander - Thank you for bringing this contradictory guidance to our attention. We recommend not setting **allowedToReadOtherUsers** to `false` as indicated in the Microsoft Graph article and [this default user permissions guidance](https://learn.microsoft.com/en-us/entra/fundamentals/users-default-permissions#:~:text=BitLocker%20key(s).-,Read%20other%20users,-This%20setting%20is).

We'll also update the JSON sample in the Cloud Adoption Framework that you pointed to from `"allowedToReadOtherUsers": false` to `"allowedToReadOtherUsers": true`.
