### ISSUE TITLE
Additional Examples

### ISSUE THREAD

**Issue by Teejer** [microsoftgraph/microsoft-graph-docs-contrib#9217]
Can we get more examples on how to do this with the libraries you provide. Specifically php and c#?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b92a5cd-9005-21a0-3cfc-ab779b06c893
* Version Independent ID: a5bcc015-9b4f-034e-3d0c-1511115dde75
* Content: [Get deviceLocalCredentialInfo - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/devicelocalcredentialinfo-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/devicelocalcredentialinfo-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/devicelocalcredentialinfo-get.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @SanDeo-MSFT
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Teejer** [comment]
Do you mean next wednesday? Or should it be there today? I don't see them.

**Comment by FaithOmbongi** [comment]
Hi @Teejer - Sorry, I mean Wednesday the 13th.
