### ISSUE TITLE
permission for App Registration - using this api

### ISSUE THREAD

**Issue by aclottan** [microsoftgraph/microsoft-graph-docs-contrib#9218]
[Enter feedback here]

it should be added, to the current note:

"To add members to a role-assignable group, the calling user must also be assigned the RoleManagement.ReadWrite.Directory permission."

that this permission is also needed if calling this api using App Registration permissions (from a service etc).
it will save a lot of time !

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add members - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yuhko-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @aclottan -Could you help clarify the change you're requesting? I see the article already has the note.

<img width="517" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/14026935/bea16b4e-763d-4d27-9424-980cf50e63d8">

**Comment by aclottan** [comment]
the important remarks mentioned that the "calling user" must be assigned with a role.
i think it's important to mention that if using the API from an application (via app registration), the application should also have this permission assigned (by going to the app registration -> api permission -> add permission -> microsoft graph -> application permission
and granting admin concent

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/63653394/ba3ced35-3afc-4a0c-88fb-899c853e86a4)

**Comment by yuhko-msft** [comment]
@FaithOmbongi - how about we say " the **caller** must have RoleManagement.ReadWrite.Directory permission" instead of calling user? caller can be any instance (such as a user or an app)

**Comment by FaithOmbongi** [comment]
Ah, gotcha. Thanks @aclottan and @yuhko-msft . I've raised a PR to fix the description as per @yuhko-msft's guidance.

**Comment by yuhko-msft** [comment]
[heart]         Yuhsing Ko reacted to your message:
________________________________
