### ISSUE TITLE
Beta HTTP request example appearing in V1 documentation

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-docs-contrib#9220]
For the example below, a beta url is provided in V1 docs. This prevents successful compilation validation
Example 2: Retrieve all decision items for which you're a reviewer and expand the definitions

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/11347476/255f6883-c002-43b6-b602-92fd661c165b)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70082db1-8c88-6fb8-363b-b29ef44e7262
* Version Independent ID: 62bf7a96-af5f-21bd-7f42-e74cf54e3648
* Content: [List decisions - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/accessreviewinstance-list-decisions.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @jyothig123
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @fey101 for reporting this error. I've raised a PR to fix the URLs.
