### ISSUE TITLE
Beta HTTP Example Request On V1 Documentation

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-docs-contrib#9221]
](https://learn.microsoft.com/en-us/graph/api/intune-apps-enterprisecodesigningcertificate-update?view=graph-rest-1.0&tabs=http#request)
![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/11347476/378d897e-2c9a-4ec6-a639-58da7ea16244)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb6960a8-3f8a-dffc-008e-71baf297d73f
* Version Independent ID: 1025214d-95c0-8518-8248-e53b30ce1998
* Content: [Update enterpriseCodeSigningCertificate - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/intune-apps-enterprisecodesigningcertificate-update?view=graph-rest-1.0&tabs=http#request)
* Content Source: [api-reference/v1.0/api/intune-apps-enterprisecodesigningcertificate-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/intune-apps-enterprisecodesigningcertificate-update.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @jaiprakashmb
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
> ](https://learn.microsoft.com/en-us/graph/api/intune-apps-enterprisecodesigningcertificate-update?view=graph-rest-1.0&tabs=http#request) ![image](https://private-user-images.githubusercontent.com/11347476/310518846-378d897e-2c9a-4ec6-a639-58da7ea16244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjUyNzIsIm5iZiI6MTcxMDI2NDk3MiwicGF0aCI6Ii8xMTM0NzQ3Ni8zMTA1MTg4NDYtMzc4ZDg5N2UtMmM5YS00ZWM2LWE2MzktNThkYTdlYTE2MjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE3MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYjYxYjBjYzMxMDJiY2E1N2RjM2M2NDBjNmE5ZGFkNTRmODE1ZGIyYTQyYjIxYjY3NGViNzIyNDUwYjU0ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jGFlbBE9pZKzXl-oEyFe4acsbc4cDq6OoB0PXCSiJGs)
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: bb6960a8-3f8a-dffc-008e-71baf297d73f
> * Version Independent ID: 1025214d-95c0-8518-8248-e53b30ce1998
> * Content: [Update enterpriseCodeSigningCertificate - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/intune-apps-enterprisecodesigningcertificate-update?view=graph-rest-1.0&tabs=http#request)
> * Content Source: [api-reference/v1.0/api/intune-apps-enterprisecodesigningcertificate-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/intune-apps-enterprisecodesigningcertificate-update.md)
> * Product: **intune**
> * Technology: **microsoft-graph**
> * GitHub Login: @jaiprakashmb
> * Microsoft Alias: **MSGraphDocsVteam**
PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/23889 fixes this issue.

**Comment by Danielabom** [comment]
Fix applied.
