### ISSUE TITLE
Beta HTTP Request On V1 Documentation - ScheduleActionsForRules

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-docs-contrib#9222]
[here]](https://learn.microsoft.com/en-us/graph/api/intune-deviceconfig-devicecompliancepolicy-scheduleactionsforrules?view=graph-rest-1.0&tabs=http#request)

![image](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/assets/11347476/8072eb21-48c3-4e17-b295-e9b6b21195bd)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c291feb3-c438-40c7-c915-902f714ba8f6
* Version Independent ID: c1f6bd07-4779-29a5-1b6c-122797248323
* Content: [scheduleActionsForRules action - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/intune-deviceconfig-devicecompliancepolicy-scheduleactionsforrules?view=graph-rest-1.0&tabs=http#request)
* Content Source: [api-reference/v1.0/api/intune-deviceconfig-devicecompliancepolicy-scheduleactionsforrules.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/intune-deviceconfig-devicecompliancepolicy-scheduleactionsforrules.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @jaiprakashmb
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Danielabom** [comment]
Fix applied.
