### ISSUE TITLE
Documentation Samples for Adding / Updating Custom Security Attributes using the C# Graph SDK do not work

### ISSUE THREAD

**Issue by stephajn** [microsoftgraph/microsoft-graph-docs-contrib#9232]
I have followed the code sample to assigning a single string, boolean, and integer custom attributes to a user. However, when calling the Graph API, I get an exception saying that the property is invalid.

Given this example:
Attribute Set Name: "SomeAttributeSet"
Attribute Name: "Foo"
Attribute Data Type: single value string
Attribute Data Value: "bar"

I have this code:

```
protected const string CustomSecurityAttributeOdataType = "#Microsoft.DirectoryServices.CustomSecurityAttributeValue";

User requestBody = new()
{
    CustomSecurityAttributes = new CustomSecurityAttributeValue
    {
        AdditionalData = new Dictionary<string, object>
        {
            {
                "SomeAttributeSet", new
                {
                    OdataType = MicrosoftGraphApiClientBase.CustomSecurityAttributeOdataType,
                    Foo = "Bar"
                }
            }
        }
    }
};

await graphClient.Users[azureObjectId].PatchAsync(requestBody);
```
When I call the Graph API, I get back an error saying,  "Invalid Property: SomeAttributeSet"

But I have confirmed that the attribute set exists, and that the name is matched.
I even did a test where I set the attribute value in the portal, and then retrieve the User object and confirmed that the custom attribute is coming back as expected.

I am using Microsoft.Graph 5.41.0 NuGet package to accomplish this.

Also, the document doesn't seem to have any indications about whether multiple attributes can be updated at once or if one individual request for each attribute being set has to be made. This would be a good example to add if such a thing is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21bf7805-cb34-c496-fe55-ac4236813a67
* Version Independent ID: 21bf7805-cb34-c496-fe55-ac4236813a67
* Content: [Manage custom security attribute assignments - Microsoft Graph](https://learn.microsoft.com/en-us/graph/custom-security-attributes-examples?tabs=csharp)
* Content Source: [concepts/custom-security-attributes-examples.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/custom-security-attributes-examples.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by FaithOmbongi** [comment]
Hi @rolyon can you assist with the last query? Thanks.

>>Also, the document doesn't seem to have any indications about whether multiple attributes can be updated at once or if one individual request for each attribute being set has to be made. This would be a good example to add if such a thing is supported.

Hi @stephajn - For the C# issue, I recommend that you file the issue in the [C# SDK repo](https://github.com/microsoftgraph/msgraph-sdk-dotnet) for investigation. Thank you.

**Comment by Yottster** [comment]
We've been struggling quite a bit with this as well. 
Think this is the correct way to set it:
```csharp
User requestBody = new()
{
    CustomSecurityAttributes = new CustomSecurityAttributeValue
    {
        OdataType = "#Microsoft.DirectoryServices.CustomSecurityAttributeValue",
        AdditionalData = new Dictionary<string, object>
        {
            {
                "SomeAttributeSet", new
                {
                    Foo = "Bar"
                }
            }
        }
    }
};

await graphClient.Users[azureObjectId].PatchAsync(requestBody);
```
