### ISSUE TITLE
Issues in doc for cloud clipboard

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs-contrib#9237]
There are few issues on the site

**Wrong link**

> This API doesn't support using another user's credentials to get a [cloudClipboardItem (../resources/cloudclipboarditem.md) for a user.

**Wrong http request**

> GET /user/cloudClipboard/items

Same in the example

should be `/me/cloudClipboard/items`

**Additional question**

I'm receiving the error 409 and according to the documentation, I need strongly authenticated devices. What's the definition of a strongly authenticated device?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 568f8a4d-e22f-304c-f02b-ea0fb268cd9b
* Version Independent ID: 4c5accda-4c7f-9b87-7a88-83983c27afa7
* Content: [List cloudClipboard items - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/cloudclipboardroot-list-items?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/cloudclipboardroot-list-items.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/cloudclipboardroot-list-items.md)
* Service: **microsoft-graph**
* Sub-service: **non-product-specific**
* Product: **project-rome**
* GitHub Login: @FaithOmbongi 
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @yuechen7, can you assist here? Thanks.

**Comment by yuechen7** [comment]
@MartinM85 Thank you for the information. 
Strong Authentication means that the user will need to use [Multifactor authentication](https://learn.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/multi-factor-authentication-microsoft-365?view=o365-worldwide) to log in.  Also need to ensure that the user has at least 2 devices.

**Comment by MartinM85** [comment]
@yuechen7 Thanks for the response.  I've two devices with multi-factor authentication, but I'm still receiving the error 409.
