### ISSUE TITLE
Example is missing code snippet for PowerShell

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs-contrib#928]
[Enter feedback here]
Example is missing code snippet for PowerShell

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 142c5acc-75e4-ec8f-dbb2-c09a85883abf
* Version Independent ID: 111751c1-75c1-0f51-f9d8-e5ce4312f220
* Content: [Update directorySetting - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/directorysetting-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/directorysetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/beta/api/directorysetting-update.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @adimitui
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @bachoang for raising this issue. The code snippets are autogenerated weekly, so I've raised a PR to request a regeneration. Hopefully, the PowerShell snippets will be included in next week's run.
