### ISSUE TITLE
While trying to create a resource for metered Graph API using the az resource create --resource-group  cmdlet fails consistently.

### ISSUE THREAD

**Issue by souravmishra-msft** [microsoftgraph/microsoft-graph-docs-contrib#929]
While trying to create a resource for metered Graph API using the az resource create --resource-group  cmdlet fails consistently.

az : ERROR: (InternalServerError) S2S33101: Failed to get token from tokenEndpoint: 'https://login.windows.net/e0fd434d-ba64-497b-90d2-859c472e1a92/oauth2/v2.0/token', clientId: 
'e3b317b2-ee2c-4eb2-ab20-c166ef7fe246', resource: '[https://graph.microsoft.com//.default](https://graph.microsoft.com/.default)', activityId: '343fc496-48d4-405e-8935-6d4d53e7d160'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b356f4b8-50b3-7ff6-8c3f-a5210b027c7c
* Version Independent ID: b356f4b8-50b3-7ff6-8c3f-a5210b027c7c
* Content: [Enable metered APIs and services in Microsoft Graph - Microsoft Graph](https://learn.microsoft.com/en-us/graph/metered-api-setup?tabs=azurecloudshell&source=docs#enable-an-application)
* Content Source: [concepts/metered-api-setup.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/concepts/metered-api-setup.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TIWittel** [comment]
Hi guys...I'm have with the same problem. Someone could help me?

**Comment by JSP-Neto** [comment]
Hello everyone, everything good?

I'm having exactly the same problem.

I need to use the Metered MSteams API and I cannot perform the command in cloud azure powershell.

I opened a ticket on the azure portal 3 days ago and no one helps me :/

ID 2310070040001245
