### ISSUE TITLE
No explanation on follow/unfollow

### ISSUE THREAD

**Issue by javieralvarezchiang** [microsoftgraph/microsoft-graph-docs-contrib#95]
This page doesn't inform the user about the effects of this endpoint. My guess it that it would create an email trigger every time the driveitem changes, but that's just a hunch. It could be anything. A poll or a push mechanism that is not documented or linked here.

Second: If this is true, then I wouldn't expect app-only tokens to work with this endpoint, and indeed, I was not able to test this with app-only tokens, only with delegate

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfdc98d4-f1ea-3dfd-079e-b87d418615f9
* Version Independent ID: 77b39edd-8bc3-914c-8870-0215251bc14e
* Content: [Follow drive item - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/driveitem-follow?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-follow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-follow.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @learafa
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We are currently working on improving docs and we'll do our best to keep your feedback into account while doing that. In the meantime, I'm going to close this item. Thanks for your understanding.
